- packages/lexical-playground/__tests__/utils/index.mjs
- packages/lexical-playground/src/Editor.jsx
- packages/lexical-playground/src/appSettings.js
Let's have some actual example text to show!
> Add example rich text

- README.md
Just getting myself on the contributors list 😄
> README.md typo: "documentation"

- README.md
Fixed some typos on the README, excited to try this out!
> Fix(README): Typos

- packages/lexical/src/LexicalSelection.js
Fixes https://github.com/facebook/lexical/issues/1680. It turns out our selection restoration logic wasn't attempting to optimize text nodes where possible and instead was optimized around element node selection.
> Fix selection issue with insertNodes

- packages/lexical-playground/src/App.jsx
- packages/lexical-playground/src/index.css
This should improve discoverability of the Lexical website.
> Make playground logo a link

- packages/lexical-playground/src/ui/Modal.css
Fixes https://github.com/facebook/lexical/issues/1694
> Fix dialog css

- packages/lexical-rich-text/src/index.js
> Fix rich text align for multiple nodes

- packages/lexical-playground/split/index.html
- packages/lexical-playground/src/Settings.jsx
I found this page via PR previews and it seemed broken since the host was hardcoded.
May be this fixes it?
> Fixes split view in PR previews

- packages/lexical-code/src/index.js
Pasting code causing chain of redundant text transforms (textNode -> codeBlock -> each child of codeBlock), while we only need to exec codeBlock transformation.
> Skip transforms of text/highlight nodes while transforming whole codeblock

- packages/lexical-playground/__tests__/keyboardShortcuts/index.mjs
- packages/lexical-playground/__tests__/regression/1730-delete-backword.spec.mjs
- packages/lexical/src/LexicalEvents.js
fixes: https://github.com/facebook/lexical/issues/1730
**Note**
similar to https://github.com/facebook/lexical/pull/1259
> fix: Ctrl+H deleteBackward

- packages/lexical-playground/src/appSettings.js
Remove the default content in the local dev env
> Remove default content

- packages/lexical-plain-text/src/index.js
- packages/lexical-playground/__tests__/e2e/Composition.spec.mjs
- packages/lexical-playground/__tests__/utils/index.mjs
- packages/lexical-playground/src/plugins/MentionsPlugin.jsx
- packages/lexical-rich-text/src/index.js
- packages/lexical/Lexical.d.ts
- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/LexicalCommands.js
- packages/lexical/src/LexicalEvents.js
Fixes https://github.com/facebook/lexical/issues/1716. Turns out our logic for detecting Android keys wasn't right in many cases, and we should have been using a better heuristic. Furthermore, this also fixes an issue where you press Enter during typing on Android.
> Fix android GBoard issues

- packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
See #1654 and #1686 for a breakdown of new behavior.
Closes #1688. See tests.
> Add Tests for special Table selection behavior

- packages/lexical-code/flow/LexicalCode.js.flow
- packages/lexical-playground/src/Editor.jsx
- packages/lexical-playground/src/nodes/ExcalidrawNode/index.jsx
- packages/lexical-playground/src/nodes/ImageNode.jsx
- packages/lexical-playground/src/nodes/PollNode.jsx
- packages/lexical-playground/src/nodes/StickyNode.jsx
- packages/lexical-playground/src/plugins/CharacterStylesPopupPlugin.jsx
- packages/lexical-react/LexicalAutoScrollPlugin.d.ts
- packages/lexical-react/flow/LexicalAutoScrollPlugin.js.flow
- packages/lexical-react/src/__tests__/unit/PlainRichTextPlugin.test.js
- packages/lexical-website-new/docs/concepts/transforms.md
- packages/shared/src/environment.js
Seems like there were some prettifier misses in previous commit which shows up in other PRs while viewing changes. So ran `npm run prettier-all`
> Run `prettier-all`

- .github/workflows/test.yml
Should skip tests if all changes are within website folder ([details](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths))
> When all the path names match patterns in paths-ignore, the workflow will not run. If any path names do not match patterns in paths-ignore, even if some path names match the patterns, the workflow will run.
> Skip tests if updating website/docs

- packages/lexical-playground/src/plugins/ActionsPlugin.jsx
- packages/lexical-playground/src/plugins/ToolbarPlugin.jsx
It should really be an option in the toolbar!
> Move sticky note to toolbar

- packages/lexical-playground/src/Editor.jsx
- packages/lexical-playground/src/Settings.jsx
- packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
> Add better initial rich text content

- packages/lexical-playground/src/plugins/ListMaxIndentLevelPlugin.js
- packages/lexical-playground/src/plugins/SpeechToTextPlugin.js
- packages/lexical-table/src/LexicalTableSelectionHelpers.js
My bad, apparently CI doesn't catch this dev-only errors
> Fix dev build/imports

- packages/lexical-playground/src/nodes/StickyNode.jsx
- packages/lexical-playground/src/plugins/ToolbarPlugin.jsx
- packages/lexical-react/src/LexicalNestedComposer.jsx
- packages/lexical-yjs/src/Utils.js
Turns out that there were some recent issue with StickyNotes that needed fixing.
> Fix issues with StickNotes in collab

- packages/lexical-playground/src/plugins/ActionsPlugin.jsx
- packages/lexical-playground/src/plugins/SpeechToTextPlugin.js
- packages/lexical/Lexical.d.ts
- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/LexicalCommands.js
Fixes https://github.com/facebook/lexical/issues/1792
> Fix readOnly button on playground

- packages/lexical-website-new/src/pages/index.js
This is likely a better use of the button!
> Change button to be playground

- packages/lexical/src/LexicalEvents.js
- packages/lexical/src/LexicalUtils.js
Fix https://github.com/facebook/lexical/issues/1307
And I apologize if https://github.com/facebook/lexical/issues/1307#issuecomment-1098724635 has already worked on it🙇
> Fix opening dev tools

- packages/lexical-playground/src/plugins/ActionsPlugin.jsx
> Disable clear button when editor is blank

- packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs
- packages/lexical-rich-text/src/index.js
Needs to handle NodeSelection
Closes #1814
> Fix format element for DecoratorNode

- packages/lexical-code/LexicalCode.d.ts
- packages/lexical-code/flow/LexicalCode.js.flow
- packages/lexical-hashtag/LexicalHashtag.d.ts
- packages/lexical-link/LexicalLink.d.ts
- packages/lexical-offset/LexicalOffset.d.ts
- packages/lexical-react/LexicalHorizontalRuleNode.d.ts
- packages/lexical-rich-text/LexicalRichText.d.ts
- packages/lexical/Lexical.d.ts
Had js.flow but was missing d.ts definitions
Closes #1816
> Add LexicalCode TS types

- packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
- packages/lexical-playground/__tests__/utils/index.mjs
> E2E split image caption utility

- packages/lexical-website-new/docs/concepts/nodes.md
> docs: fix typo in nodes page

- packages/lexical-rich-text/LexicalRichText.d.ts
Import missing
Closes https://github.com/facebook/lexical/issues/1821
> Fix LexicalRichText.d.ts any type

- packages/lexical-playground/src/plugins/ToolbarPlugin.jsx
Revamp format heading to use the same method with diff params instead of having separate methods that do the same thing
> Revamp format heading

- packages/lexical-react/src/__tests__/unit/PlainRichTextPlugin.test.js
I can see that this is potential use for setEditorState, selection is something that we don't want to replicate in a few cases, so I'm proposing to build this in ~~as an optional flag on `setEditorState`~~:
1. Restore from server
2. Side-by-side render view (i.e. https://github.com/facebook/lexical/discussions/1825)
Update: I'm proposing to build this as an optional flag for Rich/PlainTextPlugin. To do this we leverage batched updates. Why? Because `setEditorState` should ideally return the same EditorState that you have passed it.
In any case, I believe this is a temporary approach, because, as soon as we move `setEditorState` to be part of an update we can drop the selection easily with a $ function. Currently, it's complicated because an EditorState is immutable
> setEditorState ignoreSelection flag

- packages/lexical-playground/src/nodes/TweetNode.jsx
- packages/lexical-playground/src/nodes/YouTubeNode.jsx
- packages/lexical-playground/src/plugins/TwitterPlugin.js
- packages/lexical-playground/src/plugins/YouTubePlugin.js
Should fix https://github.com/facebook/lexical/issues/1696.
https://user-images.githubusercontent.com/7748470/163989526-98345536-3dbb-43b9-9bd7-63ecb5923b38.mov
> Fix bug with alignment for root level decorator nodes v2

- .prettierignore
- packages/lexical-playground/__tests__/e2e/TextEntry.spec.mjs
- packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.js
- packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.js
- packages/lexical-selection/src/__tests__/utils/index.js
- packages/lexical/src/LexicalSelection.js
Oops! Added a test so we won't hit this one again.
Fixes #1861
> Fix issue with inserting paragraphs between text nodes.

- packages/lexical-playground/src/plugins/ActionsPlugin.jsx
ActionsPlugins -> ActionsPlugin
> Fix typo in ActionsPlugin

- packages/lexical/flow/Lexical.js.flow
Follow up to https://github.com/facebook/lexical/pull/1906. This should also fix the CI.
> Fix Lexical.js.flow

- playwright.config.js
I don't think tests that hit the global timeout are being properly retried. Let's try this config.
> Change timeout config

- packages/lexical-playground/src/plugins/ToolbarPlugin.jsx
- packages/lexical-playground/src/utils/toolbar-shortcut.js
add a title with a shortcut to toolbar plugins
> Add title to toolbar plugins

- packages/lexical-code/src/index.js
- packages/lexical-dragon/src/index.js
- packages/lexical-offset/src/index.js
- packages/lexical-playground/src/plugins/AutocompletePlugin.jsx
- packages/lexical-react/src/shared/useCharacterLimit.js
- packages/lexical-selection/src/index.js
- packages/lexical-table/src/LexicalTableSelection.js
- packages/lexical-table/src/LexicalTableSelectionHelpers.js
- packages/lexical-text/src/index.js
- packages/lexical-yjs/src/Utils.js
- packages/lexical/Lexical.d.ts
- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/LexicalNode.js
- packages/lexical/src/LexicalSelection.js
- packages/lexical/src/LexicalUtils.js
- packages/lexical/src/__tests__/unit/LexicalNode.test.js
- packages/lexical/src/nodes/LexicalParagraphNode.js
- packages/lexical/src/nodes/LexicalTextNode.js
Moved `isComposing` to `TextNode` and removed `getTextContentSize` from `LexicalNode`
> cleanup LexicalNode

- packages/lexical-website-new/docusaurus.config.js
- packages/lexical-website-new/package.json
I've installed algolia config and package as well. We have to apply to get algolia search
https://docsearch.algolia.com/apply/
It asks for details regarding organisation. Can someone help here? 
fixes 
- https://github.com/facebook/lexical/issues/1759
> Add algolia config

- packages/lexical-website-new/i18n/en/code.json
- packages/lexical-website-new/i18n/en/docusaurus-theme-classic/footer.json
A previous PR updated this copy, but we didn't run the write-translations script, so the changes didn't actually take effect. This updates the translatitons.
https://github.com/facebook/lexical/pull/1921
> Fix translations

- packages/lexical-react/src/LexicalTreeView.jsx
> fixed formatting for sub and sup options

- packages/lexical-playground/src/plugins/TypingPerfPlugin.js
This should change the measurement heuristics in cases where UI changes might occur in selectionchange, before the setTimeout fires. This causes the toolbar UI to be included in typing metrics, which isn’t correct.
> Improve typing perf accuracy

- packages/lexical-list/src/formatList.js
- packages/lexical-playground/__tests__/e2e/ElementFormat.spec.mjs
- packages/lexical-playground/src/plugins/ToolbarPlugin.jsx
- packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.js
- packages/lexical-selection/src/index.js
- packages/lexical/src/LexicalEvents.js
- packages/lexical/src/LexicalSelection.js
Fixes https://github.com/facebook/lexical/issues/1961. Fixes https://github.com/facebook/lexical/issues/1954.
We had some wonky logic in the handling of elements and also formatting when not collapsed that are fixed by this PR.
> Refine Selection mechanics

- packages/lexical-playground/__tests__/e2e/List.spec.mjs
- packages/lexical-selection/src/index.js
- packages/lexical/src/LexicalSelection.js
Turns out we didn't handle the logic correctly when working with a single node that is both the start and end!
Fixes https://github.com/facebook/lexical/issues/1966
> Fix offset issue when copying Lexical content

- packages/lexical-code/src/index.js
- packages/lexical-dragon/src/index.js
- packages/lexical-offset/src/index.js
- packages/lexical-playground/src/plugins/AutocompletePlugin.jsx
- packages/lexical-react/src/shared/useCharacterLimit.js
- packages/lexical-selection/src/index.js
- packages/lexical-table/src/LexicalTableSelection.js
- packages/lexical-table/src/LexicalTableSelectionHelpers.js
- packages/lexical-text/src/index.js
- packages/lexical-yjs/src/Utils.js
- packages/lexical/Lexical.d.ts
- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/LexicalNode.js
- packages/lexical/src/LexicalSelection.js
- packages/lexical/src/LexicalUtils.js
- packages/lexical/src/__tests__/unit/LexicalNode.test.js
- packages/lexical/src/nodes/LexicalParagraphNode.js
- packages/lexical/src/nodes/LexicalTextNode.js
As discussed here: https://github.com/facebook/lexical/pull/1920
> Revert "cleanup LexicalNode (#1920)"

- packages/lexical-playground/src/App.jsx
> Fix class -> className in react

- packages/lexical-playground/__tests__/e2e/Keywords.spec.mjs
- packages/lexical/src/LexicalEvents.js
- packages/lexical/src/LexicalReconciler.js
Extracted from https://github.com/facebook/lexical/pull/1943.
> Add skipNativeSelectionDiff to reconciler

- packages/lexical-code/LexicalCode.d.ts
- packages/lexical-code/flow/LexicalCode.js.flow
- packages/lexical-code/src/__tests__/unit/LexicalCodeNode.test.js
- packages/lexical-code/src/index.js
- packages/lexical-list/LexicalList.d.ts
- packages/lexical-list/flow/LexicalList.js.flow
- packages/lexical-list/src/LexicalListItemNode.js
- packages/lexical-list/src/LexicalListNode.js
- packages/lexical-list/src/formatList.js
- packages/lexical-playground/__tests__/e2e/ElementFormat.spec.mjs
- packages/lexical-playground/__tests__/e2e/Indentation.spec.mjs
- packages/lexical-react/src/shared/useList.js
- packages/lexical-rich-text/src/index.js
- packages/lexical-table/LexicalTable.d.ts
- packages/lexical-table/flow/LexicalTable.js.flow
- packages/lexical-table/src/LexicalTableCellNode.js
- packages/lexical-table/src/LexicalTableNode.js
- packages/lexical-table/src/LexicalTableRowNode.js
- packages/lexical/Lexical.d.ts
- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/LexicalReconciler.js
- packages/lexical/src/nodes/LexicalElementNode.js
Fixes https://github.com/facebook/lexical/issues/1981. Introduces, `ElementNode.canIndent()` method to help assist in getting the right behavior for specific elements.
> Improve multi element indentation

- .flowconfig
Ignore the autogenerated NPM (release) folder
> Flow ignore npm folder

- packages/lexical-list/src/LexicalListItemNode.js
- packages/lexical-list/src/__tests__/unit/LexicalListItemNode.test.js
- packages/lexical-list/src/formatList.js
- packages/lexical-playground/__tests__/e2e/BlockWithAlignableContents.spec.mjs
- packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
- packages/lexical-playground/__tests__/e2e/List.spec.mjs
- packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
- packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs
This PR fixes collaboration issues around lists. Specifically, how the value of list items is handled. For some reason, we never put it on the node as a property, which mean it could never be syncronized across clients. :/
> Fix collab bugs

- packages/lexical-website-new/docs/collaboration.md
- packages/lexical-website-new/docs/collaboration/_category_.json
- packages/lexical-website-new/docs/collaboration/react.md
Credit goes to @rchrd2 https://discuss.yjs.dev/t/lexical-text-editor/1087/3
> Add collaboration example with yjs

- packages/lexical/src/LexicalReconciler.js
This revises the logic and makes it special case only for iOS/Safari where we have an anchor type of element. We always need to set the selection in this case.
> Fix selection bug

- packages/lexical-playground/src/plugins/CharacterStylesPopupPlugin.jsx
The first render was never processed - we were only handling after the next event
Closes https://github.com/facebook/lexical/issues/2015
> Fix floating toolbar not showing on render

- packages/lexical-plain-text/src/index.js
- packages/lexical-rich-text/src/index.js
- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/LexicalEditor.js
- packages/lexical/src/LexicalUpdates.js
- packages/lexical/src/LexicalUtils.js
> Fix bad optional command payload

- packages/lexical-playground/src/plugins/CommentPlugin.jsx
This PR tweaks comment selection so it's a bit more responsive.
> Improve comment selection

- packages/lexical-playground/src/plugins/CharacterStylesPopupPlugin.jsx
- packages/lexical-playground/src/plugins/CommentPlugin.jsx
Make the UI of the playground a little nicer!
> Fix positioning when window resizes

- packages/lexical/src/LexicalNode.js
Not sure why we needed to map all the keys to a Set and then check the Set - might be missing something.
> Simplify isSelected

- packages/lexical/Lexical.d.ts
Follow up on #1906
**I have very limited knowledge in Typescript**, I don't even know how I can test that the syntax is correct (I pasted it in https://www.typescriptlang.org/play and it seemed fine) or how to test it.
> Add type predicate to $isLeafNode in Lexical.d.ts

- packages/lexical-playground/src/plugins/CharacterStylesPopupPlugin.jsx
> Fix CharacterStyles position

- packages/lexical-playground/src/plugins/CommentPlugin.jsx
This introduces a new state value to tracked MarkNode's that are selected rather than trying to derive it from a Map – which doesn't always work with React concurrent mode due to how it handles async updates and batching.
> Improve CommentPlugin mark selection consistency

- packages/lexical-playground/__tests__/e2e/Links.spec.mjs
- packages/lexical/src/LexicalSelection.js
Fixes https://github.com/facebook/lexical/issues/2056.
> Fix bug in insertParagraph

- packages/lexical/Lexical.d.ts
- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/LexicalEditor.js
- packages/lexical/src/__tests__/unit/LexicalEditor.test.js
> feat(parseEditorState): adding support for parsed JSON in addition to stringified JSON

- packages/lexical-playground/src/appSettings.js
- packages/lexical-playground/src/plugins/CommentPlugin.jsx
This was another obvious issue on reflection. We should check against no real text being selected.
> Fix wrap node bug

- packages/lexical-playground/src/index.css
- packages/lexical-playground/src/plugins/CharacterStylesPopupPlugin.jsx
- packages/lexical-playground/src/ui/ContentEditable.css
Fixes https://github.com/facebook/lexical/issues/2079.
> Fix character styles position + caret color

- packages/lexical-mark/flow/LexicalMark.js.flow
- packages/lexical-mark/src/MarkNode.js
- packages/lexical-mark/src/index.js
- packages/lexical-playground/src/plugins/CommentPlugin.jsx
- packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
- packages/lexical-playground/src/themes/PlaygroundEditorTheme.js
- packages/lexical-react/package.json
- packages/lexical-react/src/LexicalTreeView.jsx
- packages/lexical-utils/LexicalUtils.d.ts
- packages/lexical-utils/flow/LexicalUtils.js.flow
- packages/lexical-utils/src/index.js
- packages/lexical-yjs/src/index.js
- packages/lexical/Lexical.d.ts
- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/LexicalEditor.js
Improves commenting by adding support for overlapping comments.
> Commenting improvements

- packages/lexical-playground/src/App.jsx
- packages/lexical-playground/src/Editor.jsx
Updates the text to reflection the correct location and also adds a console.warn for those peaking about and profiling.
> Update debug view prompt

- packages/lexical/src/LexicalSelection.js
There was a TODO that needed addressing appropriately, this PR resolves that.
> Improve insertText heuristic, address TODO

- packages/lexical/src/LexicalSelection.js
We were missing some cache invalidation in a few areas, and also missing marking the selection is dirty too.
> Fix missing cache invalidation logic

- package-lock.json
- packages/lexical-headless/package.json
- scripts/npm/packages.js
- scripts/updateVersion.js
Some missing refs to headless package in release scripts
> Add missing references for headless package

- packages/lexical-mark/LexicalMark.d.ts
- packages/lexical-playground/src/plugins/CharacterStylesPopupPlugin.tsx
- packages/lexical-playground/src/plugins/CommentPlugin.tsx
- packages/lexical-utils/LexicalUtils.d.ts
> Add comment button to CharacterStylesPopupPlugin

- packages/lexical-code/package.json
- packages/lexical-dragon/package.json
- packages/lexical-file/package.json
- packages/lexical-hashtag/package.json
- packages/lexical-headless/package.json
- packages/lexical-plain-text/package.json
- packages/lexical-rich-text/package.json
These entrypoints should point to the js files in the bundle.
> Fix extensions

- packages/lexical-list/src/formatList.js
- packages/lexical-playground/__tests__/e2e/List.spec.mjs
Fix for #2142
https://user-images.githubusercontent.com/132642/167981375-624f4bb0-2cde-49f9-9bfc-7231008183fd.mov
https://user-images.githubusercontent.com/132642/167981418-2619bc3d-305d-4ab0-bf62-50995b739a69.mov
> Replace element node with list item instead of appending. Fix #2142

- package-lock.json
- package.json
> Add `utility-types` to package.json

- packages/lexical/src/LexicalConstants.js
- packages/lexical/src/LexicalEvents.js
- packages/lexical/src/LexicalUtils.js
- packages/lexical/src/nodes/LexicalTextNode.js
This should fix https://github.com/facebook/lexical/issues/2123 and possibly https://github.com/facebook/lexical/issues/2168. It also fixes some other composition issues that might affect Chrome + FF too.
> Fix Safari IME issues

- examples/emoticons.md
- jest.config.js
- packages/lexical-dragon/README.md
- packages/lexical-dragon/package.json
- packages/lexical-mark/LexicalMark.ts
- packages/lexical-mark/src/MarkNode.ts
- packages/lexical-mark/src/index.ts
- packages/lexical-playground/vite.config.js
- scripts/build.js
> Migrate `lexical-mark` to TypeScript

- packages/lexical-react/src/shared/useDecorators.js
Hopefully fixes https://github.com/facebook/lexical/issues/2195.
> Improve useDecorators sequencing

- packages/lexical-utils/src/__tests__/unit/LexicalEventHelpers.test.js
- packages/lexical/src/nodes/LexicalTextNode.js
> Support Strikethrough and italic paste from Google Docs

- packages/lexical-react/flow/DEPRECATED_useLexical.js.flow
- packages/lexical-react/flow/DEPRECATED_useLexicalAutoFormatter.js.flow
- packages/lexical-react/flow/DEPRECATED_useLexicalCanShowPlaceholder.js.flow
- packages/lexical-react/flow/DEPRECATED_useLexicalCharacterLimit.js.flow
- packages/lexical-react/flow/DEPRECATED_useLexicalDecorators.js.flow
- packages/lexical-react/flow/DEPRECATED_useLexicalEditorEvents.js.flow
- packages/lexical-react/flow/DEPRECATED_useLexicalHistory.js.flow
- packages/lexical-react/flow/DEPRECATED_useLexicalList.js.flow
- packages/lexical-react/flow/DEPRECATED_useLexicalPlainText.js.flow
- packages/lexical-react/flow/DEPRECATED_useLexicalRichText.js.flow
We need these for syncing back to Meta's internal code base.
> Add missing deprecated types

- packages/lexical-website-new/docs/concepts/serialization.md
Add docs for HTML serialization
> Serialization docs

- packages/lexical/src/LexicalEvents.ts
- packages/lexical/src/LexicalReconciler.ts
- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/LexicalUpdates.ts
- packages/lexical/src/LexicalUtils.ts
Based on the comments of https://github.com/facebook/lexical/pull/2209. Addresses issues in comments and also a regression in scroll behavior around anchor points on element nodes.
> Alter sequence for commitPendingUpdates

- packages/lexical/src/LexicalReconciler.ts
- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/LexicalUtils.ts
Removes some unnecessary runtime checks.
> Simplify runtime logic

- packages/lexical-clipboard/src/clipboard.ts
- packages/lexical/src/nodes/LexicalLineBreakNode.ts
This extracts improvements out of https://github.com/facebook/lexical/pull/2241.
> Improve copy + paste logic

- packages/lexical-code/src/__tests__/unit/LexicalCodeNode.test.ts
- packages/lexical-hashtag/src/__tests__/unit/LexicalHashtagNode.test.ts
Just a couple more tests to alert us if serialization interfaces change.
> Serialization tests

- packages/lexical-react/src/LexicalAutoFocusPlugin.ts
- packages/lexical/Lexical.d.ts
- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/LexicalUtils.ts
Fixes https://github.com/facebook/lexical/issues/2280.
> Improve scroll plugin

- packages/lexical/Lexical.d.ts
- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/LexicalUtils.ts
Let's avoid exposing the raw Set.
> Revise $hasUpdateTag

- packages/lexical/src/LexicalEditor.ts
- packages/lexical/src/nodes/LexicalDecoratorNode.ts
We should be keeping consistent.
> Ensure decorator warnings are consistent with other warnings

- packages/lexical-website-new/docs/concepts/commands.md
I fixed broken link in lexical-website-new.
> Fix broken link

- packages/lexical-playground/__tests__/e2e/CharacterLimit.spec.mjs
- packages/lexical-playground/__tests__/e2e/Emoticons.spec.mjs
- packages/lexical-playground/src/plugins/MentionsPlugin.tsx
- packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
- packages/lexical-selection/src/__tests__/utils/index.ts
- packages/lexical-yjs/src/Utils.ts
- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/__tests__/unit/LexicalNode.test.ts
Immutable nodes were renamed as tokens.
> Remove immutable node references

- packages/lexical-link/src/index.ts
- packages/lexical-mark/src/MarkNode.ts
- packages/lexical-overflow/src/index.ts
- packages/lexical-playground/src/nodes/StickyNode.tsx
- packages/lexical-playground/src/plugins/CommentPlugin.tsx
- packages/lexical-rich-text/src/index.ts
This fix various issues in core/playground with serialization methods that were missing.
> Fix various JSON/HTML issues

- packages/lexical-react/src/LexicalCheckListPlugin.tsx
https://user-images.githubusercontent.com/6481831/171696493-6e2e66f9-0284-4729-8083-5269a38f9818.mov
> Disable checklist items in readOnly mode

- packages/lexical-playground/src/ui/Placeholder.css
> fix placeholder overflow

- packages/lexical-link/src/index.ts
Fixes https://github.com/facebook/lexical/issues/2329.
> Fix link toggle bug

- packages/lexical-website-new/docs/concepts/serialization.md
Makes it clearer how to use headless vs no headless.
> Update serialization docs

- scripts/build.js
We don't use these anymore since moving to Vite.
> Remove watch mode scripts

- packages/lexical/src/LexicalUpdates.ts
The was caught from an internal issue.
> Avoid possible reconciler infinite loops

- packages/lexical-playground/src/Editor.tsx
- packages/lexical-playground/src/collaboration.ts
- packages/lexical-playground/src/commenting/index.ts
- packages/lexical-playground/src/plugins/CommentPlugin.tsx
- packages/lexical-react/LexicalCollaborationPlugin.d.ts
This PR adds Yjs collaboration support to the playground CommentPlugin.
> Add collaboration support for commenting

- packages/lexical-playground/src/plugins/TwitterPlugin.ts
- packages/lexical-playground/src/plugins/YouTubePlugin.ts
> Handle other selection types for embed

- packages/lexical-playground/src/ui/ColorPicker.css
- packages/lexical-playground/src/ui/ColorPicker.tsx
Introduces an input field in the color picker
https://user-images.githubusercontent.com/64399555/172930181-2508094d-e46a-46bd-b595-0bd0debbce68.mp4
> feat: color picker input

- packages/lexical-markdown/README.md
- packages/lexical-website-new/docs/collaboration/react.md
> fix(doc): inconsistency in import names

- packages/lexical-clipboard/src/clipboard.ts
Fixes #2405
> Sometimes other rich text apps only include the list items on the clipboard without the parent list and this breaks @lexical/list since it expects all ListItemNodes to be within a ListNode parent.
https://user-images.githubusercontent.com/13852400/173455405-c00e5b0a-8116-4a1d-b889-5f7c4c2236d1.mov
> Prevent orphan ListItems on clipboard from crashing the editor

- packages/lexical-website-new/docs/getting-started/react.md
> docs(react): add "namespace" to "initialConfig"

- packages/lexical-link/src/index.ts
Fix an incorrect import which is blocking syncs with WWW
> Fix non-existant Spread import

- packages/lexical-playground/src/index.css
- packages/lexical-playground/src/plugins/ToolbarPlugin.tsx
> fix: highlight in dropdown

- scripts/build.js
Tested internally and the sync works with this PR.
> Exclude TS files from WWW build

- .lintstagedrc.js
- packages/lexical-history/src/index.ts
This is causing some bugs internally.
This reverts commit 60ea11b5a67af5c55f9eca2b3cb8b41d7d56e521.
> Revert "Prevent dispatching redundant can undo/redo commands (#2394)"

- scripts/clean.js
- scripts/npm/packages.js
The shared PKG package was never cleaned up
> shared PKG to cleanup

- packages/lexical-playground/__tests__/e2e/MaxLength.spec.mjs
This reverts commit e5b574dcce6dd03470ff780fcc72b82619db8333.
> Revert "add e2e tests for MaxLength plugin (#2466)"

- packages/lexical/src/LexicalEvents.ts
I had this in my local branch last week and was going to use it for a topic on an internal IME talk but never got the chance. Best to put up the PR and land this fix before I forget when I come back from parental leave!
> Fix FF issue with composition

- packages/lexical/src/LexicalMutations.ts
- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/LexicalUpdates.ts
- packages/lexical/src/LexicalUtils.ts
Make suggested amend by @trueadm in #2482 and building on top of #2487.
Tested internally with enhanced E2E suite and all are passing as expected.
> Migrate to TS strict mode 5/n

- packages/lexical-playground/src/nodes/ImageNode.tsx
- packages/lexical/src/nodes/LexicalParagraphNode.ts
Fixes copy+paste of images on the playground.
> Fix image copy+paste

- packages/lexical/src/LexicalMutations.ts
- packages/lexical/src/LexicalNode.ts
- scripts/error-codes/codes.json
> fix: typo edtior to editor

- package-lock.json
- packages/lexical-clipboard/package.json
- packages/lexical-html/package.json
> Add missing dependencies

- packages/lexical-playground/__tests__/e2e/CharacterLimit.spec.mjs
- packages/lexical-playground/__tests__/e2e/Composition.spec.mjs
- packages/lexical-playground/__tests__/e2e/Emoticons.spec.mjs
- packages/lexical-playground/__tests__/e2e/History.spec.mjs
- packages/lexical-playground/__tests__/e2e/HorizontalRule.spec.mjs
- packages/lexical-playground/__tests__/e2e/Mentions.spec.mjs
- packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
- packages/lexical-playground/__tests__/e2e/TextEntry.spec.mjs
- packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs
- packages/lexical-playground/__tests__/keyboardShortcuts/index.mjs
- packages/lexical-playground/__tests__/regression/231-empty-text-nodes.spec.mjs
Uses keyboard shortcuts introduced in previous PRs
> chore: use keyboard shortcuts

- packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
- packages/lexical/src/nodes/LexicalTextNode.ts
https://user-images.githubusercontent.com/64399555/176701853-0ef15dee-18c7-4b92-8498-11381ee0aeae.mp4
> fix: import color and vertical align info from html string

- packages/lexical-code/src/index.ts
- packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs
- packages/lexical/src/nodes/LexicalTextNode.ts
> Fix pasting inline code blocks

- packages/lexical-playground/src/App.tsx
- packages/lexical-playground/src/index.css
- packages/lexical-playground/src/plugins/PasteLogPlugin.tsx
Have you ever asked yourself: "what's on my clipboard"?
If so, this PR's got something for you!
**Is it beautiful?** 
No.
**Does it work?** 
Probably.
**Will it show you what's on your clipboard?** 
YES! It sure will.
This is behind the isDevPlayground flag, so it will only show up in local environments for now. I'm working on a better design for this, maybe stealing @zurfyx's idea to put it in with the tree view. We can merge it as-is or if people have ideas I can iterate on the UI.
https://user-images.githubusercontent.com/14864325/177725652-804ecdbc-460a-453b-87b6-3f5b90d97bc3.mov
> I just wanna know what's on my clipboard.

- packages/lexical-playground/src/nodes/TweetNode.tsx
I added a separate flag for checking if the Twitter script has been loaded instead of just checking to see if the script element has been created.
The bug in the below issue was caused because `getHasScriptCached` would return `true` even though the API request had not fully resolved.
Closes #2612
> Fix TweetNode not loading on editor state import

- packages/lexical-playground/src/plugins/TwitterPlugin.ts
- packages/lexical-playground/src/plugins/YouTubePlugin.ts
- packages/lexical-utils/flow/LexicalUtils.js.flow
- packages/lexical-utils/src/index.ts
> Add $insertBlockNode

- packages/lexical-markdown/src/v2/MarkdownImport.ts
- packages/lexical-playground/__tests__/e2e/Markdown-v2.spec.mjs
> Fix markdown text matchers during md import

- packages/lexical-playground/__tests__/e2e/AutoLinks.spec.mjs
- packages/lexical-playground/src/plugins/AutoLinkPlugin.tsx
Closes #2653
Should probably follow up with user-entered URLs, even though these are in a better position because you can change them
> Autolink default protocol

- packages/lexical-playground/src/nodes/TweetNode.tsx
- packages/lexical-playground/src/nodes/YouTubeNode.tsx
- packages/lexical-playground/src/plugins/ToolbarPlugin.tsx
https://user-images.githubusercontent.com/7748470/179281529-88300cee-385e-4876-81ae-16f82e6e7e28.mov
Closes #1779
> Add text fallbacks to YouTubeNode and TweetNode on conversion to CodeBlock

- docs/design.md
- packages/lexical-clipboard/src/clipboard.ts
- packages/lexical-code/src/CodeHighlighter.ts
- packages/lexical-headless/src/__tests__/unit/LexicalHeadlessEditor.test.ts
- packages/lexical-list/src/__tests__/unit/utils.test.ts
- packages/lexical-markdown/src/convertToMarkdown.ts
- packages/lexical-offset/src/index.ts
- packages/lexical-plain-text/src/index.ts
- packages/lexical-playground/src/plugins/ClickableLinkPlugin/index.ts
- packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx
- packages/lexical-react/src/__tests__/unit/Collaboration.test.ts
- packages/lexical-rich-text/src/index.ts
- packages/lexical-yjs/src/SyncEditorStates.ts
- packages/lexical/src/LexicalEditor.ts
- packages/lexical/src/LexicalReconciler.ts
- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/LexicalUpdates.ts
- packages/lexical/src/LexicalUtils.ts
- packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx
- packages/lexical/src/nodes/LexicalElementNode.ts
> chore: fix some typo

- packages/lexical-playground/src/nodes/PollNode.css
> fix: cross button css in poll node

- packages/lexical-website-new/src/components/CommunityHowToContribute/index.js
@yangshun knows that I-dont-like-typos 😄
> Fix typo in community page

- packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs
- packages/lexical-playground/src/index.css
- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
feat: replace select with dropdown for code
> feat: Replace select with dropdown for code

- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
> chore: fix aria-label typo

- packages/lexical/src/LexicalUtils.ts
> fix(lexical): ts expect error

- packages/lexical/src/__tests__/unit/LexicalNode.test.ts
Fixes noisy warnings in unit tests runs.
> Make importJSON static in TestNode

- packages/lexical-playground/src/plugins/CommentPlugin/index.tsx
- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
- scripts/build.js
Thanks for open sourcing this awesome editor. 
Some things that I noticed while trying to build the playground, they're unrelated but each in a separate commit.
> chore(lexical-playground): typos, improved build

- packages/lexical/src/LexicalReconciler.ts
- packages/lexical/src/LexicalUtils.ts
Fix internal build error caused by linting of invariant errors.
> Fix internal build error

- packages/lexical-markdown/src/MarkdownShortcuts.ts
- packages/lexical-playground/__tests__/e2e/Markdown-v2.spec.mjs
Fixes #2783
https://user-images.githubusercontent.com/132642/183533142-ba39a9b9-2b18-4ed4-9ff6-9f79932068cf.mov
> Fix selection adjustment after text match transformer

- packages/lexical-playground/src/nodes/AutocompleteNode.tsx
- packages/shared/src/environment.ts
> chore: add some declare global

- packages/lexical-link/src/index.ts
- packages/lexical-playground/__tests__/e2e/Links.spec.mjs
- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
- packages/lexical-react/src/LexicalTreeView.tsx
1. Fix #2816
2. Floating toolbar will now show up on collapsed selection on links
3. TreeView displays link and link node properties
Closes https://github.com/facebook/lexical/issues/2816
> Fix collapsed selection on links

- packages/lexical-code/src/CodeNode.ts
Closes https://github.com/facebook/lexical/issues/2822 https://github.com/facebook/lexical/issues/2821
> Fix Code imports

- packages/lexical-website-new/docs/concepts/commands.md
- packages/lexical-website-new/docs/concepts/transforms.md
Fixes some broken repo links in the docs.
> fix: broken links in docs

- packages/lexical-mark/src/MarkNode.ts
> Rename local variables

- packages/lexical-react/flow/LexicalCollaborationPlugin.js.flow
> Fix small type issue in `LexicalCollaborationPlugin.js.flow`

- packages/lexical/src/LexicalEvents.ts
> Revert inadvertent change

- packages/lexical-playground/src/plugins/CommentPlugin/index.css
Noticed this redundant css property so decided to clean it up.
> Remove redundant css property

- packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx
- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
- packages/lexical-playground/src/utils/sanitizeUrl.ts
This is new PR for #2825, removed the package.json commit.
> Added sanitizer to FloatingLinkEditor

- packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
> fixed typo

- packages/lexical/src/LexicalEditor.ts
- packages/lexical/src/LexicalEvents.ts
- packages/lexical/src/LexicalMutations.ts
- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/LexicalUtils.ts
- scripts/error-codes/codes.json
Fixes https://github.com/facebook/lexical/issues/2108.
> Use window of current default view

- packages/lexical-website/docs/getting-started/theming.md
_properies_ was used instead of properties
> Fix typo in theming.md

- packages/lexical-react/src/LexicalComposer.tsx
- packages/lexical-website/docs/concepts/read-only.md
- packages/lexical/src/LexicalEditor.ts
> Fix editable property being forced to true

- packages/lexical-playground/src/Editor.tsx
It was accidentally removed in #2929
> Add table cell menu back

- packages/lexical-react/src/LexicalContentEditable.tsx
- packages/lexical/src/LexicalEditor.ts
> Fix bugs with isEditable

- packages/lexical-yjs/src/Bindings.ts
- packages/lexical-yjs/src/CollabDecoratorNode.ts
- packages/lexical-yjs/src/CollabElementNode.ts
- packages/lexical-yjs/src/CollabTextNode.ts
- packages/lexical-yjs/src/SyncEditorStates.ts
- packages/lexical-yjs/src/Utils.ts
- scripts/error-codes/codes.json
We had bunch of "Should never happen" exceptions, and then they happened 🤷‍♂️
> Update collab errors, related cleanup

- packages/lexical-code/src/CodeHighlighter.ts
Nested updates on transforms do not happen immediately after the transform, instead at the end of the transform loop. This is causing a rare condition on highlights as it relies on the node reference to be alive. 
Instead, we want to use the NodeKey instead and validate properly.
Closes https://github.com/facebook/lexical/issues/3023
> Fix code highlighter race condition on transform

- packages/lexical-website/docs/collaboration/react.md
- Note regarding editor state for composer
- Newly added initialEditorState for collab plugin
> Update collab docs

- packages/lexical-website/docs/faq.md
$getRoot need to be called to return a root node.
error screenshot:
> Update faq.md to fix error of clearing contents

- scripts/www/rewriteImports.js
Annotation is missing from generated files.
> Add oncall annotation

- packages/lexical-playground/src/index.css
- packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx
Before:
https://user-images.githubusercontent.com/13852400/192622552-0c426932-c78e-403d-a801-9d7519e7fd0f.mov
After:
https://user-images.githubusercontent.com/13852400/192622565-533b01ee-eabc-4e6f-a6ae-0c3f3074f1a8.mov
> Fix Resize and Scroll Positioning on Typeahead/Node Menu

- packages/lexical-website/docs/concepts/commands.md
I removed the extra 'is' in line 9 which I believe is a typographical error.
> Removed extra 'is' in line 9

- packages/lexical/src/LexicalNode.ts
- packages/lexical/src/LexicalReconciler.ts
- packages/lexical/src/nodes/LexicalElementNode.ts
Working on broader lifecycle documentation - this is just saving my progress, basically.
> Add some inline documentation

- packages/lexical-playground/__tests__/e2e/AutoLinks.spec.mjs
- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
- packages/lexical-react/src/LexicalAutoLinkPlugin.ts
> Add logic to catch separators

- packages/lexical-react/flow/LexicalTypeaheadMenuPlugin.js.flow
- packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx
Accidentally made this required #3087.
> Make onClose optional on Flow Types.

- packages/lexical/src/LexicalSelection.ts
https://user-images.githubusercontent.com/193447/194315509-00153074-e5a4-46c4-999c-e54013d7b8f6.mp4
Closes https://github.com/facebook/lexical/issues/3130
> Fix table paste

- packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx
> Support multiple classes

- README.md
- packages/lexical-website/docs/intro.md
We should have removed this ages ago as it's no longer valid.
> Remove development notice

- packages/lexical-code/src/CodeNode.ts
- packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
Closes https://github.com/facebook/lexical/issues/3173
> Fix copy-paste CodeBlock with BR

- packages/lexical-playground/__tests__/regression/3136-insert-nodes-adjacent-to-inline.spec.mjs
- packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
- packages/lexical/src/LexicalSelection.ts
> Fix insertNodes when replacing content adjacent to an inline element

- .github/workflows/dev-release.yml
- .github/workflows/nightly-release.yml
- scripts/npm/release.js
Next step is to automate tagging.
> Nightly and Dev releases

- packages/lexical-react/src/LexicalTreeView.tsx
Fixes #3196 
https://user-images.githubusercontent.com/42532987/196240849-5d891d98-d9e0-4f1a-8639-72b6098837c6.mp4
> fix: play `time travel` after reaching maximum range

- package-lock.json
- packages/lexical-list/src/formatList.ts
- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
- packages/lexical-selection/src/range-selection.ts
https://user-images.githubusercontent.com/13852400/196535010-c60c61cc-f306-4915-bfa9-91b4c82711b8.mov
> Allow Block change with GridSelection

- packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
- packages/lexical-selection/src/lexical-node.ts
> Don't apply element based offsets to text nodes in $patchStyleText

- packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
- packages/lexical-table/src/LexicalTableSelectionHelpers.ts
Before
https://user-images.githubusercontent.com/13852400/196785448-43576860-81a9-46fc-a85f-677deb6afc16.mov
After
https://user-images.githubusercontent.com/13852400/196785485-3b4bf307-9b58-40d9-86f3-b1d8687c23c1.mov
> Fix TableSelection Mouse Up Propagation Bug

- packages/lexical-react/src/DEPRECATED_useLexicalDecorators.tsx
- packages/lexical-react/src/LexicalPlainTextPlugin.tsx
- packages/lexical-react/src/LexicalRichTextPlugin.tsx
- packages/lexical-react/src/shared/useDecorators.tsx
Closes https://github.com/facebook/lexical/issues/3224
> Memoize ErrorBoundary

- packages/lexical-mark/flow/LexicalMark.js.flow
- packages/lexical-mark/src/index.ts
This should allow this function to work for MarkNode subclasses
> Allow overriding mark node create function

- packages/lexical-playground/src/index.css
- packages/lexical-playground/src/plugins/DraggableBlockPlugin/index.css
- packages/lexical-playground/src/plugins/DraggableBlockPlugin/index.tsx
- packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.css
- packages/lexical-playground/src/plugins/FloatingTextFormatToolbarPlugin/index.css
- packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
- packages/lexical-playground/src/utils/setFloatingElemPosition.ts
Reduce rendering consumption by creating compositing layers
> pref(lexical-playground): reduce rendering consumption by creating compositing layers

- package-lock.json
- packages/lexical-playground/__tests__/utils/index.mjs
- packages/lexical-table/flow/LexicalTable.js.flow
- packages/lexical-table/src/LexicalTableSelection.ts
- packages/lexical-table/src/LexicalTableSelectionHelpers.ts
There were some reports of the mouse cursor jumping, copy + paste acting a bit funky, and text selection within cells not working as intended. This PR aims to fix this.
https://user-images.githubusercontent.com/13852400/197644587-6d01b509-52ea-4ded-b114-8d24ee13cb0b.mov
> Improve logistics around table/grid selection

- packages/lexical-selection/flow/LexicalSelection.js.flow
- packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
- packages/lexical-selection/src/lexical-node.ts
> Allow clearing styles with $patchStyleText

- packages/lexical-code/src/CodeHighlighter.ts
The `isHighlighting` flag gets set to `true` when there is more than 1 `CodeNode` rendered on the page on load, causing subsequent `CodeNodes` to not get highlighted.
Fixes #3257
> Refactor `isHighlighting` flag into object literal

- packages/lexical-code/src/CodeHighlighter.ts
https://github.com/facebook/lexical/pull/3256#discussion_r1004847199
> Use set for highlighting cache

- packages/lexical-code/src/CodeNode.ts
- packages/lexical-link/src/index.ts
- packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
1. CodeNode importDOM logic was leaking onto non-code block
2. Handle empty links
Fixes https://github.com/facebook/lexical/issues/3193
> Fix paste CodeNode leak  and and empty links

- packages/lexical-playground/src/plugins/DragDropPastePlugin/index.ts
- packages/lexical-rich-text/flow/LexicalRichText.js.flow
- packages/lexical-utils/flow/LexicalUtils.js.flow
- packages/lexical-utils/src/index.ts
The need for batching is still not very obvious and verbose - this PR aims to simplify drag&drop&paste further
> DragDropPaste abstraction - mediaFileReader

- packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
- packages/lexical-playground/__tests__/keyboardShortcuts/index.mjs
- packages/lexical-playground/src/Editor.tsx
- packages/lexical-playground/src/nodes/ImageComponent.tsx
- packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx
- packages/lexical-playground/src/plugins/LinkPlugin/index.tsx
- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
- packages/lexical-playground/src/utils/url.ts
- packages/lexical-react/flow/LexicalLinkPlugin.js.flow
- packages/lexical-react/src/LexicalLinkPlugin.ts
Looks like a desirable feature, at least based on the usage inside Meta. Let's make this built-in into the LinksPlugin
https://user-images.githubusercontent.com/193447/202585095-a04f669b-51af-450a-8ab1-56dccc0d4a6e.mov
> LinkPlugin to support link paste

- packages/lexical-dragon/src/index.ts
We should be validating the domains match up for the Dragon plugin.
> Validate dragon origin

- packages/lexical-playground/src/plugins/TablePlugin.tsx
Fixes https://github.com/facebook/lexical/issues/3364
> Fix experimental tables

- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/nodes/LexicalRootNode.ts
This fixes some issues encountered internally around selection bug reports. This probably fixes some reported github issues too!
> Fix selection bugs with decorators

- packages/lexical-playground/__tests__/e2e/Indentation.spec.mjs
- packages/lexical-rich-text/src/index.ts
Fixes https://github.com/facebook/lexical/issues/3388
> Fix element indent duplication

- packages/lexical/src/LexicalSelection.ts
Fixes https://github.com/facebook/lexical/issues/3346.
> Fix insertNodes bug around isolated decorators

- packages/lexical-selection/src/range-selection.ts
Fixes https://github.com/facebook/lexical/issues/3373.
> Fix bad selection on $wrapNodes

- packages/lexical-playground/src/plugins/CollapsiblePlugin/index.ts
- packages/lexical-react/src/LexicalBlockWithAlignableContents.tsx
Fixes #3322, #3339
Will also fix other click-related issues due to wrong event prevention logic in block decorators wrapper (add block decorator, select content, try to click to change selection)
> Fix collapsible bugs

- packages/lexical-code/src/CodeHighlighter.ts
Fixes https://github.com/facebook/lexical/issues/3275.
> Fix selection bug in code highlighting transform

- packages/lexical-rich-text/src/index.ts
- packages/lexical/src/LexicalEvents.ts
Fixes https://github.com/facebook/lexical/issues/3365.
> Apply event propagation between all event types

- packages/lexical-playground/src/plugins/ClickableLinkPlugin/index.ts
- packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx
Fixes https://github.com/facebook/lexical/issues/3358.
> Fix link opening heuristic

- packages/lexical/src/nodes/LexicalTextNode.ts
> Don't unnecessarily mark text nodes as dirty

- packages/lexical-playground/__tests__/e2e/Extensions.spec.mjs
- packages/lexical/src/LexicalEvents.ts
I somehow undid the Grammarly fix when I cleaned up the PR. No idea how I missed that. Added a regression test so it doesn't go missed again.
> Fix grammary 2

- packages/lexical-code/src/CodeNode.ts
- packages/lexical-code/src/index.ts
- packages/lexical/src/index.ts
Exports serialized node types from main lexical package.
> Exports serialized node types

- packages/lexical-playground/src/ui/ImageResizer.tsx
> Fix issue with readonly image resizing

- packages/lexical-react/src/LexicalAutoFocusPlugin.ts
> Update conditional statement in LexicalAutoFocusPlugin to the same logic as in LexicalSelection

- packages/lexical-playground/__tests__/e2e/TextEntry.spec.mjs
Extracted case from https://github.com/facebook/lexical/issues/3460.
> Add e2e test for text replacement

- packages/lexical-playground/__tests__/e2e/TextEntry.spec.mjs
I jumped the gun a bit with https://github.com/facebook/lexical/pull/3470.
> Fix test for collab

- packages/lexical/src/LexicalGC.ts
These were added in https://github.com/facebook/lexical/pull/3478 by accident.
> Revert changes

- packages/lexical/src/nodes/LexicalTextNode.ts
> Add missing annotation to internal field of Textnode

- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/nodes/LexicalLineBreakNode.ts
- packages/lexical/src/nodes/LexicalParagraphNode.ts
> Revert "Fix exportJSON return types for ParagraphNode and LineBreakNode"

- packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
fixes: https://github.com/facebook/lexical/issues/3494
original PR: https://github.com/facebook/lexical/pull/3524
> RTL fix for checkbox

- package-lock.json
- package.json
- packages/lexical-file/src/fileImportExport.ts
- packages/lexical-playground/vite.config.js
- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/LexicalVersion.ts
- packages/lexical/src/index.ts
- scripts/build.js
- tsconfig.json
We don't need this any more as we get the version from the base package.json when we do the update.
> Remove VERSION

- CHANGELOG.md
Missing changelog entry for 0.7
> Add missing changelog entry to 0.7

- packages/lexical/src/LexicalUpdates.ts
Sorry, this is my first PR, I think I didn't line it up with the bug I created earlier - https://github.com/facebook/lexical/issues/3535
I have tested the suggested changes locally and it works as expected.
Sorry for the confusion
> Fix bug 3535

- packages/lexical-playground/src/plugins/ClickableLinkPlugin/index.ts
- packages/lexical-selection/flow/LexicalSelection.js.flow
- packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
- packages/lexical-selection/src/index.ts
This was accidentally removed.
> Add $wrapNodes back to flow

- packages/lexical-text/src/index.ts
Check for ParagraphNode instance rather than type
> Fix placeholder text for custom Paragraph Nodes

- packages/lexical-selection/flow/LexicalSelection.js.flow
I missed something when I added this back earlier.
> Fix flow again

- packages/lexical-react/src/LexicalCheckListPlugin.tsx
Fixes https://github.com/facebook/lexical/issues/3574.
> Fix left arrow selection on list nodes

- packages/lexical/src/LexicalUtils.ts
Closes https://github.com/facebook/lexical/issues/3570
> check read only flag during $setSelection

- packages/lexical-react/src/LexicalTreeView.tsx
- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/LexicalUpdates.ts
We should be using the actual node count here rather than the dirty node count.
> Use the actual node count rather than the dirty node count

- packages/lexical-playground/src/plugins/ImagesPlugin/index.tsx
- packages/lexical-table/src/LexicalTableSelection.ts
- packages/lexical/src/LexicalEditor.ts
- packages/lexical/src/LexicalEvents.ts
- packages/lexical/src/LexicalMutations.ts
- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/LexicalUpdates.ts
- packages/lexical/src/LexicalUtils.ts
A better solution than what I did in https://github.com/facebook/lexical/pull/3573.
> More extensive fixes for Lexical in iframes

- packages/lexical-yjs/src/SyncCursors.ts
Fixes https://github.com/facebook/lexical/issues/3549 and probably a bunch of other bugs with collaboration cursors not working as expected. Turns out we were not assigning the correct position when selection was a type of `element` and furthermore, we weren't validating that this could happen, meaning it could potentially crash a client and cause the cursor to get stuck in the wrong place.
> Fix various collaboration cursor bugs

- packages/lexical/src/nodes/LexicalTextNode.ts
Closes #3548
Copied from Google Docs:
> Fix copy/paste issue with line breaks within paragraphs 

- packages/lexical/src/nodes/LexicalTextNode.ts
https://discord.com/channels/953974421008293909/956360788069744681/1054366339273338990
> Fix import issue with line break nodes

- packages/lexical/src/LexicalSelection.ts
This line was never meant to be here.
> Fix bad rebase

- packages/lexical-playground/src/index.css
> background-repeat: no-repeat;

- packages/lexical-website/docs/concepts/dom-events.md
- packages/lexical-website/sidebars.js
> Add docs re: working with DOM Events

- packages/lexical-website/docs/concepts/listeners.md
> Add docs for root listener

- packages/lexical/src/LexicalUpdates.ts
Fixes https://github.com/facebook/lexical/issues/3160.
> selectionChange fix

- packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.tsx
> Close Excalidraw only on Escape key down

- packages/lexical-react/src/LexicalCheckListPlugin.tsx
> Attach checkbox click listeners to editor root element instead of document

- packages/lexical/src/nodes/LexicalParagraphNode.ts
fixed the issue of missing styling information of paragraph while importing dom
> fix: styling information of paragraph are missing while importing dom

- packages/lexical/src/LexicalReconciler.ts
Fixes https://github.com/facebook/lexical/issues/3687.
> Fix reconciler bug with handling of text content

- packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
- packages/lexical/src/LexicalSelection.ts
Fixes https://github.com/facebook/lexical/issues/3682.
> Fix select all + delete behaviour

- packages/lexical-utils/src/index.ts
Fixes https://github.com/facebook/lexical/issues/2593
> Fix $restoreEditorState

- packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
- packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
- packages/lexical/src/LexicalSelection.ts
Fixes https://github.com/facebook/lexical/issues/3683 and probably a ton of other over-selection bugs.
> Fix over selection

- packages/lexical-utils/package.json
- packages/lexical-utils/src/index.ts
> Fix restoreEditorState

- packages/lexical/src/LexicalSelection.ts
Fixes https://github.com/facebook/lexical/issues/3853.
> Fix backspace regression

- packages/lexical/src/LexicalSelection.ts
Fixes https://github.com/facebook/lexical/issues/3792.
> Ensure deletions capture existing formatting

- libdefs/prismjs.js
- packages/lexical-code/src/CodeHighlightNode.ts
- packages/lexical-code/src/CodeHighlighter.ts
- packages/lexical-code/src/CodeNode.ts
- scripts/build.js
Added the Code highlight of Java and C++ programming lang.
> Added support for Java & C++

- README.md
Badge was outdated (refer to https://github.com/badges/shields/issues/8671).
> Update badge URL in README

- packages/lexical-playground/src/nodes/PollNode.tsx
- packages/lexical-playground/src/plugins/PollPlugin/index.tsx
> Fix PollNode copy and paste missing options

- packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx
Fixes #3830
cc @Karibash
https://user-images.githubusercontent.com/13852400/222200101-3ad4cbb0-2ebb-43b7-b13f-66cafc6cfb59.mov
> Reposition Node Menu when Node Changes

- packages/lexical-selection/src/range-selection.ts
> deprecate $wrapNodes

- .github/workflows/nightly-release.yml
- .github/workflows/test.yml
To be merged after 0.9.0. Reverts facebook/lexical#4071
> Revert "Revert "chore: prevent action from running on forks""

- packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
- packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
- packages/lexical-table/src/LexicalTableUtils.ts
- packages/lexical-table/src/index.ts
https://user-images.githubusercontent.com/193447/224352080-d2bac438-07f9-4afa-8a03-dcd414b15109.mov
> Remove columns w/ span support

- packages/lexical-playground/src/ui/ContentEditable.css
- packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx
Handle the `@media (max-width: 1025px)` case
> Revise padding for smaller res

- packages/lexical-playground/src/plugins/AutoLinkPlugin/index.tsx
- packages/lexical-react/flow/LexicalAutoLinkPlugin.js.flow
- packages/lexical-react/src/LexicalAutoLinkPlugin.ts
> Add a function to create a LinkMatcher based on a RegExp

- packages/lexical-playground/src/plugins/DraggableBlockPlugin/index.tsx
> fix: drag-over event on windows

- packages/lexical-selection/src/lexical-node.ts
- packages/lexical-selection/src/range-selection.ts
- packages/lexical-selection/src/utils.ts
This PR adds inline API documentation to the lexical/selection module.
> Improve Documentation #2845 - lexical/selection

- packages/lexical-playground/src/nodes/PollComponent.tsx
> Fixed `aria-label` typo

- packages/lexical-playground/__tests__/utils/index.mjs
- packages/lexical-playground/src/index.css
- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
Not adding the dropdown buttons just yet as I think we probably want to abstract the methods, but we're also actively rewriting the methods..
> Table toolbar foundation

- packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
- packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
https://user-images.githubusercontent.com/193447/228661844-f8b71a49-20c6-415c-ad74-b3c61b40c48e.mov
> Preserve content with merging cells

- .flowconfig
- package-lock.json
- package.json
- packages/lexical-react/flow/LexicalContentEditable.js.flow
Flow deprecated `$Partial`, this upgrade is a must-have to make types works internally
> Upgrade Flow to 0.2

- packages/lexical-table/src/LexicalTableUtils.ts
Bug: Deleting a table row causes a crash
Fixes https://github.com/facebook/lexical/issues/4265
> last table row delete throwing error

- packages/lexical-playground/src/nodes/EquationComponent.tsx
- packages/lexical-playground/src/ui/KatexEquationAlterer.tsx
- packages/lexical-playground/src/ui/KatexRenderer.tsx
This is a PR to make sure that Katex doesn't blow up the editor page by throwing an uncaught error. 
Closes #4185
> Add try catch around katex renderer

- packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
- packages/lexical-playground/__tests__/utils/index.mjs
- packages/lexical-table/src/LexicalTableNode.ts
- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/nodes/LexicalElementNode.ts
Manually tested deleteForward with a table
> Replace canExtractContents with ShadowRoot check

- packages/lexical-playground/src/plugins/MentionsPlugin/index.tsx
Slightly improve readability of conditions in MentionsPlugin
> Refactor Check for mention match function

- packages/lexical-playground/src/plugins/CodeActionMenuPlugin/components/PrettierButton/index.tsx
This pull request resolves #4309
> Fix crash on prettier formatting fail

- packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
- packages/lexical-playground/__tests__/utils/index.mjs
- packages/lexical-playground/src/Editor.tsx
- packages/lexical-playground/src/appSettings.ts
- packages/lexical-react/flow/LexicalTablePlugin.js.flow
- packages/lexical-react/src/LexicalTablePlugin.ts
- packages/lexical-table/src/LexicalTableCellNode.ts
Gate background color under another TablePlugin feature
> Table feature: background color

- packages/lexical-playground/src/utils/url.ts
Previously you could cause an anchor to be rendered with javascript: url in this editor via.
> Sanitize floatingLinkEditor

- packages/lexical-react/src/LexicalClickableLinkPlugin.tsx
Add missing null check, adjust dom traversal util
> Fix clickable link plugin #4514

- packages/lexical-react/src/shared/useCharacterLimit.ts
https://github.com/facebook/lexical/assets/132642/2ef747d2-4492-45d6-b634-19d2303da2f9
> Max length recalculation. Fix #4542

- packages/lexical-react/src/shared/LexicalMenu.ts
Closes #4545.
Demo (before and after):
https://github.com/facebook/lexical/assets/65129988/4855d4f6-fc19-4f8b-9332-41af475f68ce
> Fix MenuTypeahead position

- packages/lexical-rich-text/src/index.ts
> Don't throw error on format element

- packages/lexical-clipboard/src/clipboard.ts
Brought to you by free in-flight wifi on Delta (no affiliation)
> Add clipboard documentation

- packages/lexical-website/src/pages/docs/error/index.js
- scripts/error-codes/formatProdErrorMessage.js
Follow up for #4627 to support any amount of arguments
> Add error formating params

- packages/lexical-code/src/CodeNode.ts
- packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/HTMLCopyAndPaste.spec.mjs
- packages/lexical/src/nodes/LexicalTextNode.ts
- The language and indentation of code block is preserved when serialized/deserialized
> Preserving language and indentation of code block when serialized/deserialized

- packages/lexical-playground/src/ui/ImageResizer.tsx
- packages/lexical-react/flow/LexicalTablePlugin.js.flow
Fixes #4712
And adds missing flow type for #4689
https://github.com/facebook/lexical/assets/132642/2e0078d6-ba46-4d93-b483-3cdba6e8998e
> Image resizer fix

- packages/lexical-utils/src/__tests__/unit/LexlcaiUtilsInsertNodeToNearestRoot.test.tsx
- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/__tests__/unit/LexicalSelection.test.ts
Trunk seems broken, this one fixes it with some adjustments to #4756
> Fixes broken trunk

- packages/lexical/flow/Lexical.js.flow
> Flow key down command

- packages/lexical/flow/Lexical.js.flow
I faced it after the latest release. A quick fix that removes duplication.
> Remove duplicate declaration

- packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
Fixes #4440 
Before:
https://github.com/facebook/lexical/assets/52599529/396e064f-503a-4122-ad0c-08c36c334adb
After:
https://github.com/facebook/lexical/assets/52599529/c1dd0398-8811-42f5-b4b8-46d8b3cd4140
> Fix width reflow in columns when resizing tables

- packages/lexical/flow/Lexical.js.flow
> Add setStyle to Flow types

- packages/lexical-table/src/LexicalTableSelectionHelpers.ts
> Fix table imports

- packages/lexical-playground/src/plugins/DraggableBlockPlugin/index.tsx
Add support for collapsed margins for draggable blocks in the playground.
**Before**
https://github.com/facebook/lexical/assets/46543621/0472a2ba-5171-4e6f-bd3b-b40d875a4d1f
**After**
https://github.com/facebook/lexical/assets/46543621/76d9c86d-ca60-4067-9711-582e58f4c937
> feat(playground): add support for collapsed margins in draggable block

- packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/LinksHTMLCopyAndPaste.spec.mjs
- packages/lexical/src/nodes/LexicalLineBreakNode.ts
- packages/lexical/src/nodes/LexicalTextNode.ts
> Stop collapsing non-collapsible whitespace on paste

- packages/lexical/flow/Lexical.js.flow
> Add missing flow def

- packages/lexical-website/docs/collaboration/react.md
Added Yjs link and Yjs providers to the collaboration documentation.
> Added extra Yjs information to collaboration docs

- packages/lexical-react/src/LexicalTabIndentationPlugin.tsx
- packages/lexical-react/src/LexicalTablePlugin.ts
- packages/lexical-utils/src/index.ts
Moved `$filter` and `$insertFirst` to `@lexical/utils`
> refactor: moved functions to `@lexical/utils`

- packages/lexical-playground/src/plugins/AutoEmbedPlugin/index.tsx
> Fix: fixes regex in YouTube AutoEmbedPlugin

- package-lock.json
- packages/lexical-html/package.json
> fix(lexical/html): missing @lexical/utils dependency

- packages/lexical-table/flow/LexicalTable.js.flow
Yet another Flow replication issue
> Fix getTableSelectionFromTableElement flow

- packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx
> feat: LexicalClickableLinkPlugin should support ctrl click mode #4565

- packages/lexical-playground/src/nodes/TweetNode.tsx
- packages/lexical-playground/src/plugins/AutoEmbedPlugin/index.tsx
Support embed link format like: https://x.com/reactjs/status/1636441676506906626?s=20
> Playground: embed twitter support x.com

- packages/lexical-utils/src/index.ts
- packages/lexical-utils/src/markSelection.ts
- packages/lexical-utils/src/mergeRegister.ts
- packages/lexical-utils/src/positionNodeOnRange.ts
- packages/lexical-utils/src/px.ts
Porting a couple utilities we already use internally. Should probably add some tests but they're already pretty useful to build spellcheckers, hovercards (while maintaining visible selection), and soon the new CharacterLimit plugin.
https://github.com/facebook/lexical/assets/193447/d165e2dc-64ea-48b0-a6de-0d86465f7f56
> Range utils

- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
- packages/lexical-rich-text/src/index.ts
> Add conditional format setting, if the node is link fetch the parent paragraph node

- packages/lexical-playground/__tests__/e2e/AutoLinks.spec.mjs
- packages/lexical-react/src/LexicalAutoLinkPlugin.ts
> fix: Make autolinks working for formatted text

- packages/lexical-link/src/index.ts
- packages/lexical-selection/src/range-selection.ts
- packages/lexical-utils/src/index.ts
- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/LexicalUtils.ts
Cloning is not ideal, but it should fix the broken cyclic imports
> Fix @lexical/utils import

- packages/lexical-website/docs/concepts/nodes.md
- packages/lexical/src/nodes/LexicalDecoratorNode.ts
Add description for DecoratorNode.prototype.decorate method, add description to the docs website "Extending DecoratorNode" section.
> docs: improve DecoratorNode docs

- .github/workflows/pre-release.yml
- package.json
This sets us up to automatically release when generated release branches are merged.
> Automatic release on merge

- packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx
- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
> Clear link using key shortcut bug

- packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
- packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts
> fix: typo Contaner -> Container

- package-lock.json
- packages/lexical/src/LexicalEvents.ts
- packages/lexical/src/LexicalSelection.ts
> Fix bug on window.event conflict

- packages/lexical-markdown/src/MarkdownImport.ts
- packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs
Fixes #5385 
please check the [comment](https://github.com/facebook/lexical/issues/5385#issuecomment-1856764614) as well 🙏🏻.
thank you.
before: 
https://github.com/facebook/lexical/issues/5385#:~:text=before%2D-,convertfrommarkdown,-.mov
after:
https://github.com/facebook/lexical/assets/40269597/ad4316a6-6cdb-49f1-853e-1f32568811cc
> Fix $convertFromMarkdownString breakdown due to no parent

- packages/lexical-playground/src/plugins/CollapsiblePlugin/index.ts
Resolves #5415 
before:
https://github.com/facebook/lexical/assets/17613480/4486b335-74a5-49a5-a6c9-9d4cb9127f3a
after:
https://github.com/facebook/lexical/assets/17613480/ca1a1b42-dbf9-4ce6-93f3-9a66f5292bf7
> Fixed the error when CollapsibleTitleNode type enter key

- packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
- packages/lexical-table/src/LexicalTableUtils.ts
Resolves #5286 #5408
before:
https://github.com/facebook/lexical/assets/17613480/7d49ce8f-a6dc-46d7-aabd-c27ecb7b48af
after:
https://github.com/facebook/lexical/assets/17613480/2833e1da-09cc-4d9a-aca7-a90ffd482dcd
> Fix insert image to new inserted table row in playground report error

- packages/lexical-website/docs/concepts/editor-state.md
> Add link to state update blog

- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
> Revert "Inserting hyperlink through toolbar doesn't open floating editor in edit mode"

- .flowconfig
- package-lock.json
- package.json
Utility PR to update Flow version
> Update Flow version

- packages/lexical-playground/__tests__/e2e/AutoLinks.spec.mjs
- packages/lexical-react/src/LexicalAutoLinkPlugin.ts
fixes #5403 
fixes #5370 
before: in the Issues above
after:
https://github.com/facebook/lexical/assets/40269597/790f451f-a29a-4799-a7a8-d9114b193404
> Fix AutoLinkPlugin triggers endless transforms

- packages/lexical-react/flow/LexicalTypeaheadMenuPlugin.js.flow
- packages/lexical-table/flow/LexicalTable.js.flow
Table + TypeaheadMenu missing flow types
> Add missing flow types

- packages/lexical-website/docs/react/plugins.md
Fix this example to be proper JSX and use the correct variable name.
> fix: update docs example

- packages/lexical-playground/__tests__/e2e/List.spec.mjs
- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
Before
https://github.com/facebook/lexical/assets/7893468/65dd9a8c-45f6-435a-a002-1c6232e41150
After
https://github.com/facebook/lexical/assets/7893468/654e5111-c84b-4b2e-8fd1-3f95690f984f
Fixes #5039
> Unbullet one list item not the whole list

- packages/lexical/src/LexicalSelection.ts
@ivailop7 Can you directly merge it?
> style: fix broken eslint check of #5625

- packages/lexical-playground/src/nodes/LayoutContainerNode.ts
Handle DOM methods for LayoutContainerNode
> ImportDOM and ExportDOM for LayoutContainerNode

- packages/lexical-playground/src/nodes/ExcalidrawNode/index.tsx
Was mentioned in Discord the height and width were not parsed when DOM Importing
> Fix height and width parsing in ImportDOM for ExcalidrawNode

- packages/lexical-react/package.json
> Fix order of exports in lexical-react

- packages/lexical-list/src/LexicalListItemNode.ts
for context see https://github.com/facebook/lexical/pull/5803#issuecomment-2033428655
test that everything works ok
https://github.com/facebook/lexical/assets/19604232/6b84f496-282f-46e9-88ef-800693696bdc
> remove duplicate list merging

- scripts/build.js
- scripts/www/rewriteImports.js
Took this out by mistake in previous PR
> Add missing rewrite of utils import

- packages/lexical-react/src/LexicalClearEditorPlugin.ts
Before
#3456 
After
https://github.com/facebook/lexical/assets/163521239/4b4c660b-4770-4320-bece-649345b4123b
> Fix #3456 stale selection state after clear format

- packages/lexical-react/src/shared/useDecorators.tsx
> Refine useDecorators type

- package-lock.json
- packages/lexical-devtools-core/package.json
- packages/lexical-devtools/package.json
- packages/lexical-react/package.json
- scripts/npm/packages.js
- scripts/updateVersion.js
> fix(@lexical/react): @lexical/react 0.14.4 brings in @lexical/devtools-core dependency without declaring it

- package-lock.json
- packages/lexical-devtools/package.json
- packages/lexical-devtools/src/components/EditorsRefreshCTA.tsx
- packages/lexical-devtools/src/entrypoints/devtools-panel/App.tsx
- packages/lexical-devtools/src/entrypoints/devtools-panel/main.tsx
- packages/lexical-devtools/src/entrypoints/popup/main.tsx
Empty state:
Multiple editors:
https://github.com/facebook/lexical/assets/1125900/872af713-5131-437d-8db1-1013a73545b8
> feat(@lexical/devtools): Added styling to devtools panel

- packages/lexical-playground/__tests__/e2e/Autocomplete.spec.mjs
- packages/lexical-playground/src/nodes/AutocompleteNode.tsx
- packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
- packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts
- packages/lexical/src/index.ts
* Adds Comment on uuid in `AutoCompleteNode`
* FIxes issue #5943
> Refactor AutoCompleteNode: Add comment and move styling to theme. fixes(#5943)

- packages/lexical/src/LexicalEvents.ts
- packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx
- scripts/error-codes/codes.json
Follow up to https://github.com/facebook/lexical/pull/6002
> Root element count invariant & test

- packages/lexical-website/docs/collaboration/faq.md
- packages/lexical-website/sidebars.js
This adds FAQ page with to address common pitfalls around Yjs integration. This is a first PR in a series that shall improve documentation in this area.
**Closes:** #4442
See Vercel bot preview
> [@lexical/website] Documentation: Added FAQ page around Lexical collaborative mode

- .github/pull_request_template.md
**Closes:** #6123 <- this should be just Closes #6123 without anything between keyword and #issue to close auto linked issue when the PR gets merged.
we could make it headings or list if additional formatting is needed:
or
- Closes #6123
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
> [Lexical] Feature: Merging PR closes auto-linked issue

- .github/workflows/after-approval.yml
- .github/workflows/tests-extended.yml
use lexical bot for adding label
Tested using "commented" review status
> [Lexical] use lexical bot for adding label

- packages/lexical-devtools/README.md
- packages/lexical-devtools/safari-xcode/Lexical Developer Tools/Lexical Developer Tools.xcodeproj/project.pbxproj
- packages/lexical-website/docs/getting-started/devtools.md
- doc(@lexical/devtools): Added link to the Mac App Store
- fix(@lexical/devtools): Correct signing mode for Debug run mode
See website preview
> [lexical-devtools] Documentation Update: Added link to the Mac App Store

- packages/lexical-table/flow/LexicalTable.js.flow
- packages/lexical-table/src/LexicalTableSelectionHelpers.ts
- packages/lexical-table/src/index.ts
- packages/lexical/flow/Lexical.js.flow
- packages/lexical/src/index.ts
Just added bunch of exports that were useful to me.
Might help others.
> Few missing exports that are useful

- .github/ISSUE_TEMPLATE/bug_report.md
Add impact description to help us priotise
> Add impact description to bug report issue template

- packages/lexical-website/docs/concepts/history.md
- packages/lexical-website/sidebars.js
> (docs) Add existing history page to navigation

- packages/lexical-playground/src/plugins/TableCellResizer/index.tsx
https://github.com/facebook/lexical/pull/6416 was approved without passing the CI-checks
> [lexical-playground] Refactor: run prettier to fix CI

- packages/lexical-react/flow/LexicalDraggableBlockPlugin.js.flow
www autoformats the file as such in the sync diff so syncing the changes over
> [lexical-react]: sync format in flow file

- packages/lexical-react/flow/LexicalOnChangePlugin.js.flow
> Flow add tags type to OnChange plugin

- packages/lexical-react/flow/LexicalDraggableBlockPlugin.js.flow
> be in sync with www

- packages/lexical-website/docs/react/index.md
Fix broken UI in "Getting Started Guide" button  https://lexical.dev/docs/react/
Closes #
> docs: prevent automatic <p> tag wrapping

- packages/lexical-react/flow/LexicalContentEditable.js.flow
We need these internally, only the Flow path is manual...
> Flow: add more HTMLDivElementDOMProps

- scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/package-lock.json
- scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/package.json
GitHub has identified a security vulnerability defined in svelte package < 4.2.19
https://github.com/sveltejs/svelte/security/advisories/GHSA-8266-84wp-wv5c?fbclid=IwZXh0bgNhZW0CMTEAAR0SbKxlitu6Jx6gHzu6LXpO8ISnbPg8rA9QkETVKR7sitC5OYfMdIRDbKw_aem_L69Gc8C41CMosfKKxjjWQw
upgrade the svelte package to fix it
see automated tests
> Address svelte vulnerability

- packages/lexical-playground/__tests__/e2e/Links.spec.mjs
- packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
tag flaky tests that failed on PRs (due to flakiness) as flaky
only adding
```
{
tag: '@flaky',
}
```
https://github.com/facebook/lexical/discussions/6289
> CI: tag flaky test

- packages/lexical-table/src/LexicalTableUtils.ts
Fixes #6671
https://github.com/user-attachments/assets/802a4ef6-0677-4e2c-835b-1bd4d1c53b19
> Support backward selection in rows deletion

- packages/lexical-playground/src/plugins/CollapsiblePlugin/index.ts
> [lexical-playground] Remove unused command

- packages/lexical-playground/src/nodes/LayoutItemNode.ts
Fix missing importDOM for the Layout Item Node
> Fix importDOM for Layout plugin

- packages/lexical-link/flow/LexicalLink.js.flow
> Link flow types

- package-lock.json
address security vulnerability https://nvd.nist.gov/vuln/detail/CVE-2024-21538
Package Dependency
Manifest file: [package-lock.json](https://github.com/facebook/lexical/blob/main/package-lock.json)
Package name: [cross-spawn](https://npmjs.com/package/cross-spawn)
Affected versions: >= 7.0.0, < 7.0.5
Fixed in version: 7.0.5
Severity: HIGH
> [*] Chore: npm upgrade cross-spawn

- scripts/__tests__/integration/fixtures/lexical-esm-astro-react/package-lock.json
Address security vulnerability
https://nvd.nist.gov/vuln/detail/CVE-2024-21538
Package Dependency
Manifest file: [scripts/tests/integration/fixtures/lexical-esm-astro-react/package-lock.json](https://github.com/facebook/lexical/blob/main/scripts/__tests__/integration/fixtures/lexical-esm-astro-react/package-lock.json)
Package name: [cross-spawn](https://npmjs.com/package/cross-spawn)
Affected versions: >= 7.0.0, < 7.0.5
Fixed in version: 7.0.5
Severity: HIGH
> [__tests__] npm upgrade cross-spawn

- packages/lexical-playground/src/index.css
> [lexical-playground] Fix CSS property

- .github/workflows/tests.yml
- packages/lexical-playground/__tests__/e2e/List.spec.mjs
Adds merge_group as a trigger for the tests that are required for merge, so hopefully they run when a PR enters the merge queue.
Follow up to #6928
PRs can't be merged
Hopefully PRs can be merged
> [*] Bug Fix: add merge_group to the tests workflow

- packages/lexical-devtools-core/flow/LexicalDevtoolsCore.js.flow
* adding a test comment
flow
* no change
* no change
> [lexical-onboarding] testing sev mitigation

- packages/lexical-devtools-core/flow/LexicalDevtoolsCore.js.flow
This reverts commit f49f068b96c218d92d1ab719ffeebb5346707304.
this if for lab1a
> Revert "[lexical-onboarding] testing sev mitigation (#6952)"

- packages/lexical-dragon/flow/LexicalDragon.js.flow
This reverts commit f989d198043980ad62fb4ca2e55166a9ac0f87f5.
Closes #
> Revert "Test comment for pr testing (#6953)"

- scripts/__tests__/integration/fixtures/lexical-esm-nextjs/package-lock.json
Manifest file: [scripts/tests/integration/fixtures/lexical-esm-nextjs/package-lock.json](https://github.com/facebook/lexical/blob/main/scripts/__tests__/integration/fixtures/lexical-esm-nextjs/package-lock.json)
Package name: [next](https://npmjs.com/package/next)
Affected versions: >= 9.5.5, < [14.2.15](https://github.com/intern/bunny/?q=obi%2014.2.15)
Fixed in version: [14.2.15](https://github.com/intern/bunny/?q=obi%2014.2.15)
Severity: HIGH
> [__tests__] npm upgrade next

- README.md
> Documentation: Fix typo "nest nest"->"nest" in README.md

- scripts/__tests__/integration/fixtures/lexical-esm-astro-react/package-lock.json
Package Dependency
Manifest file: [scripts/tests/integration/fixtures/lexical-esm-astro-react/package-lock.json](https://github.com/facebook/lexical/blob/main/scripts/__tests__/integration/fixtures/lexical-esm-astro-react/package-lock.json)
Package name: [astro](https://npmjs.com/package/astro)
Affected versions: < 4.16.17
Fixed in version: 4.16.17
Severity: MODERATE
> [__test__] npm upgrade astro

- packages/lexical/README.md
Minimal should be 'minimum'
Seemless is 'seamless'
> Lexical Docs: 2 updates to spelling README.md

- packages/lexical-website/docs/concepts/listeners.md
3 updates to spelling and grammar
> Listeners Lexical: 3 updates to spelling and grammar - Update listeners.md 

- packages/lexical/src/__tests__/unit/LexicalSelection.test.ts
As a follow-up to #7046 it makes sense to do more thorough unit testing so that the existing behavior of methods that are targeted for refactoring have a better specification to avoid compatibility issues. The goal is to refactor getNodes and related methods for compatibility.
This only adds more tests for the current behavior.
> [lexical] Chore: Add more tests for RangeSelection.getNodes()

- packages/lexical-playground/src/plugins/ToolbarPlugin/utils.ts
Follow-up to #7155, which introduced some toolbar code to workaround a bug that was in insertNodes at the time. I think the PR sat long enough that I did end up fixing the root cause in insertNodes in the same PR rather than a follow-up (probably for #6763 and/or #7173), but didn't go back to clean up that toolbar code at the same time. Removing the workaround didn't break the e2e tests that I wrote to specifically reproduce that issue (#5686), so I don't think it's useful anymore.
Had extra code to work around a bug that wasn't needed by the time the PR landed
Extra code is gone but e2e tests still pass
> [lexical-playground] Chore: Remove insertNodes workaround in ToolbarPlugin

- packages/lexical-playground/src/plugins/TableCellResizer/index.tsx
- The `TableCellResizer` component's event handling logic runs regardless of whether a table exists in the editor
- This leads to unnecessary effect hook executions and potential performance overhead
Changes in this PR:
- Added a check to prevent event listener setup when no table exists
- The entire event handling effect is now skipped when there's no table in the editor
- This change improves performance by avoiding unnecessary effect hook executions
Closes #7099
https://github.com/user-attachments/assets/e8608f95-a4cf-467d-85ba-f0884ad20bb4
https://github.com/user-attachments/assets/f34832bf-8b64-4987-afd9-af7538fd6aea
> [lexical-playground] Bug Fix: Optimize table cell resizer event listeners

- package-lock.json
- packages/lexical-website/docusaurus.config.js
- packages/lexical-website/package.json
> 2024 recap shortcut

- packages/lexical-selection/flow/LexicalSelection.js.flow
- packages/lexical-table/flow/LexicalTable.js.flow
- packages/lexical-table/src/LexicalTableNode.ts
- packages/lexical-utils/flow/LexicalUtils.js.flow
- packages/lexical/flow/Lexical.js.flow
Just adds a few missing flow types for functionality that I've worked on in the past few months related to NodeCaret and tables.
> [lexical][lexical-utils] Chore: Add some missing flow types for NodeCaret and table related functionality

- package-lock.json
- packages/lexical-code/package.json
Closes #7312
Updates prismjs dependency https://github.com/PrismJS/prism/releases/tag/v1.30.0
> [lexical-code] Chore: Update prismjs dependency to 1.30.0

- packages/lexical-website/docs/collaboration/react.md
> Update react.md, fix typo

- scripts/__tests__/integration/fixtures/lexical-esm-nextjs/package-lock.json
Manifest file: [scripts/tests/integration/fixtures/lexical-esm-nextjs/package-lock.json]
(https://github.com/facebook/lexical/blob/main/scripts/__tests__/integration/fixtures/lexical-esm-nextjs/package-lock.json)
Package name: [next](https://npmjs.com/package/next)
Affected versions: >= [14.0.0](https://github.com/intern/bunny/?q=obi%2014.0.0), < [14.2.25](https://github.com/intern/bunny/?q=obi%2014.2.25)
Fixed in version: [14.2.25](https://github.com/intern/bunny/?q=obi%2014.2.25)
Severity: CRITICAL
> [__tests__] Update next version

- packages/lexical-react/src/__tests__/unit/LexicalNestedComposer.test.tsx
- packages/lexical/src/LexicalUpdates.ts
Previously, event listeners delegated from nested editors to their parent would call the parent's listeners from the child's update context instead of the parent's. This update ensures that command listeners are always triggered from the correct update context. The originating editor is still present as the second argument to the command listener.
This also changes updateEditorSync (an internal function) to always trigger the update synchronously, and to trigger a nested synchronous update if any options are provided.
The way command listeners were triggered when delegated from a nested editor to its parent would call the parent's update listener with the wrong update context ($getEditor() !== editor).
Closes #7377
Unit tests for expected behavior
See #7377 for repro of incorrect editor …
> [Breaking Change][lexical] Bug Fix: Ensure updateEditorSync is always synchronous and use it when triggering listeners

- scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/package-lock.json
- scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/package.json
GitHub detected vulnerabilities in dependency:
- [@sveltejs/kit](https://npmjs.com/package/@sveltejs/kit)
Existing Tests
> Chore: Update sveltejs dependency

- package-lock.json
- packages/lexical-website/docs/concepts/serialization.md
- packages/lexical-website/package.json
Updating docusaurus-plugin-internaldocs-fb fixes the constant warnings of a missing hg when not installed (common for folks outside of meta).
Also moved HTML related docs in serialization.md to the HTML section of that page. Having them in the JSON section was confusing.
> [lexical-website] Chore: Update docusaurus-plugin-internaldocs-fb and reorg serialization docs

- packages/lexical-code/src/CodeHighlighter.ts
Using Code Highlight plugin is not possible in headless environments :
```
Error: registerMutationListener is not supported in headless mode
```
```
Error: registerMutationListener is not supported in headless mode
```
Highlight works without any error.
> [lexical-code] Bug Fix: Allow Code Highlighter to be working in headless mode

- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
- packages/lexical-selection/src/range-selection.ts
Bug Fix: unbulleting an image doesn't work
Closes #5698
1. Add an image
2. Select the image
3. Change formatting to bullet list
4. Change formatting back to normal
The image is still an element of a bullet list, also notice that when you change formatting when the image is selected the dropdown is not updated.
The image is unbulleted correctly, formatting dropdown is updated accordingly.
https://github.com/user-attachments/assets/6e987e46-b940-4598-b30d-d9a48c004de6
> [lexical-selection][lexical-playground] Bug Fix: unbulleting an image doesn't work #5698

- examples/node-replacement/src/plugins/ToolbarPlugin.tsx
- examples/react-rich-collab/src/plugins/ToolbarPlugin.tsx
- examples/react-rich/src/plugins/ToolbarPlugin.tsx
- examples/react-table/src/plugins/ToolbarPlugin.tsx
- packages/lexical-playground/src/plugins/CommentPlugin/index.tsx
- packages/lexical-rich-text/src/index.ts
- packages/lexical-website/docs/concepts/commands.md
- scripts/__tests__/integration/fixtures/lexical-esm-astro-react/src/components/plugins/ToolbarPlugin.tsx
- scripts/__tests__/integration/fixtures/lexical-esm-nextjs/app/plugins/ToolbarPlugin.tsx
- What is the current behavior that you are modifying? 
`COMMAND_PRIORITY_LOW` and other priorities were re-defined in some files.
- What are the behavior or changes that are being added by this PR?
`COMMAND_PRIORITY_LOW` and other priorities are now sourced from the `lexical` package
> [lexical-playground][lexical-rich-text][lexical-website][tests][examples] Chore: source command priority from package

- packages/lexical-selection/src/range-selection.ts
Discussion https://github.com/facebook/lexical/pull/4059#issuecomment-2986873965
> Add in favor for to deprecated tag

- packages/lexical-devtools-core/src/generateContent.ts
Adds NodeState to TreeView, aiding debugging
> [lexical-devtools-core] Chore: add NodeState to TreeView

- packages/lexical/src/LexicalUtils.ts
Similar to #7659, check the import json as well
tested it internally, the page doesn't crash
> [lexical] Bug Fix: Workarounds for import json 

- examples/node-state-style/src/plugins/StyleViewPlugin.tsx
- packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
remove redundant fragment
Closes #
> [lexical-playground][examples] Refactor: remove redundant fragment

- packages/lexical-code-shiki/src/CodeHighlighterShiki.ts
- packages/lexical-list/src/utils.ts
remove unnecessary assertion in lexical-code-shiki
> [lexical-code-shiki] Refactor: remove unnecessary assertion

- packages/lexical-code/src/CodeHighlighterPrism.ts
- packages/lexical/src/LexicalSelection.ts
- packages/lexical/src/nodes/__tests__/unit/LexicalParagraphNode.test.ts
- packages/lexical/src/nodes/__tests__/unit/LexicalTextNode.test.tsx
remove unnecessary assertion in lexical & lexical-code
> [lexical][lexical-code] Refactor: remove unnecessary assertion

- packages/lexical-link/flow/LexicalLink.js.flow
- packages/lexical-react/flow/LexicalCollaborationPlugin.js.flow
- packages/lexical-yjs/flow/LexicalYjs.js.flow
Flow will ban codeless suppressions soon. This PR adds error codes to a few codeless suppressions in lexical.
flow
> [Chore] Update flow suppressions to use error code

- packages/lexical-react/src/LexicalNodeContextMenuPlugin.tsx
> [lexical-react] Fix the context menu event listener element

- examples/node-replacement/package-lock.json
- examples/node-state-style/package-lock.json
- examples/react-plain-text/package-lock.json
- examples/react-rich-collab/package-lock.json
- examples/react-rich/package-lock.json
- examples/react-table/package-lock.json
- examples/vanilla-js-iframe/package-lock.json
- examples/vanilla-js-plugin/package-lock.json
- examples/vanilla-js/package-lock.json
- scripts/__tests__/integration/fixtures/lexical-esm-astro-react/package-lock.json
- scripts/__tests__/integration/fixtures/lexical-esm-nextjs/package-lock.json
- scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/package-lock.json
(automated commit from call-post-release.yml)
> [examples] Chore: Update examples for v0.35.0

- packages/lexical-react/flow/LexicalContentEditable.js.flow
> Make ref optional in ContentEditable flow

- packages/lexical-react/flow/LexicalCollaborationContext.js.flow
> Expose LexicalCollaboration Context to flow

- examples/extension-react-table/package-lock.json
- examples/extension-vanilla-react-plugin-host/package-lock.json
- examples/extension-vanilla-tailwind/package-lock.json
- examples/node-replacement/package-lock.json
- examples/node-state-style/package-lock.json
- examples/react-plain-text/package-lock.json
- examples/react-rich-collab/package-lock.json
- examples/react-rich/package-lock.json
- examples/react-table/package-lock.json
- examples/vanilla-js-iframe/package-lock.json
- examples/vanilla-js-plugin/package-lock.json
- examples/vanilla-js/package-lock.json
- scripts/__tests__/integration/fixtures/lexical-esm-astro-react/package-lock.json
- scripts/__tests__/integration/fixtures/lexical-esm-nextjs/package-lock.json
- scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/package-lock.json
Updates package-lock.json files for examples
> Update examples for v0.36.2
