packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.jsx

This should stop the playground from crashing when attempting to use Excalidraw on the playground in prod.

Fix Excalidraw on playground

---

packages/lexical-playground/src/plugins/CharacterStylesPopupPlugin.jsx

Fix CharacterStylePopup top position

---

packages/lexical-playground/src/plugins/ToolbarPlugin.jsx

The logic for getting he ID from the URL for the TwitterPlugin failed to strip out the URL params. This PR fixes that logic.

Improve tweet ID parsing logic

---

README.md
examples/decorators.md
packages/lexical-history/README.md
packages/lexical/README.md

We forgot to update various docs when we launched typed over string literal commands.

Fix docs for typed commands

---

packages/lexical-playground/src/plugins/ToolbarPlugin.jsx

"Tweet" was the only option not capitalized in the insert menu, now it is.

Capitalize 'tweet' in Playground Insert Menu

---

packages/lexical-website-new/docs/concepts/transforms.md

I used ` ```typescript` for TS files but ` ```ts ` can be used too. Should I use the short or the long form?

Fix syntax highlighting on transforms docs (#1691)

---

packages/lexical-selection/src/index.js
packages/lexical/src/LexicalUtils.js

Fixes an issue where you might apply an old (frozen) selection to `$setSelection`

Fix bug with $setSelection

---

packages/lexical-website-new/src/components/HomepageExamples/index.js

There has been a lot of confusion caused by the fact that there are code editors on the landing page, which leads people to believe that Lexical is a code editor and these editors are implemented with Lexical. In fact, they are CodeSandbox embeds demonstrating Lexical Code. This should clarify things for now.

Show preview instead of editor by default

---

packages/lexical-website-new/src/components/HomepageExamples/styles.module.css

The docs site codesandbox is kinda overflowing in mobile and tablet view. Seems like it was due to the explicit 750px given although its parent had `col--8`.
Before | After |
--- | --- |

fix: docs site codesandbox

---

packages/lexical-code/src/index.js

When you have a single codeblock, it should be possible to use the arrow keys to move the selection out of the code block without being stuck in the code block forever.

Improve CodeBlock selection escaping

---

.github/workflows/test.yml

Bumps the following actions to latest versions:
`actions/checkout@v2` => `actions/checkout@v3`
`actions/setup-node@v2` => `actions/setup-node@v3`
`actions/cache@v2` => `actions/cache@v3`

Bumped actions/checkout, actions/cache, actions/setup-node to v3

---

packages/lexical-markdown/src/utils.js

I've included h4 and h5 in the lexical markdown so that we'd be able to handle them in the markdown mode. Also fixes h3 which was converted to h2 previously. 
Also we might want to include them inside the dropdown too?
But the name small heading and large heading is quite confusing thoughts?
Fixes: 
- https://github.com/facebook/lexical/issues/1628

include heading 4 and 5 in lexical markdown

---

packages/lexical/src/LexicalUtils.js
packages/shared/src/environment.js

Fixes https://github.com/facebook/lexical/issues/1695. Our detection for Safari fails on Chrome on iOS, but really they're the same rendering engine, thus we need to also check for iOS too.

Fix detection of iOS browser

---

package-lock.json
packages/lexical-playground/src/plugins/CharacterStylesPopupPlugin.jsx

Fixes  #1704
This PR fixes the Playground Popup Positioning to Handle Various Edge Cases top, left  and right position 
Before:
https://user-images.githubusercontent.com/22450188/163326237-b65f071b-5b1d-4e6c-b55a-e3ee9744ceb8.png
https://user-images.githubusercontent.com/22450188/163326356-74214cff-00ef-4e4f-a413-19181afa7ebc.png
https://user-images.githubusercontent.com/22450188/163326498-47f0516a-0e84-402e-b8d5-3de718bb7cd6.png
After:
https://user-images.githubusercontent.com/35562131/163366694-0eb71c18-f746-4c08-bfb1-80cdb75826e7.png
https://user-images.githubusercontent.com/35562131/163366784-118e31f2-1315-432d-980b-7da3e54dc1f0.png
https://user-images.githubusercontent.com/35562131/163367031-8786caf4-3cbc-49d2-9ac5-50b21f7b337e.png

Fix PlaygroundPopupPositioning For Various Edge Cases top and left position

---

packages/lexical-table/src/LexicalTableSelection.js
packages/lexical-table/src/LexicalTableSelectionHelpers.js

This PR improves the UX for when an entire Table is selected. Now it'll show the entire table as selected rather vs using default range selection UI in the table cell text nodes.
Before:
https://user-images.githubusercontent.com/13852400/163275084-ff620f5f-45f6-438a-afdc-d0fd9ddf19fb.mov
After:
https://user-images.githubusercontent.com/13852400/163275096-a58b288b-8116-48eb-ae1e-08252882540f.mov

Improve CMD+A support for documents containing Tables

---

packages/lexical-playground/src/plugins/CharacterStylesPopupPlugin.jsx
packages/lexical-playground/src/plugins/ToolbarPlugin.jsx
packages/lexical/src/LexicalEvents.js
packages/lexical/src/LexicalReconciler.js

If we reconcile a selection change, in most cases we should attempt to "ignore" the subsequent incoming selection change event, as it won't give us any real value. Plus this can avoid issues around changing format part way through text.

Skip reconciled selection changes

---

packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs
packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/ToolbarPlugin.jsx
packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
packages/lexical-playground/src/themes/PlaygroundEditorTheme.js

This PR introduces 
- one new menu item to the toolbar (H3) 
- Adds h4 and h5 in markdown spec
- Adds separate classes in case if want to use it for overriding style
- Changes block name from large heading to heading 1, small heading to heading 2

Add h3 to dropdown and add tests for h4 and h5

---

.github/workflows/test.yml

I believe this should start triggering workflows on PRs with base branch as main. 
We can catch the failures and fix it in PR instead of having to fix them separately
- https://github.com/facebook/lexical/pull/1750

trigger workflows on PRs

---

packages/lexical-playground/src/plugins/ToolbarPlugin.jsx

When moving selection through code blocks, we can skip font-size and font-family logic entirely.

Optimize toolbar perf

---

package.json

Changes `accessible` to `accessibility` in the README.

Fixes typo in README.md

---

packages/lexical-playground/src/plugins/TableCellResizer.jsx
packages/lexical-playground/src/themes/PlaygroundEditorTheme.css

Fix table cell height

---

packages/lexical-markdown/src/autoFormatUtils.js
packages/lexical-markdown/src/convertFromPlainTextUtils.js
packages/lexical-markdown/src/utils.js
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs

With this PR, we now complete the markdown import code including:
1. importing paragraph markdown
2. importing text markdown like links and BIUS
3. importing codeblocks
4. unit tests for much of the above.

Markdown import

---

packages/lexical-playground/src/plugins/ActionsPlugin.jsx

Added `title` and `aria-label` attributes to the playground editor.

feat: added title and aria-label to playground editor buttons

---

packages/lexical-playground/__tests__/e2e/Clear.spec.mjs
packages/lexical-playground/src/plugins/ActionsPlugin.jsx

Added confirmation modal for clear text in playground.
this commit resolves #1794.

feat: added confirmation modal before clear text

---

packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical/src/LexicalSelection.js

Fixes #1678 
~~I'm not sure this is actually the right way to handle this though. The logic in this function is sort of messy, and this change certainly doesn't help things. It's also pretty specific to LinkNodes (the only thing implementing isInline right now) in that it basically assumes that the inline element has just a TextNode in it.~~
This function might be something we need to think about refactoring or totally rethinking. I want to add some tests here to catch weird behavior.
EDIT:
I was able to implement a solution that I think it more robust and should handle most cases of inline elements. Still thing we might be able to refactor this function, but I'm concerned about bloating core if we add a bunch of sub-functions to make it more readable.

Fix inlines in insertParagraph

---

packages/lexical-playground/__tests__/e2e/Images.spec.mjs
packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/ToolbarPlugin.jsx

Currently activeEditor was stuck on the nested editor once focused, this is because commands only bubble so once it's on the nested editor it needs manual correction.
This meant that once you had inserted an image caption the toolbar would no longer properly work for inserting any other node.
In this case I think the fix is pretty straightforward and we can just leverage bubbling and listening to the top editor instead.

Fix toolbar active editor

---

examples/emoticons.md

Just a small fix on the Emoticons example code syntax.

Fix code syntax in the emoticons example

---

packages/lexical-playground/src/appSettings.js
packages/lexical/src/LexicalEvents.js

This should fix some issues where backspacing on Android + GBoard can cause content to duplicate.

Further improve Android + GBoard compatibility

---

packages/lexical-playground/__tests__/e2e/Images.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/ImagesPlugin.js
packages/lexical-playground/src/plugins/ToolbarPlugin.css
packages/lexical-playground/src/plugins/ToolbarPlugin.jsx
packages/lexical-playground/src/ui/Button.jsx

Added modal for image plugin to allow option to add custom URI and files. 
~~File button is disabled, to be implemented later (or should I do it in this PR too?).~~
Upload file feature to be implemented in another PR.
part of #1799
Encountered a few issues, not sure if should be addressed in this PR.
1. Image cannot be added if current selection is null.
2. Random image added using https://source.unsplash.com/random are cached by `useSuspenseImage`.

feat: image plugin take arbitrary url

---

packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs

Broke e2e test Toolbar in #1817, modified test to use `insertSampleImage` to add images.
(my bad)

fix: Toolbar e2e test fail on adding image

---

packages/lexical-dragon/LexicalDragon.d.ts

"registerDragonSupport" is a named export but the type declaration file for dragon lists it as a default export.

Type Fix: export "registerDragonSupport" as named not default.

---

packages/lexical-playground/src/index.css

Although the button was disabled it was kinda not very different from other buttons. So this might actually be better
Before: 
After:

Adds disabled state css for action items

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.css
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.jsx

Addresses #1811 
Modal does not appear in case you didin't make any change in excalidraw, it appears only in case there is something created with this tool.

Open a confirm modal on discard excalidraw

---

packages/lexical-list/src/LexicalListItemNode.js
packages/lexical-playground/__tests__/e2e/List.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-selection/src/index.js
packages/lexical/Lexical.d.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalNode.js

Will add a test, just wanted to write the explanation while it's fresh:
The root cause of this issue is that, in $wrapLeafNodesInElements, we call [$removeParentEmptyElements](https://github.com/facebook/lexical/blame/0e159ecb6bf4002777c91305312bd4182ff94391/packages/lexical-selection/src/index.js#L507) to try to remove all the nodes that are empty after their former leaves are appended to their new parents (the "elements" in "$wrapLeafNodesInElements"). This function tries to crawl up the tree, removing newly-empty nodes as it goes (uses getLatest to access the pending state).
The problem with this is that the implementation of LexicalNode.remove() actually [removes the parent under certain conditions](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalNode.js#L98-L …

Add preserveEmptyParent param to LexicalNode.remove

---

packages/lexical-yjs/src/SyncCursors.js

I noticed while playing with collaboration that if a user highlighted multiple adjacent text blocks, then the remote user would see blocks in the middle double-highlighted. (See screenshot). This turned out to be because the DOM function `getClientRects()` can return multiple identical rects for some elements. The fix is just to ignore duplicate rects.

Fix collab selections possibly doubling up when spanning text nodes

---

packages/lexical/Lexical.d.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalCommands.js
packages/lexical/src/LexicalEvents.js
packages/lexical/src/LexicalUtils.js

Adding a command that will be dispatched on keyDown with any of the modifier keys (cmd/ctr/shift/alt) which will simplify adding editor shortcuts (and help getting rid of root listener)

Add KEY_MODIFIER_COMMAND

---

packages/lexical-plain-text/src/index.js
packages/lexical-rich-text/src/index.js

Fixes https://github.com/facebook/lexical/issues/1849 and fixes https://github.com/facebook/lexical/issues/1846.
If we have support for `beforeinput`, we can use that event for signal rather than blocking the return/enter key press via `preventDefault()`. This allows iOS to function better – although it's a bit strange how this is the only platform that suffers from this issue :P

Avoid preventDefault on pressing enter

---

packages/lexical-code/LexicalCode.d.ts
packages/lexical-code/flow/LexicalCode.js.flow

Adds types of `getCodeLanguages` and `getDefaultCodeLanguage` in `@lexical/code`

fix: missing types in LexicalCode

---

packages/lexical-website-new/docs/concepts/commands.md

You can see a live version [here](https://lexical-git-add-documentation-for-commands-fbopensource.vercel.app/docs/concepts/commands).

Add Documentation for Commands

---

packages/lexical-website-new/docs/concepts/editor-state.md

It appears lexical/Readme.md had decent info regarding editor state, so I've added "initial state -> change -> persist" example as it seems to be a common ask.
Preview: https://lexical-git-state-docs-fbopensource.vercel.app/docs/concepts/editor-state

State docs

---

packages/lexical-link/LexicalLink.d.ts

Fixes missing `ElementNode` import in `LexicalLink.d.ts`

@lexical/link: Fix missing import in LexicalLink.d.ts

---

packages/lexical-rich-text/LexicalRichText.d.ts

replaces `HeadingNode` import to `LexicalEditor`
Reference https://github.com/facebook/lexical/blob/main/packages/lexical-rich-text/flow/LexicalRichText.js.flow#L16

fix: incorrect import in lexical-rich-text types

---

packages/lexical-website-new/docs/getting-started/quick-start.md

add $createTextNode in import code example.

docs : fix code typo in quick-start

---

packages/lexical/Lexical.d.ts
packages/lexical/flow/Lexical.js.flow

Type missing from DecoratorNode `isTopLevel`.

Add missing type to DecoratorNode

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawImage.jsx
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.css
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.jsx
packages/lexical-playground/src/nodes/ExcalidrawNode/index.jsx

- Set readOnly mode when Excalidraw is open to avoid unnecessary updates
- Move Excalidraw Modal to a portal to avoid interacting with Lexical and other wrappers event listeneners
- Fix Excalidraw image size
- Remove Excalidraw Node if the content of the saved drawing is empty

Excalidraw fixes

---

packages/lexical/src/LexicalReconciler.js

If the editor is in a read only mode, do not attempt to reconcile selection.

Do not reconcile selection during readOnly

---

packages/lexical-code/LexicalCode.d.ts
packages/lexical-hashtag/LexicalHashtag.d.ts
packages/lexical-link/LexicalLink.d.ts
packages/lexical-list/LexicalList.d.ts
packages/lexical-overflow/LexicalOverflow.d.ts
packages/lexical-react/LexicalHorizontalRuleNode.d.ts
packages/lexical-rich-text/LexicalRichText.d.ts
packages/lexical-table/LexicalTable.d.ts
packages/lexical/Lexical.d.ts

Uses TypeScript type predicates for `$isXNode` and `$isXSelection` checks in the `.d.ts` files. Looks like this is already happening in flow.

Use TS type predicates for $isXNode checks

---

packages/lexical/src/nodes/LexicalTextNode.js

Fixes https://github.com/facebook/lexical/issues/1887. The foundations were already there, just needed to wire up the outer tag generation for them! :)

Add subscript/superscript elements to TextNode

---

packages/lexical/flow/Lexical.js.flow

Using $isLeafNode with Flow typing does not refine the type. This is because it's not declared as a predicate function (`%checks`). In order to have a predicate function, Flow needs the implementation. I suggest to add the function implementation in the flow file. This is not ideal as it duplicates things : the implementation in the flow file could get out of sync from the actual implementation, but in my opinion this is still an improvement.
I only do it for Flow here, as I am not very familiar with TypeScript

Add predicate to  $isLeafNode in .flow file

---

README.md

There is a `npm run test` in the readme `contributing to lexical` section. So I've changed the command to run e2e test.

change test command to e2e command

---

packages/lexical/Lexical.d.ts
packages/lexical/flow/Lexical.js.flow

Removes `HorizontalRuleNode` and associated functions from `lexical` as these exports are not present in `lexical`.

Remove HorizontalRuleNode from lexical types

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.js
packages/lexical-selection/src/index.js

Fixes https://github.com/facebook/lexical/issues/1911. Turns out the fast-path logic wasn't too smart after all.

Simplify extraction of text

---

packages/lexical/Lexical.d.ts

Fixes https://github.com/facebook/lexical/issues/1885
```typescript
type EditorThemeClasses = {
list?: {...};
// Handle other generic values
[key: string]:
| EditorThemeClassName
| Record<
string,
| EditorThemeClassName
| Array<EditorThemeClassName>
| Record<string, EditorThemeClassName>
>;
}
```
This only handles the current structure for `list` key. If we want it recursive I can update it to
```typescript
type EditorThemeRecursiveClassName = {
[key: string]: EditorThemeClassName | Array<EditorThemeClassName> | EditorThemeRecursiveClassName
}
type EditorThemeClasses = {
list?: {...};
[key: string]: EditorThemeClassName | EditorThemeRecursiveClassName;
}
```

fix: editor theme class name type for list

---

packages/lexical-table/src/LexicalTableSelectionHelpers.js

https://user-images.githubusercontent.com/377544/164468711-42ebe76d-156f-4734-96fb-1d1bfba168c5.mp4
When there're text `hello`, the `selection.anchor.getNode()` is `<span>`, not `<p>` anymore.

Fix Table can delete empty lines when there're text

---

packages/lexical-markdown/LexicalMarkdown.d.ts
packages/lexical-markdown/flow/LexicalMarkdown.js.flow
packages/lexical-markdown/src/convertToMarkdown.js
packages/lexical-markdown/src/index.js
packages/lexical-markdown/src/utils.js
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs
packages/lexical-playground/src/plugins/ActionsPlugin.jsx

- Some basic markdown exporting
- Updated md button in the playground to be a bit more functional: toggling editor content between its markdown representation within code block and back to rich text.
https://user-images.githubusercontent.com/132642/164358063-5adc98bd-19eb-40d1-baf9-7e9ae05329f2.mov

Base markdown export & import/export toggle for the playground

---

README.md

The collab server appears to start with `npm run start` now. This line isn't needed anymore.

Remove line from README about starting collab server

---

packages/lexical-clipboard/src/clipboard.js
packages/lexical-playground/__tests__/e2e/Keywords.spec.mjs
packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical-playground/src/plugins/CharacterStylesPopupPlugin.jsx
packages/lexical-react/src/LexicalLinkPlugin.js
packages/lexical-react/src/LexicalTreeView.jsx
packages/lexical-react/src/__tests__/unit/useLexicalCharacterLimit.test.js
packages/lexical-selection/src/index.js
packages/lexical/Lexical.d.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalEditorState.js
packages/lexical/src/LexicalEvents.js
packages/lexical/src/LexicalParsing.js
packages/lexical/src/LexicalSelection.js
packages/lexical/src/__tests__/unit/LexicalEditor.test.js
packages/lexical/src/__tests__/unit/LexicalEditorState.test.js

Fixes https://github.com/facebook/lexical/issues/1904. This was an interesting one. Logically, we were missing some selection resolution code around the handling of inline elements – but by fixing that, it also made it clear that some of the logic for handling links and character offset resolution was also a bit loose. This PR fixes that and adds a regression test to capture that main issue.

Fix boundary selection issues

---

packages/lexical-playground/src/nodes/StickyNode.jsx

There is a common misconception about `useCallback` that it prevents function creation during render. It actually doesn't prevent it and when used for this goal, it decreases performance. `useCallback` is needed when referential equality matters, for exampled for memoized components props (`React.Memo()`) or when used in a hook dependency array. There is a very good article explaining it better than me in https://kentcdodds.com/blog/usememo-and-usecallback. 
In StickyNode this is not one of these cases where it's needed.
`handleDelete` and `handleColorChange` are both passed to a `<button>`, which is a host component and doesn't do any referential equality check. 
`handlePointerMove` and `handlePointerUp` are a bit more tricky. Referential equality **does** matter here as …

Remove useCallbacks in StickyNode

---

packages/lexical-website-new/src/components/CommunityLinks/index.js

This would be an improvement from the current content
There is always scope for improvement.

Updating content of community links description

---

packages/lexical-clipboard/src/clipboard.js
packages/lexical-website-new/src/components/CommunityLinks/index.js

This is a quick fix for the regression we're seeing with Lexical and copying of rich text content. Today, we're inserting an empty string into the clipboard, which is causing big issues for users on FF.

Fix text/html copy regression

---

packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/ActionsPlugin.jsx
packages/lexical-playground/src/plugins/CharacterStylesPopupPlugin.jsx
packages/lexical-playground/src/plugins/ToolbarPlugin.jsx
packages/lexical-playground/src/ui/Modal.jsx

Add descriptive `aria-labels` to all buttons in the toolbar and in the actions footer bar, which just show an icon.  
This should be used as the default button label by screen readers, overwriting the shortened `title` attribute introduced in #1924, 
The `title` attribute also has some accessibility shortcomings, highlighted in #1726.

Add aria-labels to toolbar and footer bar.

---

packages/lexical-plain-text/src/index.js
packages/lexical-playground/__tests__/e2e/Images.spec.mjs
packages/lexical-rich-text/src/index.js
packages/lexical/src/LexicalEvents.js
packages/lexical/src/LexicalReconciler.js

This should fix some of the issues with Safari in https://github.com/facebook/lexical/issues/1938. Specifically, calling `preventDefault` on the enter key causes a big pause in Safari. Given we already have a codepath for iOS, we can re-use it for Safari on desktop too. I also noticed that pressing enter that Safari was not scrolling correctly to the new content – so this also fixes that.

Fix bugs around pressing the enter key in Safari

---

packages/lexical-playground/src/nodes/TweetNode.jsx
packages/lexical-playground/src/nodes/YouTubeNode.jsx
packages/lexical-react/flow/LexicalDecoratorBlockNode.js.flow
packages/lexical-react/src/LexicalDecoratorBlockNode.js

Embed nodes do not correctly update. It turned out that the format logic was missing from the constructor and the clone methods, which was why it was never being kept on the node.

Fix formatting on embeds

---

packages/lexical-code/src/index.js

If we're not changing node values, let's just not mark the node dirty which is more expensive? #1966

CodeHighlight setFormat do not mark dirty

---

packages/lexical-playground/__tests__/e2e/BlockWithAlignableContents.spec.mjs
packages/lexical-playground/__tests__/e2e/Composition.spec.mjs
packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/File.spec.mjs
packages/lexical-playground/__tests__/e2e/Images.spec.mjs
packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical-playground/__tests__/e2e/List.spec.mjs
packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/e2e/TextEntry.spec.mjs
packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs
packages/lexical-playground/__tests__/keyboardShortcuts/index.mjs
packages/lexical-playground/__tests__/utils/index.mjs

Image tests seems to be flaky because of lag time in the image being totally rendered? We don't have any retries in the HTML assertion logic on the left frame in collab, so this adds that. We can also configure it to be per-test, if we want.
The Image test that is checking if the Add Caption button and resize corners show up when focused is just legitimately failing because this doesn't work in collab. When you click on the image on the left, the one on the right doesn't become "focused", showing Add Caption and the resizers.  Not sure if it should.
Turns out the retry logic we had in place for HTML assertions against the right-hand frame made it impossible for the those assertions to properly fail. When refactored the retry logic it exposed a bunch of collab bugs. I added fixme …

Improve CI

---

packages/lexical-code/src/index.js
packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/ToolbarPlugin.jsx

- Remove duplicates from language dropdown (but keep mappings like 'py' => 'python', 'js' => 'javascript')
- Prevent setting unknown language to a code node
- Manual labeling langues (it's less dynamic than before, but looks way nicer)
Before
After

Deduplicate code langs in a toolbar, prevent setting unknown language

---

packages/lexical-playground/__tests__/e2e/Composition.spec.mjs
packages/lexical-yjs/src/CollabElementNode.js
packages/lexical-yjs/src/Utils.js
packages/lexical/src/LexicalUpdates.js
packages/lexical/src/LexicalUtils.js

Turns out that `skipTransforms` never worked properly because we also reset the value (wrongly) back to `false`. I also noticed we can improve perf by checking if nodes were attached or not before calling the transform on them too!

Fix bug with skipTransforms

---

packages/lexical-playground/src/nodes/ImageNode.jsx
packages/lexical-playground/src/ui/EquationEditor.jsx

Follow up on #1935.
ImageNode : `setShowCaption`, `onResizeStart` and `onResizeEnd` are all three passed to `ImageResizer` which does not do any referential equality check. 
`onDelete` however is in the dependency array of a useEffect. I wonder if this is needed as this useEffect needs to be run at first render only, but linters would probably complain if all dependencies are not listed.
EquationEditor : `onChange` is passed to an `<input>`

Remove useCallbacks in ImageNode and EquationEditor

---

examples/decorators.md

Follow up on #1935
To stop the bleeding,  I think the first step is to remove it from the documentation.
We could argue that there is no implementation of `useVideoDialog` provided and it's left to the imagination of the reader. So we don't actually know if there is a referential equality check done with `onSubmit` inside the hook, but the most probable case is that there is none as `onSubmit` will be likely passed to a `<button>`.

Remove useCallback from decorators.md

---

packages/lexical/src/LexicalEvents.js
packages/lexical/src/LexicalReconciler.js

This better revises formatting that was introduced in https://github.com/facebook/lexical/pull/1962. Specifically, we try to persist selection formats for collapsed selection if we're on the same offset and key within the given threshold.

Persist collapsed formats across selection updates

---

packages/lexical-clipboard/src/clipboard.js
packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/TableCellResizer.jsx
packages/lexical-rich-text/src/index.js
packages/lexical-table/src/LexicalTableSelection.js
packages/lexical-table/src/LexicalTableSelectionHelpers.js

This is the first iteration of this feature and does not support "growing" the table to accommodate incoming data that doesn't fit, it will just stop at the existing boundaries. Support for this will be coming soon.
This PR also updates the selection to only be the data that was just pasted.
Tested Lexical -> Lexical and Google Docs & Quip -> Lexical
See the video below.
https://user-images.githubusercontent.com/13852400/165002354-88ff3fb3-1564-4ee8-9ef3-afb2bb8fd1f5.mov

Merge Tables on Paste

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/nodes/StickyNode.jsx

The z-index can be off at times for StickyNode, so we need to wrap the `<div>` in a container to be able to apply z-index.

Improve StickyNode styling

---

packages/lexical/src/LexicalSelection.js

We have a `isTokenOrInertOrSegmented` method that we're not using in the selection logic. This adds it to a relevant conditionals to dedupe similar logic.

Use isTokenOrInertOrSegmented in selection

---

packages/lexical/Lexical.d.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalNode.js
packages/lexical/src/nodes/LexicalTextNode.js

We did this recently in another PR, but we reverted that due to larger changes. We only wanted this singular change, and the comments have been removed.

Move isComposing to TextNode

---

packages/lexical/src/LexicalSelection.js

If your carat is focused at the start of a segmented TextNode segment and press backspace, we remove the subsequent segment, rather than what should probably be the preceding segment. A small Regex adjustment fixes this issue.
https://user-images.githubusercontent.com/7748470/165857212-e4e9aebd-2e07-42d7-b624-3dc6832705a4.mov
https://user-images.githubusercontent.com/7748470/165857096-71c33ff9-0b4b-4b20-bdc9-9b6b290281f9.mov

Fix small segmented node bug on backspace

---

packages/lexical-markdown/src/index.js
packages/lexical-markdown/src/v2/MarkdownExport.js
packages/lexical-markdown/src/v2/MarkdownShortcuts.js
packages/lexical-markdown/src/v2/MarkdownTransformers.js
packages/lexical-markdown/src/v2/index.js
packages/lexical-playground/__tests__/e2e/Markdown-v2.spec.mjs
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/Editor.jsx
packages/lexical-playground/src/Settings.jsx
packages/lexical-playground/src/nodes/EquationNode.jsx
packages/lexical-playground/src/nodes/ImageNode.jsx
packages/lexical-playground/src/nodes/TweetNode.jsx
packages/lexical-playground/src/plugins/ActionsPlugin.jsx
packages/lexical-playground/src/plugins/MarkdownShortcutPlugin.jsx
packages/lexical-playground/src/plugins/MarkdownTransformers.js
packages/lexical-react/src/LexicalMarkdownShortcutPlugin.jsx

Playground use with custom markdown transformers: 
- Image
- Katex equation
- Table (extremely basic, lots to improve)
- Tweet (more for a demo purpose and no real usage, although markdown allows html-like tags to be used so it can be a legal way to allow embeds within markdown)
https://user-images.githubusercontent.com/132642/165447693-3a01b590-603b-4928-af92-dd3e405669a5.mov

Tests, playground usage, table/image/hr/tweet transformers

---

packages/lexical-playground/src/plugins/ClickableLinkPlugin.js

Clicking a link node that has an invalid href causes a frustrating error to throw. Let's swallow the error instead.

Stop link clicking exception

---

packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical/src/LexicalSelection.js

This improves on the heuristics of `insertText`, so that it better handles inline elements. Working with @acywatson on this, so it might need some further work.

Improve insertText handling of inline elements

---

package-lock.json
packages/lexical-clipboard/LexicalClipboard.d.ts
packages/lexical-clipboard/flow/LexicalClipboard.js.flow
packages/lexical-clipboard/package.json
packages/lexical-clipboard/src/__tests__/unit/clipboard.test.js
packages/lexical-clipboard/src/clipboard.js
packages/lexical-clipboard/src/index.js
packages/lexical-list/src/LexicalListItemNode.js
packages/lexical-list/src/LexicalListNode.js
packages/lexical-plain-text/src/index.js
packages/lexical-playground/__tests__/e2e/List.spec.mjs
packages/lexical-playground/src/nodes/EquationNode.jsx
packages/lexical-playground/src/nodes/ImageNode.jsx
packages/lexical-playground/src/nodes/MarkNode.js
packages/lexical-rich-text/src/index.js
packages/lexical-selection/LexicalSelection.d.ts
packages/lexical-selection/flow/LexicalSelection.js.flow
packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.js
packages/lexical-selection/src/index.js
packages/lexical/Lexical.d.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalSelection.js
packages/lexical/src/nodes/LexicalElementNode.js
packages/lexical/src/nodes/LexicalParagraphNode.js

Solves the problems described in #1957 and the `Lexical -> HTML` & `Lexical -> Lexical (Clone)` conversion functions now have identical outputs, which will make debugging issues in the future much easier.
This PR also adds an `extractWithChild` method to `ElementNodes` that can be used to ensure there's a tightly coupled relationship between parent and child. This is useful situations where the `ElementNode` provides important context for its children e.g. `Heading -> TextNode` or `List -> ListItem`.
NOTE: Most of the line count is from the new tests in `clipboard.test.js`. 
`Lexical -> Lexical (Clone)` and `Lexical -> HTML` are tested individually and then they're both ran through the same processing code and compared to each other ensure the end output is the same. …

Improve Lexical -> HTML and Lexical -> Lexical Copy and Paste Data Model Conversion

---

.flowconfig
package-lock.json
packages/lexical-headless/LexicalHeadless.d.ts
packages/lexical-headless/LexicalHeadless.js
packages/lexical-headless/README.md
packages/lexical-headless/flow/LexicalHeadless.js.flow
packages/lexical-headless/package.json
packages/lexical-headless/src/__tests__/unit/LexicalHeadlessEditor.test.js
packages/lexical-headless/src/index.js
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalEditor.js
packages/lexical/src/LexicalUpdates.js
scripts/build.js
scripts/www/rewriteImports.js

- Adds `@lexical/headless` with `createHeadlessEditor`
- Adds `_headless` to editor
- Skips reconciler and dom selection sync if is headless
- Unit tests are running in node environment to check `editor.update`, `editor.setEditorState` and `editor.register***`
E.g. can run markdown import/export from node:

Headless mode `@lexical/headless`

---

packages/lexical-playground/src/App.jsx

Very important change:
Before 
After

Adjust octocat colors to match rest of background

---

packages/lexical/src/LexicalSelection.js

When selection is within the content of a DecoratorNode, selection should be `null`.

Fix decorator content selection bug

---

packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.js
packages/lexical/src/LexicalSelection.js

Setting anchor to an end of a text node right before link node, selecting link and calling selection.toggleFormat caused crash since Selection#formatText didn't adjust for inline elements. Note that updated version relies on current usage of inline elements (links) that are non empty.

Adjust first node when applying format to selection

---

packages/lexical/src/LexicalSelection.js

A follow up to https://github.com/facebook/lexical/pull/2063, that applies a better heuristic for collapsed selection in a decorator.

Better fix for decorator content selection bug

---

packages/lexical-code/LexicalCode.d.ts
packages/lexical-code/flow/LexicalCode.js.flow
packages/lexical-list/src/LexicalListNode.js
packages/lexical-list/src/__tests__/unit/LexicalListNode.test.js
packages/lexical-markdown/flow/LexicalMarkdown.js.flow
packages/lexical-markdown/src/index.js
packages/lexical-markdown/src/v2/MarkdownExport.js
packages/lexical-markdown/src/v2/MarkdownImport.js
packages/lexical-markdown/src/v2/MarkdownShortcuts.js
packages/lexical-markdown/src/v2/MarkdownTransformers.js
packages/lexical-markdown/src/v2/utils.js

- Update `ListNode.clone()` to be backward compatible if passing tag instead of listType
- Move markdown transformer types from .js to .flow
- Fix `$createCodeNode()` to accept optional highlighting language

Fix lists backward compatibility & markdown typedefs

---

packages/lexical-list/src/LexicalListItemNode.js
packages/lexical-list/src/LexicalListNode.js

Added/removed styles might overlap (e.g. property-specific classes in stylex) so make sure we delete first and then add needed classes
```
existing classes = [a, d]
classes to add = [a, b, c]
classes to remove = [a, d]
existing classes should become [a, b, c]
```

Fix add/remove classes order

---

packages/lexical-playground/src/Editor.jsx
packages/lexical-playground/src/plugins/TabFocusPlugin.jsx

This plugin will attempt to restore selection to the previous location in an editor when you tab focus back into the editor.

Add TabFocusPlugin

---

packages/lexical/Lexical.d.ts
packages/lexical/flow/Lexical.js.flow

I doesn't look like this property is actually used anywhere (correct me if I am wrong). It seems that it has been supplanted by ContentEditable style.
----
We've briefly discussed if we should instead get rid of the ContentEditable style and move it to root. The reasons we are not going this way are
1. ContentEditable is already used for the "global styles" and this means people would have to migrate after this change
2. If you want small differences for the root style of a nested composer, you can just pass a different ContentEditable style as the theme will be inherited from the parent if you don't pass it. If we go with root style approach, you will have to merge it with the parent's theme ( `initialTheme={{...baseTheme, root: 'nestedTheme__root'}}`).
3. We would like to stick with the …

Remove root style from EditorThemeClasses

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.jsx

Removing the empty node from the editor on discard changes from excalidraw.

Delete the excalidraw node from editor on discard changes

---

packages/lexical-playground/src/plugins/TabFocusPlugin.jsx
packages/lexical-rich-text/src/index.js
packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.js
packages/lexical-selection/src/index.js
packages/lexical/src/LexicalNode.js
packages/lexical/src/LexicalSelection.js
packages/lexical/src/LexicalUtils.js

Today, we call `selection.getNodes()` a lot. One such case is when you do `node.isSelected()`. If you do this in a hot path, it can cause a lot of slow-down. We can however apply a caching heuristic to `selection.getNodes()`. Upon the first pass we can cache the return value on the selection object. We just need to ensure we invalidate this cache correctly so we don't wrongly use the cache when something might have changed. My heuristic is:
- When calling `set` on a point, or add/clear/delete, thus "mutation" the selection.
- When calling `$setSelection`
- When mutating a node, via `getWritable()`
I might have missed some cases but let's see how this works out. In perf testing this dramatically improves performance in some cases.

Add a cache for selection.getNodes()

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.jsx
packages/lexical-playground/src/nodes/ExcalidrawNode/index.jsx

Only include the modal on open excalidraw. The rest of the elements include them only in case something has been already created with the tool.

Show excalidraw nodes only in case elements have been created

---

.github/workflows/test.yml
packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.js

We only cache the node_modules in the project root. Before https://github.com/facebook/lexical/pull/2073 was merged, we depended on dangerjs, which had a dependency on https-proxy-agent, so by coincidence, playwright was able to resolve that module because it was there in the root node_modules as a dependency of dangerjs.
Since we use a fork of playwright locally in the packages directory, a different node_modules gets created in packages/playwright-core as part of the workspace install. We don't cache this, and we don't run an npm install on a cache hit, so https-proxy-agent isn't there when playwright needs it to download browsers.
This fixes that by caching the playwright-core local node_modules. 
It also adds a GitHub Secret to the cache key which can be used to manually bust the …

Fix CI Caching

---

packages/lexical/src/LexicalEvents.js
packages/lexical/src/LexicalUtils.js

We have reports of emojis being inserted multiple times on Windows + Firefox using the Windows emoji picker. We actually fixed this issue in the past: https://github.com/facebook/lexical/pull/738. However, we can't use setTimeout, as it means that we invalidate composition too late.
In order to make the composition sequence work the same in FF as it does in Chrome/Webkit – we can defer ending composition till the subsequent `input` event comes in. Thus making the sequence behave like `compositionstart` -> `input` -> `compositionend`, even though `input` occurs after `compositionend` in Firefox.

Fix Firefox composition bug with emojis

---

packages/lexical-markdown/LexicalMarkdown.d.ts
packages/lexical-markdown/src/v2/MarkdownShortcuts.js
packages/lexical-react/LexicalMarkdownShortcutPlugin.d.ts
packages/lexical-react/src/LexicalMarkdownShortcutPlugin.jsx

- Make `transformers` prop optional for `<LexicalMarkdownShortcutsPlugin>` (as it was before)
- Add Horizontal Rule as a part of default transformers (as it was before)

Make markdown transformers optional

---

packages/lexical-playground/src/plugins/ActionsPlugin.tsx

Action button title/aria-label says 'speect' instead of 'speech'.

Fix typo in playground: speect → speech

---

packages/lexical-playground/src/plugins/ToolbarPlugin.tsx

This PR cleans up the Toolbar from the Playground, removing a ref that's never set.
Feel free to close this, if `mouseDownRef` is needed, but on master it's never actually used which caused me some confusion as I was replicating the Toolbar

Remove unused ref in Playground ToolbarPlugin

---

packages/lexical-markdown/src/v2/MarkdownExport.js

This should be a better fix: instead of checking for linebreaks and decorators, all we care is to see if sibling is element (then traverse inside) or if it's a text node (then return)

Better handling of siblings in md export

---

packages/lexical-website-new/docs/getting-started/quick-start.md

Instead of setting default onError on config  in createEditor.  i edit some docs for who use vanilla-js that onError is not optional. so include onError on config.

anotate onError is not optional type for who use vanilla-js in docs

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawImage.tsx

Hi there, Excalidraw core team member here 👋🏽
I was just playing around with the playground and realized that the saved scenes weren't being rendered because of the `appState` props null checking, we don't really need the `appState` when rendering the scenes.

[Lexical Playground]: Fixes Excalidraw saved scenes rendering

---

packages/lexical/src/LexicalNode.js

The variable dfsAncestor in LexicalNode.js looks useless. Although it is used for conditional judgment in the code, the code executed when the condition is true only reassigns dfsAncestor, which has no effect on the overall logic of the function getNodesBetween.

delete unuse variable dfsAncestor

---

packages/lexical/src/LexicalEvents.js
packages/lexical/src/LexicalSelection.js

We should be validating `window.event` is valid before attempting to use it.

Ensure window.event is valid

---

packages/lexical-website-new/docs/concepts/editor-state.md

We should be recommending people to use `JSON.stringify(editorState)` directly.

Fix editor-state.md

---

packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.js
packages/lexical/src/LexicalSelection.js

Replacing selected node with decorator/linebreak does not adjust selection properly. It supposed to move selection to the end of newly inserted node, which didn't happen for non-text/element nodes
Fix #2161

Adjust selection to be after decorator node when moving selection to the end of decorator/linebreak

---

packages/lexical-website-new/docs/concepts/nodes.md

There are some small typos in the documentation. This PR fixes them.

Fix typos in nodes.md

---

packages/lexical-playground/__tests__/e2e/Focus.spec.mjs
packages/lexical/src/LexicalEvents.js
packages/lexical/src/LexicalSelection.js

When the user moves selection outside the editor, we should aim to keep the selection object the same within the editor.

Ensure selection is not prematurely nulled out on blur

---

packages/lexical/src/LexicalEvents.js
packages/lexical/src/LexicalUtils.js

Fixes https://github.com/facebook/lexical/issues/2199. When handling text replacements, we need to handle the logic at a later stage than beforeinput. That's because we don't know what the selection should be after the replacement.

Fix text replacement event handling

---

packages/lexical-markdown/src/v2/MarkdownImport.js
packages/lexical-markdown/src/v2/MarkdownShortcuts.js
packages/lexical-markdown/src/v2/utils.js
packages/lexical-playground/__tests__/e2e/Markdown-v2.spec.mjs
packages/lexical-playground/src/plugins/MarkdownTransformers.ts

- Similar to #2136 which added intraword into markdown shortcuts (`_` should not be converted into italic if not surrounded with space/punctuation/newline), handling it during markdown import
- Couple fixes for playground transformers (table & tweet)
Fix #2159

Add intraword format support for Markdown import

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/MentionsPlugin.tsx

Fixes Issue #2217 
Instead of tracking both an `isSelected` and an `isHovered` state, this PR moves to a single piece of state to represent both (isSelected). This results in clearer UX, where only one item in the dropdown is highlighted at a time. More importantly, it fixes a bug where clicking on a hovered item does not insert the correct item.
Now any focus interaction can be paired with any selection action. Some examples:
- Use your keyboard to navigate + select a mention
- Use your mouse to hover + select a mention
- Use your mouse to hover over a mention, then keyboard (enter or tab) to select it
- Use your mouse to hover over a mention, then keyboard to navigate to another, then keyboard to select it
Hope this helps!

Replace isHovered with isSelected in mentions typeahead

---

packages/lexical/src/LexicalEvents.js

#2203 is causing an internal Meta error that `window.getSelection()` is undefined when server-side rendered. 
I think we should be fine to bypass this check completely as we don't need it until the editor is loaded and interactable

Fix window undefined issue when SSR

---

packages/lexical/src/LexicalEvents.js

Reverts facebook/lexical#2229
Come to think of it, I'm not sure this is the right fix. @thegreatercurve this code path is on a DOM event listener, which means there must be a window present for it to fire to begin with?

Revert "Fix window undefined issue when SSR"

---

packages/lexical-headless/src/__tests__/unit/LexicalHeadlessEditor.test.js
packages/lexical-plain-text/src/index.ts
packages/lexical-rich-text/src/index.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical-website-new/docs/concepts/commands.md
packages/lexical-website-new/docs/faq.md
packages/lexical/Lexical.d.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalCommands.js
packages/lexical/src/LexicalEvents.js

The `INSERT_TEXT_COMMAND` is misleading. It appears to be a signal for a user to detect some user text insertion, and allowing them to override it or change what is coming in. Actually, this couldn't be further from the truth – it's actually an internal signal used to let plugins know of a controlled text insertion, rather than a non-controlled text insertion (we let the browser do it and do not override). This PR renames it to `CONTROLLED_TEXT_INSERTION` to better communicate intent.
I also added a piece in the FAQ to explain how to go about listening for text insertions the correct way – using node transforms.

Rename insert text command

---

packages/lexical/Lexical.d.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalNode.js

`getTopLevelElement` should get the top most nested element, not the root.

Fix getTopLevelElement shouldn't get the root node

---

packages/lexical-react/src/LexicalAutoFocusPlugin.ts
packages/lexical-react/src/LexicalAutoLinkPlugin.ts
packages/lexical-react/src/LexicalAutoScrollPlugin.ts
packages/lexical-react/src/LexicalBlockWithAlignableContents.tsx
packages/lexical-react/src/LexicalCharacterLimitPlugin.tsx
packages/lexical-react/src/LexicalCheckListPlugin.tsx
packages/lexical-react/src/LexicalClearEditorPlugin.ts
packages/lexical-react/src/LexicalCollaborationPlugin.ts
packages/lexical-react/src/LexicalComposer.tsx
packages/lexical-react/src/LexicalContentEditable.tsx
packages/lexical-react/src/LexicalHashtagPlugin.ts
packages/lexical-react/src/LexicalHistoryPlugin.ts
packages/lexical-react/src/LexicalLinkPlugin.ts
packages/lexical-react/src/LexicalListPlugin.ts
packages/lexical-react/src/LexicalMarkdownShortcutPlugin.tsx
packages/lexical-react/src/LexicalNestedComposer.tsx
packages/lexical-react/src/LexicalOnChangePlugin.ts
packages/lexical-react/src/LexicalPlainTextPlugin.tsx
packages/lexical-react/src/LexicalRichTextPlugin.tsx
packages/lexical-react/src/LexicalTablePlugin.ts
packages/lexical-react/src/__tests__/unit/LexicalComposer.test.tsx
packages/lexical-react/src/__tests__/unit/PlainRichTextPlugin.test.tsx
packages/lexical-react/src/__tests__/unit/utils.tsx
packages/lexical-react/src/useLexicalNodeSelection.ts
packages/lexical-react/src/useLexicalTextEntity.ts
scripts/build.js

The recent refactor of `@lexical/react` to TS has caused some the imports to be incorrectly re-written. If relative imports are used, then we inline the module. We only want to do this for shared modules, otherwise this will cause major issues for npm/www releases.

Fix relative imports in @lexical/react

---

packages/lexical/src/index.js

This would be useful for cases where we want to use `RootNode` in a node transform.

Expose RootNode to be used in node transform

---

packages/lexical-markdown/src/v2/MarkdownExport.ts

When typing and combining different text-format's on text nodes, i.e. "**bold** _italic_" it's easy to break the markdown export as it currently applies the formatting characters around included whitespace.
i.e. `"  foo  "` becomes `"**  foo  **"` when we actually want it to be `"   **foo**   "`
This PR fixes that
---
Before:
After:
closes #2250

Trim whitespace before applying text formatting during markdown export

---

packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/Settings.tsx
packages/lexical-playground/src/appSettings.ts
packages/lexical-playground/src/plugins/MaxLengthPlugin.tsx
packages/lexical-selection/LexicalSelection.d.ts
packages/lexical-selection/flow/LexicalSelection.js.flow
packages/lexical-selection/src/index.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/nodes/LexicalElementNode.ts

This PR adds a MaxLengthPlugin, and an associated `@lexical/selection` helper function `trimTextContentFromAnchor` to make all the logic work well. Internally, we expose `RootNode` to be treated always as a dirty element if any of its children are dirty too.

Add MaxLengthPlugin

---

packages/lexical/Lexical.d.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx
packages/lexical/src/index.ts

The use case for this is taking a previously saved editor state and inserting it into an active editor state. In order to do this, we need the parsed nodes we want to insert to be in the activeEditorState, which is not the case if we just use the unstable_parseEditorState API and pass them in. Previously, we exported $createNodeFromParse for this.

Expose $parseSerializedNode

---

packages/lexical-history/src/index.ts
packages/lexical-selection/src/index.ts

This fixes some bugs reported in #2230. Specifically:
- History plugin should ignore a dirty leaf if it hasn't actually changed.
- We should adjust the anchor offset in the case it comes before the remaining offset.

Fix some bugs around MaxLength plugin

---

packages/lexical-website-new/docs/concepts/serialization.md

Documentation for the `Lexical` -> `HTML` and `HTML` -> `Lexical` introduced in #2246.

Add HTML export/import documentation to website

---

packages/lexical/flow/Lexical.js.flow

These methods will always return an ElementNode, but the method itself is on LexicalNode, so adding "this" to the return type means that TextNode.getTopLevelElement() returns a union of TextNode or ElementNode, which is wrong and causes issues downstream.

Fix flow round II

---

packages/lexical/src/LexicalUtils.ts

Extra overhead for production mode since we don't freeze selection there

Check for frozen selection only on dev env

---

packages/lexical-playground/vite.config.js

This should fix the invariant issue we've recently being seeing.

Ensure Babel plugins run for ts/tsx modules

---

packages/lexical-selection/src/index.ts

Another fix based off feedback from https://github.com/facebook/lexical/issues/2230#issuecomment-1136480124.

Fix bug in trimTextContentFromAnchor

---

packages/lexical-playground/src/plugins/AutocompletePlugin.tsx
packages/lexical-playground/src/plugins/CommentPlugin.tsx
packages/lexical-react/src/__tests__/unit/PlainRichTextPlugin.test.tsx
packages/lexical-react/src/shared/useCharacterLimit.ts
packages/lexical-text/LexicalText.d.ts
packages/lexical-text/flow/LexicalText.js.flow
packages/lexical-text/src/index.ts
packages/lexical-utils/src/__tests__/unit/LexicalRootHelpers.test.ts

The idea behind the curry suffix was to be able to provide an alternative that worked immediately on the read clause. For $textContent, which is widely used, the curry suffix is unnecessary (it doesn't take any parameter) and seemed confusing (maybe more now because someone killed the alternative function). So just cleaning this up and making it a single function without the suffix

Rename $rootTextContentCurry -> $rootTextContent

---

packages/lexical-playground/src/plugins/MaxLengthPlugin.tsx
packages/lexical-utils/LexicalUtils.d.ts
packages/lexical-utils/flow/LexicalUtils.js.flow
packages/lexical-utils/src/index.ts

Based off further feedback from https://github.com/facebook/lexical/issues/2230#issuecomment-1137838765. We can actually apply a heuristic where if the last editor state content was already at the max length, we just try and restore that editor state entirely.

Tune MaxLengthPlugin behavior for restoration

---

packages/lexical/Lexical.d.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalUtils.ts

This PR exposes two new update based utility functions:
- `$getUpdateTags`
- `$addUpdateTag`
These allow you to access any update tags that might existing the current update cycle. It also allows you to add an update tag to the given update too.

Expose $getUpdateTags and $addUpdateTag

---

packages/lexical-link/LexicalLink.d.ts
packages/lexical-link/flow/LexicalLink.js.flow
packages/lexical-link/src/index.ts
packages/lexical-react/src/LexicalLinkPlugin.ts

`toggleLink` isn't a React specific function. As such I moved it to lexical/link so that it can be used by other frameworks

move toggleLink to lexical/link

---

packages/lexical-playground/src/nodes/EmojiNode.tsx
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalNode.ts

We're missing a bunch of warnings and we're also missing the opportunity to do it on creation of the editor rather than at creation of node.

Improve DEV warnings for node methods

---

packages/lexical-playground/src/index.css

The Font Family overflows a bit behind the dropdown arrow.
Before:
After:

Fix overflow in select toolbar

---

packages/lexical-playground/src/plugins/CharacterStylesPopupPlugin.tsx

Fixes #2287 
https://user-images.githubusercontent.com/64399555/170713005-71aa49ee-71f1-4c06-a837-2122cf96a623.mp4
**Note:** Would require suggestions on how to handle the popup if the screen size is less than that of popup (or if we can ignore that case altogether)

Confine character popup to rootElementRect

---

packages/lexical-playground/__tests__/e2e/MaxLength.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs

Adds e2e for #2255 
https://user-images.githubusercontent.com/64399555/170990797-ea6962b4-b571-476f-9de9-4027b1cdaee1.mp4

Add e2e test for MaxLengthPlugin

---

packages/lexical-playground/src/index.css

In the playground, if page scroll is present then position of dropdown is not correct.

Fixed dropdown position in playground example

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/ToolbarPlugin.tsx

Closes #2190
https://user-images.githubusercontent.com/64399555/170961978-128faa38-23e9-4cdb-8e03-63e5f64d8f11.mp4
**Note:** Is it okay to leave the hashtag as is? Because lexical changes the node from text to hashtag whenever a string starts with "#". But due to changing the background color to default, the light blue background of the hashtag is being removed.

Feat: Add clear formatting button to playground

---

packages/lexical/src/LexicalEvents.ts

We should be ensuring that the anchor node is not the root before calling `getTopLevelElementOrThrow` on it, which will result in an invariant.

Strengthen onClick conditional

---

packages/lexical-react/src/LexicalTablePlugin.ts
packages/lexical-table/LexicalTable.d.ts
packages/lexical-table/flow/LexicalTable.js.flow
packages/lexical-table/src/index.ts
packages/lexical/Lexical.d.ts

`$createTableNodeWithDimensions` has an option to toggle headers on table cells. 
`INSERT_TABLE_COMMAND` enabled by LexicalTablePlugin should also accept this option (to disable marking first row/column as headers).

Add includeHeaders argument to INSERT_TABLE_COMMAND

---

packages/lexical-html/src/index.ts
packages/lexical-playground/src/nodes/EquationNode.tsx
packages/lexical-playground/src/nodes/ImageNode.tsx
packages/lexical-playground/src/nodes/StickyNode.tsx
packages/lexical-playground/src/nodes/YouTubeNode.tsx
packages/lexical-react/src/LexicalHorizontalRuleNode.tsx
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalNode.ts
packages/lexical/src/LexicalUtils.ts

This PR adds robust fallback logic for `exportDOM` and `importDOM` on the base `LexicalNode` class.
https://user-images.githubusercontent.com/13852400/171728151-9b5dfa4a-c239-4376-9b89-935242d697cf.mov

Add default exportDOM and importDOM methods

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical-playground/src/index.css
packages/lexical-playground/src/nodes/ImageNode.tsx
packages/lexical-rich-text/src/index.ts
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUtils.ts

Right now, how copy+cut with `NodeSelection` is broken. This PR attempts to actually make it work.

Enable copy+paste on NodeSelection

---

packages/lexical-playground/src/themes/PlaygroundEditorTheme.css

Small fix so that markers get aligned with the text as well. (Followed by Google Docs and Word too)

include bullet points as a part of list item

---

packages/lexical/src/LexicalEvents.ts

Fixes https://github.com/facebook/lexical/issues/2341#issuecomment-1146764943. This logic introduced in a recent PR, should only occur during node selection.

Fix copy + paste in plain text

---

packages/lexical-playground/src/collaboration.ts

Tested locally and the yjs demo server works `?collabEndpoint=wss://demos.yjs.dev`

Playground: allow custom collab endpoints

---

packages/lexical-website-new/docs/getting-started/react.md

Introduced by 0.3.0 global renaming.
I haven't checked if it's generalized to all the documentation 🤔

doc: fix wrong components names

---

packages/lexical/src/LexicalUtils.ts

After digging into https://bugzilla.mozilla.org/show_bug.cgi?id=1768330, I was able to reproduce the issue using Firefox on Windows. I couldn't get it working with Firefox on macOS. When you zoom in, and do `getBoundingClientRect`, you get back decimal numbers, and strangely, doing it of two elements that are the same size, can return slightly different values. One being `123.21` pxiels and the other being `123.22` pixels, which then causes the logic to incorrectly scroll.

Fix scrolling issues due to browser rounding bugs

---

packages/lexical-playground/__tests__/e2e/ClearFormatting.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/ToolbarPlugin.tsx

PR #2295 introduced the Clear All Formatting option but still, it doesn't correctly clear the text-alignment of the nodes by removing the styles. Instead, it adds an additional inline styling of "text-align: left" to all nodes. To correct this I have used the `$getNearestBlockElementAncestorOrThrow` to find the blockElement ancestor which aligns the node and formatted it to "" align (i.e. removal). While working on this, I've also realized that previously we didn't cover the alignment for Youtube videos and other nodes of the `DecoratorBlockNode` type and have fixed it as well.
cc @thegreatercurve 
Sorry for the inconvenience!

Fix: text alignment in clear formatting

---

packages/lexical-playground/__tests__/e2e/ClearFormatting.spec.mjs

We should be skipping if in plain text mode.

Fix ClearFormatting tests

---

packages/lexical/src/nodes/LexicalTextNode.ts

We can improve how spellcheck works in FF by using the composed text diffing path that avoids setting the text node to the entirely and just updates parts of it. This will incur a slight performance overhead, but it improves FF functionality for spellcheck users.

Improve FF spellcheck behavior

---

packages/lexical/src/LexicalEvents.ts

Turns out some logic added in https://github.com/facebook/lexical/pull/2203 isn't actually needed. This fixes compatibility with the Microsoft Editor extension.

Remove un-needed code

---

packages/lexical-playground/src/ui/Input.css

Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1067136
This would cause issues when there's less space like this:

fix overflow issue in input field

---

packages/lexical-website-new/docs/react/plugins.md

The current plugins names used in the docs (under ```/react/plugins```) give the following error:
**_Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports._**
That's because the names of the plugins that are used in the ```import```s do not match the names that were given to the plugins when they were created and ```export```ed. For example:
**Incorrect**
```jsx
import {LexicalListPlugin} from '@lexical/react/LexicalListPlugin';
```
**correct**
```jsx
import {ListPlugin} from '@lexical/react/LexicalListPlugin';
```
This is corrected by renaming the plugins names in …

fixed the names of plugins used in the docs

---

packages/lexical/src/LexicalEditor.ts

Came across this when working on the TS types auto-generation. 
The types for `LexicalEditor.toJSON` are `toJSON(): SerializedEditor`, but we're not actually turning the editor state into JSON. 
This causes a type issue on the ImageNode in the playground here, for the nested editor on the caption: https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/nodes/ImageNode.tsx#L396 
Am I right in thinking that the `.toJSON` method on the editor should also call `.toJSON` on the editor state?

Editor instance `toJSON` should call `toJSON` method on editor state

---

packages/lexical-playground/src/plugins/ClickableLinkPlugin.ts

For this plugin we want to let user selecting links with mouse but let clicking on links. It used to check pointer down & pointer up coordinates to detect selection, while it can be simplified to just checking if selection is collapsed.

Simplify clickable links checks

---

packages/lexical-html/src/index.ts
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalNode.ts

Because nodes are now serialized and added to the clipboard (#2370) there's no need for these default import/export DOM methods.

Remove default json and node-type from DOM output.

---

packages/lexical/src/LexicalEvents.ts

Turns out we were applying a blanket `preventDefault()` on all backspaces that were not range selection.

Fix backspace bug with non-RangeSelection

---

packages/lexical/src/__tests__/utils/index.tsx

The warnings make the unit test run incredibly slow. Interestingly, just implementing these two methods makes the unit tests run from 80 seconds to 50 seconds on my laptop.

Add importJSON/exportJSON to test nodes

---

packages/lexical-selection/src/index.ts

Fixes https://github.com/facebook/lexical/issues/2357. We no longer need to check for graphemes, as we already attempt to restore content from the last update instead, which is much more reliable.

Fix MaxLength bug

---

packages/lexical/src/LexicalSelection.ts
packages/lexical/src/index.ts

⚠️ While I tried not to make any breaking changes, there are still minor (but still interesting to bundle in because they're sort of fixes):
- LexicalNode
- LexicalEditor
- EditorState
- RangeSelection
- NodeSelection
All of the above will now only be exported as types, instead of interfaces or classes. These were always meant to be exported this way but originally were exported as classes because of Flow limitations.

Fix exposed private methods

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical-selection/src/index.ts

Currently we face an issue while pasting from Lexical <-> Lexical, the styles and formatting get copied as they should be (Thanks to #2370) But the problem is that the toolbar doesn't recognize the styles that are being pasted. You can see the issue in the video below:
https://user-images.githubusercontent.com/64399555/173834698-d79eef4f-771d-4585-abdc-bf9904f0a7cc.mp4
This is apparently because all the styles are stored in a Map which only gets set on applying a style, this PR adds the functionality to add styles to the Map even on paste.
https://user-images.githubusercontent.com/64399555/173834724-424b655b-50e7-4e5a-b35d-b5520c62b55d.mp4

fix: add styles on copy

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical/src/nodes/LexicalTextNode.ts

Before
https://user-images.githubusercontent.com/132642/173874728-2782a7d1-f1c0-4531-a966-1ea3e78011b9.mov
After
https://user-images.githubusercontent.com/132642/173874726-13f067fb-1f46-494c-b0a4-44342e8b710b.mov

Remove redundant newlines on pasting html

---

packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalMutations.ts
packages/lexical/src/LexicalSelection.ts

When we try and handle DOM text mutations, sometimes the mutation might not be one we want to use. One case is where a mutation happens on a node where the previous selection format did not match. Fixes https://github.com/facebook/lexical/issues/2403.

Improve text mutations around selection format changes

---

packages/lexical-code/src/index.ts
packages/lexical-link/src/index.ts
packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical-list/src/LexicalListNode.ts
packages/lexical-mark/src/MarkNode.ts
packages/lexical-playground/src/nodes/EquationNode.tsx
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/__tests__/utils/index.tsx
packages/lexical/src/nodes/__tests__/unit/LexicalElementNode.test.tsx

The `Spread` type could be a lot simpler, and is failing to pick up a few type issues, so this PR simplifies the logic and fixes any type errors.
```ts
// new:
export type Spread<T1, T2> = Omit<T2, keyof T1> & T1;
// old: 
export type Spread<T1, T2> = {[K in Exclude<keyof T1, keyof T2>]: T1[K]} & T2;
```

Improve `Spread` type

---

packages/lexical/flow/Lexical.js.flow

We can remove this due to #2390.

Remove unnecessary editor state generic from Flow types

---

packages/lexical-playground/__tests__/e2e/AutoLinks.spec.mjs
packages/lexical-playground/__tests__/e2e/Autocomplete.spec.mjs
packages/lexical-playground/__tests__/e2e/BlockWithAlignableContents.spec.mjs
packages/lexical-playground/__tests__/e2e/ElementFormat.spec.mjs
packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical-playground/__tests__/e2e/List.spec.mjs
packages/lexical-playground/__tests__/e2e/Markdown-v2.spec.mjs
packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/e2e/TextEntry.spec.mjs
packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs

Turns out the test failure was that we were checking both frames and expecting the same result.
Also, added the possibility to assert specific frames.

Fix Autocomplete test on Collab

---

.flowconfig
jest.config.js
packages/lexical-markdown/README.md
packages/lexical-playground/src/App.tsx
packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/appSettings.ts
packages/lexical-playground/src/nodes/ImageNode.tsx
packages/lexical-playground/src/nodes/StickyNode.tsx
packages/lexical-react/src/LexicalComposer.tsx
packages/lexical-react/src/LexicalPlainTextPlugin.tsx
packages/lexical-react/src/LexicalRichTextPlugin.tsx
packages/lexical-react/src/__tests__/unit/PlainRichTextPlugin.test.tsx
packages/lexical-rich-text/src/index.ts
packages/lexical-website-new/docs/concepts/editor-state.md
packages/shared/src/warnOnlyOnce.ts
tsconfig.json

Seemingly a gimmick but it's actually important for 2 reasons:
1. Support users to switch between plain text and rich text without conditionals
2. Fix nested editor initialEditorState population, which is very complicated is things are loosely coupled by plugins. Instead, with a LexicalComposer + NestedLexicalComposer we can handle this easily out of the box

initializeEditorState on LexicalComposer

---

package.json
packages/lexical-playground/__tests__/e2e/BlockWithAlignableContents.spec.mjs
packages/lexical-playground/src/index.css
packages/lexical-playground/src/nodes/ExcalidrawNode/index.tsx
packages/lexical-playground/src/nodes/StickyNode.tsx
packages/lexical-playground/src/nodes/TweetNode.tsx
packages/lexical-playground/src/nodes/YouTubeNode.tsx
packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts
packages/lexical-react/flow/LexicalBlockWithAlignableContents.js.flow
packages/lexical-react/src/LexicalBlockWithAlignableContents.tsx
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalReconciler.ts
packages/lexical/src/nodes/LexicalDecoratorNode.ts

Decorator now has an additional config parameter like createDOM. Do we strictly need DOM like in createDOM? The answer is we don't, we can't potentially build a good abstraction on top that extract the styles. However, it's reality, it's annoying, usually these nodes are tied with the component itself, so for the user having to create an additional abstract to pass their own styles in a different way it's not convenient.
This way we can pass `theme.embedBlock` and the component will automatically be rendered correctly without any further modifications.

Customizable DecoratorBlockNode via theme

---

packages/lexical-playground/src/ui/ImageResizer.tsx

This is fixed by dynamically adding `-webkit-user-select: none` to body when resizing
https://user-images.githubusercontent.com/22126563/174114795-47c42850-3f63-4083-be46-a3018ba8f6b3.mov
#2398

fix(lexical-playground): image node resizing bug in safari

---

packages/lexical-react/src/LexicalPlainTextPlugin.tsx
packages/lexical-react/src/LexicalRichTextPlugin.tsx

Minified to 
```
exports.RichTextPlugin=function({contentEditable:a,placeholder:c,initialEditorState:f}){void 0!==f&&(void 0)();let [b]=e.useLexicalComposerContext(),g=t(b),d=u(b);w(b,f);return h.createElement(h.Fragment,null,a,g&&c,d)}
```
`(void 0)()` -> that's really bad

Fix bad warnOnlyOnce minification

---

packages/lexical-website-new/src/css/custom.css

"Visit Playground" text color becomes invisible when using dark mode
https://user-images.githubusercontent.com/78015359/174300865-2e290ec4-88bb-4568-8879-72d99c6b5056.mp4

Fix button--outline hover color dark mode

---

packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs
packages/lexical-playground/src/index.css
packages/lexical/src/LexicalSelection.ts

Bad node offset when selection is backwards. Fixes https://github.com/facebook/lexical/issues/2439

Fix can format backwards when at first text node boundary

---

README.md

Fixes incorrect plugin names used in JSX to match imported names and comments out the theme ellipsis so the code is copyable into a test js runtime like Codesandbox.

Fix component/plugin import names in get started section

---

packages/lexical-link/src/index.ts
packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-playground/__tests__/keyboardShortcuts/index.mjs
packages/lexical-playground/src/plugins/ToolbarPlugin.tsx
packages/lexical/src/LexicalSelection.ts

- Fix pasting text in front of/after inline elements (links)
- Fix copying link (partially or full content), similar as it does in quip, notion, etc if copy link (even partial text) it has to include `<a>` tag as wrapper
https://user-images.githubusercontent.com/132642/174496291-64aa0022-6cd3-402a-80ea-0afb7ce30306.mov
https://user-images.githubusercontent.com/132642/174496323-b90d5bdf-b052-4735-a7aa-a3188f4e42aa.mov

Inserting inline elements

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical-list/src/LexicalListNode.ts
packages/lexical-list/src/__tests__/unit/LexicalListNode.test.ts
packages/lexical-react/src/LexicalComposer.tsx
packages/lexical-react/src/LexicalDecoratorBlockNode.ts
packages/lexical-react/src/useLexicalTextEntity.ts
packages/lexical-table/src/LexicalTableCellNode.ts
packages/lexical-table/src/LexicalTableRowNode.ts
packages/lexical-text/src/index.ts
packages/lexical-utils/src/index.ts
packages/lexical-website-new/docs/concepts/serialization.md
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalConstants.ts
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalMutations.ts
packages/lexical/src/LexicalNode.ts
packages/lexical/src/LexicalReconciler.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/nodes/LexicalElementNode.ts
packages/lexical/src/nodes/LexicalParagraphNode.ts
packages/lexical/src/nodes/LexicalTextNode.ts
packages/shared/types.d.ts
tsconfig.build.json
tsconfig.json

Writing these as smaller PRs as some of these types fixes involve changing business logic. This PR reduces the number of TS errors from 129 to 0 and enables strict mode for the build config (i.e. excluding Playground).
To test TS strict mode, run `tsc -p tsconfig.build.json`. 
**This PR needs to be reviewed carefully as it touches core business logic.**
#2469

Migrate to TS strict mode 3/n 

---

packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical/src/LexicalSelection.ts

This PR fixes #2484 by adding additional guards in `RangeSelection#insertText` to ensure the proper branch is taken in order to avoid infinite recursion for situations where text is inserted into nodes where the `parentNode` has `canInsertTextBefore` and/or `canInsertTextAfter` return `false`.
**Test failures before the fix:**
https://user-images.githubusercontent.com/463105/175008972-848431e1-8701-45b0-9aaa-0381fdf7b2ff.mp4
https://user-images.githubusercontent.com/463105/175008977-6624611c-308f-40cf-af95-899b029eae4b.mp4

Fix infinite recursion in insertText in RangeSelection

---

packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical/src/LexicalSelection.ts

Fix bug: Copy/Pasting formatted text from/to the editor places the caret at wrong place.
The reason for this bug appears to be that at some point the last element inserted is not equal to the last element
https://user-images.githubusercontent.com/22126563/174320921-b8ca7305-2fe9-41cc-abd6-b3270249e478.mov
closes #2459

fix(lexical): caret at wrong place when paste

---

packages/lexical-playground/src/plugins/ImagesPlugin.ts

I'm sorry. I made a mistake in this [PR](https://github.com/facebook/lexical/pull/2027). This is a redundant piece of code. I don't think we need it at all, because there is `rangeSelection.applyDOMRange(range);` to set the selection later.
We can remove it, and it won't make any difference.

chore(lexical-playground): remove redundant code

---

packages/lexical-website-new/docs/concepts/selection.md

Tiny typo fix in docs/concepts/selection

---

packages/lexical-markdown/src/v2/MarkdownShortcuts.ts
packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs
packages/lexical/src/LexicalSelection.ts

It seems that the problem is mainly related to the `selectionchange` event not being fired correctly. The update of the button style on the toolbar depends on the selectionchange event. However, when focusNode, focusOffset, anchorNode, and anchorOffset are exactly the same and selection has a format applied, the event is not fired correctly.
https://user-images.githubusercontent.com/22126563/175352875-77839c7a-06c6-450d-8dd3-d6eac56c9fb7.mov
closes #2498

fix(lexical): "selection.format" is not set correctly

---

packages/lexical-playground/__tests__/e2e/Composition.spec.mjs
packages/lexical-playground/src/plugins/TextFormatFloatingToolbarPlugin.tsx

Float toolbar should not be displayed during composition.
https://user-images.githubusercontent.com/22126563/175507437-674a9c3a-2eba-4498-8b0c-2dbd876e717f.mov
closes #2344

fix(lexical-playground): Floating toolbar displayed on composition

---

packages/lexical-html/src/index.ts

Nothing is generated if selection is null. This PR fixes $generateHtmlFromNodes to output whole editor contents if selection is null.
https://lexical.dev/docs/concepts/serialization
> When generating HTML from an editor you can pass in a selection object to narrow it down to a certain section or pass in null to convert the whole editor.
I think it might be more natural to generate it even when the selection is undefined.

Fix $generateHtmlFromNodes behavior if selection is null

---

README.md
docs/testing.md
package.json

The npm scripts for e2e testing have changed and this PR update docs and the run-all npm script.
https://github.com/facebook/lexical/pull/2513

Update e2e test docs and run-all script

---

packages/lexical-playground/__tests__/e2e/Images.spec.mjs
packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs
packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical/src/LexicalSelection.ts

The current logic is based on hardcoded conditions that rely on either the first node being a TextNode or the second. This breaks when the immediate sibling is not a TextNode. Given that `formatText` has to look exclusively at text nodes we can improve the logic by looking exclusively at the sorted text nodes.
https://user-images.githubusercontent.com/193447/175930858-4941a0d7-ae79-4a68-b61f-bee2b74b8d11.mov
Closes https://github.com/facebook/lexical/issues/2523

Revisit formatText node selection

---

packages/lexical-markdown/src/v2/MarkdownExport.ts
packages/lexical-markdown/src/v2/MarkdownImport.ts
packages/lexical-markdown/src/v2/MarkdownTransformers.ts
packages/lexical-playground/__tests__/e2e/Markdown-v2.spec.mjs

Adjustments around how markdown import/export deal with new lines:
- Export will use `\n\n` as block separator
- Import ignores empty paragraphs (but keeps empty quotes, lists, headings)
- Paragraph content is appended to the previous sibling if it is not empty separated by [hard line breaks](https://spec.commonmark.org/0.30/#hard-line-breaks)
- Multi-line blockquote content is appended 
These changes should make our markdown a bit closer to commonmark spec. It still has some differences, e.g. we do not support nested quotes (in general we do not nest quotes in editor) or soft line breaks
input:
```markdown
Paragraph text
continuation
Another paragraph
- List item
continuation
> Quote line 1
> line 2
continuation
```
output:
```html
<p>
Paragraph text<br>
continuation
</p>
<p>
Another …
```

Improve markdown newline export/import

---

package-lock.json
packages/lexical-headless/package.json
packages/lexical-playground/package.json
packages/lexical-react/package.json
packages/lexical-text/package.json
packages/lexical-utils/package.json
packages/lexical/package.json

We don't use `utility-types` any more but it's still incorrectly listed as an import in some packages. This PR Removes the imports.

Remove `utility-types` from all packages

---

packages/lexical-history/src/index.ts
packages/lexical-playground/__tests__/e2e/History.spec.mjs

The reason for the below bug is that when the `beforeInput` and `input` events fire simultaneously during composition, to trigger the update listeners,  the `beforeInput` event was being classed as an `OTHER` `changeType` instead of `COMPOSING_CHARACTER`. 
This PR ensure all composition events are classed as `COMPOSING_CHARACTER`. 
This ensures all history events when composing are correctly merged, meaning on undo or redo, the whole composed word is removed/re-inserted.
NOTE: There seems to be disparities between how some editors handle this. Word and Notes will remove the whole composed word on undo, despite if you pause during composition. ProseMirror and Quill will take you back to the last pause point.
Closes #2479

Fix IME bug in `lexical-history`

---

packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical/src/LexicalUtils.ts

This PR fixes #2520 by considering siblings in `$shouldInsertTextAfterOrBeforeTextNode`.

fix: insert text after delete next to inline node

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs

Reported by TextExpander users (app for text snippets) and matches other editors behavior
Before:
After:
https://user-images.githubusercontent.com/132642/175525525-a83d4702-5abc-4048-8317-1ec3a9c56bdb.mov

Pasting multi-line plain text into rich-text mode produces separate paragraphs

---

packages/lexical/src/LexicalConstants.ts
packages/lexical/src/nodes/LexicalTextNode.ts

Small improvement to the API of `TextNode`, to make the logic consistent with `toggleFormat`
Closes #2491

Add ability to set format and details on TextNode by `string`

---

packages/lexical-list/src/LexicalListNode.ts
packages/lexical-list/src/utils.ts
packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs

Fixes #2503
This probably needs a more comprehensive fix - we need to think about how we want to deal with unexpected HTML structures. Maybe we want to first parse the DOM and then sanitize it, or maybe we need a second sanitization pass on the returned subtree.
This also needs tests.

Normalize list children

---

packages/lexical-playground/src/index.css

Selection indicators do not wrap with wrapping text in the TreeView. It seems easiest to just remove the wrapping and show the indicators below the text with the correct scroll bars showing.
Closes #2311

Remove `white-space: pre-wrap;` for tree view

---

packages/lexical/src/LexicalEvents.ts

After we have selected an image/poll. When we click on an empty paragraph node or the end of a paragraph that ends with an image/poll, the `domAnchor.nodeType` will be ELEMENT_NODE
https://user-images.githubusercontent.com/22126563/176342847-82d30cc5-7094-4f9d-abd7-cbf428a15b02.mov
closes #2457

fix(lexical): deselecting a image/poll node by clicking

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical/src/nodes/LexicalTextNode.ts

function `convertSpanElement` does not handle `text-decoration: underline`
closes #2552 
https://user-images.githubusercontent.com/22126563/176366558-08a7e3d8-f317-4bb3-89b1-7e598f971ebd.mov

fix(lexical): Text with underline format is stripped out on paste

---

packages/lexical-playground/src/commenting/index.ts

Commenting is not working in collab mode after the #2496 TS migration. This PR fixes it.
[Can be reproduced on [playground](https://playground.lexical.dev/split?isCollab=true) as well]
https://user-images.githubusercontent.com/64399555/176446636-819079c8-fc89-4fcd-847f-aaead5311516.mp4
https://user-images.githubusercontent.com/64399555/176446981-2e682ec9-aae8-47c3-bbc9-efcf0e366323.mp4

fix: commenting issue after ts migration

---

packages/lexical-react/flow/LexicalAutoFocusPlugin.js.flow
packages/lexical-react/src/LexicalAutoFocusPlugin.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalEditor.ts

For long documents, `selectStart` is often more appropriate, whereas for shorter inputs `selectEnd` is preferable. Let's give the users the option to customize where the initial selection should be

Customize default focus position

---

packages/lexical/src/LexicalEvents.ts

Looks like 90% of the work to add dragend was done here: https://github.com/facebook/lexical/pull/1986
Only missing to add 'dragend' to the list of events.

Added dragend to list of rootElementEvents

---

packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

Like what we do with update and readOnly listeners #1602, add tests and fixes for command and mutation listeners to ensure we do not execute listeners that were added during current update cycle. This can cause an infinite listeners loop if we register to listener within synchronous useEffect call

Ensure to call existing listeners only (not newly added ones)

---

packages/lexical-playground/src/nodes/PollNode.css

Before:
Fixed after using `left` instead of `start`:

Fix Poll node arrow position

---

packages/lexical-playground/src/index.css

fix toolbar-item button style bug in safari.
closes #2622 .
before:
after:

fix(lexical-playground): fix toolbar-item button style bug in safari

---

packages/lexical/src/__tests__/unit/LexicalNode.test.ts

This clutters up the output on failures:
```
console.warn
TestNode should implement "exportJSON" method to ensure JSON and default HTML serialization works as expected
362 |             !proto.hasOwnProperty('exportJSON')
363 |           ) {
> 364 |             console.warn(
|                     ^
365 |               `${name} should implement "exportJSON" method to ensure JSON and default HTML serialization works as expected`,
366 |             );
367 |           }
at createEditor (packages/lexical/src/LexicalEditor.ts:364:21)
at createTestEditor (packages/lexical/src/__tests__/utils/index.tsx:394:30)
at packages/lexical/src/__tests__/utils/index.tsx:63:25
at mountMemo (node_modules/react-dom/cjs/react-dom.development.js:17225:19)
at Object.useMemo …
```

Fix unit test warning

---

packages/lexical-code/src/index.ts
packages/lexical-plain-text/src/index.ts
packages/lexical-playground/src/plugins/ActionsPlugin.tsx
packages/lexical-playground/src/plugins/CommentPlugin.tsx
packages/lexical-playground/src/plugins/TextFormatFloatingToolbarPlugin.tsx
packages/lexical-rich-text/src/index.ts
packages/lexical/src/LexicalCommands.ts
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts

Implements inference and enforcement of the payload type for `LexicalCommand`, as discussed in point 2. in #2536.

Capture the expected payload type in commands

---

packages/lexical-playground/src/commenting/index.ts
packages/lexical-playground/src/plugins/CommentPlugin.css
packages/lexical-playground/src/plugins/CommentPlugin.tsx

Fixes #2494
This modifies the code to introduce thread deletion too (removal), while comments are marked as deleted on deletion. Demo:
https://user-images.githubusercontent.com/64399555/176635280-a3a39f2a-4830-44b8-b083-75e6fe743613.mp4

feat: new way to delete comments and threads

---

packages/lexical-react/src/shared/useYjsCollaboration.tsx

Re-mounting collab editor does not trigger yjs tree update and keeps editor blank. Deleting root ydoc from ydocMap on collab unmount will make sure that re-mount will follow same doc sync process as original mount:
https://github.com/facebook/lexical/blob/11ad8f14bbd6ee523337a074e717cb55b3be5c18/packages/lexical-playground/src/collaboration.ts#L26-L31
Issue:
https://user-images.githubusercontent.com/132642/178752416-09283f40-ce3e-4d1a-b9fb-202c4e9bb931.mov

Delete doc from ydocMap on unmount. Fixes init on re-mount

---

packages/lexical-playground/src/plugins/CommentPlugin.css
packages/lexical-playground/src/plugins/CommentPlugin.tsx

The comment box in the footer of the collab comments sidebar is mainly there for decorative purposes, but as it doesn't allow replies, it's causing some UX confusion (i.e. #2615)
Rather than refactor it to be a thread, as it doesn't really showcase any functionality of Lexical that can't be shown with the inline comments, I thought it would be simpler to just remove the box.
Closes #2615
|Before|After|
|--|--|
|<img width="274" alt="image" src="https://user-images.githubusercontent.com/7748470/178762709-37a565aa-8c4e-4de9-9a52-74f81ca85587.png">|<img width="274" alt="image" src="https://user-images.githubusercontent.com/7748470/178762526-2801d6e7-4bd4-4acc-8ffe-61c2d6cd3c85.png">|

Remove comment box from comments sidebar footer

---

packages/lexical-devtools/src/background/index.ts
packages/lexical-devtools/src/content/index.ts
packages/lexical-devtools/src/devtools/index.ts
packages/lexical-devtools/src/panel/components/App/index.css
packages/lexical-devtools/src/panel/components/App/index.tsx
packages/lexical-devtools/src/panel/components/Node/index.tsx
packages/lexical-devtools/src/panel/components/TreeNode/index.tsx
packages/lexical-devtools/src/panel/components/TreeView/index.css
packages/lexical-devtools/src/panel/components/TreeView/index.tsx
packages/lexical-devtools/src/panel/components/main/index.css
packages/lexical-devtools/types.ts

- Fetches JSON `editorState._nodeMap` on initial app loading, and on subsequent updates.
- Renders tree `<Node>`s recursively.
https://user-images.githubusercontent.com/4361605/178168320-1aca6b43-cb8b-4325-9483-f4bce942a4cb.mov
---
Developer Tools Web Extension Planning Issue: #2127

Port ASCII State Tree to Browser Extension

---

packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs
packages/lexical/src/LexicalConstants.ts
packages/lexical/src/LexicalEvents.ts

Fix range selection formatting.
It looks like this bug is related to the format of our rangeSelection calculation. Here our calculation is not quite the same as the google doc. As an example:
- In google doc. When we have three letters 1(italic) 2(bold) 3(underline), and we select them, the selection will show that the format is nothing at this time. Only when all textNodes have a format at the same time will the selection show that it has a format.
- And in lexical, our logic is that as long as the anchorNode or focusNode has a certain style, we will show that selection.format has that style.
- When we can calculate the selection range correctly, the problem mentioned in the issue does not exist anymore.
----
closes #2626 
https://user-images.githubusercontent.com/22126563/178920657-20ba0 …

fix(lexical): calculate range selection formatting

---

packages/lexical-website-new/docs/react/plugins.md

Thank you for amazing work.
The `RichTextPlugin` currently accepts a placeholder as `JSX.Element | string`. 
But, docs are still documented as `null`. This PR fixes it.
https://github.com/facebook/lexical/blob/48bfe0809b4ea74ef09dbece193e8d1cc1f638d1/packages/lexical-react/src/LexicalRichTextPlugin.tsx#L30

fix(doc): RichTextPlugin placeholder

---

packages/lexical-utils/src/index.ts

Specify the return type of `$getNearestNodeOfType`.
an example:
```ts
const parentList = $getNearestNodeOfType(anchorNode, ListNode);
const listType = parentList?.getListType();
```
Currently `listType` is of type `any`, but after this PR it will be of type `ListType | undefined`.

Specify the return type of getNearestNodeOfType.

---

packages/lexical-code/src/index.ts
packages/lexical-playground/src/plugins/CodeActionMenuPlugin.css
packages/lexical-playground/src/plugins/CodeActionMenuPlugin.tsx
packages/lexical-playground/src/plugins/ToolbarPlugin.tsx

Keeps the language name consistent and friendly name.
https://user-images.githubusercontent.com/22126563/179778474-80f8d9c8-f96d-422c-8f05-5fed97fd2a63.mov
closes: #2657

fix(lexical-playground): code lang display

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical/src/nodes/LexicalTextNode.ts

We can't do this by default, as it wreaks havoc on plain text implementations and any editor that doesn't support these features.
The solution for supporting pasted arbitrary styles is to allow easier extension of the default nodes HTML importDOM functionality and then let people add support that way, maybe with some helper for commonly used ones.

Remove default styling imports on HTML paste

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

This allows the `LexicalTypeaheadMenuPlugin` to be utilized in React 17

Conditionally utilize `startTransition` if it's present

---

packages/lexical-list/src/formatList.ts
packages/lexical-playground/__tests__/e2e/List.spec.mjs

When the anchor and focus of our selection fall on the textNode, we don't have to change the selection because the textNode will be appended to the newly generated paragraph.
When selection is in empty nested list item, selection is actually on the listItemNode. When the corresponding listItemNode is deleted and replaced by the newly generated paragraph, we should manually set the selection's focus and anchor to the newly generated paragraph.
closes #2640
https://user-images.githubusercontent.com/22126563/180176157-f72e29ce-4cfc-4a70-8dc4-43719f7be7e1.mov

fix(lexical-list): remove list breaks if selection in empty

---

packages/lexical-playground/src/plugins/CommentPlugin/index.css

The icons related to comments are missing https://playground.lexical.dev/; this PR aims to fix that
.

fix: path to icons

---

packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

Twitter username can have underscores(`_`).
`\w` is equivalent to `[0-9a-zA-Z_]`.

Fix VALID_TWITTER_URL to allow underscores.

---

packages/lexical-playground/src/plugins/ComponentPickerPlugin/index.tsx

Use the correct import path that available in NPM package

fix(lexical-playground): LexicalTypeaheadMenuPlugin import

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawImage.tsx

This PR is nearly the same as #2174.
The Exclidraw feature isn't available in the current version, and this PR fixes it.
The reason is that in https://github.com/facebook/lexical/pull/2496/files#diff-f45027bac56b3f85c3bec26a2889fb714d521d060db7b1d9554ff6d1fc3421efR88 , the change in #2174 is reverted and the bug appears again.

fix(playground): fix rendering Exclidraw

---

packages/lexical-table/flow/LexicalTable.js.flow

Changed type for includeHeaders parameter from string to boolean to match the type of the parameter from the $createTableNodeWithDimensions function.

Changed type of includeHeaders parameter

---

jest.config.js

The coverage reports are causing the unit tests to fail in #2687, with the below error. The code in the PR is absolutely fine though.
```
Failed to collect coverage from /Users/johnflockton/Development/lexical/packages/lexical-react/src/LexicalLinkPlugin.ts
ERROR: Jest worker encountered 3 child process exceptions, exceeding retry limit
STACK: Error: Jest worker encountered 3 child process exceptions, exceeding retry limit
at ChildProcessWorker.initialize (/Users/johnflockton/Development/lexical/node_modules/jest-worker/build/workers/ChildProcessWorker.js:170:21)
at ChildProcessWorker._onExit (/Users/johnflockton/Development/lexical/node_modules/jest-worker/build/workers/ChildProcessWorker.js:254:12)
at ChildProcess.emit (node:events:527:28)
at Process.ChildProcess._handle.onexit …
```

Remove unit test coverage reports

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

Typeahead plugin gives error on some instances:
i) No option found, []
ii) On switching from linebreak in quote node to heading node
https://user-images.githubusercontent.com/64399555/180824717-377b0d41-4828-4838-a2b5-72971542c6ef.mp4

fix: check if options are empty

---

packages/lexical-link/flow/LexicalLink.js.flow
packages/lexical-link/src/__tests__/unit/LexicalLinkNode.test.ts
packages/lexical-link/src/index.ts
packages/lexical-react/src/LexicalLinkPlugin.ts

Issue: https://github.com/facebook/lexical/issues/2671
Support `target` and `rel` for LinkNode
Ideas for the future:
- Add an option in the [playground](https://playground.lexical.dev/) if link should be opened in the new tab

feat: Link node with target and rel

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.tsx
packages/lexical-playground/src/nodes/ExcalidrawNode/index.tsx
packages/lexical-playground/src/plugins/ExcalidrawPlugin/index.ts

Closes #1812 
- Add listeners for ESC key in Ecalidraw modal.
- Remove `onHide` method in favour of just `onDelete`, which was causing bugs (i.e. leaving empty Excalidraw nodes in the editor).

Listen for ESC in Escalidraw modal 

---

packages/lexical-playground/src/plugins/ActionsPlugin/index.tsx

Minor Typo Found while testing:
`setIsReadyOnly` -> `setIsReadOnly`

Fix: Minor Typo on Lexical Playground ActionsPlugin

---

packages/lexical-playground/src/hooks/useReport.ts
packages/lexical-playground/src/plugins/TypingPerfPlugin/index.ts
packages/lexical-react/src/LexicalTreeView.tsx

- Fixed `timeoutId` type (`setTimeout` returns a number  in browser  and `Timeout` object in node)
- Removed `window.` prefix, since it might break during **SSR**

fix: `timeoutId` type

---

packages/lexical/src/LexicalNode.ts

If a node is inserted while a `decoratorNode` is selected, it gives an error as it fails to receive a `topLevelElement`
Fix: The `topLevelElement` should be itself during a node selection so that the inserted node can be added using `insertAfter`
https://user-images.githubusercontent.com/64399555/182132955-f6fe368e-a68c-4bad-ad98-d862ae5495e6.mp4
https://user-images.githubusercontent.com/64399555/182132988-7ec067ac-7342-4a07-90a0-11b0055ca318.mp4

fix: getTopLevelElement for decoratorNode

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical-rich-text/src/index.ts
packages/lexical/src/LexicalEvents.ts

This adds some pretty fragile logic to preserve the formatting of a Google Docs "Title" when pasted into a Lexical editor using the core HeadingNode from @lexical/rich-text.
I do not understand why Google doesn't put something vaguely resembling semantic HTML on the clipboard when users copy from Docs, but I don't think it's going to change and we need to find a more robust way to deal with the idiosyncrasies.  
I noticed CKEditor has a whole separate plugin just for handling pasted HTML from Docs. Perhaps the most robust solution would be to not use HTML at all and instead build a conversion between the Google Docs JSON format (that is also on the clipboard) and Lexical.
For now, we have this.

Convert pasted Google Docs Title text into a Heading

---

packages/lexical/src/LexicalSelection.ts

There are cases (like, when the only item in selection is a decorator block) that you will not have text nodes in selection.
This used to fail with `Cannot read properties of undefined (reading 'getFormatFlags')
` previously, now it currently returns abruptly without failing.
Previously:
https://user-images.githubusercontent.com/3399236/178030889-eed3780a-6550-4b55-80f0-7af98dfe09fd.mov
Now:
https://user-images.githubusercontent.com/3399236/178030969-ca3994ec-8def-4a94-889b-fe49ee967745.mov
(basically it will not fail)

fix: Verify if there are text nodes before continue

---

packages/lexical/src/LexicalNode.ts

I realised we should also check for `isTopLevel` in #2741.

Tighten check on top level decorator nodes 

---

packages/lexical-devtools/src/devtools/index.ts
packages/lexical-devtools/src/panel/components/App/index.tsx
packages/lexical-devtools/src/panel/components/Chevron/index.css
packages/lexical-devtools/src/panel/components/TreeNode/index.css
packages/lexical-devtools/src/panel/components/TreeNode/index.tsx
packages/lexical-devtools/src/panel/components/TreeView/index.css
packages/lexical-devtools/src/panel/components/TreeView/index.tsx
packages/lexical-devtools/src/panel/components/main/index.css
packages/lexical-devtools/types.ts

https://user-images.githubusercontent.com/4361605/181681718-e1288646-d7bd-4c6e-9baf-77fa4c9d3da0.mov
---
Developer Tools Web Extension Planning Issue: #2127

Highlight DOM Nodes onHover of Lexical DevTools Node

---

packages/lexical-website-new/docs/collaboration/react.md

It's easy to miss and it breaks collab setup

Add initial editor state for collab example

---

packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalUtils.ts

These aren't exported externally so it's not a breaking change.

Remove unused function args from LexicalUtils

---

packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs
packages/lexical/src/LexicalEvents.ts

Selecting empty paragraphs calculated wrong selection format:

Fix selection format for empty paragraphs

---

packages/lexical-playground/__tests__/e2e/Keyboard.spec.mjs
packages/lexical/src/LexicalEvents.ts

Pressing `^ + T` works in Safari since it triggers onbeforeinput with `inputType=insertText`, while chrome uses `inputType=insertTranspose`:
fix #2751
https://user-images.githubusercontent.com/132642/182932055-f9a849a7-28f8-40c8-a320-312a2d4afb44.mov

Handle `insertTranspose` for `beforeinput` event

---

packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs
packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
packages/lexical-selection/src/__tests__/utils/index.ts
packages/lexical/src/LexicalSelection.ts

A few bugs in formatText affected selection retention and nodes formatting in case selection starts with non-text node:
1. Selection changes after formatting
https://user-images.githubusercontent.com/132642/183076029-8d848c8b-4427-4c9e-bb1e-aa9c78ae1ca5.mov
https://user-images.githubusercontent.com/132642/183076594-afb91e3d-6e51-44f6-994c-b35420246be8.mov
2. Selection formats only first text node
https://user-images.githubusercontent.com/132642/183076292-32adb1b1-6104-408c-8a3f-ce0f409c90e1.mov
3. Backward selection (focus is before anchor) converted to a regular one (anchor goes first). Select word backward, make it bold, press Shift + left arrow. Expected selection to keep expanding backward
https://user-images.githubusercontent.com/132642/183086040-c8f09519-25ef-4f45-933e-39d15822f002.m …

Selection#formatText to retain selection and handle all text nodes

---

.flowconfig
jest.config.js
packages/lexical-playground/src/nodes/ImageNode.tsx
packages/lexical-playground/src/nodes/PollNode.tsx
packages/lexical-playground/src/nodes/StickyNode.tsx
packages/lexical-playground/src/plugins/ActionsPlugin/index.tsx
packages/lexical-playground/src/plugins/CommentPlugin/index.tsx
packages/lexical-playground/vite.config.js
packages/lexical-playground/vite.prod.config.js
packages/lexical-react/flow/LexicalCollaborationContext.js.flow
packages/lexical-react/flow/LexicalCollaborationPlugin.js.flow
packages/lexical-react/src/LexicalCollaborationContext.ts
packages/lexical-react/src/LexicalCollaborationPlugin.ts
packages/lexical-react/src/LexicalNestedComposer.tsx
packages/lexical-react/src/__tests__/unit/utils.tsx
tsconfig.json

This PR moves `useCollaborationContext` out of the `LexicalCollaborationPlugin` and into its own file.
`LexicalCollaborationPlugin` imports functions from `@lexical/yjs`, which has a `yjs` peer dependency, and also from `y-websocket`.
At the same time, `useCollaborationContext` is used in `LexicalNestedComposer`.
The combination of those 2 was causing the application to crash if you tried to use `LexicalNestedComposer` without adding `yjs` and `y-websocket` as a dependency on your project.
`yjs` should not be mandatory to use nested composers.
By splitting the 2, it should hopefully solves this issue, as the new context file only imports types from `yjs` and has no runtime dependencies to either `yjs` nor `y-websocket`.

chore: Move useCollaborationContext to dedicated file

---

packages/lexical-playground/src/index.css

fix: dropdown icon css

---

packages/lexical-playground/src/plugins/CommentPlugin/index.css

**Description**
The list of comments do not scroll when overflowed, since the removal of footer section. This pr sets the height of the comment list section, and enables scrolling when overflowed.

Fixing comments list scrolling issue

---

packages/lexical-react/src/LexicalAutoLinkPlugin.ts
scripts/error-codes/codes.json

Fix the message when checking for the node registration in the autolink plugin.

chore(auto-link-plugin): fix invariant message for node registration check

---

packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/__tests__/utils/index.tsx

Fixes #2753
When running #insertNodes top level decorators should be treated as element nodes (vs text nodes, inline elements or inline decorators)
https://user-images.githubusercontent.com/132642/183555305-c7e13e25-cbe3-4e33-b939-0b7a40c37f67.mov

Fix inserting nodes next to top level decorators

---

packages/lexical-devtools/public/inject.js
packages/lexical-devtools/public/manifest.json
packages/lexical-devtools/src/background/index.ts
packages/lexical-devtools/src/content/index.ts
packages/lexical-devtools/src/devtools/index.ts
packages/lexical-devtools/src/inject/index.ts
packages/lexical-devtools/types.ts
packages/lexical-devtools/vite.config.js

This moves all of the code that was previously running as an inline string in `devtools.inspectedWindow.eval()` like so:
And moves it to a new `inject.ts` file:
---
Developer Tools Web Extension Planning Issue: #2127

Inject DevTools Script in Browser Extension

---

packages/lexical-react/src/LexicalTreeView.tsx

in cases where the debugger is a decendent of a form, the button will by default submit. preventing this.

prevent button from submitting forms

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical/src/LexicalSelection.ts

Fix #2810
`deleteLine()` relies on `domSelection.modify('extend', 'backward', 'lineboundary')` which works great when selection is on text, but needed couple adjustments if original or extended selection ends on element
https://user-images.githubusercontent.com/132642/184060903-2cc91a19-bc21-4071-8854-7a273053fb75.mov

Fix selection#deleteLine

---

packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
packages/lexical-selection/src/index.ts

Currently if a css property has a colon in its value the rest of the value following the colon gets cut off.
Ran into this when using a font family with a prefix e.g. `font-family: prefix:Arial`

fixed getStyleObjectFromRawCSS to handle css values with a colon

---

packages/lexical-list/src/formatList.ts
packages/lexical-selection/src/index.ts

Makes the helper function `$wrapLeafNodesInElements` transfer indent and formatting information to the newly created Element
https://user-images.githubusercontent.com/64399555/184502356-d016e5da-e159-4d81-b909-d8b912dcab49.mp4

fix: transfer format and indent info on wrap

---

packages/lexical-playground/src/nodes/FigmaNode.tsx
packages/lexical-playground/src/nodes/TweetNode.tsx
packages/lexical-playground/src/nodes/YouTubeNode.tsx
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

Adds fallback for FigmaNode similar to Youtube and Twitter
https://user-images.githubusercontent.com/64399555/184502809-94206350-ce8d-4b82-b57a-5e2d0fe78b42.mp4

fix: add fallback for code formatting

---

packages/lexical-playground/src/index.css

set cursor grab when image can be dragged. 
I've tried a lot but still can't resolve the problem of not being able to set the cursor when dragging

fix: set cursor grab when image can be dragged

---

packages/lexical-playground/src/index.css

The toolbar sometimes shows it's scrollbar at max width if the first dropdown contains a long enough string #2848
Fixes the below:

Small toolbar style fix

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

Right now the Typeahead Menu moves as you type and positions itself with the cursor instead of the trigger, this PR locks the left value at the trigger.
Before:
After:

Adjust Typeahead Styles

---

packages/lexical/src/LexicalUtils.ts

We should allow controlled text insertion for instances when a word can be transformed into an emoji (i.e. "angry" becomes "😡"), such as using the native MacBook control strip or a dynamic emoji keyboard.
Fixes #2850

Fix emoji insertion issue

---

packages/playwright-core/bundles/utils/package-lock.json

The package jpeg-js before 0.4.4 is vulnerable to Denial of Service (DoS) where a particular piece of input will cause the program to enter an infinite loop and never return.
**CVE-2022-25851**
`CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H`

Infinite loop in jpeg-js

---

packages/lexical-website-new/docusaurus.config.js
packages/lexical-website-new/package.json

This makes it so that adding a JSDOC comment to a function in one of the packages automatically does an incremental rebuild of the website in dev mode (npm run start:website)

Add watch mode for auto-gen doc comments in dev

---

packages/lexical/src/LexicalEvents.ts

This was an obvious bug on reflection – the boolean flag should have been `true` for delete backward.
Fixes https://github.com/facebook/lexical/issues/2824

Fix delete backward bug

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical/src/LexicalSelection.ts

Previously, trying to insert a code block in the middle of a list (i.e., not the last item in a multi-item list) would cause the page to crash because of an infinite loop (in LexicalNode.isAttached) that ultimately happened because, in insertNodes, we were appending a node to it's own child.
This changes how we handle inserting ElementNodes when the calculated insertion target ends up being a LineBreakNode. This happens when there's a LineBreak with nothing else after it OR all the content up to the LineBreak border is selected.
Now, we move the target to the LineBreakNode parent and get rid of the LineBreak.
This prevents the editor from crashing, but it doesn't perfectly handle the case where a LineBreakNode is in the middle of the parent Element (i.e., there's content before and …

Change linebreak node handling in insertNodes

---

packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/ActionsPlugin/index.tsx

Not sure when, but the border radius of the text and debug views is incorrect. This PR fixes them back to how they were before.

Fix playground visual styling

---

packages/lexical-website-new/docs/react/plugins.md

In [«Getting Started with React»](https://lexical.dev/docs/getting-started/react) there are the imports shown. But since they are not quite obvious (for a beginner) it's probably good to add them here, at least in the first example so people can then figure out the other imports easily themselves (same logic for all other components)

add the corresponding import to react doc

---

packages/lexical-website-new/docs/concepts/transforms.md

`addTransform` was renamed a couple of times (first to `addNodeTransform` then `registerNodeTransform`) but the doc page on transforms still referenced the original naming.

Replaced `addTransform` with `registerNodeTransform` in transforms doc

---

packages/lexical-react/flow/LexicalMarkdownShortcutPlugin.js.flow
packages/lexical-react/src/LexicalMarkdownShortcutPlugin.tsx

The `LexicalMarkdownShortcutPlugin` package extends the defaults from `@lexical/markdown` with a HR transform but didn't expose that default list making it harder for anyone wanting to use the defaults plus their own extensions.

Exported DEFAULT_TRANSFORMERS array in react LexicalMarkdownShortcutPlugin

---

packages/lexical-history/src/index.ts

Merging history entries from different editors can lead to a situation where the initial state update of a nested editor is merged with a change from the parent editor, leading to the EditorState with containing just the parent editor change never going onto the undo stack.
Example is an ImageNode that eagerly renders a nested editor caption with initial state set to undefined. This causes the following series of events:
1) editor.update -> insertImageNode
2) nestedEditor.update -> initializeEditorState
3) LexicalHistory updateListener (1) -> applyChange
4) HISTORY_PUSH -> put state before image node insertion onto undo stack, set historyEntry.current to new state with image inserted.
5) LexicalHistory updateListener (2) -> applyChange
6) HISTORY_MERGE (because of tag) -> don't push …

Don't merge history entries from different editors

---

packages/lexical-playground/__tests__/e2e/HorizontalRule.spec.mjs
packages/lexical-playground/__tests__/e2e/Images.spec.mjs
packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs
packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs
packages/lexical-playground/src/index.css
packages/lexical-playground/src/nodes/EquationNode.tsx
packages/lexical-playground/src/nodes/ExcalidrawNode/index.tsx
packages/lexical-playground/src/nodes/ImageNode.tsx
packages/lexical-playground/src/ui/ImageResizer.tsx
packages/lexical-react/src/LexicalHorizontalRuleNode.tsx
packages/lexical-rich-text/src/index.ts
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalSelection.ts

Keyboard navigation today around node selection is a bit wonky and broken. Specifically, you can't actually select a node using the keyboard arrow keys properly, nor can you escape node selection and move back to range selection using the keyboard arrow keys.
This PR fixes that problem and also tackles a few accessibility issues along the way with image nodes and horizontal rule nodes too.

Improve heuristics around node selection and keyboard navigation

---

packages/lexical-playground/src/commenting/index.ts

There're two plugins that use TOGGLE_CONNECT_COMMAND (collab + comments collab), returning `false` with higher priority for comments to let regular collab plugin handle toggle command as well

Playground: Fix collab connect/disconnect toggling

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

This would enable us to use keyboard shortcuts on `LexicalTypeaheadMenuPlugin` dropdown menu  without necessarily triggering conflicting key commands (ESC, ARROW, ENTER) declared by custom plugins. Currently only the opposite is possible since the priority is already at the lowest. 
Some more detailed background: https://stackoverflow.com/questions/73471798/lexical-key-command-conflict-and-priority

LexicalTypeaheadMenuPlugin - Increase priority for keyboard commands

---

packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/ActionsPlugin/index.tsx

The editor box doesn't properly clip at the boundaries of the white box (regression from https://github.com/facebook/lexical/pull/2724). This PR puts back the correct dimensions so the actions bar floats over the editor content
.

Fix editor content clipping bug

---

packages/lexical-code/src/CodeHighlighter.ts

Setting content from outside of editor (e.g. via setEditorContent) does not trigger highlighting as it checked for selection to retain it. In such cases if there's no selection or if it's not a range we don't need to change it and just run highlighting update

Allow code highlighting to run without active selection

---

packages/lexical-playground/src/nodes/ImageNode.tsx
packages/lexical-rich-text/src/index.ts

https://github.com/facebook/lexical/pull/2884 Introduced a bug where keyboard controls on inputs and other controls within a decorator were incorrectly triggering navigation on the decorator itself. We should always ensure that we're not within the decorator when doing such things.

Fix overriding keyboard controls on internal decorator

---

packages/lexical-clipboard/LexicalClipboard.js
packages/lexical-code/LexicalCode.js
packages/lexical-dragon/LexicalDragon.js
packages/lexical-file/LexicalFile.js
packages/lexical-hashtag/LexicalHashtag.js
packages/lexical-headless/LexicalHeadless.js
packages/lexical-history/LexicalHistory.js
packages/lexical-html/LexicalHtml.js
packages/lexical-link/LexicalLink.js
packages/lexical-list/LexicalList.js
packages/lexical-mark/LexicalMark.js
packages/lexical-markdown/LexicalMarkdown.js
packages/lexical-offset/LexicalOffset.js
packages/lexical-overflow/LexicalOverflow.js
packages/lexical-plain-text/LexicalPlainText.js
packages/lexical-rich-text/LexicalRichText.js
packages/lexical-selection/LexicalSelection.js
packages/lexical-table/LexicalTable.js
packages/lexical-text/LexicalText.js
packages/lexical-utils/LexicalUtils.js
packages/lexical-yjs/LexicalYjs.js
packages/lexical/Lexical.js

These seem to have been renamed to `ts` modules by accident. This breaks local package referencing outside of Vite.

Fix Lexical package main entry points

---

packages/lexical/src/LexicalReconciler.ts

We do this on lines 595-596 regardless.

Remove unnecessary text append in decorator node reconciler logic

---

packages/lexical-playground/__tests__/e2e/MaxLength.spec.mjs

Follow up to #2467 which failed e2e

chore: add e2e tests for maxlength plugin

---

.gitignore
packages/lexical-playground/__tests__/e2e/CodeActionMenu.spec.mjs
packages/lexical-playground/__tests__/e2e/Images.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalUtils.ts

Different approach (old https://github.com/facebook/lexical/pull/2872) by levering mouse down.
Techical considerations:
- The mousedown event alone is insufficient for to track the new selection. The DOM anchor/focus nodes will still be marked as null.
- Mousedown + mouseup combination is unreliable. FF has a different order: Chrome/Safari: mousedown -> selectionchange -> mouseup; FF (sometimes): mousedown -> mouseup -> selectionchange
- Since mousedown + selectionChange seems reliable across browsers I'm relying on this order in this PR.
https://user-images.githubusercontent.com/193447/186977135-0c511363-d2ce-4d23-a7a7-0fc6654a6ea3.mov
Closes https://github.com/facebook/lexical/issues/2856

Attempt transform of NodeSelection to RangeSelection on mouseDown

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-rich-text/src/index.ts
packages/lexical/src/LexicalSelection.ts

Pasting link within text moved selection to its end:
https://user-images.githubusercontent.com/132642/187054081-5adf11b1-6221-4970-a43b-afed5de53d03.mov

Fix link pasting

---

packages/lexical-markdown/flow/LexicalMarkdown.js.flow
packages/lexical-markdown/src/MarkdownShortcuts.ts
packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts
packages/lexical-react/src/LexicalMarkdownShortcutPlugin.tsx
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/index.ts

The markdown plugin should ensure that certain Lexical nodes are registered with the editor before attempting to apply a markdown transform. To do so, we can specify a list of dependencies for each transform, resulting in invariants if the node hasn't been registered.
This PR also introduces `$getEditor` to the public Lexical API, so the currently active editor is retrievable without having to pass around the editor binding.

Provide markdown plugin node dependencies

---

packages/lexical-list/src/index.ts
packages/lexical-mark/src/index.ts
packages/lexical/src/index.ts

Sorry if the similar PR to https://github.com/facebook/lexical/pull/2894 is bad practice, I'm new to contributing to OSS. The reason for this new PR is I changed the merge source branch name to reflect the changes now being made compared to previous changes.

Add serialized node type exports

---

packages/lexical/src/LexicalUpdates.ts

Fixes https://github.com/facebook/lexical/issues/2907.

Ensure we only mutate a non-readonly editor state

---

packages/lexical/flow/Lexical.js.flow
packages/lexical/src/index.ts

It's redundant now, so we can remove it.

Remove $getEditor

---

packages/lexical/src/LexicalUtils.ts

I've come full circle on this, and now I think the best idea here is to allow programmatic updates of the editor state regardless of the value of editor._readOnly. In attempting to implement something in the core that would stop programmatic updates by default and allow overriding that for specific updates via an update option, the intent was to make it easy for people to convert their editors into static content without having to worry about adding separate conditionals in all the places where programmatic updates can be triggered.
Practically, there are a lot of challenges with implementing this in the core. Command listeners are implicitly wrapped in a single editor.update, which causes a lot of problems with trying to apply behavior-changing modifiers (like options or tags) to …

Allow selection in readonly mode

---

packages/lexical-react/src/shared/useYjsCollaboration.tsx
packages/lexical/src/LexicalNode.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/nodes/LexicalElementNode.ts
packages/lexical/src/nodes/LexicalTextNode.ts

One thing I discovered in exploring readOnly is that a lot of these checks are redundant, since we already check readOnly in the getWritable method.

Remove redundant readonly checks.

---

packages/lexical-react/src/LexicalAutoEmbedPlugin.tsx

The `AutoEmbedPlugin` import from the source folder  `@lexical/react/src/LexicalTypeaheadMenuPlugin` which generates type definitions giving issue in downstream users.

Do not import LexicalTypeaheadMenuPlugin from src folder

---

packages/lexical-plain-text/src/index.ts
packages/lexical-rich-text/src/index.ts

We should let the default browser logic work if we don't have any selection, as we might be inside a decorator or other part of the editor that is showing some content unrelated to Lexical's selection model.

Avoid preventing default for copy events when there is no selection

---

packages/lexical/src/LexicalEvents.ts

When we have nested Lexical editors, we run into issues where events are duplicated on the parent editor due to how event propagation works. Rather than block the native event propagation – which can cause bugs around UIs that use other event systems (React's for example) we locally stop propagation for Lexical aware things.

Prevent nested editor event duplication

---

packages/lexical/src/LexicalUpdates.ts

If not, we'll hit an invariant!

Ensure editor states are cloned if read only

---

packages/lexical/src/LexicalEvents.ts

Sometimes in Android, you're not always in composition, so we should validate this before making assumptions. Fixes #2937.

Fix Android backspace bug

---

packages/lexical-playground/src/themes/PlaygroundEditorTheme.css

When a `position` property is declared on a DOM element, Safari will show the range selection highlighting between 2 elements when the anchor node is at the end of an element and the focus node at the start of the next sibling.
Removing the styling should fix this issue without causing any regressions.
Before
After
Closes #2797

Fix Safari selection bug

---

packages/lexical-react/flow/LexicalNestedComposer.js.flow
packages/lexical-react/src/LexicalNestedComposer.tsx
packages/lexical-utils/src/index.ts

This fixes a nasty bug whereby nested editors incorrectly inherited the transforms of the parent editor. Also provides a way of defining nodes separately from the parent editor.

Fix bug where transforms are inherited by nested editors

---

packages/lexical-react/flow/LexicalComposer.js.flow

We missed this one on the readOnly API change.

Fix Flow Type

---

packages/lexical-react/src/LexicalAutoLinkPlugin.ts

As can be seen at https://codesandbox.io/s/lexical-rich-text-example-5tncvy, if any sort of formatting is active (bold, italic, etc...) while typing a link, the formatting will be disabled on the text of the detected url, and on subsequent keystrokes, the url will break.
By applying the parent node's format to the autolink, this problem is resolved.

Fix link breaking when formatting on

---

scripts/build.js

Add empty comment in front of 'export' in a bundled file

---

.github/workflows/release.yml
.github/workflows/version.yml
package.json
scripts/npm/increment-version.js
scripts/npm/release.js
scripts/updateVersion.js

This will initially let us manually kick off end-to-end automated releases. Later, we can adjust the config easily to add support for nightly prerelease runs, or even release on every commit (to a different channel) if we want.
What this actually does now:
Creates a new manually-initiated workflow that creates a new branch, bumps the version across all packages, commits the changes, and pushes the branch to the remote. From there, someone needs to create a PR for it.
Creates a second automated workflow that runs when a commit is pushed to the "next" or "latest" branch. This won't actually release right now because I commented that step out, but once enabled, this would publish all packages to the npm release channel associated with the destination branch ('next' for prerelease and …

Automated releases

---

.github/workflows/version.yml

Add npm install step

---

packages/lexical-code/src/CodeNode.ts
packages/lexical-html/src/index.ts
packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical-website/docs/concepts/serialization.md
packages/lexical/src/LexicalNode.ts
packages/lexical/src/nodes/LexicalTextNode.ts

When parsing html we should ignore newlines except if it's within `<pre>` or code-like tags where it needs to be preserved. Although we can check for explicit`<pre>` tag, we can't easily check for code-like cases (e.g. github gists use tables for it) so this PR introduces "preformatted" flag for DOMTransformerFn, which will indicate that nested content should preserve newlines, otherwise it'll be removed.
Before:
https://user-images.githubusercontent.com/132642/189204784-3fa241d7-f07f-4543-b997-9bf6d0b312a6.mov
After:
https://user-images.githubusercontent.com/132642/189204778-6db2ba17-7727-466b-ba77-6253ffeef2aa.mov

Clean up redundant newlines during pasting

---

packages/lexical-plain-text/README.md
packages/lexical-rich-text/README.md
packages/lexical-website/docs/getting-started/quick-start.md

The link to rich-text and plain-text is "Page Not Found" in an [official document](https://lexical.dev/docs/getting-started/quick-start).
I changed the URL to the package page.
Let me know if this is not the intended link.

docs: Fix URL of rich-text and plain-text

---

packages/lexical-website/docs/concepts/editor-state.md

The documentation on saving/loading editor state is unclear what kind of data is expected from the `initialEditorState` which leads to confusion as in #1937. Mocked-up the `loadContent` function to return an `'empty'` initial editor state to make it clear.

docs: loadContent clarification

---

packages/lexical-react/flow/LexicalTableOfContents__EXPERIMENTAL.js.flow
scripts/www/rewriteImports.js

The current REGEX assumes it will end with a quote but React package imports always have a submodule

Fix WWW import rewrite for React

---

scripts/build.js

Noticed that `/**/` ([#2970](https://github.com/facebook/lexical/pull/2970)) is added in front of `exports.<api exports>`:
```
/**/exports.exportFile = exportFile;
```
Updated reg expo will only prefix `export` word

Fix www exports

---

.github/workflows/release.yml
package.json
scripts/npm/increment-version.js
scripts/npm/release.js
scripts/npm/update-changelog.js

This adds some logging and optional dry-run argument to the release script.
The workflow to create a release branch now works. The next step is to run this workflow, which kicks off whenever we push to latest or next. In that case, it runs the release build and releases on the appropriate channel. dry-run mode is controlled by a github secret and these branches are protected (like main) such that they can only be touched via PR.
After this is approved, I'll try releasing to the "next" branch, first as a dry run, then live, to see if it all works (including npm auth). "latest" is our stable branch and we won't touch that until we're sure next has been working well for a while.

[Automated Releases] Add logging and dry run to release script

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-playground/src/plugins/TableCellResizer/index.tsx
packages/lexical-react/src/LexicalTreeView.tsx
packages/lexical-rich-text/src/index.ts
packages/lexical-selection/src/index.ts
packages/lexical-table/src/LexicalTableCellNode.ts
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/LexicalTableRowNode.ts
packages/lexical-table/src/LexicalTableSelection.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical-utils/src/index.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx
packages/lexical/src/index.ts
packages/lexical/src/nodes/LexicalGridCellNode.ts
packages/lexical/src/nodes/LexicalGridNode.ts
packages/lexical/src/nodes/LexicalGridRowNode.ts

Long-term, we want to eventually remove these APIs from Lexical's core. This work can likely be done by migrating the logic into the table package directly, or by using an alternative approach to handling tables. Lots of the logic for handling grids in core is just purely around tables and it seems unnecessary that every Lexical user should take the 3-4kb cost for having this logic if they don't ever use it.
Short-term though, this is a lot of work to do and we have higher priorities to fulfil first as a team. So in the interests of advocating for users to not invest more time into this APIs, this PR adds the `DEPRECATED_` prefix to all the Grid APIs.

[0.5] Add DEPRECATED prefix to Grid APIs

---

packages/lexical-text/flow/LexicalText.js.flow
packages/lexical-text/src/index.ts

These helpers are pretty specific for old markdown implementation

Rm unused helpers from older markdown code

---

packages/lexical/src/LexicalUpdates.ts

Fixes #2993 
Have made changes as suggested by @trueadm. Cursory testing within our app suggests this change fixes the useEffect cleanup bug I noted in #2993, although I cannot speak to any other side effects it might have.

Capture pendingDecorators after garbage collecting detached decorators

---

packages/lexical/src/LexicalEvents.ts

Should resolve part of the issue found in https://github.com/facebook/lexical/issues/2991. This strengthens the logic around making selection dirty.

Strengthen RangeSelection dirty toggle

---

packages/lexical-list/src/formatList.ts
packages/lexical-markdown/src/MarkdownShortcuts.ts
packages/lexical-playground/src/plugins/ImagesPlugin/index.ts
packages/lexical-playground/src/plugins/PollPlugin/index.ts
packages/lexical-playground/src/plugins/TablePlugin.tsx
packages/lexical-react/src/LexicalTablePlugin.ts
packages/lexical/src/LexicalNode.ts
packages/lexical/src/LexicalReconciler.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/nodes/LexicalElementNode.ts

Full pass on existing code to determine which ones are actually `$isRootOrShadowRoot` vs solely `$isRootNode`

[0.5] Revise usage of root node vs shadow

---

packages/lexical-selection/flow/LexicalSelection.js.flow
packages/lexical-selection/src/index.ts

We currently offer `$getSelectionStyleValueForProperty` and `$getStyleObjectFromCSS` as a way to directly access the value of the style properties they set on a TextNode.
Problem is it only works when these styles are applied via @lexical/selection, lexical style changes are never taken into account.
There's 3 ways to fix this:
1. Have this function be more generic and less Node centric. The style records are always computed regardless of the source. (They weren't cleaned up anyway)
2. Have some sort of listener that listens to TextNode modifications are updates the Map accordingly (difficult to use)
3. Add to cache whenever you setValue: requires moving all style CSS to core (worth it?)
This PR implements 1 which is the one with the least friction and more user-friendly. …

getStyleObjectFromCSS to compute when cache miss

---

packages/lexical-history/src/__tests__/unit/LexicalHistory.test.tsx
packages/lexical-playground/src/plugins/ComponentPickerPlugin/index.tsx
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-selection/README.md
packages/lexical-selection/flow/LexicalSelection.js.flow
packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
packages/lexical-selection/src/index.ts

The "LeafNodes" part is a lie. Plus, given it's part of the @lexical/selection package we can simplify the name

[0.5] $wrapLeafNodesInElements -> $wrapNodes

---

packages/lexical-html/src/index.ts
packages/lexical/src/nodes/LexicalElementNode.ts

This is a breaking change, so we'll need to go to 0.5.
Previously, we treated undefined differently than null here for backwards compat. undefined would end up just returning an empty string, which is super confusing. Now, leaving off the selection argument completely will return the entire contents of the editor converted to HTML.

[0.5] Treat undefined selection the same as null in $generateNodesFromHtml

---

packages/lexical-react/flow/LexicalCollaborationPlugin.js.flow
packages/lexical-react/src/LexicalCollaborationPlugin.ts
packages/lexical-react/src/shared/useYjsCollaboration.tsx
packages/lexical-yjs/src/SyncCursors.ts

By default cursors container is appended into body, which works fine for regular layout, but in case it has any nested scrolling or more complicated positioning cursors are not rendered correctly, especially after scrolling. This PR adds `cursorsContainerRef` to `<CollaborationPlugin>` which defines where cursors will be appended.
https://user-images.githubusercontent.com/132642/190506567-913b0270-956a-408a-9642-b070b09a5be1.mov
https://user-images.githubusercontent.com/132642/190506563-127afa67-96da-48be-a367-ba4131dbcdb0.mov

Add optional cursors container prop for a better positioning in scrollable layouts

---

packages/lexical-plain-text/flow/LexicalPlainText.js.flow
packages/lexical-plain-text/src/index.ts
packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/nodes/ImageComponent.tsx
packages/lexical-playground/src/nodes/StickyComponent.tsx
packages/lexical-react/flow/DEPRECATED_useLexicalPlainText.js.flow
packages/lexical-react/flow/DEPRECATED_useLexicalRichText.js.flow
packages/lexical-react/flow/LexicalComposer.js.flow
packages/lexical-react/src/DEPRECATED_useLexicalPlainText.ts
packages/lexical-react/src/DEPRECATED_useLexicalRichText.ts
packages/lexical-react/src/LexicalComposer.tsx
packages/lexical-react/src/LexicalPlainTextPlugin.tsx
packages/lexical-react/src/LexicalRichTextPlugin.tsx
packages/lexical-react/src/__tests__/unit/utils.tsx
packages/lexical-react/src/shared/usePlainTextSetup.ts
packages/lexical-react/src/shared/useRichTextSetup.ts
packages/lexical-rich-text/flow/LexicalRichText.js.flow
packages/lexical-rich-text/src/index.ts
packages/lexical/src/nodes/LexicalTextNode.ts

Remove warning, make the change permanent

[0.5] Remove initialEditorState from  Plain/RichTextPlugin

---

packages/lexical-react/src/LexicalCollaborationPlugin.ts
packages/lexical-react/src/shared/useYjsCollaboration.tsx

This PR is a follow-up of [this discord thread](https://discord.com/channels/953974421008293909/1013899629894565979/1013900284247953498).
I tested this feature, by connecting the WebsocketProvider to my custom Websocket server which removes the YDoc from persistence when there were no connections (last user disconnected)
Here is the `initialEditorState` that I passed to `CollaborationPlugin`
```js
<CollaborationPlugin
id="main"
providerFactory={createWebsocketProvider}
shouldBootstrap={!skipCollaborationInit}
initialEditorState={`{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"1","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text" …
```

feat(lexical-react): add initialEditorState for LexicalCollaborationPlugin

---

packages/lexical-playground/src/plugins/AutoEmbedPlugin/index.tsx
packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx
packages/lexical-react/src/LexicalAutoEmbedPlugin.tsx
packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

Before (notice the embed/dismiss menu is on the left + the floating menu opens even though it's an autolink)
After (correct positioning)

Add position property to menus & disable floating link toolbar for autolink nodes

---

packages/lexical-mark/src/index.ts

As noted in #3026, creating a nested mark while wrapping a forward selection is currently broken because the logic sets all inline elements as the target node to be wrapped, whereas if the inline element is a mark node we should continue in to the existing mark node to split its children, rather than wrap the entire mark node. This only affects forward selections because the forward selection contains the mark node, whereas a backward selection which ends inside another mark node does not include that mark node.
I also added some comments and renamed one variable for additional clarity in following the logic. The comments may be able to be improved, they reflect my understanding of this code just coming to it from the outside.
Fixes #3026

Fix nested mark creation when wrapping forward selection

---

packages/lexical/src/LexicalUtils.ts

The `$shouldInsertTextAfterOrBeforeTextNode` condition was not correct
Before
https://user-images.githubusercontent.com/193447/191381565-012a9ae1-184a-446c-ae31-96b3275317a8.mov
After
https://user-images.githubusercontent.com/193447/191381566-f0156ef3-5c84-4c8c-b4df-919a06ac0c83.mov
Closes https://github.com/facebook/lexical/issues/3044
*Tried writing an E2E test but our custom Playwright IME doesn't work exactly the same way as the browser and I couldn't get it to repro there, we have to look into this at some other point*

Fix composition text boundary for canInsertTextAfter

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/ComponentPickerPlugin/index.tsx
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-table/src/LexicalTableSelection.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Long term the solution is to improve on the React-only approach MVP here (#2929) but this gets the existing solution in much better shape.
This PR fixes the following known table bugs (seen list at bottom).
Most notably, now you can change the block type within a `TableCell` without it breaking.
https://user-images.githubusercontent.com/13852400/189770404-f6fe9a07-289b-4c4e-9530-e067341cb9e8.mov

Fix (Known) Table Bugs

---

packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/nodes/LexicalElementNode.ts

Before
https://user-images.githubusercontent.com/13852400/191811851-aa1c7b6d-188d-411a-b1a5-0aa3a5d37248.mov
After
https://user-images.githubusercontent.com/13852400/191811862-da68fa77-9192-4c61-b3ff-62edf3ea2710.mov

Improve table selection handling when there are no siblings

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

It was flagged to me that sometimes the node will "update" but the text will be the same. This should not result in the typeahead menu closing so I've removed the line.
Manually tested and the behavior seems identical. Unsure why this line was there in the first place.

Refine Typeahead isOpen logic.

---

packages/lexical-react/src/LexicalHorizontalRuleNode.tsx

Hi the team,
Feel free to reject this pull request if you had a reason to remove exportDOM/importDOM for HorizontalRuleNode here https://github.com/facebook/lexical/pull/2324.
Currently, we lose the information during import/export since the horizontal rule is replaced by a div due to the DecoratorNode type (the root decorated with the React Component)

feat: add export/import DOM for horizontal rule node

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs

Fix pasting from google docs adds extra paragraphs / linebreaks
Closes: #3058

fix(lexical-clipboard): pasting from google docs

---

packages/lexical-playground/src/Editor.tsx

Idk if it was an accident or on purpose, but regular tables are no longer resizable, because TableCellResizer was removed. It doesn't look like this plugin clashes with the new experimental table at a first glance.

chore(lexical-playground): add resizability back to regular tables

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-playground/src/ui/ColorPicker.tsx
packages/lexical-playground/src/ui/DropDown.tsx

Added support for readonly mode in toolbar
Closes: #3065
https://user-images.githubusercontent.com/22126563/192739816-f2deec60-f231-4b83-b63c-dd5f937c9bfa.mov

fix(lexical-playground): read-only mode

---

packages/lexical-playground/src/nodes/TweetNode.tsx

Very opinionated PR but I think having a fallback to text for non-Lexical editors is a much better experience
https://user-images.githubusercontent.com/193447/193140469-eb026434-73a2-4155-978d-6ee0af7aacae.mov

Tweet fallback to text on copy

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical-clipboard/src/index.ts
packages/lexical-playground/src/nodes/TweetNode.tsx
packages/lexical-rich-text/src/index.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/index.ts

Copying a Node will only store `text/html` into the clipboard. This differs from copying a RangeSelection when we copy `text/plain`, `text/html` and `application/x-lexical-editor` to fulfill a wider range of use cases. For example, when pasting content we would rather have the JSON serialized content as its the exact copy (most fidelity) Lexical can offer.
The current Node and Grid selection copy relies on the Clipboard API that is still relatively new, to the point that even some everly green browsers do not support setting more than one item at once.
At the same time, the fact that only the newest browsers can rely on Clipboard means that older browsers that we still want to support will be unable to copy Node or Grid.
The main difference between a RangeSelection and a NodeSelection …

Double-trigger hack for high-fidelity Node/Grid selection

---

packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/images/icons/caret-right-fill.svg
packages/lexical-playground/src/index.css
packages/lexical-playground/src/nodes/PlaygroundNodes.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/Collapsible.css
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleContainerNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleContentNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/index.ts
packages/lexical-playground/src/plugins/ComponentPickerPlugin/index.tsx
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

Kind of an experiment with nested elements (vs going w/decorator and nested editors). Main part is in transformers that enforce nesting structure (and if it's violated unwrap content and convert collapsible content into regular paragraphs)
```
CollapsibleContainer
> CollapsibleTitle
> CollapsibleContent[isShadowRoot]
> Paragraph
> Heading
> ...
```
https://user-images.githubusercontent.com/132642/192806800-292aa729-c5e6-41d1-9ba6-02259f1d9d6e.mov

Add collapsible container plugin

---

packages/lexical-clipboard/flow/LexicalClipboard.js.flow
packages/lexical-clipboard/src/clipboard.ts
packages/lexical-rich-text/src/index.ts

`copyToClipboard` is an asynchronous operation. Moreover, it can fail on certain selection or browser conditions. This PR makes it so that it returns a `Promise<boolean>` which should help the user handle the response appropriately.
For our immediate use case, cut, this helps us understand when the clipboard operation is complete so that we can remove the content safely from the screen (fixes race condition).
Closes https://github.com/facebook/lexical/issues/3103

copyToClipboard to return success

---

packages/lexical-html/src/index.ts

Otherwise it'll fail with "document" is not defined

Fix DOM availability check

---

packages/lexical-table/src/LexicalTableSelectionHelpers.ts

There was an issue reported where Table key navigation took priority over Typeaheads that were open inside of them. This PR and #3106 solve this.

Lower key navigation command priority for Tables

---

packages/lexical-react/flow/LexicalTypeaheadMenuPlugin.js.flow
packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

When using virtualization or other special rendering methods you may want to listen for the `SCROLL_TYPEAHEAD_OPTION_INTO_VIEW_COMMAND` command.
This PR also increases the priority of typeahead command listeners since when the menu is open any keystrokes may be relevant to the typeahead's internal behavior. For example, there was an issue reported where Table key navigation took priority over Typeaheads that were open inside of them. This PR and #3107 solve this.

Typeaheads: Add scroll command and increase priority

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/AutoEmbedPlugin/index.tsx
packages/lexical-playground/src/plugins/ComponentPickerPlugin/index.tsx
packages/lexical-playground/src/plugins/MentionsPlugin/index.tsx
packages/lexical-react/flow/LexicalAutoEmbedPlugin.js.flow
packages/lexical-react/flow/LexicalTypeaheadMenuPlugin.js.flow
packages/lexical-react/src/LexicalAutoEmbedPlugin.tsx
packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

Lexical is a rich text editing framework, not a popover framework, so it's a slippery slope to start including dynamic positioning with our plugins. It should be up to the developer to wire our `anchor` to a popover solution of their choice or use a React Portal and menu with some basic margin.
When this plugin was originally created it was designed with the common "bottom" alignment hard coded by forcing the `anchor` to be positioned below the line (see red box below).
This works for common use cases but quickly gets in the way as soon as you want to use a popover with auto alignment that may shift positioning to the top of the anchor when it'd otherwise be off screen.
Now the `anchor` is positioned "over" the selection so you can handle the menu positioning however you'd like.

Typeaheads: Remove hard-coded "bottom" alignment (Breaking change)

---

packages/lexical-playground/src/plugins/DraggableBlockPlugin/index.tsx

fix(lexical-playground): draggable blockplugin uses unexposed apis

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/AutoEmbedPlugin/index.tsx
packages/lexical-playground/src/plugins/ComponentPickerPlugin/index.tsx
packages/lexical-playground/src/plugins/MentionsPlugin/index.tsx
packages/lexical-react/flow/LexicalTypeaheadMenuPlugin.js.flow
packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

- Cleans up old containers after the menu closes (fixes memory leak).
- (BREAKING CHANGE) Use a ref instead of the element directly (better compatibility).
- Properly set the width for `NodeMenus` (powers AutoEmbed)
This PR adds some sort-of hacky CSS into the playground to make this work, but long term we can consider swapping in a Popover library.

[0.6] More Typeahead Changes

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical/src/LexicalSelection.ts

https://user-images.githubusercontent.com/193447/194163012-f8f06978-afee-48c7-8a20-efabd706c7c5.mov
This PR also prevents TableCellNode properties from being copied over, which was being done accidentally by the previous behavior. Is this what the best behavior? It is with the currently supported feature for TableCells but won't be as soon as we add more. Unfortunately, the good fix for this second issue is to delegate all this Grid logic to it's own package. https://github.com/facebook/lexical/issues/3121

Fix GridSelection comparison

---

packages/lexical-playground/src/plugins/ComponentPickerPlugin/index.tsx

Previously the string `h1` would match the dynamic table options in the component picker.
Before:
After:

Fix Dynamic Table Options on Playground Component Picker

---

packages/lexical/src/LexicalMutations.ts

DOM mutations inside inputs of decorator nodes sometimes do not resolve to the correct state.
https://user-images.githubusercontent.com/1575198/194123575-fa20d99d-0d5e-494d-bf1b-be4b614b79cd.mov
**Discord related thread:** https://discord.com/channels/953974421008293909/955972012541628456/1027227449278349385
**Note:**
This does not seem to be fixing the problem with nested lexical editors, but it fixes the problem when decorator nodes have other non-lexical fields, i.e. a custom `contentEditable` element.
Here are steps to reproduce the issue in this specific use case:
1. Replace lexical caption field on the ImageNode with a `conentEditable` field
```diff
diff --git a/packages/lexical-playground/src/nodes/ImageComponent.tsx b/packages/lexical-playground/src/nodes/ImageComponent.tsx
index …
```

Ignore mutations which do not have target node

---

packages/lexical-utils/src/__tests__/unit/LexicalElementHelpers.test.ts
packages/lexical-utils/src/index.ts

PR Branch:
LexicalElementHelpers tests
addClassNamesToElement() and removeClassNamesFromElement()
✓ basic (2 ms)
✓ empty
✓ multiple
✓ space separated (1 ms)
Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        3.324 s
Main:
LexicalElementHelpers tests
addClassNamesToElement() and removeClassNamesFromElement()
✓ basic (3 ms)
✕ empty
✓ multiple (1 ms)
✓ space separated (1 ms)

Ignore empty class names in addClassNamesToElement

---

packages/shared/src/environment.ts
packages/shared/src/getDOMSelection.ts

Resolves #3095 and remove duplicate `CAN_USE_DOM`

Check if DOM is accessible when calling `getSelection`

---

packages/lexical-rich-text/src/index.ts

Null check got lost when moving to experimental copy helper. It avoids cut/copy event from being handled in non-active editor (e.g., when running cut in nested editor)

Fix nested editor cut

---

packages/lexical-website/docs/concepts/commands.md

Fixed faulty file extension in the url for the useList example in the Commands docs, ending in a 404 page.
Changed the file extension from .ts to .js.

docs: Fixed broken link

---

packages/lexical-playground/src/nodes/TableComponent.tsx
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

This would allow synchronous updates (e.g. for tests and some cases of headless mode):
```js
editor.update(() => {
...
}, { flushSync: true });
// Update and listeners are already executed
```

Add flushSync option to update()

---

examples/decorators.md
packages/lexical-link/src/index.ts
packages/lexical-list/src/index.ts
packages/lexical-playground/src/plugins/CommentPlugin/index.tsx
packages/lexical-playground/src/plugins/EquationsPlugin/index.tsx
packages/lexical-playground/src/plugins/ExcalidrawPlugin/index.ts
packages/lexical-playground/src/plugins/FigmaPlugin/index.tsx
packages/lexical-playground/src/plugins/ImagesPlugin/index.tsx
packages/lexical-playground/src/plugins/PollPlugin/index.tsx
packages/lexical-playground/src/plugins/SpeechToTextPlugin/index.ts
packages/lexical-playground/src/plugins/TablePlugin.tsx
packages/lexical-playground/src/plugins/TwitterPlugin/index.ts
packages/lexical-playground/src/plugins/YouTubePlugin/index.ts
packages/lexical-react/flow/LexicalAutoEmbedPlugin.js.flow
packages/lexical-react/src/LexicalAutoEmbedPlugin.tsx
packages/lexical-react/src/LexicalHorizontalRuleNode.tsx
packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx
packages/lexical-table/src/index.ts
packages/lexical-yjs/src/index.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalCommands.ts
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

In the future, when we add logging for commands to the developer extension, we need a way of getting access to the command types as plain strings. At the moment we can't do that as the commands are originally instantiated as empty objects.
This diffs adds in an optional type object for the command object, which we can use in the logger.

Add type to commands for logging 

---

.github/workflows/dev-release.yml
.github/workflows/nightly-release.yml

The last change wasn't quite right - the workflow is now that a pre-release branch should be created every night, then the team will need to merge that into main, then into next to actually release. We can fully automate IF we are willing to drop branch push protections.

Change release workflows

---

packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical-selection/src/lexical-node.ts

Fixes #3115.
As mentioned in that issue, it might be better to fix this by checking before splitting instead, I'm not sure.

Fix when the selection is anchored to the end of a text node followed by a non-text node

---

packages/lexical-rich-text/src/index.ts

Internal test fails because we freeze Selection in dev and  [this PR] (https://github.com/facebook/lexical/pull/3177/files) causes us to try to get a reference to the frozen one via read callback and then try to modify it in a subsequent update.

Fix frozen selection

---

package-lock.json
packages/lexical-list/src/formatList.ts
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-selection/src/range-selection.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

This is a patch. The real solution is to refine [the way selection is modified after hitting backspace](https://github.com/facebook/lexical/blob/573a716ef97218927007943689c420a8749107ce/packages/lexical/src/LexicalSelection.ts#L1818). The focus should not be moved to a node with a different `shadowRoot`, but right now this is how native domSelection works.
Before:
https://user-images.githubusercontent.com/13852400/196534120-69f71430-b0b5-4686-bfac-2e4ed95b04d2.mov
After:
https://user-images.githubusercontent.com/13852400/196534211-dad4ada4-9db1-435d-b9ea-cb3ba433ba33.mov

Refine backspace handling in Tables

---

packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/plugins/TableOfContentsPlugin/index.css
packages/lexical-playground/src/plugins/TableOfContentsPlugin/index.tsx

* The outline had a problem where it rendered headings text twice. This was due to the plugin being called two times - merge conflict side effect or something? 
* Hid the outline scrollbar, and decreased its width so it fits next to the editor.
* Moved the scroll callback numbers to constants for better readability and modularity.

fix: fixed dual text appearance problem and removed outline scrollbar

---

packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical-list/src/formatList.ts
scripts/error-codes/codes.json

Generics are a lie https://github.com/facebook/lexical/issues/3152#issuecomment-1273576531
Turns out there is a way to make this fail.. we need to investigate the root of the problem. Fixing the existing crash scenario
---
See https://github.com/facebook/lexical/issues/3227

Handle bad list item children gracefully

---

packages/lexical-list/src/LexicalListNode.ts
packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs

ListNode was trying to convert anything that wasn't another ListNode or a ListItem into a new text node. We shouldn't do that in a lot of cases, but this code hasn't been touch since Lexical was called Outline :)

Fix list paste issue

---

packages/lexical-code/flow/LexicalCode.js.flow
packages/lexical-code/src/CodeHighlighter.ts
packages/lexical-code/src/index.ts

Prism has powerful functionality to handle various languages including custom language, 
but some other tools like [ANTLR](https://www.antlr.org) have their own grammar definition and parser generator.
This PR exposes the Tokenizer interface at `registerCodeHighlighting` in @lexical/code plugin to handle such a case.

Expose Tokenizer interface to accept custom tokenizer other than Prism at @lexical/code

---

packages/lexical-markdown/src/MarkdownImport.ts
packages/lexical-markdown/src/__tests__/unit/MarkdownImport.test.ts

The`importTextMatchTransformers` use the splitText method to handle the match and continue the loop. 
However it never use the left part of the match as the split text method returns an array of text node. 
Thus if you have a future textMatchTransformers match in the left part (before the replaceNode) it won't be caught.
I just catch the left part of the match and do a recursive call to the same method to handle this.
Let me know if there any other way of doing it.

Handle left part of match

---

.eslintrc.js
eslint-plugin/package.json
eslint-plugin/src/index.js
eslint-plugin/src/rules/index.js
eslint-plugin/src/rules/no-optional-chaining.js
package-lock.json
package.json

Resolves #3074
1. Created a new `eslint-plugin` inside the project directory and added a new rule (`no-optional-chaining`) in it.
2. Added the plugin in `.eslintrc.js` to detect the usage of optional chaining
3. Added the locally created `eslint-plugin-lexical` to _package.json_
Rule reference: https://github.com/mysticatea/eslint-plugin-es/blob/master/lib/rules/no-optional-chaining.js

chore: add new `eslint-plugin` with rule `no-optional-chaining` locally

---

packages/lexical/src/LexicalSelection.ts

Lexical does not provide a way to control whether it should auto-scroll or not when the selection changes.
**Context:**
I am working on the implementation of a "click to set cursor near decorator nodes" feature https://github.com/facebook/lexical/issues/3157. I am using lexical selection to detect where the custom caret is supposed to be. Since lexical (which matches with the native APIs) does not allow distinguish if the caret is set before or after an element, I chose to treat such selection as "after the previous node" (as opposed to "before the current/offset node") because input changes from this state create a new block between the nodes, so it feels natural to visually indicate the caret at the end of "the previous node".
```
node1[caret]
node2
```
_any input changes format the …

Allow skipping auto-scroll action on selection change

---

packages/lexical-react/src/DEPRECATED_useLexicalDecorators.tsx
packages/lexical-react/src/LexicalPlainTextPlugin.tsx
packages/lexical-react/src/LexicalRichTextPlugin.tsx
packages/lexical-react/src/shared/useDecorators.tsx

`<ErrorBoundary fallback={null} />` fails (in contrast with `<Suspense fallback={null} />`), so changing to `<ErrorBoundary fallbackRender={() => null} />`

Fix error boundary fallback

---

packages/lexical/src/LexicalEditor.ts

It shouldn't matter if the editor is empty when called `editor.focus`. The cursor should still appear somewhere in the editor when the method is called.

Select end if root has no children in focus logic

---

package-lock.json
packages/lexical/src/LexicalReconciler.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx
packages/lexical/src/__tests__/utils/index.tsx

If link empty link (inline element) is the list child it would've had `<br>` added in dom

Do not reconcile terminating linebreak for inline elements

---

packages/lexical/src/LexicalEditor.ts

Reverts facebook/lexical#3254
Looks like this fails some collab tests:
https://github.com/facebook/lexical/actions/runs/3322384417/jobs/5492978426

Revert "Select end if root has no children in focus logic"

---

packages/lexical/src/LexicalUtils.ts

This is a little more complicated than I thought, but I think the issue is that the TS compiler isn't convinced by the instanceof and __type checks that nodesOfType will actually return T and not a different subtype of LexicalNode. My solution is to cast to T, because these checks should verify that all nodesOfType are of the same subtype of LexicalNode at runtime.

Fix nodesOfType return type

---

packages/lexical-react/src/LexicalCollaborationContext.ts
packages/lexical-react/src/LexicalCollaborationPlugin.ts
packages/lexical-yjs/src/SyncCursors.ts

- fix(lexical-yjs): remove height from collab cursor name
We remove the selection height because it does not work with a common CSS style
```css
* {
box-sizing: border-box;
}
```
when we remove the height it works
---
- feat(collab): add cursorColor prop for LexicalCollaborationPlugin
I had to create a sibling for the caret span in order to give devs the possibility to provide any color for the caret, name, and selection.
---
Also, I think that we should add the possibility to specify a className (for the name at least) to give more freedom.
CC @fantactuka

Improve Collab cursor, add custom cursorColor

---

packages/lexical/src/LexicalEditor.ts

We already had `root` theme class but it was never applied to root node, it's quite useful for font styles (especially for nested editors which otherwise might inherit styles from its decorator)

Add root theme class

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-selection/src/range-selection.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalNode.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts

Tables had some logic to override the deletion logic that was incomplete. This prevented new lines from being deleted.
However, when attempting to fix this (and switching the DELETE_CHARACTER command to be unhandled) it uncovered a bigger problem, the fact that selection can expand beyond a ShadowRoot and cause cells to be deleted. This shouldn't be the responsibility of tables, so I'm handling the ShadowRoot case appropriately in Selection but rather generic.
Closes https://github.com/facebook/lexical/issues/3278

selection.modify to respect ShadowRoot

---

packages/lexical-playground/src/index.css
packages/lexical-react/src/LexicalTablePlugin.ts

This PR would fix initializing tables that are a part of initial content. The problem is that mutation listeners are not called for existing nodes, hence if table is inserted as initial content, it won't get its selection + listeners initialized causing multiple bugs (around columns/rows management and selection). 
My first attempt was to replace it with node transform, but it when it runs, table DOM element is not yet created (for newly inserted node) so it can't initialize all DOM listeners.
So instead, it would still use mutation listener, but also run through existing nodes on mount to initialize it as well.
Before
https://user-images.githubusercontent.com/132642/198669600-b16bf448-3ed5-40fc-a669-1c5feaca90f6.mov
After
https://user-images.githubusercontent.com/132642/198669590-850c9492 …

Fix initial content tables initialization

---

.github/workflows/nightly-release.yml
.github/workflows/pre-release.yml

This makes it so that commits tagged with the prerelease "-next" suffix will trigger a release when merged into main. This might finally make nightly releases work, but we'll have to merge the PRs each day to trigger the release. Full automation would require taking branch protections off of main, which I don't want to do yet (looking for alternatives).
This also makes the PRs only generate Mon-Fri.

Release on matching tag push to main

---

scripts/npm/increment-version.js
scripts/npm/update-changelog.js

Fix `npm run increment-version` to handle commit messages with quotes
Additionally, simplified the argument so that it's `npm run increase-version minor` instead of `npm run increase-version -- -i minor`

Handle quotes in increment-version changelog

---

packages/lexical-headless/src/__tests__/unit/LexicalHeadlessEditor.test.ts
packages/lexical/src/LexicalUpdates.ts

In non-headless mode there's a separate logic that either reuses previous selection or relies on dom. For headless we just copy previous selection

Preserve selection for pending state

---

packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/nodes/LexicalDecoratorNode.ts

While navigating within the editor using keyboard keys (Arrow Left/Right) it automatically captures decorator nodes as a selection step. Whereas it is a cool feature, in some products such behavior can be not the desired one.
There is no easy way to override this behavior as it mostly requires reimplementing lexical's [selection modify](https://github.com/facebook/lexical/blob/a2d745fa10f593600938c0c0670f2c8b373935a5/packages/lexical/src/LexicalSelection.ts#L1704) handler to be able to handle text selection correctly.
Add a new flag to allow optionally disable automatic selection as a step of keyboard selection navigation.
**Note:** This is different from `isIsolated` which prevents selection altogether.

Optional decorator nodes selection with keyboard navigation

---

packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
packages/lexical-selection/src/range-selection.ts

Fixes https://github.com/facebook/lexical/issues/2647
The wrapping nodes function should skip nested leaf nodes if their parents are already wrapped (appended).

Fix wrapping nodes with nested leaf nodes

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical/src/LexicalSelection.ts

Pasting text near decorator nodes loses the parent element and inserts children nodes inline as direct children of the root node.
**Steps to reproduce:**
https://user-images.githubusercontent.com/1575198/198649730-9be20a68-687d-47cc-b759-c6f26a2589fb.mov
(**Note:** There is a visual glitch where the cursor is set near the last HR whereas in fact it is set between the nodes. This is reported separately here https://github.com/facebook/lexical/issues/3156)

Fix pasting text near decorator nodes

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

Trying to cache it between re-renders is causing a race condition where the activeRange can be nulled when the listener triggers.

Create range on each listener invocation in Typeahead

---

packages/lexical-playground/src/plugins/CollapsiblePlugin/Collapsible.css

Polish CSS styling fill caret icon.
Result:

fix: align center fill caret icon on `CollapsiblePlugin`

---

scripts/npm/increment-version.js

Not quite sure why this suddenly broke - maybe an npm version change in the Github Actions runtime

Fix increment-version

---

packages/lexical-react/src/LexicalCollaborationContext.ts

Plenty of colors had contrast less than 2, now all are 4.5+

Update collab cursor colors to pass a11y contrast ratio

---

README.md
packages/lexical-website/docs/getting-started/react.md
packages/lexical-website/docs/react/plugins.md

This pr fixes missing `ErrorBoundary` props to `PlainTextPlugin` in docs and README.md.

docs: set `ErrorBoundary` props to `PlainTextPlugin`

---

packages/lexical-link/flow/LexicalLink.js.flow
packages/lexical-link/src/index.ts
packages/lexical-react/flow/LexicalAutoLinkPlugin.js.flow
packages/lexical-react/src/LexicalAutoLinkPlugin.ts
packages/lexical-website/docs/react/plugins.md

this is a follow-up to #2687 (which resolved issue #2671) that extends support for setting link target and rel to the `AutoLinkPlugin` component via its `matchers` prop. it adds optional `rel` and `target` fields to the `LinkMatcherResult` type and forwards those along to `$createAutoLinkNode`, or uses `linkNode.setRel` / `linkNode.setTarget` in `handleLinkEdit` if they have changed.
i also updated the lexical-react docs plugins page’s `AutoLinkPlugin` section to adopt the default protocol behavior introduced in #2654 and added commented-out example usage of the new LinkMatcher `rel` and `target` fields ([preview](https://lexical-git-fork-acusti-feat-link-node-with-ec78d1-fbopensource.vercel.app/docs/react/plugins#lexicalautolinkplugin)). i wasn’t sure how to properly document it, so if …

feat: Extend support for link target and rel to lexical-react’s AutoLinkPlugin

---

packages/lexical/flow/Lexical.js.flow

Apparently, we need this on strict Flow-based surfaces

Nit FlowFixMe hint

---

packages/lexical-playground/src/hooks/useLexicalEditable.ts
packages/lexical-playground/src/hooks/useLexicalSubscription.tsx
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-playground/src/plugins/TableCellResizer/index.tsx

Resizer and menu shouldn't be available on non-editable
Porting useLexicalSubscription from internal, may eventually move to @lexical/react

Disable table addons on non-editable

---

packages/lexical-rich-text/src/index.ts

When copying, MSWord adds content as an image to the clipboard (apart from various text formats data), and our file copy/pasting logic which is executed before text content parsing inserts that image instead of actual text content:
https://user-images.githubusercontent.com/132642/200468353-3922b892-8045-43eb-86bd-45b445798900.mov

Filter out mixed files + content copy pasting

---

packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

It turns out that a small mistake on `beginUpdate` causes the pendingEditorState to be lost when the rootElement has not yet been set. This rarely happens with React, but it turns out it can be reproable when dynamically switching editors.

Fix content loss when setEditorState + update race condition

---

packages/lexical-website/docs/demos/plugins/images.md
packages/lexical-website/docs/demos/plugins/lists.md
packages/lexical-website/docs/demos/plugins/mentions.md
packages/lexical-website/docs/demos/plugins/tables.md

Add table plugin example

---

packages/lexical-utils/flow/LexicalUtils.js.flow
packages/lexical-utils/src/__tests__/unit/LexicalUtilsSplitNode.test.tsx
packages/lexical-utils/src/index.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts

1. `$splitNode` would allow splitting current tree up until root or shadow root and enhance insertions. As of now `$insertNodeoNearestRoot` takes nearest top-level child and appends node after it, which is not very precise. Here's an example with nested lists:
```
- Top level
- Text before <split here> text after
- More nested items
- More top level items
```
with selection on `<split here>`, `$insertNodeoNearestRoot` would insert node after the whole list. `$splitNode` aims to allow splitting nested trees to insert where user would expect, e.g. calling `$splitNode(listItem, 1)` would split it into two separate lists:
```
- Top level
- Text before
-
- text after
- More nested items
- More top level items
```
It should address limitation of #2322 and allow splitting any arbitrary nested …

Add $splitNode & $copyNode

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx
packages/lexical-utils/flow/LexicalUtils.js.flow
packages/lexical-utils/src/__tests__/unit/LexicalUtilsSplitNode.test.tsx
packages/lexical-utils/src/__tests__/unit/LexlcaiUtilsInsertNodeToNearestRoot.test.tsx
packages/lexical-utils/src/index.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/__tests__/utils/index.tsx
packages/lexical/src/index.ts

Using `$splitNodes` allows insertion in the middle of the text with nodes tree being split up until nearest root:
https://user-images.githubusercontent.com/132642/200885233-6a0f0983-63fe-4be6-b12a-b1ef1a9c5946.mov

Improve $insertNodeToNearestRoot

---

packages/lexical-website/docs/demos/plugins/sticky-notes.md

Add sticky notes plugin example

---

scripts/www/rewriteImports.js

Summary:
There is an extra space found in the docblock comment of '@oncall'. This was brought into WWW files.
This diff removes the unnecessary trailing space.
Test Plan:
CI

[Lexical] [WWW] Remove the extra space after the oncall shortname

---

packages/lexical-website/docs/demos/plugins/images.md
packages/lexical-website/docs/demos/plugins/markdown.md

Add markdown plugin example

---

packages/lexical-website/docs/demos/plugins/embeds/_category_.yml
packages/lexical-website/docs/demos/plugins/embeds/figma.md
packages/lexical-website/docs/demos/plugins/embeds/twitter.md
packages/lexical-website/docs/demos/plugins/embeds/youtube.md

Add YouTube, Figma and Twitter plugin examples 

---

packages/lexical-website/docs/demos/plugins/collapsible-container.md

Add collapsible container plugin example

---

packages/lexical-link/src/index.ts
packages/lexical-playground/__tests__/e2e/AutoLinks.spec.mjs
packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical-playground/__tests__/e2e/List.spec.mjs
packages/lexical-playground/__tests__/regression/1083-backspace-with-element-at-front.spec.mjs
packages/lexical-playground/__tests__/regression/3136-insert-nodes-adjacent-to-inline.spec.mjs

This prevents lexical links from being vulnerable to reverse tabnabbing by default.

Add rel noopener by default

---

.flowconfig
packages/lexical-playground/src/ui/Modal.tsx
packages/lexical-playground/vite.config.js
packages/lexical-playground/vite.prod.config.js
packages/lexical-react/src/LexicalNodeEventPlugin.ts
tsconfig.json

This plugin makes it easy and simple to attach event listeners to specific types of Lexical node without needing to manually do the wiring.

Add LexicalNodeEventPlugin to @lexical/react

---

packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs

Handle links that are wrapped in parenthesis: 
```js
([title](url))
->
(<a href="url">title</a>) instead of (<a href="url)">title</a>
```

Fix md links regexp

---

packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUtils.ts

This fixes two bugs reported:
- We were incorrectly finding the rects of the parents of the body element.
- We were not taking into account the Shadow DOM.

Fix bug in scrollIntoViewIfNeeded

---

packages/lexical/src/LexicalReconciler.ts

We already apply this logic in other places in the reconciler, so we just needed to apply it to one more place.

Ensure we do not render br after non inline decorators

---

packages/lexical-table/src/index.ts

Exports SerializedTableNode, SerializedTableRowNode and SerializedTableCellNode from @lexical/table package

Exports SerializedNodes from @lexical/table

---

packages/lexical/src/LexicalSelection.ts

Turns out that the element merging logic appended to the end rather than at the start. Not sure how we didn't see this before! Also, we should ensure that we avoid selecting an empty text node after insertion.
Fixes https://github.com/facebook/lexical/issues/3311.

Fix insertNodes merging logic

---

packages/lexical-website/docs/demos/plugins/excalidraw.md
packages/lexical-website/docs/demos/plugins/images.md

**Problem**: the example works in the CodeSandbox itself but not when it is embedded. I am not sure what the problem is.

Add excalidraw plugin example

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/HorizontalRule.spec.mjs
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs
packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-react/src/LexicalHorizontalRuleNode.tsx

Fixes https://github.com/facebook/lexical/issues/3417.
This is an interesting problem. It seems having a `<div>` as a top level block in the contenteditable causes selection to break around it – even if it uses `display: contents`. Having the `<hr>` be the top level block works though. I hate content editable sometimes.

Fix browser selection with horizontal rule

---

packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUtils.ts

Without regressing https://github.com/facebook/lexical/issues/2199 and https://github.com/facebook/lexical/pull/2853, this PR aims to fix text replacement for both Grammarly but also MacOS/iOS text replacement too, which we seem to have regressed on.
Fixes https://github.com/facebook/lexical/issues/3428.

Fix text replacement via insertText

---

packages/lexical-playground/__tests__/e2e/Headings.spec.mjs
packages/lexical-rich-text/src/__tests__/unit/LexicalHeadingNode.test.ts
packages/lexical-rich-text/src/index.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalSelection.ts

On backspace at the start of heading, they shouldn't collapse into a paragraph, and on enter in the middle of a heading, they should stay as a heading.
Closes #1170 #1158
Before 
https://user-images.githubusercontent.com/7748470/204026666-11d75e18-8890-438b-b284-f01853005c62.mov
After
https://user-images.githubusercontent.com/7748470/204026688-55507bcc-3e83-4b5d-91c4-252789c2f894.mov

Fix a couple of bugs with Headings creation

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

Command listeners in the typeahead plugin have the highest possible priority which means users cannot override the commands. This caused the related issue tagged below. 
Closes #2978

Change command priority in typeahead

---

packages/lexical-playground/__tests__/e2e/HorizontalRule.spec.mjs

Fixes: https://github.com/facebook/lexical/issues/3155
When the cursor focus is set on a paragraph next to a decorator node (not inline) pressing the "Delete" ("Backspace") key removes the node.
Fixing deletion behavior makes bug described here a bit more noticeable: https://github.com/facebook/lexical/issues/3156

Fix deleting empty paragraphs

---

packages/lexical/flow/Lexical.js.flow
packages/lexical/src/nodes/LexicalLineBreakNode.ts
packages/lexical/src/nodes/LexicalParagraphNode.ts

The `exportJSON()` types for `ParagraphNode` and `LineBreakNode` did not match the `importJSON()` types for those nodes. This PR makes the `exportJSON()` return type consistent with the expected type for `importJSON()` - the same way as it is for all other nodes.
The Flow file was also updated with the types, but this caused an error as the type `type` in `SerializedLexicalNode` is a string, but the `SerializedParagraphNode` and `SerializedLineBreakNode` types use the literal strings `'paragraph'` and `'linebreak'` respectively and so `$FlowExpectedError` was added with a justification.

Fix exportJSON return types for ParagraphNode and LineBreakNode

---

packages/lexical-playground/src/plugins/HorizontalRulePlugin/index.ts
packages/lexical-utils/src/__tests__/unit/LexicalUtilsSplitNode.test.tsx
packages/lexical-utils/src/__tests__/unit/LexlcaiUtilsInsertNodeToNearestRoot.test.tsx
packages/lexical-utils/src/index.ts
packages/lexical/src/__tests__/utils/index.tsx
packages/shared/src/invariant.ts

- Update `$splitNode` to thrown if called on root
It's possible to keep `$splitNode` working with root. E.g., if we have root with 2 children, and trying to call `$splitNode(root, 1)`, it'll return `[firstRootChild, secondRootChild]` without modifying (splitting) the tree. But then it means those children might be elements or decorators, so it would require API call site to check return type. Plus, there's no guarantee that there will be left or/and right tree at all since root can be empty. Supporting all of these will make `$splitNode` return type too vague (`[null | ElementNode | DecoratorNode, null | ElementNode | DecoratorNode]`) and it seems easier to handle root separately instead 
- Add root selection case for `$insertNodeToNearestRoot`
- Some test utils fixes (import/export) to …

$splitNode & $insertNodeToNearestRoot for root selection

---

packages/lexical/src/LexicalSelection.ts

This bug fix was extracted from https://github.com/facebook/lexical/pull/3434. We were never defining the type as "text" meaning text nodes could be improperly represented.

Fix bug in selectPointOnNode

---

packages/lexical-react/src/LexicalComposerContext.ts
packages/lexical-react/src/LexicalNestedComposer.tsx

Confirmed you can't type in caption below when `isEditable`  is `true` on parent.
Closes #1546

Add isEditable listener to nested composer

---

packages/lexical-website/docs/demos/plugins/excalidraw.md
packages/lexical-website/docs/demos/plugins/horizontal-rule.md

Add horizontal rule plugin

---

packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-playground/src/ui/DropDown.tsx

If this is merged, this will add `type` attribute to `<button />` components in playground.
This will fix an issue where clicking on any given button unintentionally submits a form, if the Lexical editor is used within a `<form />`

patch(Playground): add `type="button"` to <button /> components

---

packages/lexical-react/src/LexicalComposer.tsx

Fix for Server Side Rendering, `document is undefined` error when invoking `LexicalComposer`

check CAN_USE_DOM before accessing document

---

packages/lexical/src/nodes/LexicalTextNode.ts

Changes done to ensure that superscript & subscript styling are properly imported from html string.

Fix superscript & subscript not being converted from html string

---

packages/lexical-playground/__tests__/e2e/Images.spec.mjs
packages/lexical-playground/src/nodes/ImageComponent.tsx
packages/lexical-rich-text/src/index.ts
packages/shared/src/caretFromPoint.ts

This PR polishes the current drag&drop experience
1. Shows caret while dragging and dropping
2. Simplifies the code
3. Fixes insert position for Firefox
Before (1)
https://user-images.githubusercontent.com/193447/199136886-b6c1dfda-48e6-481b-b053-1ce1aa7970ea.mov
After (1)
https://user-images.githubusercontent.com/193447/199136909-40755c8c-1858-44f0-ad06-2de31ddc516f.mov

Show caret while drag&drop

---

packages/lexical-playground/__tests__/e2e/Headings.spec.mjs
packages/lexical-rich-text/src/__tests__/unit/LexicalHeadingNode.test.ts
packages/lexical-rich-text/src/index.ts

Follow up to #3441 to allow collapsing a heading to a paragraph when the editor is empty. Simplifies some of the logic from the previous PR as well.
https://user-images.githubusercontent.com/7748470/204591618-52a788b5-6b68-40c4-a223-dfdae4bea029.mov

Change heading to paragraph when heading is empty

---

packages/lexical/src/LexicalEditor.ts

Nested editors should inherit headless flag from its parent. It fixes issues with headless conversion logic, where nested editors keep having `_pendingEditorState` as they are not reconciled properly due to missing headless flag

Inherit headless flag from parent editor

---

packages/lexical-markdown/src/MarkdownExport.ts

Markdown export completely ignores decorators if there's no explicit md transformer for it, this PR adds fallback to its text content (similar as we do for copy-pasting). It would still be possible to exclude decorators from output either by overridding text content (which would also affect copy-pasting) or by providing custom md export transformer

Markdown decorators export fallback to text content

---

packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalConstants.ts
packages/lexical/src/LexicalReconciler.ts
packages/lexical/src/nodes/LexicalElementNode.ts

This PR adds `start` and `end` as valid format alignment types.
Closes #3467
Ensured text alignment end gets applied to the paragraph block:

Add start and end as format types

---

packages/lexical-selection/src/lexical-node.ts
packages/lexical-utils/src/index.ts
packages/lexical/src/LexicalNode.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/nodes/LexicalElementNode.ts

`ElementNode.splice` is a very hot method that gets called often. Looking at some profile traces, it seems that we can improve the runtime by moving out `isPointRemoved` as a nested closure, so it doesn't get created each time the method is called. I also noticed in cloning that we weren't cloning the linked list properties, so I snuck that in this PR too.

Improve element splicing and node removal

---

libdefs/prismjs.js
packages/lexical-code/src/CodeHighlightNode.ts
packages/lexical-code/src/CodeHighlighter.ts
packages/lexical-code/src/CodeNode.ts
scripts/build.js

* Add support for `typescript` language in code nodes
* Add `ts` => `typescript` mapping
* Include Prism Typescript highlighting

Support TypeScript language in code nodes

---

packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical-utils/src/__tests__/unit/LexicalEventHelpers.test.tsx
packages/lexical/src/LexicalGC.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUpdates.ts
packages/shared/src/environment.ts

Moving selection on large DOM sets is not cheap in Chrome. It's actually one of the most expensive things you can do on Webkit/Chromium. In order to improve performance, you can separate DOM mutations, and in doing so make it easier for the recalculation of DOM layers to apply to selection.
The easiest way to approach tackling this problem is using a simple `requestAnimationFrame` however, this then moves much of the intended logic for dealing with problems within Lexical to being async. In reality, we don't always need this to be async and in most cases sync is fine. For when we do have async, Lexical can gradually pick-up, but this is mostly an edge-case.

Improve selection performance on large updates

---

packages/lexical-headless/README.md

Currently, it's not obvious that `@lexical/headless` needs to be installed. Other packages like rich-text don't need to be installed. This is a simple PR to make docs a little more clear.

Inform users that they need to install headless

---

packages/lexical-playground/src/nodes/PollComponent.tsx
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUtils.ts

Turns out we had a strange bug in `isSelectionCapturedInDecoratorInput`. Fixes https://github.com/facebook/lexical/issues/3488.

Fix decorator input selection

---

packages/lexical-react/src/LexicalNodeEventPlugin.ts
packages/lexical/src/LexicalUtils.ts

Fixes https://github.com/facebook/lexical/issues/3490. It seems that we didn't have a codepath for when the reconciler does a move – a destroy from one parent and create in another. This should be an update.

Fix mutation listener for when DOM moves occur

---

packages/lexical-website/docs/demos/plugins/markdown.md
packages/lexical-website/docs/demos/plugins/poll.md
packages/lexical-website/docs/demos/plugins/speech-to-text.md

Add poll and speech-to-text plugin examples

---

packages/lexical-playground/__tests__/e2e/Focus.spec.mjs

We need to skip tests that use tab for changing focus on Mac/Webkit because tab works differently that it does on Windows/Chrome/Firefox unless changed in the macOS system preferences.

Skip tab e2e test in webkit

---

packages/lexical-playground/src/plugins/AutoEmbedPlugin/index.tsx
packages/lexical-react/src/LexicalAutoEmbedPlugin.tsx

This PR adds support for async parseURL calls, which may be necessary for making sure something is embeddable. It also lets parse URL add arbitrary data to its match result which may be useful for caching async results.
Most of the changed lines here relate to adding async support on the playground.

Improve Auto Embed

---

packages/lexical-history/src/index.ts
packages/lexical-yjs/flow/LexicalYjs.js.flow
packages/lexical-yjs/src/CollabElementNode.ts
packages/lexical-yjs/src/SyncEditorStates.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalGC.ts
packages/lexical/src/LexicalReconciler.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts

⏸ [0.7] Remove IntentionallyMarkedAsDirtyElement from public API

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/HorizontalRule.spec.mjs
packages/lexical-playground/src/index.css
packages/lexical-playground/src/nodes/TableNode.tsx
packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts
packages/lexical-rich-text/src/index.ts
packages/lexical-selection/src/range-selection.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalMutations.ts
packages/lexical/src/LexicalReconciler.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts
packages/lexical/src/nodes/LexicalElementNode.ts

This PR adds emulated block cursors to Lexical. Taking inspiration from ProseMirror, we can opt to use a trick to get around these problems:
- Have a virtual emulated cursor which is just a non editable div with no content that shows a horizontal cursor. This would be applied by the reconciler between boundaries of block level decorator elements. 
This logic works by teaching the entire core the concept of a "block cursor element". This element gets inserted when selection can exist in a position where the browser can't render a native cursor accurately between block elements. We insert the block cursor to show a blinking horizontal line that can be themed too.
Fixes https://github.com/facebook/lexical/issues/3417. Partly addresses https://github.com/facebook/lexical/issues/3426.

⏸ [0.7] Add block emulated cursors

---

packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

There's an issue with editor.setEditorState with unset root element. We've discovered it with nested editors when nested LexicalComposer was conditionally hidden, but it's easy to reproduce with a regular one too by creating an instance and setting some editor state and skipping `setRootElement` call:
```
const editor = createEditor({ ... });
editor.setEditorState(initialState);
```
Although it seems fine, editor won't have its state reconciled due if it does not have root element set due to reconciler condition and will keep having `editor._pendingEditorState` equal to `initialState` and `editor._editorState` set to empty state. This could lead to unexpected results, e.g., if you try to serialize editor right after that (without setting root element), it will use previous editor state …

Fix dom-less reconciliation

---

packages/lexical-code/flow/LexicalCode.js.flow
packages/lexical-code/src/CodeNode.ts
packages/lexical-link/flow/LexicalLink.js.flow
packages/lexical-link/src/index.ts
packages/lexical-list/flow/LexicalList.js.flow
packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical-mark/src/MarkNode.ts
packages/lexical-overflow/src/index.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
packages/lexical-rich-text/src/index.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalNode.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/nodes/LexicalElementNode.ts
packages/lexical/src/nodes/LexicalParagraphNode.ts

This PR adds an optional `restoreSelection` argument to the `insertBefore`, `insertAfter`, `replace` APIs, avoiding doing O(n) selection restoration, which allows for far greater performance when selection is handled automatically at the end of a given operation.

Improve insertBefore, insertAfter, replace selection restoration logic

---

packages/lexical-code/flow/LexicalCode.js.flow
packages/lexical-code/src/CodeHighlighter.ts

~In the original implementation, CodeNode is removed when the backward deletion occurs at the beginning of the Node.~
~In some use cases, implementing a code editor, such behavior is not needed.~
~The "Preserve" setting is for making it controllable.~
The former PR #3243 enabled to use arbitrary Tokenizer other than Prism and 'javascript' is not always appropriate to the default so make it a Tokenizer setting.
This PR contains 2 changes but I'm happy to divide them if required.

Move default language setting to Tokenizer

---

packages/lexical-website/docs/concepts/node-replacement.md

Change the type of the `node` config param in the [Node Overrides](https://lexical.dev/docs/concepts/node-replacement) example from an object to array. This matches the actual node type as defined in [EditorConfig](https://lexical.dev/docs/api/classes/lexical.LexicalEditor#_nodes).

Docs: fix "node" type in "Node Overrides" example code

---

packages/lexical-offset/src/index.ts

I created a function called `createChildrenArray` that does the same thing, except doesn't need an active editor. We should be using that instead here.

Fix lexical-offset

---

packages/lexical-website/docusaurus.config.js
packages/lexical-website/i18n/en/docusaurus-plugin-content-docs/current.json
packages/lexical-website/i18n/en/docusaurus-theme-classic/navbar.json

Add demos section to the navbar

---

packages/lexical-react/src/LexicalLinkPlugin.ts

If we're trying to paste content in over a range of selection that contains an element, then avoid applying the link logic.

Fix paste for LexicalLinkPlugin

---

packages/lexical/src/LexicalEvents.ts

Closes #3538 
Validated that it fixes the issue on mobile, and doesn't cause regressions with #2901 on desktop.

Change mousedown event type to fix selection Chromium bug on Android

---

packages/lexical/src/LexicalNode.ts

This method used to safely return an empty list instead of throwing if the parent isn't found. This changes it back to that approach, so the API matches similar methods and the linked list change remains an implementation detail.

Don't throw if getPreviousSiblings can't find a parent

---

packages/lexical-playground/src/plugins/ClickableLinkPlugin/index.ts

Currently, the `ClickableLinkPlugin` does not detect clicking on links with the middle mouse button. This PR enables this. Clicking with the middle button will open links in new tab automatically.

[Playground] Support clicking on links with middle mouse button

---

packages/lexical-playground/src/nodes/ImageComponent.tsx

Resolves : #3562
Issue: When resizing an Image over a long distance in lexical playground, the draggable event of the image is getting triggered. This causes the image to be stuck in the resizing state.
https://user-images.githubusercontent.com/27125472/207942913-2fa4b848-9d2d-48d4-abe3-11d291958643.mp4
Fix: Added a condition to not set the draggable flag if the image is in resizing state. 
https://user-images.githubusercontent.com/27125472/207944605-6c161d87-f56f-44f0-90be-971e40e23187.mp4

Image gets stuck in resizing state fix (#3562)

---

packages/lexical/src/LexicalSelection.ts

Resolves: https://github.com/facebook/lexical/issues/3563
If the emulated cursor (added in https://github.com/facebook/lexical/pull/3434) is the last one in the editor state and you try to delete forward, then you will get an error `Uncaught Error: Minified Lexical error #66.`
Check if the current selection node has a parent.

fix: deleting forward on the last decorate node

---

packages/lexical/src/LexicalUtils.ts

We should be using our helper function when traversing the DOM tree to account for Shadow DOM.

Utilize getParentElement internally when traversing up the DOM tree

---

packages/lexical-link/src/index.ts

`$applyNodeReplacement` was missed in `LinkNode`. I'm assuming this is not intentional.

Allow LinkNode to be replaced by custom node, fix bug in #3367

---

packages/lexical/src/LexicalNode.ts
packages/lexical/src/__tests__/unit/LexicalNode.test.ts

When node is being replaced we should preserve its empty parent (in case it has `canBeEmpty: false`), as otherwise parent might be deleted and replacement fail. E.g., LinkNode has `canBeEmpty: false` and attempting to replace its text node child would fail. 
~~*Will add test, want to see CI results in case I've missed anything*~~

Preserve empty parent during replacement

---

packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical-list/src/LexicalListNode.ts
packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs

Adds support for HTML copy+paste of checklists into @lexical/list.
We still need to figure out how to support checklists from GDocs and Quip - or if we even want to. Is that something you should have to turn off or turn on?

Add HTML paste support for checklists

---

packages/lexical-markdown/src/MarkdownImport.ts

While `MarkdownImport` already escapes some special characters of the `tag` in `TextTransformer`s, it seems that plus sign is one that's missing and therefore you can't use `+` character in your custom `TextTransformer.tag`.
This PR attempts to fix the issue by adding the plus sign to the list of characters to escape. Fixes #3596.

Escape plus signs of the tag in MarkdownImport, fixes #3596

---

packages/lexical-website/docs/concepts/editor-state.md

says `lexical/PargraphNode` which is mispelling of "paragraph"
In any case seems this node is imported from `lexical` anyways in the playground example

Fix typo in documentation

---

packages/lexical-playground/src/utils/getSelectedNode.ts

Fixes `getSelectedNode` logic for forward selection.

Fix getSelectedNode logic for forward selection

---

packages/lexical-react/src/shared/useYjsCollaboration.tsx

I don't believe we ever meant to stop propagation in these command listeners. It blocks the default behavior happening on the plain/rich text plugins.

Allow focus/blur propagation in useYjsFocusTracking

---

.github/workflows/size-limit.yml
package-lock.json
package.json

Adds PR size report for lexical core, plain and rich text packages

Add size limit report

---

packages/lexical/src/nodes/LexicalTextNode.ts

This fixes a bug where if you had the HTML `<em><em>foo</em></em>` it would first be italic for the first `<em>` but then undo itself on the next `<em>`. Ouch.
Turns out we were never checking if it was already toggled!

Fix bug in convertTextFormatElement

---

packages/lexical/src/LexicalUtils.ts

Fixes https://github.com/facebook/lexical/issues/3620.

Add logic in isSelectionCapturedInDecoratorInput for contentEditables

---

.flowconfig
packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/vite.config.js
packages/lexical-playground/vite.prod.config.js
tsconfig.json

It's pretty annoying not having this on the playground and it degrades the editing experience for the majority of users. We factored this out to make tab behavior more configurable, but I think we want our public-facing default to include this behavior.

Add TabIndentationPlugin to playground.

---

packages/lexical-playground/src/plugins/CommentPlugin/index.css
packages/lexical-playground/src/plugins/FloatingTextFormatToolbarPlugin/index.css
packages/lexical-playground/src/plugins/FloatingTextFormatToolbarPlugin/index.tsx

This isn't really a solution, however the commenting UI isn't really approachable on mobile and needs a big rework before we should show it again.

Hide commenting controls on mobile screen sizes

---

packages/lexical/src/LexicalReconciler.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

Fixes https://github.com/facebook/lexical/issues/3602.
I think a bit of logic was missed from https://github.com/facebook/lexical/pull/1993. It's hard to fully know though. Would be good to have the eyes of @zurfyx on this.

Fix bug in reconciler sub-tree text content cache

---

packages/lexical-playground/src/plugins/TablePlugin.tsx

The reason tsc complains is that createContext is a generic function. Not sure if other similar calls need to be fixed. They look good.

Remove ts-ignore for createContext

---

packages/lexical-rich-text/src/index.ts

We should have been checking the decorator is inline or not.

Fix bug with ArrowDown/ArrowUp in RichTextPlugin

---

packages/lexical-playground/src/nodes/ImageNode.tsx

This PR adds width and height to image nodes when they are serialized or get converted back to Lexical nodes.

Add width and height to serialized image nodes

---

packages/lexical/src/LexicalNode.ts

This fixes a typo in LexicalNode for method getLatest.
editor.read doesn't exist, it's editorState.read

updated typo

---

packages/lexical/src/nodes/LexicalParagraphNode.ts
packages/lexical/src/nodes/__tests__/unit/LexicalParagraphNode.test.ts

The standard ParagraphNode does not expose the config property available to its updateDOM method. 
This can make for a nasty TypeScript problem when creating a custom ParagraphNode for the replacement API. The reason is that TypeScript will insist that there's no such config property. But there is. This PR will convince TS otherwise!
I encountered this problem while building a LinedCodeNode. This PR is 1/2 that will let it work without patches. 
-j

Add config to updateDOM in ParagraphNode 

---

packages/lexical-clipboard/src/clipboard.ts

If an uncollapsed selection ends or starts at the end of a line of specialized TextNodes, such as code tokens, we will get a 'blank' TextNode in `$appendNodesToJSON`. In other words, we'll get a TextNode with a text length of 0 (`''`). 
We do not want empty TextNodes, per @trueadm. He calls it an anti-pattern. 
So, this PR filters the occasional empty TextNode out of JSON, should it appear. 
I am not filtering it out of the sibling function, `$appendNodesToDOM`, however, as this can be handled via the exportDOM method instead. It is a more flexible method than exportJSON, so can be leveraged a little more surgically. 
Filtering could be added to the `$appendNodesToDOM` method, however, it might be a little more involved. You might have to add a line break (a br?). I was very ginger about …

Discard empty TextNode that can creep into appendJSON

---

packages/lexical-code/src/CodeNode.ts
packages/lexical-code/src/__tests__/unit/LexicalCodeNode.test.ts
packages/lexical-website/docs/concepts/serialization.md

This pull request is the first of at least two that are also needed to implement my LinedCodeNode without patches. 
I've extended my work on this node to allow it to override the official CodeNode via the override API so it can work with — I hope — Lexical's existing core library packages, notably @lexical/markdown.
_In this pull request:_ 
- Reduced priority level for several importDOM converters so an overriding CodeNode can take over
- Without this, the official CodeNode will win the race to control how importDOM elements are handled
- Exposed the editor config in the CodeNode's updateDOM method
- Added a more generic return type to the CodeNode's collapseAtStart method so CodeNode overrides can apply more nuanced logic
Coming soon-ish:
A pull request to make the new …

Tweak CodeNode to allow for overrides

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

fix an issue where the menu would cause the editor to scroll.
https://user-images.githubusercontent.com/5945154/211185806-6659b340-cf12-4e52-bb32-716862ba0c44.mp4
Only scrollIntoView will be done when there are not enough positions.
https://user-images.githubusercontent.com/5945154/210514951-e3e60bdf-497a-4b8e-bd68-455842d38f73.mp4

fix: type-ahead menu scroll problem

---

packages/lexical-playground/src/plugins/TableOfContentsPlugin/index.tsx
packages/lexical-react/src/LexicalTableOfContents__EXPERIMENTAL.tsx

Previously, the Table of Contents plugin didn't update correctly if a heading was updated. For example, if you enable ToC on the Lexical Playground and drag one heading after another (with the `DraggableBlockPlugin`), the ToC didn't update.
This PR adds handling of such events and includes minor code cleanup:
- Create a separate TS type for ToC that can be used throughout the plugin without needing to duplicate
- Introduces a utility function to transform a heading node to an array to be included in the ToC
- Updates the ToC only once per listener trigger - previously it was updated once for each mutation

Update listener in toc

---

packages/lexical-playground/src/nodes/TableNode.tsx

The Lexical Playground environment has two components, Table and Table (Experimental), the former draggable but not the latter.
I thought it would be desirable to have a component that is draggable like the Table component, so I fixed this as a bug.
<details>
<summary>Before/After</summary>
Before:
After:
</details>

fix(lexical-playground): NewTablePlugin is not draggable

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical/src/index.ts

The error logic and prevent default in $copyToClipboardEvent is causing an issue for input or textareas in within decorator nodes. The native selection is overridden, but when no Lexical selection is found, an error is thrown.
Closes #3717 
Closes #3698 
https://user-images.githubusercontent.com/7748470/212957866-84e70cce-3f58-4f2d-8e20-7f391a53cace.mov

Remove preventDefault from $copyToClipboardEvent

---

packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts

The equation markdown transformer is not working when your LaTeX is only one character long.  For instance, you can use this text:
```
What is the $x$-intercept of line $k$?
```
**Current Result**
**Expected**
You can take a look at the new RegEx [here](https://regex101.com/r/2GgxP1/1)

Fix equation transformer in Playground

---

packages/lexical-playground/src/themes/PlaygroundEditorTheme.css

There appears to be some issues with `list-style-position: inside;` on Safari, but we can probably just remove it as we're setting a margin-left any way. It's the same as putting the marker on the outside.
Closes #3752

Edit CSS to fix marker alignment issue in Safari

---

packages/lexical-react/src/LexicalNodeEventPlugin.ts

Today, while using the supremely useful `NodeEventPlugin`, I watched as the number of "click" event listeners on my code lines exponentially increased on every click. 
After some hunting and pecking, I discovered that the WeakMap that tracks elements in this plugin was being reset on every render. In other words, it reset to {} on each click. I therefore moved the WeakMap up a line, placing it outside the scope of the `registerMutationListener` function that makes use of it. 
Hark! The exponential increase ceased, the WeakMap stabilized, and a whole bunch of my code went from "bad" to "good."
@trueadm I see you worked heavily on this plugin, is this OK?
I have run `npm run test-unit` and observed Greenland. I am rolling the dice on the e2es, as I'm still not confident in them.
This …

Stabilize WeakMap in NodeEventPlugin

---

packages/lexical-playground/src/nodes/TableComponent.tsx
packages/lexical-playground/src/plugins/ComponentPickerPlugin/index.tsx

I have made the following two fixes:
1. https://github.com/facebook/lexical/commit/70eed93ed3231f24a12ae3dabf017a1035429772: When the ComponentPicker options are opened at a position overlapping the table, strings in the cell overlap and become difficult to read.
* Intention: Another idea I had was to increase the z-index of the ComponentPicker options, but it doesn't feel right that only the table cells are floating, so I modified it as shown in PR.
1. https://github.com/facebook/lexical/commit/d67b6024ec0bb73d46b0b2d9a89d25baad291fe4: Missing `Table (Experimental)` in ComponentPicker options (maybe not a bug).
<details>
<summary>Before/After</summary>
</details>

fix(lexical-playground): fix bugs related to ComponentPickerPlugin

---

packages/lexical-playground/src/plugins/TableOfContentsPlugin/index.tsx
packages/lexical-react/src/LexicalTableOfContents__EXPERIMENTAL.tsx

Fixes a bug where the TableOfContents would display the wrong order of headings if the user cuts/copy and pastes headers.
It seems `getPreviousSiblings` does not return the correct order, so iterate over the siblings instead.
To reproduce:
- Enter a few headings and enable ToC in playground.
- Copy or cut one heading
- Paste the heading above or below another heading
- ToC will have the wrong order
Also cleans up the code a little bit:
- Don't redefine TableOfContentsEntry type in the TableOfContent Plugin. Just export the already existing type and use this instead.
- Wrong keys in heading render map. Keys should be attached to the direct childs.

Fix copy paste wrong order in TableOfContents

---

packages/lexical/src/LexicalSelection.ts

When the target is the root node, we want to ensure that it hits [this bit of logic a little further down instead](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalSelection.ts#L1418-L1428).
Ensure that the nodes can be inserted correctly at the start: 
Closes #3606.

Add check that target is not the root node

---

packages/lexical/src/LexicalConstants.ts
packages/lexical/src/nodes/LexicalTextNode.ts
packages/lexical/src/nodes/__tests__/unit/LexicalTextNode.test.tsx

Add a new `highlight` variant to `TextFormatType`, to cover the use case of highlighted text.

Add highlight TextFormatType

---

packages/lexical-list/src/LexicalListNode.ts

ListNode's exportDOM ignored its theme classes unlike other core nodes. Using super.exportDOM preserves it since it uses createDOM under the hood

List node export dom with css classes

---

packages/lexical-playground/src/index.css
packages/lexical-table/src/LexicalTableSelection.ts

This doesn't break any core selection functionality. It just moves the logic for reseting the default browser selection styles into the custom stylesheet.  
This is because injecting it into the DOM via innerHTML causes a CSP rule issue as detailed in the below issue.
What is looks like without the resets applied: 
With the reset applied:
Closes #3477

Remove innerHTML injection from table selection

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical-code/src/CodeHighlightNode.ts
packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical/src/LexicalNode.ts

Whilst we await for schemas, this PR adds in the functionality to Lexical nodes to create a wrapping parent which is then used in the clipboard to normalize partial matches
Ensure partial list item nodes on the clipboard are correctly wrapped in a list node.
https://user-images.githubusercontent.com/7748470/215815295-d9032624-bbfa-4c82-a4b7-32788673f8b5.mov
Closes #3743

Add `createParentElementNode` method on LexicalNode to fix copy/paste issues with clipboard

---

packages/lexical-playground/src/nodes/ImageComponent.tsx
packages/lexical-react/src/useLexicalNodeSelection.ts

This pull request helps make editor instances more portable. 
If an editor instance is moved around the DOM via drag and drop, setState functions that are nested inside a Lexical listener can result in a noop warning. While Lexical lives on, the React components surrounding it will not. 
This pull request adds `isMounted` to one spot to prevent this from happening. 
A previous PR accidentally snuck the same code into ImageComponent, which also needed this fix.

Fix is selected noop

---

packages/lexical-playground/src/themes/PlaygroundEditorTheme.css

Re-add `list-style-position:inside` to fix regression caused by removing it as part of the fix for #3752.
I've added a Webkit bug report for the initial issue: https://bugs.webkit.org/show_bug.cgi?id=251681
Closes #3807

Add list-style-position:inside

---

packages/lexical/src/LexicalConstants.ts

Add IS_HIGHLIGHT format to combined formats to properly calculate format. 
This fixes an issue with `selection` not having the correct format.

Add IS_HIGHLIGHT format to combined formats to properly calculate format

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical/src/LexicalSelection.ts

Resoves: https://github.com/facebook/lexical/issues/3041
Pasting top level nodes (isInline set to `false`) within a paragraph places node in paragraph instead of breaking paragraph and placing node between.
https://user-images.githubusercontent.com/4542049/197205190-a048afb8-059c-4934-9cc8-5827b491bf60.mov
https://user-images.githubusercontent.com/4542049/197206901-6afc13cc-7a12-416b-9fc3-c0b9ae3140a3.mov
This is still partially broken for `headings` and `quotes` because when they get broken the second part becomes paragraph instead of whatever node it originally was but it is still an improvement on current behavior.

Fix pasting top level nodes inline

---

packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleContainerNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleContentNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/index.ts

Add the required methods for correct serialization/deserialization of the Container, Title and Content sections of the Collapsible Container Plugin.

Add exportDOM and importDOM for Collapsible Container Plugin

---

packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical/src/LexicalEvents.ts

Repro Steps:
1. Load Workplace on desktop
2. Navigate to system preferences >> keyboard >> text
3. Set "i" to replace with "I"
4. Navigate to playground
5. Type "i"+" " 
6. Check if "i" is replaced to "I " or not.
Bug observed: Observe that, the text "i" is replaced to "I" instead of "I " when typed "i"+" ".

Add anchor dirty node check for text length less than 2 chars

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

resolve #3716 and  #3815 
When the amount of a document is more than one page and when users use the typeahead menu in the middle of the document, the layout shifts
1. I changed the `if else statement` into an early return statement
2. I removed `parentNode`, because the previous `parentNode` was very similar to the target node. 
3. I made `typeaheadContainerNode`  for detecting the typeahead menu out of the viewport

Fix(#3716,#3815): Prevent layout shift while using typeahead menu

---

packages/lexical-playground/__tests__/e2e/CodeActionMenu.spec.mjs
packages/lexical-playground/src/plugins/CodeActionMenuPlugin/components/PrettierButton/index.tsx
tsconfig.json

- Dynamically loaded prettier and its parsers in code block on click of prettier icon.
- Reduced around **1170.37KB (1.17MB)** from main bundle and created respective chunks which will be loaded only on demand
Ran `yarn build-playground-prod`
|Before|After|
|---|----|
|![before](https://user-images.githubusercontent.com/42532987/209449958-c784bdd2-9428-4a4c-971e-3afc73dc95be.png)|![after](https://user-images.githubusercontent.com/42532987/209449953-cb6e0932-5e80-430c-a0e5-24aa2a1e426e.png)|
<details>
<summary>Before</summary>
[before.webm](https://user-images.githubusercontent.com/42532987/209450098-df7fbb71-3e6b-4086-b867-84413f20aa83.webm)
Prettier and all its parsers are loaded initially
</details>
<details>
<summary>After</summary> …

perf(playground): load prettier and its parsers on demand in code block

---

packages/lexical-playground/src/plugins/TablePlugin.tsx
packages/lexical-table/src/LexicalTableUtils.ts
packages/lexical-table/src/index.ts

The idea behind this changement is to allow the user of the API to choice if the header will be only row, column or Both.
For example: 
```tsx
function onClick() {
activeEditor.dispatchCommand(INSERT_TABLE_COMMAND, {
columns,
includeHeaders: true,
rows,
});
}
```
This will make the header as column and row like before.
but, if you add columns and row as an object for includeHeaders like that:
```tsx
function onClick() {
activeEditor.dispatchCommand(INSERT_TABLE_COMMAND, {
columns,
includeHeaders: {columns: false, rows: true},
rows,
});
}
```
Or like that if you make columns as true and rows as false 
Do this functionnality looks good for you ?

Add more configuration for heading in INSERT_TABLE_COMMAND

---

packages/lexical-utils/src/index.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts

https://github.com/facebook/lexical/pull/3238 introduced an import to a third party in core, which obviously doesn't work. In order to make this work without reverting that PR, I had to bring `$splitNode` into core.
Fixes https://github.com/facebook/lexical/issues/3860.

Fix bad import into core

---

packages/lexical-react/src/shared/useYjsCollaboration.tsx
packages/lexical-yjs/src/SyncEditorStates.ts

This PR makes the updates tags for updates coming from yjs change based on origin, so if the changes came from UndoManger the tag is set to `collaboration-history` and if the updates came from other places like websocket the tag is set to `collaboration`, 
this is to be able to know which updates came from the user's interaction and which updates came from other users through yjs

[0.8] feat: set the update tag from yjs based on the origin

---

packages/lexical-react/src/LexicalNestedComposer.tsx
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

This PR extends the node overrides: when "withKlass" is specified, node transforms are registered with both nodes by registerNodeTransform. 
Due to the implementation of Node Transforms, it is applied only to the exact same type of registered node.
According to [here](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalEditor.ts#L679), it seems to determine nodes to apply the transform by the result of static LexicalNode#getType().
[Node overrides](https://lexical.dev/docs/concepts/node-replacement) is very powerful but due to the above implementation, Node Transforms added by some plugins do not work with Node overrides.

[0.8] Apply node transform not only to the original node but also to the overriding node

---

packages/lexical-playground/__tests__/e2e/ElementFormat.spec.mjs
packages/lexical-playground/__tests__/e2e/Indentation.spec.mjs
packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalReconciler.ts

Add ability to customise the indentation of tabs by specifying a CSS variable. This can any CSS unit that is accepted by `calc`.
Closes #3473

[0.8] Allow users to customise the indentation of tabs

---

packages/lexical-react/src/LexicalBlockWithAlignableContents.tsx

The format property allows undefined, but cannot be omitted because it is not optional.
https://github.com/facebook/lexical/blob/98bba10e112c750779b174278556a14608a39df4/packages/lexical-react/src/LexicalBlockWithAlignableContents.tsx#L35
```tsx
class LinkCardNode extends DecoratorNode<React.ReactElement> {
public decorate(editor: LexicalEditor, config: EditorConfig): React.ReactElement {
return (
<BlockWithAlignableContents
className={className}
format={undefined} // undefined must be specified.
nodeKey={this.getKey()}
>
text
</BlockWithAlignableContents>
);
}
}
```
Change the format property to optional so that it can be omitted.
```ts
type Props = Readonly<{
format?: ElementFormatType | null;
}>;
```
```tsx
class LinkCardNode extends DecoratorNode<React.ReactElement> {
public …
```

[0.8] Allow the format property to be omitted

---

packages/lexical-react/flow/LexicalContentEditable.js.flow
packages/lexical-react/src/LexicalContentEditable.tsx

The `@ts-ignore` amongst the ContentEditable props was masking for incorrect type issues. 
Tested Flow types internally to validate that they work correctly.
Closes #3550 
Closes #3658

[0.8] Update ContentEditable types

---

packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical-list/src/formatList.ts
packages/lexical-list/src/index.ts
packages/lexical-list/src/utils.ts
packages/lexical-react/src/shared/useList.ts

In $handleIndent and $handleOutdent the Github diff gets messy with line mapping. The only thing I did there was remove the for loop, and that's why the indentation of the whole function changed.
In fact, literally all I did in this PR was remove 100 unnecessary lines of code. Everything is still working fine.

[0.8] List indentation simplified

---

CHANGELOG.md

Since the latest release is v0.8.0 I would assume this was a typo in the changelog.

Fix v0.8.9 typo in changelog, should be v0.8.0

---

packages/lexical-playground/src/ui/ColorPicker.tsx

Close color pickers on select

---

packages/lexical/src/LexicalSelection.ts

Fixes https://github.com/facebook/lexical/issues/3891 and https://github.com/facebook/lexical/issues/3892.

Further tweaks to format/style selection

---

packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx

This PR fixes an [issue](https://github.com/facebook/lexical/issues/3897) found within the floating link editor plugin used on the playground.

Playground: fix issue with floating link editor plugin not closing

---

packages/lexical-playground/__tests__/e2e/Extensions.spec.mjs
packages/lexical-playground/__tests__/e2e/Images.spec.mjs

Tracking long-term fix here: https://github.com/facebook/lexical/issues/3915
These need to be disabled for now as they're causing us to waste a ton of time with investigating low-signal CI failures.

Add fixme annotation to flaky collab tests

---

packages/lexical-headless/src/index.ts
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/index.ts

Align types for createEditor APIs

---

packages/lexical-table/src/LexicalTableCellNode.ts
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/LexicalTableRowNode.ts

Actually, if i use the node override like [that](https://lexical.dev/docs/concepts/node-replacement). 
i can't pass something else than "tablecell" in getType function. (Or i have to change with a as or to use a // @ts-ignore)
```tsx
export class CustomTableCellNode extends TableCellNode {
public static getType(): 'tablecell' {
return 'tablecell';
}
public static clone(node: TableCellNode): TableCellNode {
return new CustomTableCellNode(
node.__headerState,
node.__colSpan,
node.__width,
node.__key,
);
}
public createDOM(config: EditorConfig): HTMLElement {
const dom = super.createDOM(config);
return dom;
}
}
```
```tsx
public static getType(): 'tablecell' {
console.log('getType called');
// @ts-ignore
return 'custom-tablecell';
}
```
With this, now we should be able to use a string while …

fix: change tablecell return type for TableCellNode

---

packages/lexical-history/src/index.ts
packages/lexical-playground/__tests__/e2e/History.spec.mjs

This appears to fix the undo functionality in situations where the editorState is initialized with a Selection. Previously, the first entry would be discarded, rather than merged (since prevSelection was non-null) leading historyState.current to still be empty, meaning the first actual change to the content would not be placed onto the undo stack.
Fixes #3912

Remove condition for history merge on null prev selection

---

packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical-selection/src/lexical-node.ts

Fix toggling styles on collapsed selections with $patchStyleText

---

packages/lexical-playground/src/index.css

**Before:**
Unable to begin typing text unless clicking in this narrow area. Clicking toward the bottom will not activate the text area.
<hr/>
**After:**
You can now activate the text area with a click in a larger area that fills the available space.
<hr/>
**Potential Concerns:**
None at the moment. Seems to be working well in my limited testing.

Expand the actionable empty playground editor text area via flex

---

packages/lexical-markdown/src/MarkdownImport.ts
packages/lexical-plain-text/src/index.ts
packages/lexical-rich-text/src/index.ts
packages/lexical/src/LexicalConstants.ts
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalUtils.ts
packages/shared/src/environment.ts

Native webkit doesn't add Safari version in the useragent string. This PR checks for the existence of webkit engine in that string. This fixes a varity of issues including autocompleting Chinese characters.
Before:
https://user-images.githubusercontent.com/59730495/217489536-0593dc29-7f9f-47e3-8c9a-6d3b02579005.mov
After:
https://user-images.githubusercontent.com/59730495/217489590-cb2ac870-1e33-41dd-988f-a54328a27118.mov

Added Chinese character support for native webkit

---

packages/lexical-website/docs/faq.md

As per https://lexical.dev/docs/concepts/commands#editorregistercommand, the method is `registerCommand`

fix: change from `addCommandListener` to `registerCommand`

---

package-lock.json
packages/lexical-playground/src/App.tsx
packages/lexical-playground/src/images/icons/file-earmark-text.svg
packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/DocsPlugin/index.tsx

This PR closes the issue #3918 
Added <b>Docs Button</b> in Lexical Playground that links to the official documentation of lexical.
This feature makes handy to have the docs a click away when you're exploring the playground as mentioned in issue #3918

added docsfeature-button in lexical playground issue#3918

---

packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical-selection/src/lexical-node.ts
packages/lexical-selection/src/range-selection.ts

Fixes #3944.
This patch also fixes a bug in $getSelectionStyleValueForProperty that
was papered over by this bug--namely that when it is called on
a collapsed selection we should report the style on the selection
regardless of whether it agrees with the current node style.

Clone objects from the CSS cache before mutating them

---

packages/lexical-react/src/LexicalAutoLinkPlugin.ts

close #3825 
https://user-images.githubusercontent.com/40270352/216878308-06bc05e5-422c-4b3e-aed9-8602ce005ee9.mov

Fix a bug that caused the Node to be regenerated when editing the end of an AutoLinkNode

---

packages/lexical-history/src/__tests__/unit/LexicalHistory.test.tsx
packages/lexical-history/src/index.ts

This fixes an issue in the lexical history plugin that does not notify that the redo action is unavailable when the user performs an update.
There is no bug reported that I can find, so here is the steps to reproduce the issue:
```
Steps to reproduce:
- Go to https://playground.lexical.dev/
- Make a change
- Undo
- Make another change
Expected: the redo button is disabled
Actual: the redo button is enabled
```
I've added a unit test to test a full sequence (probably more of that is needed for this PR but there were not enough tests for this plugin I believe).
Let me know if you need to open an issue and I will do it.

Trigger `CAN_REDO_COMMAND` as false when `redoStack` goes down to 0

---

packages/lexical-playground/__tests__/e2e/Events.spec.mjs
packages/lexical/src/LexicalEvents.ts

The "Add period with double-space after emoji" Mac feature misbehaves when triggered immediately after a node on Chrome. My hunch is that this is a Chrome-specific bug, as Safari does it correcty.
However, what brought me to this fix is the fact that this can lead to a more generic issue. We allow anyting to happen on the DOM on beforeinput. In this case, Mac is saying insert `. ` which covers the immediately previous 2 position but the targetRange could be completely arbitrary, overriding some of our other DOM elements.
Given that this is rare, it's worth switching to controlled mode when this happens and it will have no impact whatsoever on the performance.
Alternatively, we could handle it in the MutationObserver, trying to intercept what has been modified and what-not but given that …

Beforeinput prevent default on mismatching targetRanges

---

packages/lexical-react/src/LexicalBlockWithAlignableContents.tsx

When a block is deleted, one previous node is selected.
This will improve the writing experience.
https://user-images.githubusercontent.com/40270352/221128816-4a476298-d177-46c2-a122-dc917d90d34b.mov

Make one previous node be selected when deleting a block

---

packages/lexical-playground/src/plugins/MaxLengthPlugin/index.tsx
packages/lexical-selection/src/lexical-node.ts
packages/lexical/src/nodes/LexicalElementNode.ts
packages/lexical/src/nodes/__tests__/unit/LexicalElementNode.test.tsx

Fixes #3772 
In `ElementNode` I've duplicated the logic of `getTextContent` for `getTextContentSize()` to account for children where `getTextContentSize() !== getTextContent().length`.
I'm not sure that the changes are desirable.
In particular, `RootNode` overrides `getTextContent` to track the internal property `__cachedText`. 
`__cachedText` is changed manually when the editor is updated. I lack familiarity with the codebase but my guess is that it's a performance optimization.
In the current state of the PR, the same optimization is not applied to `getTextContentSize` in `RootNode`. 
What are the implications of this? I see that `getTextContentSize` is used internally in `LexicalSelection.ts`.

Account for children text content size in `ElementNode`'s `getTextContentSize`

---

packages/lexical/src/LexicalSelection.ts

This fixes a problem in RangeSelection's getNodes method, which incorrectly retrieves the nodes when the anchor is after the focus.

Fix getNodes of RangeSelection

---

packages/lexical-website/docs/concepts/listeners.md

Updating the documentation to state that the root listener function is executed directly upon registration (see [implementation](https://github.com/facebook/lexical/blob/924b729deaab492736badd72089ef9831f00568e/packages/lexical/src/LexicalEditor.ts#L610)), as this  is unexpected behaviour for event listeners.

Doc: initial execution of listener function

---

packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleContainerNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/index.ts

Fixes: #3906 
Before:
After:
Need assistance, to understand what's wrong with the definition of the useEffect that triggers this constant re-render until the first click. Secondly, is listening on window the right approach here or should I be using a rootListener? Thanks.

Listen to Collapsible Section toggle event

---

packages/lexical/src/LexicalEditorState.ts
packages/lexical/src/nodes/LexicalElementNode.ts
packages/lexical/src/nodes/LexicalRootNode.ts

More typesafe alternative to solution proposed in #3989

Improve serialization types for element node children

---

packages/lexical-playground/src/index.css

It looks to me like these elements are covering the grabber or disallowing you to resize again after some initial resizing. It's odd how the resize tends to work initially, and then breaks usually after the introduction or exit of the scrollbar. 
Moving the actions to margin creates a small gap, and applying any sort of z-index seems to raise it to the top such that the flex editor underneath isn't interfering. Another alternative is to not use flex and do something like height 98% to leave a small gap... but then we can't utilize the full real estate.
A z-index above 0 can lead to odd behavior between the action buttons and text in the editor. Hopefully this approach plays nice with other nodes / plugins.
**Current Behavior (without fixes):** …

Adjust playground CSS to fix vertical resize being disabled in select scenarios

---

packages/lexical-react/src/LexicalNestedComposer.tsx

We update editable state of nested composer on parent editor `editable` change [here](https://github.com/facebook/lexical/blob/main/packages/lexical-react/src/LexicalNestedComposer.tsx#L106-L111). These values should also be consistent on initialization.
Closes #3995

Nested composers should initialize with parent editor editable state

---

packages/lexical-playground/src/collaboration.ts
packages/lexical-playground/src/commenting/index.ts
packages/lexical-playground/src/plugins/CommentPlugin/index.tsx
packages/lexical-react/src/LexicalCollaborationPlugin.ts
packages/lexical-react/src/shared/useYjsCollaboration.tsx
packages/lexical-yjs/src/Bindings.ts
packages/lexical-yjs/src/SyncCursors.ts
packages/lexical-yjs/src/SyncEditorStates.ts
packages/lexical-yjs/src/index.ts

We always use `WebsocketProvider` as an example, but are not tied to this specific implementation and it also creates confusion for users as they assume collab provider works only with WS (#3085)

Cleanup excessive use of WebsocketProvider for types

---

packages/lexical-selection/src/lexical-node.ts

This condition will be more appropriate for the case where we have a single node selected. 
It fixes bug described here: https://github.com/facebook/lexical/issues/3791

Fix selection on color change

---

packages/lexical-selection/src/lexical-node.ts

Fixes #3650
I have added an extra condition in trimTextContentFromAnchor to only remove parent node if it is not the `RootNode`

Check if parent node is root in order to remove it in trimTextContentFromAnchor

---

packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical/src/LexicalSelection.ts

This branch was never handled by `insertNodes` and these Elements were treated like non-inline. Hence, being inserted after the `target`.
Closes #4017

Fix insertNode insertion for inline Elements inside empty Elements

---

packages/lexical/src/LexicalSelection.ts

The Chrome selection performance optimization in #3478 will never play well with non-controlled beforeinput events that do not understand Lexical and it's nearly impossible to properly handle with controlled.
**Why?**
Beforeinput consists of two mechanisms: the data itself and the range. Range is computed by the browser based on the type of the event (i.e. text input or Mac character replacement) and the current DOM selection.
When we defer we selection, we are lying to the browser sharing the wrong insertion coordinates.
For non-controlled that's impossible to fix because the point of non-controlled operation is that we don't interfere, for controlled it's nearly impossible because we can't predict with accuracy what the browser would've done wih a correct selection. We know that for …

Fix Chrome beforeinput race condition on large docs

---

packages/lexical-playground/src/index.css
packages/lexical-react/src/LexicalTreeView.tsx
packages/lexical/src/index.ts

Add logs for commands in dispatch order to the `TreeView` plugin.

Add command logging into tree view

---

packages/lexical-playground/src/appSettings.ts
packages/lexical-playground/src/images/icons/success-alt.svg
packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.css
packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx

**Summary of Changes:**
- Toggling editMode results in less jarring transition by attempting to reconcile height differences between elements.
- Reduced link-input width to allow for new buttons controlling submission and cancellation (in addition to keyboard commands).
- Escape key now exits without saving the link changes, Enter continues to submit.
- Disabled the ability to open the link when in the editor. Prior to this you could accidentally open the link when trying to move your cursor on the text by clicking. You can still click the link from the link-editor itself to test it. The link will still become clickable if you try to export it elsewhere because this only applies to things nested under ContentEditable__root.
- link-editor is flex.
- Split the state of linkUrl to not …

Improved link editor UX

---

packages/lexical-playground/src/index.css

Quick fix for an issue I noticed after the link editor ui tweaks.
**Before:**
**After:**

Styling tweaks to better accommodate long urls

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/nodes/EquationComponent.tsx
packages/lexical-playground/src/nodes/EquationNode.tsx
packages/lexical-playground/src/ui/EquationEditor.tsx
packages/lexical-playground/src/ui/KatexEquationAlterer.tsx
packages/lexical-playground/src/ui/KatexRenderer.tsx
packages/lexical/src/LexicalEvents.ts

This PR fixes a Android bug. 
Hitting backspace at the end of an `EquationNode` causes selection to be lost. After much experimentation, I found that the fix involves adding `user-select: none;` to the decorator node, like with the inline `ImageNodes`, and to change the wrapping spaces around the equation node into `img` tags instead. 
I made some simplifications to the equation node logic as well.
Closes #3426
Closes #1965

Fix EquationNode issues on Android 

---

packages/lexical/src/LexicalUpdates.ts

Introduced in #3434 as part of the block cursor implementation. This PR is debatable as I'm not sure how this conflicts with the correct behavior of block emulated nodes. My understanding that this logic is the responsible for hiding the block cursor when moving away from the editor but this doesn't work in the current version either so the whole thing needs revisiting.
As for the problem, it comes to down to block emulated nodes plus the frown upon _listener + update_ pattern. The fact that block emulated nodes bypass the typical dirty behavior means that they trigger updates regardless and the _listener + update_ pattern will continue feeding new updates. Hence, causing a loop.
It's worth noting that while frown upon, the _listener + update_ pattern is still valid and supported.
Closes …

Fix inf loop block cursor

---

packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical-list/src/__tests__/unit/LexicalListItemNode.test.ts
packages/lexical-list/src/__tests__/utils.ts
packages/lexical-list/src/formatList.ts

Properly handles siblings that contain nested lists.
https://user-images.githubusercontent.com/3211874/223054925-c7a752bd-275e-4864-b29b-0be509729d33.mov
https://user-images.githubusercontent.com/3211874/223054952-5bb5f620-489a-46bf-8959-2e996c780fd8.mov

After removing a ListItemNode, merge its siblings.

---

.vscode/settings.json
packages/lexical-playground/__tests__/e2e/CopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/keyboardShortcuts/index.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-playground/src/plugins/TablePlugin.tsx
packages/lexical-table/src/LexicalTableCellNode.ts
packages/lexical/src/LexicalNode.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/nodes/LexicalGridCellNode.ts
scripts/error-codes/codes.json

This PR adds support for cell merging on the stable tables implementation. We store this with a simple `__colSpan` and `__rowSpan` property on the GridCellNode.
There are many follow ups from this PR, including the fact that only basic cases work for now:
- Doesn't copy merged content onto the merged cell
- Rewrite `getShape()` - indexes fail when merged cells are present
- Fix paste (it's already crashing in the current version for some reason)
- Kill GridSelection - performance and budget issues (adds cost the Lexical Core plain text users that don't use tables)
Cell merging
https://user-images.githubusercontent.com/193447/223561223-16d84087-a07b-4fd3-afa6-f9ba2029e7df.mov
_(yes, the menu visibility needs a fix but we're considering dropping it for a better a11y alternative)_
Selection …

Table - cell merging

---

packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx

**Issues this caused:**
- Could not highlight text in link editor with mouse
- Sometimes needed to click twice to activate link editor buttons
- If you were editing a link over / in a table it would cause a multitude of odd behavior (such as highlighting the table or the link editor bouncing around)
Pre-Fix
https://user-images.githubusercontent.com/29527680/223772108-83d04b1a-05b5-4c3e-9086-63b7d83b431e.mov
After-Fix
https://user-images.githubusercontent.com/29527680/223772135-de1b0a53-8ce3-4c53-bd10-d766a7322dee.mov
Reference: #4013

Removed additional FloatingLinkEditorPlugin mouse listeners

---

.github/workflows/nightly-release.yml
.github/workflows/test.yml

In our forked repositories, the execution of actions looks like should be disabled, especially the "Nightly Release Branch - main" task, as it is scheduled to run regularly and is certain to fail, resulting in a large number of failure notifications via email.

chore: prevent action from running on forks

---

.github/workflows/nightly-release.yml
.github/workflows/test.yml

Realized we should revert this before doing the 0.9.0 release. Reverts facebook/lexical#4068

Revert "chore: prevent action from running on forks"

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs

Fix table RangeSelection test

---

packages/lexical-playground/src/index.css

This bug was absurd. For whatever reason, the current setup works fine in Chromium and Firefox but is unresponsive in Safari. Using a `z-index: -1` half solves the solution but causes the resize handle to disappear and the blinking cursor to disappear.
`cursor: text` seems to interfere with the resize cursor icon regardless of the stack ordering. Eliminating `cursor: text` allows the icon to seamlessly switch and the cursor behavior throughout other areas of the app seem to be interpreted by the browser just fine.
Adding the second `resize: vertical` somehow tells Safari to bring back the blinking cursor and the resize grab handle. It's utterly bizarre... I've ran this by several experienced people and we can't make sense of it other than Safari being Safari. :D 
- This fix seems to not …

Fix unresponsive resize handle in Safari

---

packages/lexical-playground/src/plugins/TablePlugin.tsx

• Resolved bug allowing empty submission
• Ability to limit the amount of rows and columns
• Simplified labeling
• Disabled submit button when criteria is outside acceptable range 
• Added placeholders
**Before:**
https://user-images.githubusercontent.com/29527680/224183063-a4cfc040-8b97-43bc-9892-48647c81d57d.mov
**After:**
https://user-images.githubusercontent.com/29527680/224183202-e54a2f18-ba5e-4478-b6e3-28b7a90cab3a.mov

Updated InsertTableDialog UX

---

packages/lexical-react/src/LexicalOnChangePlugin.ts

We are using LexicalOnChangePlugin to save the state in DB.
We also have a plugin for reactive updates:
```js
type Props = {
serializedEditorState: SerializedEditorState | undefined;
debounceTime?: number;
};
export const REACTIVE_UPDATE_TAG = 'reactive-update';
/**
* Plugin to update the editor when the incoming serializedEditorState changes
* (in cases when several users are editing at the same time)
*/
export const ReactiveUpdatePlugin = ({ serializedEditorState, debounceTime = 0 }: Props) => {
const [editor] = useLexicalComposerContext();
const checkDiff = useMemo(
() =>
debounce((current: SerializedEditorState, incoming: SerializedEditorState, update: () => void) => {
if (JSON.stringify(current) === JSON.stringify(incoming)) {
return;
}
update();
}, debounceTime),
[debounceTime]
); …
```

Pass tags to onChange for LexicalOnChangePlugin

---

packages/lexical-website/docs/concepts/transforms.md

no issue
- `editor.addUpdateListener` was renamed to `editor.registerUpdateListener` in 0.1.17

Fixed reference to old `addUpdateListener` method in transforms doc

---

packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs
packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/FloatingTextFormatToolbarPlugin/index.tsx
packages/lexical-playground/src/plugins/TablePlugin.tsx
packages/lexical/src/index.ts

For example,
when the number of lines in the editor is more than 2,
gently double-click the end of the line, a toolbar will appear, and this toolbar will not process any text content.
In this case, it is obviously unnecessary to display the toolbar.
https://user-images.githubusercontent.com/48719861/224102364-2faa88a9-0fb7-4fed-9666-cc6240717a49.mov

Fix toolbars that shouldn't appear in certain cases

---

packages/lexical-utils/src/index.ts

With Acy's help I've tried to follow his example and add inline api documentation, though I might have gone a bit overboard. Please let me know if there's anything I can do to improve the PR.

Improve Documentation #2845 - lexical/utils

---

packages/lexical/src/LexicalEditor.ts

Issue:
`editor.focus()` triggers onChange event.
Example: https://codesandbox.io/s/lexical-focus-onchange-vot70x?file=/src/Editor.js
following 
- #4091
we could handle focus update in onChange
```js
function onChange(editorState: EditorState, editor: LexicalEditor, tags: Set<string>) {
if (tags.has('focus')) {
return;
}
// do the DB update.
}
...
<OnChangePlugin onChange={onChange} />
```

Add focus tag to editor.focus

---

packages/lexical-react/src/LexicalHorizontalRuleNode.tsx

Use broader return types inside `HorizontalRuleNode` to make extending the node easier. Currently, subclasses cannot override these methods with anything other than what's specified by `HorizontalRuleNode`.

Use broader return types in `HorizontalRuleNode`

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-table/src/LexicalTableUtils.ts
packages/lexical-table/src/index.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/index.ts

Rewriting insert row so that it supports merged cells
https://user-images.githubusercontent.com/193447/223866807-9a5fc9a2-493e-47d2-8319-17727e1a974a.mov
~~(disregard the fact that the header is not kept, headers are not logically compatible with merged cells, we'll kill them and replace them for background colors)~~
Update: will iterate on this on another PR. They can't really work with merged cells themselves but we can still forbid merged cells on the headers and work on them as usual

Table insert row w/ span support

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/keyboardShortcuts/index.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-table/src/LexicalTableUtils.ts
packages/lexical-table/src/index.ts

Given our rectangular selection that can automatically span beyond the initial intended selection, the best UX friendly algo to remove rows seems to be Apple Pages: we remove all rows that are contained within the selection and if there are conflicting merged cells beyond the selection we trim those cells. 
_Surprisingly, Quip, which does rectangular selection decided to just simply remove the row itself (trimming the selected node instead) (which imo can get confusing when it's a merged cell). This makes more sense on a GDoc approach as they don't guarantee rectangular selection._
https://user-images.githubusercontent.com/193447/224103458-8519b500-e4ad-4dd9-954f-078c3e1d844a.mov
https://user-images.githubusercontent.com/193447/224103655-e428d414-76a3-42ce-87ec-cae0901ee451.mov

Remove rows w/ span support

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/ui/ContentEditable.css

Changed the position to inherit from absolute to fix this issue.
Fixes #4095

Overflow of logos of action items in Lexical Playground

---

packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/__tests__/utils/index.tsx

Turns out the append to ShadowRoot/RootNode condition was not correct. The reason why it's a rare crash is because usually we either don't insert multiple nodes at once or they fall under the replace/merge category (condition 1). This is not the case when you append a `ShadowRoot` followed by another (ElementNode).
Tables are ShadowRoot, and when pasting a table followed by a paragraph it falls under that condition.
Fixes #4114

Fix ShadowRoot + X insertNode

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs

The viewport problem seems to be flaky; but adding the same patch to the remaining tests that use the contextual menu should do the trick for now.
Eventually, we have to fix or delete the contextual menu.

Fix tables Collab E2E

---

packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical-list/src/LexicalListNode.ts
packages/lexical-list/src/formatList.ts
packages/lexical-list/src/utils.ts

This PR adds documentation to the lexical/list module @ files: formatList.ts, LexicalListItemNode.ts, LexicalListNode.ts, and utils.ts.

Improve Documentation #2845 - lexical/list

---

packages/lexical/src/LexicalUpdates.ts

See this thread: 
https://discord.com/channels/953974421008293909/1075554413587996782/threads/1082425526737711115
This should allow a safer path forward cases like this.

Catch failures in parseEditorState

---

packages/lexical-table/src/LexicalTableCellNode.ts

Just adding copy-paste support
https://user-images.githubusercontent.com/193447/224838565-abc8f1f1-ac4f-4b56-b2cb-ee56813fa6db.mov

Paste merged celled table

---

packages/lexical-list/src/LexicalListItemNode.ts

This one is a bit interesting. We had a couple of issues here.
First, we shouldn't have been using ListItemNode.setIndent in the deserialization logic for this node, as it runs a bunch of node manipulation logic that shouldn't be necessary in that code path.
Second, if you call ListItemNode.setIndent directly and you're not using a compile-time type-checker, then you can cause an infinite loop here. It's a bit of a footgun lying around.
On the other hand, you could probably cause all sorts of weird issues by passing invalid data types into node setters across the library. I'm addressing this because it seems like particularly gnarly one, but taking this to it's logic conclusion means we'd do this everywhere, which I'm not sure is practically necessary.
Fixes #4119

Validate against infinite loop in ListItemNode.setIndent

---

packages/lexical-playground/src/ui/ColorPicker.tsx

This PR technically fixes #4127 the color picker closing immediately on color selection, including typing in the TextInput field, but there are a couple more issues here that could use fixing, I'm just not sure how to go about all of them.
1. It'd be nice if you could make the ::selection background clear so that you can see the color as it changes, but only while the color picker is open. I suppose I could do that with a useEffect hook and check if the picker isOpen or not, but I'm not exactly sure how to change the raw CSS for that. 
2. If you type in the hex code and accidentally type again, either hitting enter or something, it will replace the current selection with the key stroke. I'm not sure what the best way is to prevent that, but my first thought is don't allow the TextInput to …

Color picker - fixes #4127

---

packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.css
packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx
packages/lexical-playground/src/utils/setFloatingElemPositionForLinkEditor.ts

https://user-images.githubusercontent.com/70709113/226237755-c9176cc2-8527-4a09-878d-5620e8d6c11f.mp4
https://user-images.githubusercontent.com/70709113/226237880-9a732cfa-171a-4e2f-ab5f-f4ddd4323b3a.mp4
The new floating link editor has the following benefits:
- Less distractions when writing, as it moves around in a more predictable way - always under the link. It doesn't move around when clicking on different positions in the link as seen in the old one. I found that to be pretty annoying and distracting
- The old one sometimes overlaps the link & positions itself incorrectly - as seen in the video. Very annoying! This does not happen with the new one anymore
- Even for longer selections, the floating link editor now positions itself correctly, directly under the link
- Simpler code & …

UX: Floating link editor: better positioning

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Turns out that the `mouseDown` logic inside the table plugin was handling more events than it should.
https://user-images.githubusercontent.com/193447/226449211-70ead2ad-3f37-4cf7-9565-4e007d6a7bac.mov
Fixes #3785 
Fixes #4138

Fix table stealing selectionchange

---

package-lock.json
packages/lexical-playground/package.json
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.tsx

- The used Excalidraw was over 1 year old (v0.11) and wanted to pick up a number of fixes, including better integration with Vite. The changelog is available here: https://github.com/excalidraw/excalidraw/releases
- Also includes the new Excalidraw UI
Before:
After:

Bump Excalidraw to v0.14.2

---

packages/lexical-html/src/index.ts

The HTML deserialization design is partially predicated on the user having the ability to manipulate the DOM tree in the conversion functions - this provides virtually limitless flexibility in how incoming HTML can be processed.
Previously, we copied the DOM nodes at the top level to an array, then iterated through that to initiate the HTML -> Lexical transformation. This works fine in most cases, but it can cause an issue in a couple of edge cases where you're trying to combine sibling DOM nodes into a single LexicalNode. There's no way to prevent those sibling nodes from being processed, since they have already been copied to an array, removing them from the DOM does nothing.
Alternative proposed solution was to mark the nodes as "processed" and then ignore them in the next pass, but …

Iterate through the live NodeList instead of copying to an array in $generateNodesFromDOM

---

packages/lexical-playground/src/plugins/TablePlugin.tsx
packages/lexical-react/src/LexicalTablePlugin.ts

The current logic didn't handle selection restoration properly when selection was `null`. Leveraging `insertNodeToNearestRoot` will make table E2E tests less flaky

Fix table insertion

---

packages/lexical-html/src/index.ts

Our JSDom implementation does not handle DocumentFragment constuctor as it's not attached to specific doc so we can't run headless html conversion for tests. 
document.createDocumentFragment works fine

Create fragment attached to the doc

---

packages/lexical-playground/src/plugins/TablePlugin.tsx
packages/lexical-playground/src/ui/TextInput.tsx

Previously, you were able to input text for the row / column number count.

Only allow numbers in TablePlugin row / column number input

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
packages/lexical/src/LexicalSelection.ts

It turns out that this issue can only be reproed on FF because of the way it does selection, but it's a generic issue on the underlying selection layer used across the Core.
The logic around recomputing selection for `element` selection when adding and removing nodes was not correct. Turns out that it was too generic and the removing case was badly handled. Additionally, the test case assumptions were bad too.
When the selection falls in a linebreak it turns into an `element` selection and this combined with `insertText('')` and multiple `remove()` has to be recomputed properly as the combination of multiple `remove()` with bad selection is what led to deleting more nodes than it should.
The visible result was content reappearing but the initial bug was actual linebreak being deleted when …

Fix bad selection shift at boundary

---

packages/lexical-markdown/src/MarkdownImport.ts

My understanding is that `root.selectEnd` was dropped in https://github.com/facebook/lexical/pull/3886 because it was incorrectly restoring however. However, when selection is present we still want to restore it, otherwise we risk facing the lost selection invariant.
> updateEditor: selection has been lost because the previously selected nodes have been removed and selection wasn't moved to another node. Ensure selection changes after removing/replacing a selected node.

Restore MD selection

---

packages/lexical-list/src/LexicalListItemNode.ts

We don't need to worry about this property at all for lists - the hierarchy and theming control the indent level.
Fixes #4240

Ignore __indent in list deserialization

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

In this PR:
- https://github.com/facebook/lexical/pull/3826
The logic for `scrollIntoViewIfNeeded` was changed to rely on a class that is required to be provided to the ReactDOM.createPortal element.
```
...l-playground/src/plugins/AutoEmbedPlugin/index.tsx |  200:20 |     <div className="typeahead-popover">
...l-playground/src/plugins/AutoEmbedPlugin/index.tsx |  328:29 |                   className="typeahead-popover auto-embed-menu"
...al-playground/src/plugins/MentionsPlugin/index.tsx |  696:30 |               <div className="typeahead-popover mentions-menu">
...playground/src/plugins/EmojiPickerPlugin/index.tsx |  174:30 |               <div className="typeahead-popover emoji-menu">
...ground/src/plugins/ComponentPickerPlugin/index.tsx |  383:32 |                 <div …
```

Fix TypeaheadMenuPlugin scrollIntoView to not rely on external class

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalUtils.ts

Fixes #4215
We usually dispatch command (e.g., would be SELECT_ALL_COMMAND), and later handle it in RichTextPlugin/PlainTextPlugin, but this one is slightly different, since it's specifically for node selection as range selection is handled by contenteditable. So to avoid discrepancy, when node selection would trigger command and range selection would not, handling it right in core

Support select all for node selection

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.tsx

https://user-images.githubusercontent.com/7893468/229314462-892459ed-36d2-4b20-b119-2db9b19fb4b2.mp4
- Clicking outside of the modal was set to close the modal, this meant when you draw and finish the drawing outside of the popup it was closing the popup rather than adding the shape.
- After opening an existing Excalidraw node and drawing something new, if clicking on Discard, then Discard in the popup, it deleted the node, instead of discarding the new changes only. Now it just discards the changes since the last open.

Excalidraw Component fixes

---

packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Solves the issue raised here: https://github.com/facebook/lexical/issues/4223
- The event in `mouseUpCallback` doesn't bubble up to floating tool bar event handler, so the `.pointerEvent` style is never changed from 'none' to 'auto' meaning the toolbar is not interactive when text is selected within a table cell. 
- When text is selected in table cells, it's treated as a span dom node. We can use this information to check whether we want to propagate the event up to the floating tool bar event handler. 
- If text is not selected in the table cell, but the table cell is clicked on, the event should not bubble up. This is handled in the if statement.

Bugfix: Floating tool bar not responsive in tables

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/src/LexicalTableUtils.ts

Turns out that my oversimplified solution didn't handle the combination of colSpan + rowSpan. Added rowSpan handling
https://user-images.githubusercontent.com/193447/229589365-0ff2305c-97c7-4108-9443-6b2ce3725b81.mov

Fix insertTableColumn when rowSpan > 1

---

packages/lexical-playground/src/App.tsx
packages/lexical-react/src/LexicalComposer.tsx
packages/lexical/src/LexicalEditor.ts

Bug: isEditable is true on first render even if editor initiated with false
Ref.  #4224

isEditable is true on first render even if editor initiated with false

---

packages/lexical-mark/src/index.ts
packages/lexical-playground/src/plugins/CommentPlugin/index.tsx

Solves the issue raised here: https://github.com/facebook/lexical/issues/4190
- The selection is now temporarily cached inside a ref, `selectionRef` when the comment button is clicked, rather then relying on the current selection using `$getSelection`
- This means changes in selection, caused by editor updates have no effect on the content being wrapped by the Mark node when the comment is being added.
- Able to hover over table with comment popup closing
- Now able to add comments to text inside of tables without the popup closing
- Collapsing selection is now done by the `.selectStart()` and `.selectEnd()` APIs, within the `$wrapSelectionInMarkNode` function

Bugfix: Comment popup closes when cursor hovers over table

---

packages/lexical/src/LexicalSelection.ts

`getBoundingClientRect`is not a function when`selectionTarget` is of type`Text`, So just by judging `selectionTarget! == null` will not avoid this error

fix get text selectRect error

---

packages/lexical-table/src/LexicalTableCellNode.ts

`rowSpan` and `colSpan` for old stored nodes will resolve as `undefined` and be casted as `0`, leading to bad behavior

Cell merge backwards compatiblity

---

packages/lexical-table/src/LexicalTableCellNode.ts

Missed one part in https://github.com/facebook/lexical/pull/4267

Cell merge backwards compatiblity 2

---

packages/lexical-html/src/index.ts

Let's do this for now instead of this: https://github.com/facebook/lexical/pull/4178/files
I thought of a few problems with the API and I have some other ideas around serialization options more generally.
This is a breaking change, though., so we need to go to 0.10.

[0.10] Ignore script nodes in HTML deserialization

---

packages/lexical-react/src/LexicalCollaborationPlugin.ts
packages/lexical-react/src/shared/useYjsCollaboration.tsx
packages/lexical-yjs/flow/LexicalYjs.js.flow
packages/lexical-yjs/src/Bindings.ts
packages/lexical-yjs/src/Utils.ts

Moves excluded properties to the Binding to avoid sharing them across plugin instances, allows scoping ignored properties to the node, reducing the likelihood of collisions.
Fixes #3670

Allow excluding specific properties from collab syncing via plugin

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawImage.tsx
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.tsx

- When adding images to the Excalidraw scene, the files were not persisted
- When exporting the scene, it was losing some of the scene data, like background color.
Before:
https://user-images.githubusercontent.com/7893468/231016887-7a68c03b-341b-4156-b78c-414b828893b3.mp4
After:
https://user-images.githubusercontent.com/7893468/231016948-61eae2ab-d813-4de5-b588-e5bd7732fbdd.mp4

Persist files and scene state in Excalidraw plugin

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/TreeViewPlugin/index.tsx
packages/lexical-react/src/LexicalTreeView.tsx

https://user-images.githubusercontent.com/7893468/231305891-19835d70-b54d-4833-b73b-552a8f1f5326.mp4
I've been meaning to add this for ages - the ability to toggle between node view and an exportDOM view, in order to validate if the a node's exportDOM definition is correct, since the DevTools show the createDOM output, besides manually printing exportDOM inside node methods, there is no intuitive way to check if the exportDOM properties are set correctly during development. 
Happy to hear suggestions for improvement.

ExportDOM in Debug Tree View

---

packages/lexical-link/src/__tests__/unit/LexicalLinkNode.test.ts
packages/lexical-link/src/index.ts

More targeted approach to https://github.com/facebook/lexical/pull/4329

[0.10] Ban javascript URLs in @lexical/link

---

packages/lexical-mark/flow/LexicalMark.js.flow

Subclasses of `MarkNode` can't override `clone` without adding a Flow type error ignore annotation without this change.

Change `MarkNode::clone` `node` arg type to `this`

---

packages/lexical-link/src/index.ts

#4342 Will break some links that don't use the full protocol and therefore can't be pasted correctly by the URL lib.
This fixes that by falling back to the url in the event of a failure to parse the string passed into theURL constructor.

Fall back to url if parser fails

---

packages/lexical-playground/__tests__/e2e/Hashtags.spec.mjs
packages/lexical-text/src/index.ts

Inherit format for text entity node

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-playground/src/plugins/CollapsiblePlugin/index.ts

Better handling for up/down/left/right arrows to escape collapsible when it's the last/first element in the root/shadowroot

Collapsible enhancements

---

packages/lexical-playground/src/plugins/FloatingTextFormatToolbarPlugin/index.tsx

Introduced a movement threshold so button clicks with slight motion to them aren't filtered out. The current behavior will ignore all clicks to the toolbar with even the slightest of mouse movement, causing the toolbar to feel unresponsive.
This was broken with the fix introduced in #3959. My fix should help to improve the feel of the buttons while still mitigating the toolbar flashes on drag to highlight.
Current Behavior:
https://user-images.githubusercontent.com/29527680/231000297-d6c2cb05-dc8a-4479-b8c7-32e4c3066d45.mov
---
Fixed Behavior:
https://user-images.githubusercontent.com/29527680/231000315-ad7d6c40-2c45-4f8b-88e1-614efdafadc9.mov

Improve responsiveness of the floating text format toolbar buttons

---

packages/lexical-playground/src/Editor.tsx

isSmallWidthViewport state is not set correctly when the editor is rendered in a small window. That's why DraggableBlockPlugin is enabled initially when in a small window.

Setting initial state of isSmallWidthViewport

---

packages/lexical-playground/src/nodes/FigmaNode.tsx
packages/lexical-playground/src/nodes/TweetNode.tsx
packages/lexical-playground/src/nodes/YouTubeNode.tsx
packages/lexical-react/src/LexicalDecoratorBlockNode.ts

Fix https://github.com/facebook/lexical/issues/3708
I think that thread was closed because @DaniGuardiola point was not understood, which I think was made clearer in his last comment.
To avoid confusion again, please note that this change is about the DecoratorBlockNode, not the DecoratorNode.
With this change, no one runs the risk of forgetting to override the method.

Make DecoratorBlockNode.isInline return false

---

packages/lexical-html/src/__tests__/unit/LexicalHtml.test.ts
packages/lexical-html/src/index.ts

Fixes https://github.com/facebook/lexical/issues/3705
Adds unit tests for HTML serialization

Use provided selection when serializing to HTML

---

packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-playground/__tests__/regression/3433-merge-markdown-lists.spec.mjs

Fix markdown list merging

---

packages/lexical-playground/src/plugins/FloatingTextFormatToolbarPlugin/index.tsx

So, #4298 fixed the problem where button clicks in the floating toolbar did not react if the mouse was moving.
I actually came up with a different solution, where it simply checks if the mouse is over the floating toolbar element.
It's less code and does not require a mouseDownListener - thus I think it might improve readability + performance.
Do let me know what you think, or if the previous solution is better!
ALSO: I'm currently not home and only have my laptop trackpad to test - no mouse! Please test this out with a mouse to make sure this PR does not reduce the responsiveness compared to the previous solution!

simplify logic for the fix "Improve responsiveness of the floating text format toolbar buttons"

---

packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

Fix for Issue #4347
Registered new event listener in Toolbar plugin to insert link using TOGGLE_LINK_COMMAND when we press Cmd/Ctrl + K
This is my first contribution in the repo so not sure if I did it the right way.

Updated Toolbar Plugin to Add keyboard shortcut for adding hyperlinks

---

packages/lexical/src/LexicalEvents.ts

Fix text click selection on touch devices #3098

---

packages/lexical-react/src/LexicalContentEditable.tsx

The issue
----------
Currently the `ContentEditable` component is misleading because the interface for its props makes a union with all possible HTML attributes like so `} & React.AllHTMLAttributes<HTMLDivElement>` but at the same time doesn't pass them to the actual div its creating.
Essentially if you write a code: `<ContentEditable autoCorrect="off" />` typescript won't complain because it's within the interface. However the attribute itself isn't passed down into a `div` so that's where the issue at.
Solution
--------
I assume that it's totally fine to just pass the rest of the attributes for the lack of better context

Allow to pass all possible attributes to a content editable div

---

packages/lexical/src/LexicalEvents.ts

OK, so after this great fix https://github.com/facebook/lexical/pull/4395 by @IBastawisi it kinda inspired me to do some research. It turns out that touch devices issues are famous, they keep coming!
I started with a fix https://github.com/facebook/lexical/pull/2901 that caused https://github.com/facebook/lexical/issues/3538 
Then a fix for this https://github.com/facebook/lexical/pull/3541, but that didn't to address the desktop issue #2901 fixed in the first place. And lastly https://github.com/facebook/lexical/pull/4395
---
This PR is mostly a cleanup from #4395, I don't think there's anything particularly wrong with it besides it can be done without the NodeSelection restriction (just like mouse).
https://user-images.githubusercontent.com/193447/235493747-29615342-523f-4f0b-ba3f-f5b1e5 …

Revisit touch devices

---

packages/lexical-react/src/LexicalNodeEventPlugin.ts

fixes #4213 
👋🏻 Some explanation:
- in the previous version listeners were not cleaned up because they would be added only once, and would then be cleaned up when the nodes are removed
- in this new version I've implemented listeners cleanup because `useLayoutEffect` runs twice during development which results in initial nodes getting iterated over twice. Rather than to hack-ily keep track of how many times `useLayoutEffect` ran with the same deps, I've made sure it can run as many times as it wants
- I've cleaned up some comments

fix: attach event listeners to initial nodes

---

packages/lexical-playground/__tests__/e2e/Links.spec.mjs

This test is flaky everywhere really, any objections towards disabling it for now?

Disable flaky test

---

packages/lexical-website/docs/react/plugins.md

Simple addition to the documentation for plugins regarding the TabIndentationPlugin, which corresponds to the functionality that was removed on this PR #2855.

Add documentation for TabIndentationPlugin

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-playground/__tests__/keyboardShortcuts/index.mjs
packages/lexical/src/LexicalSelection.ts

Fix elements deletion which used to delete leading element node once last character within it was deleted:
Before (deleting text within first non-paragraph element converted it to paragraph right away):
https://user-images.githubusercontent.com/132642/235222095-9e8db5af-5aa7-4d82-88b0-9da46a75ae21.mov
After (deleting text keeps original element type once text deleted until press delete once again, but select all + delete cleans up element style as well, per #3840)
https://user-images.githubusercontent.com/132642/235222279-7cfa3398-1703-4f06-9744-82d4ab2acc39.mov

Select all adjustments

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical/src/LexicalSelection.ts

Deleting empty element should not change style of its sibling element:
Before
https://user-images.githubusercontent.com/132642/233679597-948f00ba-b743-4b75-9881-e27727dcd0cc.mov
After
https://user-images.githubusercontent.com/132642/233679595-78da18b9-8e73-47d1-a5a4-91a7807b1e0b.mov

Handle empty element deletion

---

packages/lexical-react/src/LexicalNodeEventPlugin.ts

There's couple of problems with current implementation:
- It relies on mutation listener that does not run for initial state (only for added nodes)
- It attaches event to specific node, so for nodes like TableCell or Paragraph it can add hundreds or thousands of listeners for longer documents
This on attempts to add event delegation with special handling for mouseenter/leave events via capturing since those don't bubble

Event delegation for NoteEventPlugin

---

packages/lexical-selection/src/utils.ts

This function helps creates a "fake" selection by getting all the rects for a given range, then creating a span tag for each that we layer over the rect position. For reasons that are not completely clear to me, the browser sometimes gives us what amount to "duplicate" rects for our purposes - Rects that completely or partially overlap and cause visual issues like a darker colored selection.
This PR is an effort to improve our deduplication logic to better detect these overlaps, which don't always have exactly matching top, left, width, and height properties. The approach here is instead to try to figure out of the top left corner of a given rect is inside of the previous rect when traversing the rects in order from top-left to bottom-right.
Before:
After:

Improve rect deduplication

---

packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/__tests__/unit/LexicalSelection.test.ts

Fixes: #4295 
(Well, it's a strawman implementation.)
CLA signing currently pending response from `cla@meta.com`.

Tests for inserting text either side of an inline element

---

packages/lexical-clipboard/src/clipboard.ts

Issue #4409 highlights a problem where users are unable to paste text/uri-list type content. This PR aims to address and resolve this issue.
The problem is due to discrepancies in the valid MIME types for read/write operations in the clipboard between Chromium and WebKit. 
Chromium supports the read/write operations for the following MIME types [(Chromium)](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/clipboard/clipboard_writer.cc;drc=e882b8e4a8272f65cb14c608d3d2bc4f0512aa20;l=304):
- `text/plain`
- `text/html`
- `image/png`
On the other hand, WebKit supports all the above types as well as `text/uri-list` [(WebKit)](https://webkit.org/blog/10855/async-clipboard-api/).
This inconsistency causes an issue when, for example, a user opens a …

Add text/uri-list support in clipboard.

---

packages/lexical/src/LexicalGC.ts
packages/lexical/src/nodes/__tests__/unit/LexicalGC.test.tsx

Turns out we introduced a memory leak on the GC module when we launched doubly linked lists.
The root cause is that now order is important
1. We have to start with ElementNodes first, if a child is removed from the Map there's no way to traverse (next) children later (unless we keep a separate copy).
2. The attached assumption on children node  in `$garbageCollectDetachedDeepChildNodes` was not correct. It will  never be true because the parent is not attached in the first place.
Fixes #4509

Fix GC memory leak

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical/src/LexicalEvents.ts

Triple click expands selection to cover whole element, but also moves focus node to the next element sibling. So even though visually it looks like single text block is selected, selection is also expanded to the next line. If we try to modify such selection two blocks are affected. 
Easiest way to reproduce: have two paragraphs, tripple click on first, convert into heading, then both paragraphs will be converted into headings. Another example is tripple click within table cell, and pressing delete: it selects current cell and beginning of the next one. Hitting delete will completely delete one of the cells
Before:
https://github.com/facebook/lexical/assets/132642/1bf6284c-4b72-4e5e-9d62-a8368e6e732c
After:
https://github.com/facebook/lexical/assets/132642/0c9fc3ad-911c-4bd9-a3d6-f2d0ce830 …

Adjust selection after triple click

---

packages/lexical-website/docs/concepts/serialization.md

I've used the most approved code snippet from the following issue: https://github.com/facebook/lexical/issues/2452 as a base to address the case for full style serialization/deserialization of HTML styles to preserve the HTML<>JSON fidelity.
Please comment on what to modify, add, remove. I'd like to make this snippet as canonical as possible, since most people will copy-paste without any modifications. I'd like to treat it as a piece of code in the library, we just can't add to the core. Should help solve a lot of the Discord questions by providing a link.

Add HTML deserialization recipe to docs

---

packages/lexical-react/src/LexicalAutoEmbedPlugin.tsx

Pasting enbeddable url can trigger mutation listener with up to 3 dirty leaves: new node itself and (optional) siblings on both sides of the node:
Before:
See #4530
After:
https://github.com/facebook/lexical/assets/132642/301629c3-9367-4723-95d8-ba3c9fd150f7

Auto embed fix #4530

---

scripts/npm/update-changelog.js

Some weird characters in the changelog break the `exec`, let's allowlist the characters instead

Fix update-changelog not finishing

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/ListsHTMLCopyAndPaste.spec.mjs
packages/lexical-playground/src/ui/ContentEditable.css
packages/lexical-playground/src/ui/Placeholder.css
packages/lexical-rich-text/src/index.ts

That condition looks a bit odd and is likely redundant or missing extra logic. Basically any shift + arrow-up selection will be broken if going into { canBeEmpty: false } (tables, lists). Original issue uses image as an example, but even list + paragraph case is broken:
1. Add list + paragraph, press shift + up in attempt to select
2. Note that cursor just moves to the list, without selecting anything
Before: 
https://github.com/facebook/lexical/assets/132642/80813c6d-8373-407d-a7c3-dda0aaa3802d
After:
https://github.com/facebook/lexical/assets/132642/94b8cd75-1358-4b66-8afa-88b77988a512

Arrow up selection fix #4536

---

packages/lexical-playground/__tests__/e2e/Composition.spec.mjs
packages/lexical-playground/src/nodes/MentionNode.ts
packages/lexical/src/LexicalUtils.ts

We're usually very lenient when it comes to composition (as it can break easily) and we don't touch it unless it's imprescindible.
However, Mutations as they're now are breaking the `canInsert{Before/After}` rules which directly impacts things like Mentions or TabNode. This PR forbids Mutations that violate this rule and will instead fallback to `input`.
The other question is whether TabNode has to implement `canInsert{Before/After}` or we can do something smarter with it.
This PR also adjusts the behavior for MentionNode, which also makes me think whether this `canInsert` rule should be automatically applied when there's segmentation as I can't think why it would make sense to allow characters at the end when segmentation implies that the Node will be recreated as soon as you type on it. …

Mutations to respect canInsertBeforeAfter

---

packages/lexical-react/src/shared/useDecorators.tsx

createPortal missed key, so when we reconciled decorators and order/amount of decorators changed it caused full rerendering
https://github.com/facebook/lexical/assets/132642/f3470ea8-ed23-4694-ad54-c6a42dec052f

Add key to portal to avoid decorator component remounting

---

packages/lexical/src/LexicalSelection.ts

Fixes #4402 
For some reason, in this case,  the native selectionchange event doesn't fire. The best I can tell, it's because DOM Selection already matches what we try to set it to in the reconciler when we call setBaseAndExtent. I don't see where we're explicitly changing the native selection in this code path, so I guess it's the browser. In any case, this explicitly dispatches selection change to cover this case.

Fire selection change on decorator delete

---

packages/lexical/src/LexicalEditorState.ts
scripts/error-codes/codes.json

When creating a custom Node that extends an existing Node, and `exportJSON()` is implemented but uses the output of `super.exportJSON()`, the current error message `LexicalNode: Node %s does not implement .exportJSON().` is misleading.

Better Error Message for exportJSON type

---

packages/lexical/src/LexicalUtils.ts

The "cache" for getCachedClassNameArray is the theme itself. We mutate the theme object provided in the initial config, which is problematic because it can cause runtime type errors when we're looking for a string when accessing the theme properties directly, but instead we get an array.
This approach (vs #4581 ) has the advantage of leveraging the theme to keep the cache scoped to the Editor, disadvantage of still mutating the theme object, although collision probability seems low.

Another approach to fixing the className cache

---

packages/lexical-react/src/LexicalContentEditable.tsx

This PR fix accessibility of ContentEditable in the non editable mode.
When Lexical editor is not editable, there is no `role` attribute, but `aria-autocomplete` has the value 'none'. That breaks our pipeline during a11y check with the critical warning:
As I understand the issue, we can not have aria attributes without a valid role. So I keep the role 'textbox' for non-editable case, but at the same time set `aria-readonly="true"` as suggested in [doc](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/textbox_role)

Fix a11y for ContentEditable

---

packages/lexical-rich-text/src/index.ts

When pressing SHIFT+UP or DOWN to create a range selection, we want this to work correctly, without being intercepted as part of the block cursor logic.
Fixes #4561

Allow native shift+arrow selection work over decorator nodes

---

packages/lexical-playground/src/nodes/AutocompleteNode.tsx

UUID and key should be stable when the node is cloned, but currently, the old key becomes the new UUID and a new key is regenerated. 
This feels like a simple typo that arose in the v2 rewrite a few months ago.
Fixes  #4589

Fix uuid bug in `AutocompleteNode.clone()`

---

packages/playwright-core/lib/server/injected/packed/injectedScript.js

updated mouseenter event typo in injectedScript.js file

mouseenter event typo fix

---

packages/lexical-selection/src/utils.ts

closes #3946
Currently, the `getStyleObjectFromCSS` returns the object which is directly mutable. So, added logic to freeze the object before returning to avoid accidental mutations in __DEV__.

fix: freeze get style object in DEV env to avoid mutations

---

packages/lexical-markdown/src/MarkdownShortcuts.ts

On keyboards that use [dead keys](https://en.wikipedia.org/wiki/Dead_key) for backticks the markdown converter does not work properly. The second backtick (for inline code) triggers the conversion, before the user has confirmed the key.
See here:
https://github.com/facebook/lexical/assets/32648275/f3535af7-4450-4dd8-b74a-0fe88d40ca3e
The event should be ignored, if the editor is still composing.
Further below I adjusted the offset check slightly, to allow the conversion to markdown when the user confirms the key. This is required, because the cursor will not move during these two operations.

fix issue with dead keys (i.e. backticks) when converting markdown

---

packages/lexical-yjs/src/SyncEditorStates.ts

Issue explanation:
Lexical uses the delta in the events coming from yjs document to sync the state of the editor with the latest changes. According to yjs delta is a computed property, meaning that it is computed when it is accessed for the first time. yjs also says :  
> Note that this can only be safely computed during the event call. Computing this property after other changes happened might result in unexpected behavior.
[Link to yjs repo where it's explained.](https://github.com/yjs/yjs/blob/00ef472d68545cb260abd35c2de4b3b78719c9e4/src/utils/YEvent.js#L132)
Lexical accesses delta in a callback function passed to `editor.update` and this function can be scheduled to run in a separate event call. That means delta can be computed unsafely in a different event call. This affects the …

Fix issue with syncing yjs changes to Lexical

---

packages/lexical-website/src/pages/docs/error/index.js
scripts/error-codes/formatProdErrorMessage.js

Add adj/noon params into error url to support error formatting:
1. Trigger error by registrering mutation on non-existing node
2. Use website preview to get formatted error
https://lexical-czmewj31g-fbopensource.vercel.app/docs/error?code=37&a=MentionNode
Fixes #4624

Add error formating params

---

packages/lexical-code/src/CodeNode.ts

CodeNode didn't have ExportDOM defined, breaking the import/export HTML workflow.

Add missing ExportDOM to CodeNode

---

packages/lexical-rich-text/src/index.ts

Continues the support of alignment for Heading and Blockquote nodes after we now export the property in exportDOM, we now have to import it.

Import alignment for Heading and Blockquote

---

packages/lexical-code/flow/LexicalCode.js.flow
packages/lexical-react/flow/LexicalContentEditable.js.flow

`HTMLDivElement[...]` types are interpreted as `any` internally. Partially reverting https://github.com/facebook/lexical/pull/3580

Fix ContentEditable Flow types

---

packages/lexical-yjs/src/Utils.ts

`excludedProperties` is a global list of properties that are not synced in collab mode, which includes node-specific props like `__size`, `__first`, `__last` (that should be filtered for elements only), or `__text` which is relevant for text nodes. That introduces possible issue where a decorator node (let's say Emoji) can have perfectly valid `__size` property, but it won't be sync'd over collab because it's filtered out for all nodes.
This PR checks if property should be excluded based on node type (element, text, root) and any extra excluded props from plugin to avoid it
Ref #3670

Check for specific excluded props

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical-rich-text/src/index.ts
packages/lexical-utils/src/__tests__/unit/LexicalUtilsKlassEqual.test.ts
packages/lexical-utils/src/index.ts

This is also my first contribution attempt to the project. Sorry in advance if something doesn't make sense!
In #2108  we support for iframe (use React.Portal to render the content editable area in an iframe). It works well.
Recently I notice that some of the clipboard logic doesn't work in iframe. More specifically, I found that `DecoratorNode` won't be exported on copy.
After digging into it, I found that is caused by global class variables having different instances in different window. There is more detail about this behaviour [in MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_realms).
In this diff, the issue I personally encounter has been fixed. But there are wider usage of `instanceof` in the codebase.
Overall, I …

Fix clipboard if content editable is in an iframe.

---

packages/lexical-playground/__tests__/regression/4661-insert-column-selection.spec.mjs
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-table/src/LexicalTableUtils.ts

Retrieves selection anchor node in addition to focus node in order to find the start or end of table selection when inserting columns.
Fixes issue https://github.com/facebook/lexical/issues/4661
The start of selection is used as target for inserting columns if we want to insert columns before.
The end of selection is used as target if we want to insert after.
Before:
https://github.com/facebook/lexical/assets/23295934/6848a138-e92c-412e-8939-131a1b2c34e1
After:
https://github.com/facebook/lexical/assets/23295934/91ddd789-dc8c-4375-9bcb-fd4ed1a60d76

Add columns next to selection

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalUtils.ts

See issue description. Given that it works well on FF, I've decided not to overide FF's behavior for now. Safari's behavior is sometimes worse than Chrome, caret jumping around instead of selecting so Chrome + Safari are a must-do override.
I didn't narrow down to checking whether there's DecoratorNodes at its boundaries because the root cause seems to be `contenteditable=false` but it doesn't necessarily have to sit at the top
```
<div contenteditable="true"><div contenteditable="false">...</div></div>
```
^ This will not work on Chrome
Might be that the pattern is first line of descendants not contenteditable (given the correct valid Nodes that can take this properties (i.e. iframe can't take it)) but since I'm not too confident on what the pattern is and the logic might be overly …

Override selectall on RangeSelection

---

packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/index.css
packages/lexical-playground/src/nodes/InlineImageComponent.tsx
packages/lexical-playground/src/nodes/InlineImageNode.css
packages/lexical-playground/src/nodes/InlineImageNode.tsx
packages/lexical-playground/src/nodes/PlaygroundNodes.ts
packages/lexical-playground/src/plugins/InlineImagePlugin/index.tsx
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts
packages/lexical-playground/src/ui/Checkbox.css
packages/lexical-playground/src/ui/Select.css
packages/lexical-playground/src/ui/Select.tsx

I thought that perhaps a playground example of an inline image with float and wrapped text might be useful (including `updateDOM`) - and so I've created an inline image node and plugin - all 'namespaced' as a separate plugin and node from the current image node. See the attached video demo. The plugin includes a 'round trip' edit option, and so the inserted image position can be updated.
https://user-images.githubusercontent.com/405612/235197663-7ba3cfe9-60bd-4b75-82b6-75edd1f19d69.mp4

feat: playground inline image plugin

---

packages/lexical-playground/src/ui/DropDown.tsx

This Pull Request introduces a fix to maintain the dropdown menu's position relative to the toolbar during page scroll. Previously, the dropdown menu was using `position: fixed`, causing it to remain stationary in the viewport instead of moving along with the toolbar during scrolling.
adding content in the playground editor untill a scroll bar appear, and then open any dropdown menu in the toolbar and scroll the page.
The dropdown menu's positioning logic has been updated to become fixed or absolute based on the toolbar's position. 
Obtaining an accurate toolbar position is crucial for this logic. However, due to asynchronous loading of elements (like the Logo), directly extracting the toolbar's position in a `useEffect` hook can result in inaccurate values. To ensure precision, we're …

Fix dropdown menu position in playground when scroll

---

packages/lexical-playground/__tests__/e2e/TextEntry.spec.mjs

Hopefully this fixes some flakey E2Es.

Remove delay from flakey E2E test

---

packages/lexical-clipboard/src/clipboard.ts

Previously in #4649 I was supposed to fix the clipboard issue if the content editable area is in an iframe.
It turns out that I fail to handle one case of getDOMSelection (Sorry! I don't know why it was working for me previously)
In this diff, I am applying the same fix as in #3578 to lexical-clipboard package

Additional fix for editor._window in lexical-clipboard

---

packages/lexical-playground/__tests__/regression/4697-repeated-table-selection.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Earlier on table selection,  previous selection was cleared before immediately returning on mousedown if table cells were already selected. By not returning, but still clearing selection, we are able to make a proper new table selection instead of ending up in bad states.
Fixes issue #4697
See issue for more details.
Before:
https://github.com/facebook/lexical/assets/23295934/d9eec6bc-6829-4dca-a4d8-023acf3ed8fa
https://github.com/facebook/lexical/assets/23295934/e101c75e-6f2c-4369-84a7-3cda2bc72817
After:
https://github.com/facebook/lexical/assets/23295934/3d1832a2-d105-422c-b005-107c3afcc4bf
https://github.com/facebook/lexical/assets/23295934/c39419ed-08d6-4cb1-97d2-04655ab0c4f8

Allow table selection when cells are already selected

---

packages/lexical-website/docs/intro.md

Correction is needed. Update for change. Lexical being immutable can’t be recreated, only updated to insert new nodes.

correction : line 47 - create -> update

---

packages/lexical-playground/src/commenting/index.ts

The order of [CommentStore local comments](https://github.com/facebook/lexical/blob/1ce51a8b6e4bec14601829f5503022015dc05403/packages/lexical-playground/src/commenting/index.ts#L106C3-L106C12) and the [shared comments array](https://github.com/facebook/lexical/blob/1ce51a8b6e4bec14601829f5503022015dc05403/packages/lexical-playground/src/commenting/index.ts#L250) must be exactly the same. Otherwise, the order of comments may be different for different users, and most importantly the [delete operation](https://github.com/facebook/lexical/blob/1ce51a8b6e4bec14601829f5503022015dc05403/packages/lexical-playground/src/commenting/index.ts#L187C11-L187C24) depends on it.
If the delta contains more than one insert (happens during the initial load of comments) the order of the comments is reversed. …

Keeping local comments and sharedCommentsArray orders in sync

---

packages/lexical-list/src/LexicalListItemNode.ts

This PR fixes an issue with node deserialization. Currently, when importing from JSON, the `importJSON` method directly returns an instance of ListItemNode instead of an overridden one. I believe that just like other nodes, ListItemNode should also go through `$applyNodeReplacement`.

Fix: Use $createListItemNode within importJSON to override on deserialization

---

packages/lexical-markdown/src/MarkdownShortcuts.ts
packages/lexical/src/LexicalEditor.ts

Also simplifies the hasNode(s) API. I don't think using Array.prototype.every should be a problem here, but willing to listen to opposing viewpoints.

Improve md error message

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx

The current way to edit the Excalidraw node is to double click the image which is not super accessible.
This pull request adds a button to open the modal if the node is selected.

Show excalidraw edit button

---

packages/lexical-plain-text/src/index.ts
packages/lexical-playground/src/plugins/ContextMenuPlugin/index.tsx
packages/lexical-utils/src/index.ts
packages/lexical/src/LexicalCommands.ts

This PR adds cut, copy, paste, paste as plain text and delete node options to the context menu.
Demo:

Context Menu Options Added

---

packages/lexical-plain-text/src/index.ts

Android Chrome < 60 doesn't have the InputEvent constructor, so it throws on check. We don't technically support Android Chrome before 72, but I think this is a relatively unintrusive fix.

Remove instanceof checks in onPasteForPlainText

---

packages/lexical-code/src/CodeNode.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/HTMLCopyAndPaste.spec.mjs
packages/lexical/src/nodes/LexicalTextNode.ts

We should export multi-line code as pre, same as other editors do
Fixes #4677

Fix code block export

---

packages/lexical-code/src/CodeHighlighter.ts

Noticed that we don't process multi-line code tokens (like multi-line comments) and insert raw text as is without linebreak nodes:
After:

Fix multi-line token parsing

---

packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalCommands.ts
packages/lexical/src/LexicalEvents.ts

This PR adds input event to REMOVE_TEXT_COMMAND to allow preventing text drag by simple plugin:
```js
useEffect(() => {
const preventInputEvent = (inputType: string) => (event: unknown) => {
if (event instanceof InputEvent && event.inputType === inputType) {
event.preventDefault();
return true;
}
return false;
};
return mergeRegister(
editor.registerCommand(
CONTROLLED_TEXT_INSERTION_COMMAND,
preventInputEvent('insertFromDrop'),
COMMAND_PRIORITY_HIGH,
),
editor.registerCommand(
REMOVE_TEXT_COMMAND,
preventInputEvent('deleteByDrag'),
COMMAND_PRIORITY_HIGH,
),
);
}, [editor]);
```
https://github.com/facebook/lexical/assets/132642/6fcfe20a-21dd-4786-aba7-5466e449b06a
Fix #4744

Allow preventing text drag

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx
packages/lexical-playground/src/nodes/ImageComponent.tsx
packages/lexical-playground/src/nodes/InlineImageComponent.tsx
packages/lexical-playground/src/nodes/PollComponent.tsx
packages/lexical-react/src/LexicalBlockWithAlignableContents.tsx
packages/lexical-react/src/LexicalHorizontalRuleNode.tsx
packages/lexical/src/LexicalNode.ts
packages/lexical/src/LexicalUtils.ts

Deleting node with NodeSelection should move selection to its sibling. Another question is whether deletion logic should remain in plugin instead of going into core.
Fixes #4738

Add selection adjustments for node removal

---

packages/lexical-code/src/CodeHighlighter.ts

Fix missing token type

---

packages/lexical/src/LexicalSelection.ts
packages/lexical/src/__tests__/unit/LexicalSelection.test.ts

Fix $transferStartingElementPointToTextPoint()

Fix $transferStartingElementPointToTextPoint()

---

packages/lexical/src/LexicalEditor.ts
packages/lexical/src/__tests__/unit/LexicalSelection.test.ts

We missed resetting editor state back to its original (or pending value) when unset root element (by either unmounting contenteditable or directly calling `setRootElement(null)`). Which caused editor with unset root element to always return empty editor state

Reset editor state when setting null root
