packages/lexical-react/src/LexicalEditorRefPlugin.tsx

Small fix to avoid the `Its return type void is not a valid JSX element`  when using Typescript.

fix: Return LexicalEditorRefPlugin as valid JSX

---

packages/lexical-selection/src/range-selection.ts

Fix: #4773
https://jam.dev/c/fea34251-b2de-4a9c-bc1a-173c4b18bf33
https://jam.dev/c/99be1b2c-10cf-40a7-ba61-53059de667f3
------------------------------------------------------------
Fix: #4696 
https://jam.dev/c/d05b2d2d-45c3-43cb-962d-2c276905b0a9
https://jam.dev/c/4eea839f-5817-49c9-a4ac-3941fc5f5d31

Fix : Can't convert paragraph into a header if the first child of the paragraph is a LineBreakNode

---

packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalUpdates.ts

This one should allow access for deleted nodes state using prev editor state:
```js
editor.registerMutationListener(
SomeNode,
(mutations, {prevEditorState}) => {
for (const [key, type] of mutations.entries()) {
if (type === 'destroyed') {
const destroyedNode = prevEditorState.read(() => $getNodeByKey<LexicalNode>(key));
...
}
}
},
)
```

[RFC] Add prev editor state for mutation listener

---

packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
packages/lexical-website/docs/getting-started/theming.md

It seems like `placeholder` is not a property of [`EditorThemeClasses`](https://github.com/facebook/lexical/blob/4ce3483a02f39aec5a89e9a3716d67ac27ee6365/packages/lexical/src/LexicalEditor.ts#L78) anymore.

docs: remove placeholder property from exampleTheme

---

packages/lexical-playground/__tests__/e2e/DraggableBlock.spec.mjs
packages/lexical-playground/src/plugins/DraggableBlockPlugin/index.tsx

Enhances the interactivity of the Playground editor by allowing users to drop nodes into empty areas at the start or the end.
**Before**
https://github.com/facebook/lexical/assets/46543621/ad07fdc4-01cd-4b8b-8f91-4aedcc6b5b2d
**After**
https://github.com/facebook/lexical/assets/46543621/a8c72d72-f160-4c51-a4cd-9bbabfe4a1ff

feat(playground): add support for drop block on empty area

---

packages/lexical-playground/src/plugins/CommentPlugin/index.tsx
packages/lexical-react/src/LexicalEditorRefPlugin.tsx

Fixes: https://github.com/facebook/lexical/issues/4849
- fix editor ref types
- use EditorRefPlugin in the playground

fix editor ref types and use EditorRefPlugin in the playground

---

packages/lexical-plain-text/src/index.ts
packages/lexical-rich-text/src/index.ts
packages/lexical/src/LexicalCommands.ts
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/index.ts

Move the "select all" behavior from `LexicalEvents` into a new `SELECT_ALL_COMMAND`. This will make overriding the default behavior easier for developers and matches the way that commands like copy, paste, arrow up, etc are handled.
Overriding "select all" is not common, but several applications have introduced context-aware versions of the behavior that are difficult to change with lexical's current implementation. For example, an editor may choose to have the first invocation of `⌘ + a` select the current paragraph and a subsequent `⌘ + a` select the entire document.

Extract "select all" behavior to new `SELECT_ALL_COMMAND`

---

packages/lexical-list/src/formatList.ts

Earlier pressing enter unexpectedly deletes the ImageNode from the child of ListItemNode. Now it is fixed.
https://github.com/facebook/lexical/issues/4236
https://github.com/facebook/lexical/assets/63761544/d2403a7b-94cb-4441-8892-d89197264ab9

Fix: Pressing enter now doesnot delete ImageNode from the ListItemNode

---

packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts

No issue
The current `regExp` is causing non-link Markdown syntax to be parsed as a link.
Example, the markdown syntax for an image would be `![alt text](https://example.com/example.jpeg` would be detected as link markdown and render it as a link, eg `!<a href"">alt text</a>`.
It completely overrides my custom transformers that wants to parse markdown to a custom image node.
This fix updates the regex to not render a link if `!` is in front of the link markdown syntax, allowing the custom transformer to initiate if available.

Updated link markdown regex

---

packages/lexical-playground/__tests__/regression/4872-full-row-span-cell-merge.spec.mjs
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/LexicalTableSelection.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Fixes issue: #4872
Changes typing to expect undefined rows and cells and handles this where necessary.
The alternative is to always make sure that row indices are not deleted from grids during i.e. cell merge. That seems like a more fragile solution than just accepting that rows might be deleted. Currently, rows are being deleted leading to an array structure like this:
I don't know where the indices are deleted, but it seems like it is possible to do so without getting caught by the type checking.
That is why I have modified the types to accept that this might happen (and is happening today), which seems more maintainable.
Now the editor does not crash after merging cells spanning multiple full rows, and according to the type checks, it should also be ok in most other cases.
The only …

Handle undefined rows and columns in table utils after cell merge

---

packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts

Mac CI broke since this PR. Running the CI again to validate.
This reverts commit c8f8366060d5a9d8e37de1045fb5336915b84ab0.

Revert "Updated link markdown regex (#4461)"

---

packages/lexical-playground/__tests__/regression/4876-unmerge-cell.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-table/src/LexicalTableUtils.ts

Fixes #4876
When adding cells to rows when unmerging cells, $unmergeCell used `row.getNextSibling()` with the same row an all iterations  of the row span except the first to get current row node. This resulted in the same row node being used on all iterations.
https://github.com/facebook/lexical/assets/23295934/5f23b3ed-c467-4b55-b595-67bfb3ab2a12

Table unmerge

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

Hello! 
I noticed that most of the buttons on the playground are reactive depending on the current selection of the editor, with the exception of the element format dropdown (aka, the align paragraph dropdown).
I added a new element with the corresponding update logic to enable this dropdown to change with the current selection. Hope it meets the standards of the project.
Thanks for creating such an awesome project!

Adds ElementFormatDropdown to the Toolbar plugin

---

packages/lexical-website/docs/getting-started/react.md

I noticed the examples in [Getting Started with React](https://lexical.dev/docs/getting-started/react) weren't working. Updated it to reflect the recommendation from the [Listeners](https://lexical.dev/docs/concepts/listeners#registerupdatelistener) page.

docs: fix example in getting-started/react

---

.gitignore
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs
packages/lexical/src/nodes/LexicalTextNode.ts
packages/lexical/src/nodes/__tests__/unit/LexicalTextNode.test.tsx

Disables spellcheck for text nodes with code format.

fix: disable spellcheck for code format

---

packages/lexical-html/src/__tests__/unit/LexicalHtml.test.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-utils/src/__tests__/unit/LexicalUtilsSplitNode.test.tsx
packages/lexical-utils/src/__tests__/unit/LexlcaiUtilsInsertNodeToNearestRoot.test.tsx
packages/lexical/src/nodes/LexicalTextNode.ts
scripts/error-codes/codes.json

#4467 introduced an HTML import regression for trailing spaces. The root cause is that our exported HTML is not correct, the whitespaces should never be at the end or should be marked with the white-space property. This diff does the later which is equivalent to the top-most `white-space: pre-wrap`
It also fixes export for these other surfaces that implement whitespace parsing correctly (i.e. Apple Pages):
Before
https://github.com/facebook/lexical/assets/193447/9d5bb067-18f0-419b-b458-f29e84340fa8
After
https://github.com/facebook/lexical/assets/193447/4279c985-08b2-4020-8e7f-db0d204d96f0
Closes https://github.com/facebook/lexical/issues/4919
Closes https://github.com/facebook/lexical/issues/4954

Retain TextNode whitespace on export

---

packages/lexical-react/src/shared/useYjsCollaboration.tsx
packages/lexical-yjs/src/SyncEditorStates.ts

Addressing issue: https://github.com/facebook/lexical/issues/4828
Addressing issue: https://github.com/facebook/lexical/issues/4832
Dispatches `CAN_UNDO_COMMAND` & `CAN_REDO_COMMAND` in collaboration mode, mimicking the behaviour from the `HistoryPlugin`
Fixes up selection checking

fix: dispatching undo & redo states for collaboration; fixing up Point.getNode not a function

---

packages/lexical-utils/src/index.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts
packages/lexical/src/nodes/LexicalParagraphNode.ts
packages/lexical/src/nodes/LexicalTextNode.ts

Adding this dependency onto core adds another 6.9K to core unnecessarily. Since it's just a couple very lightweight functions I'm moving them into core for now while retaining the export onto @lexical/utils for backward compatibility.

Move isHTMLElement into core

---

packages/lexical-playground/src/plugins/CommentPlugin/index.css
packages/lexical-playground/src/plugins/CommentPlugin/index.tsx

Reproduction steps:
1. Open the lexical playground
2. Add more content so you can scroll down the page
3. Select some text after scrolling
4. Press the comment icon
Result:
Selection rect is not positioned correctly
Fix:
Take the scroll offset into account

Fix comment plugin selection rect top position

---

packages/lexical-react/flow/LexicalComposer.js.flow
packages/lexical-react/flow/LexicalNestedComposer.js.flow
packages/lexical-react/src/LexicalComposer.tsx
packages/lexical-react/src/LexicalNestedComposer.tsx
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/__tests__/utils/index.tsx
packages/lexical/src/index.ts

This should allow passing initialNodes to LexicalNestedComposer including node overrides (`replace` & `with`). It also exposes `LexicalNodeReplacement` type

Add nodes replacement support for nested composer

---

packages/lexical/flow/Lexical.js.flow
packages/lexical/src/nodes/LexicalTextNode.ts

Missing type for a format we already support/store

Add highlight to format types

---

packages/lexical-website/docs/concepts/serialization.md

Fixes #4987 
- Node overrides don't work if the key of the original node is passed to the replacement node
- Overriding `isSimpleText` is needed to replace the default `TextNode` with `ExtendedTextNode` without unexpectedly altering Lexical's behavior

Fix TextNode override in 'Serialization & Deserialization' doc

---

packages/lexical-html/src/index.ts
packages/lexical-react/flow/LexicalComposer.js.flow
packages/lexical-react/src/LexicalComposer.tsx
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/index.ts

With this change, I'm adding a new path for changing or extending html serialization functionality in the editor. Currently, if you want to change HTML serialization behavior on the core nodes, you generally need to override the node, which I think is an unnecessarily confusing process, given how common the use case is.

Allow overriding HTML serialization behavior from the editor config.

---

packages/lexical-link/src/index.ts

fix: LinkNode.importDOM should support all node content

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx
packages/lexical-react/src/shared/LexicalMenu.ts

If a handler was added as capturing, it must be removed as such too.

Fix event handler removal in useDynamicPositioning, remove dupe code

---

packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx

Just some nits, was faster than cloning & editing an existing very old PR

Nit: Floating toolbar

---

babel.config.js
package-lock.json
package.json
scripts/build.js

My understanding is that `"target": "ES2019",` should do the trick, but it doesn't.
This additional babel config does it but unsure why I need to import separately..
Closes https://github.com/facebook/lexical/issues/5037

Transpile optional catch binding

---

packages/lexical-playground/__tests__/e2e/MaxLength.spec.mjs
packages/lexical-selection/src/lexical-node.ts

Iteration on https://github.com/facebook/lexical/pull/5020 to handle any empty ElementNode anywhere on the content

MaxLength handle empty ElementNode

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

Hi Lexical team, I'm making some changes to the `LexicalTypeaheadMenuPlugin` such that when we're using the ContentEditable in an iframe but rendering the dropdown menu of the typeahead outside (iframe's parent), we'll still calculate the position of the dropdown menu correctly.

Allow LexicalTypeaheadMenuPlugin to work when inside an iframe

---

packages/lexical-playground/src/nodes/TableComponent.tsx
packages/lexical-playground/src/themes/PlaygroundEditorTheme.css

Though the feature is experimental, incase if you need a fix for this, kindly check out the PR. Please close them if its not necessary. 
https://github.com/facebook/lexical/issues/4857#issuecomment-1664242477
Before Fix:
https://github.com/facebook/lexical/assets/21175404/54834861-7d0f-4dec-8e06-bca5ff25db64
After Fix:
https://github.com/facebook/lexical/assets/21175404/d53c9548-12b6-4078-910b-8e8929b07975

fix : Add column shortcut gets hidden when mouse leave the table #4857

---

packages/lexical-playground/src/plugins/FloatingTextFormatToolbarPlugin/index.tsx
packages/lexical-playground/src/utils/setFloatingElemPosition.ts

fixes #5021 issue, format popup stays even after text is changed to valid link format

Fix/floating formatter #5021

---

packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

https://github.com/facebook/lexical/assets/30749436/80d97912-55e6-4a14-8df4-d192fe1fe802
This error was made in PR #4904, which caused an 'Uncaught TypeError: Cannot read properties of undefined (reading 'name')' error due to missing format types (start and end).
This PR will add start, end format options to alignment dropdown.

Fix: ToolbarPlugin paste error with start, end format

---

packages/lexical-playground/src/plugins/FloatingTextFormatToolbarPlugin/index.tsx

Improve the toolbar to format text and avoid hiding it unnecessarily
**Before**
https://github.com/facebook/lexical/assets/46543621/399604a8-b6ae-4a42-bf38-e8beba6cbca3
**After**
https://github.com/facebook/lexical/assets/46543621/d1297907-ec54-4ba1-b848-c4cae92af5b0

fix(playground-text-format-toolbar): don't hide toolbar if current node is a paragraph

---

packages/lexical-website/docusaurus.config.js

Summary:
This was never set up. It's easy enough and we should have some analytics.
Test Plan:
`npm run build` & diff before & after output. The only change was adding the gtag code.

Set up GA4 for website

---

packages/lexical-selection/src/range-selection.ts

Fixes https://github.com/facebook/lexical/issues/4491
**Note:** This PR focuses on a fix inside `$getSelectionStyleValueForProperty` and **not** on the RangeSelection style property (which I believe should be a long-term fix).
`style` property on the RangeSelection was implemented in https://github.com/facebook/lexical/pull/3863
however, it was not implemented for the case when selection is **not** collapsed
https://github.com/facebook/lexical/blob/c09ab7314fba32f0246a24df35c5d64061541978/packages/lexical/src/LexicalEvents.ts#L306-L350
Since `$getSelectionStyleValueForProperty` relies on this property, it does not return the correct value in cases when the selection is not collapsed.
This method is often used for reflecting current values on toolbars, but it does not work in half (range …

Fix getting style via $getSelectionStyleValueForProperty when selection is collapsed

---

packages/lexical/src/LexicalSelection.ts
packages/lexical/src/nodes/LexicalTabNode.ts

Composition on the entire node was hitting the "reuse" this same node part to render the new content (`firstNode.spliceText(startOffset, delCount, text, true);`). While it's a very optimal path that doesn't recreate the node and works well with composition tab node content should always strictly be `\n`. This PR forces it to recreate a new node, just like we do with token node, segmented, or other formatting edge cases.
This PR isn't ideal, the solution comes down to finding a generic solution for this issue: https://github.com/facebook/lexical/issues/5065
Chrome:
Works fairly well except that the cursor is not updated but it's a nit and doesn't affect functionality (the same functionality resembles if you select a range that includes plain text and bold) …

Fix tab replacement composition crash

---

packages/lexical-yjs/src/CollabDecoratorNode.ts
packages/lexical-yjs/src/CollabElementNode.ts
packages/lexical-yjs/src/CollabLineBreakNode.ts
packages/lexical-yjs/src/CollabTextNode.ts
packages/lexical-yjs/src/Utils.ts
packages/lexical-yjs/types.ts

Augment typedefs for yjs (collab nodes), and removed unused `_unobservers` member from the collab decorator node

chore: add typedefs for collab nodes and remove unused members

---

packages/lexical/src/LexicalSelection.ts
packages/lexical/src/__tests__/unit/LexicalSelection.test.ts

This is causing issues in the `PlainTextPlugin` prevent users from deleting line breaks within paragraph nodes. When the cursor is collapsed and on a `LineBreakNode` the selection is of type `element` which causes the condition to trigger, incrementing the offset even during a deletion. 
I think we can the original PR as it seems more like a browser bug if the base Selection offset isn't being increment for an empty node (e.g. a decorator node).
Before: 
https://github.com/facebook/lexical/assets/7748470/97778bdd-4445-4ff9-ba59-5d5de5c5bc30
After: 
https://github.com/facebook/lexical/assets/7748470/6a983d57-6bcb-4e6b-a9df-3eec6580c758

Revert Fix $transferStartingElementPointToTextPoint() #4756 

---

packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical/src/LexicalSelection.ts

`insertNodes` does too much... 
`insertNodes` is a function that's able to insert N amount of nodes and fixed the hierarchy *accordingly*.
In https://github.com/facebook/lexical/pull/1996/ we determined that insertNodes `[x, y, z]` where `y` is an ElementNode should never be merged into `z`. That makes sense, from a user PoV these are 3 separate nodes (an array) and you'd want them one next to the other.
However, when you `insertNodes` from a paste PoV, if your target is non-empty ElementNode you'd want to `insertBefore` the Element. For example, `insertNodes[$createLineBreakNode()]` with the aforementioned target should prepend it on the list of nodes.  
Where do we draw the line? ~~We don't, we reduce `insertNodes` responsibilities.~~ We can assume that the first node's target can be …

Fix insertNodes insert position at start of inline ElementNode

---

examples/decorators.md

> because it's docs only I hope it's fine I just open a PR against main 😬 
alternative is to name both payload I guess

docs: fix typo in decorators.md

---

packages/lexical-rich-text/src/index.ts

fix(lexical-rich-text): correct comment typo

---

packages/lexical/src/LexicalEvents.ts
packages/shared/src/environment.ts

**Context:**
When this [line](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalEvents.ts#L520) `editor.isComposing()` is evaluated, the value returned is always `false`, so the code within the `if` is not executed and continues to the `else`.
This causes deleting a character on an Android device to delete the character on the right.
I was testing a bit and giving a value to the `_compositionKey` property fixes it.
I don't know if it's the best solution, but this could help or be a guide.
**Issue:** https://github.com/facebook/lexical/issues/4340
**Evidence:** https://www.loom.com/share/24898783cffd4023bf85460966702898

fix: fix android backspace bug

---

packages/lexical-selection/src/lexical-node.ts

Setting styles using `$patchStyleText` does not update the selection when the anchor node is split. This causes the selection to contain a node that is not part of the selection. As a result, the toolbar/`$getSelectionStyleValueForProperty` is not able to determine the correct selection style.
https://github.com/facebook/lexical/assets/1575198/e438e605-4d4d-4c78-9967-e3176ed531f8
Update the selection anchor with the new text node after splitting.
https://github.com/facebook/lexical/assets/1575198/22c177ae-fd17-4b30-bb68-2adab21a9b78

Update anchor selection if split by patching style

---

packages/lexical-playground/src/plugins/TableCellResizer/index.tsx

Based on this [issue](https://github.com/facebook/lexical/issues/4415) with Tables current algorithm for resizing is out of shape for cases where cells are merged. What happens is it tries to map index from given active cell and make sure that it exists on each row, if not - throwing exception.
#4415 
I've updated TableCellResizer to acomodate that - now it claculates length of row based on children and their cell span. From this we are finding which column corresponds to given active cell, that now always should be less or equal to active cell. After this we are using this column to set width.
Test:
https://github.com/facebook/lexical/assets/5208565/b31e9159-4df7-40cb-a9bc-b7e4f2cb4344
E2E test - couldn't find a way to resize in unit/e2e test.

Updated cell calculation based on cellspans

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/src/LexicalTableUtils.ts

In #4660 we found an issue with $insertTableColumn function that used inital set for a table elements to insert new cells for column 1 by 1. In case you have selected 2+ columns we would insert first, and then for inserting second we would reference newly created cell that is not exist in given grid yet.
There are multiple ways to fix this issue, but batching actions into 1 array seems to be elegant enough.
| before | after |
https://github.com/facebook/lexical/assets/5208565/73083226-c074-46eb-a0eb-abdcade86a52 
https://github.com/facebook/lexical/assets/5208565/8abc7737-ac89-468c-bef7-06ad32aa0bce

Updated $insertTableColumn with batching

---

packages/lexical-react/src/LexicalAutoEmbedPlugin.tsx
packages/lexical-react/src/LexicalContextMenuPlugin.tsx
packages/lexical-react/src/LexicalNodeMenuPlugin.tsx
packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx
packages/lexical-react/src/shared/LexicalMenu.ts

Resolves #3714, which is a long-standing issue that multiple users seem to have faced. Previously, this repo has solved it by:
1. Setting all of the commands to `COMMAND_PRIORITY_NORMAL` (#2885)
2. Setting all of the commands to `COMMAND_PRIORITY_CRITICAL` (#3106)
3. Setting all of the commands to `COMMAND_PRIORITY_LOW` (#3441)
It is pretty clear that a more generic solution is needed. This PR adds a `commandPriority` prop to `LexicalMenu` and its dependent components, including:
- `LexicalTypeaheadMenuPlugin` (most often called out)
- `LexicalNodeMenuPlugin`
- `LexicalContextMenuPlugin`
- `LexicalAutoEmbedPlugin` (under `menuCommandPriority`, because this plugin registers an insertion command that should remain at `COMMAND_PRIORITY_EDITOR`)
Future changes should address:
1. Customising …

Add `commandPriority` option to `LexicalMenu` and dependent components

---

package-lock.json

Previously passed 368, now passes 370 - 375 tests (ran e2e tests twice). Unclear if changes may be in the normal error range of passing tests.

Updated package-lock.json versions with 'npm audit fix'.

---

packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/__tests__/utils/index.tsx

Functions like `insertParagraph` can generate a brand new selection. Hence, `insertNodes` needs to be restarted as the `this` no longer points to the valid selection.
I think this is only the case when this happens, I'm surprised there wasn't a test for this.

Fix insertNodes after selection swap

---

.gitignore

I frequently use --reporter=html to debug. Playwright puts the necessary files there and you have to remove them from stage.

Add playwright-report to gitignore

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical-code/src/CodeNode.ts
packages/lexical-playground/src/plugins/TableCellResizer/index.tsx
packages/lexical/src/LexicalSelection.ts

We can't use `at` until we transpile it. This is not the case now.

Fix at() transpilation

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-react/src/shared/LexicalMenu.ts

closes Facebook/lexical#5186
- positioning of the menu was done with a static margin
- menu could easily end up on top of text when using large fonts (20px+)
- positioning changed to be underneath the anchor element

Improved LexicalMenu positioning relative to text

---

packages/lexical-link/src/__tests__/unit/LexicalLinkNode.test.ts
packages/lexical-link/src/index.ts

ATM, the TOGGLE_LINK_COMMAND ignores the title in the payload. It's a one liner fix, but I wanted to ensure that it works as expected so an illustrative test is included. 
Thanks!

Link title is correctly applied through the command

---

packages/lexical-rich-text/src/index.ts

- The second parameter of `replace` had to be true, not `restoreSelection` which has nothing to do with it.
- I had to add a select, because otherwise when trying to paste a heading at the beginning of a heading an error would appear. This shouldn't be like this, maybe it's a bug in `replace`.
- Inserting a heading at the beginning of a heading does not combine them as part of the same block. I don't think it's the best behavior. I tried to fix it but `insertNodes` is still tremendously complex despite recent improvements.

fix Heading.insertNewAfter

---

packages/lexical-link/src/index.ts

I was investigating the use of `[x: string]: any;` in LexicalNode under the assumption that it would hide bugs and I found one.

Fix lexical-link typo s/_rel/__rel/

---

packages/lexical-text/src/index.ts

The typo "touple" has been changed to the correct spelling, "tuple"

Fix "touple" typo to make it correctly "tuple"

---

packages/lexical-playground/src/appSettings.ts

Small refactor to dry up some code. The `DEFAULT_SETTINGS` object implies the list of settings. There's no need to repeat the keys between the type definition and the defaults.

refactor(playground): dry settings

---

packages/lexical-list/src/LexicalListItemNode.ts

This pull request related to #5159
Lexical version:
V0.12.2
1. Click Bulleted List button
2. Type something
3. Click export DOM button, look at the DOM
4. Click on the text and then click Right Align button
5. Look at the DOM
Link to code example:
https://playground.lexical.dev/
The DOM do not change after click Right Align button
The right align style should be applied into the list item DOM

Bug: Align list item do not change the export DOM

---

README.md

This is broadly covered by https://lexical.dev/docs/concepts/nodes#creating-custom-nodes
Original file was deleted in https://github.com/facebook/lexical/pull/5121.
Closes #5190

Remove unnecessary link from README.md

---

packages/lexical-table/src/LexicalTableUtils.ts

In #4377 we have an issue when user cannot delete row if previous row is empty.
Simple fix in addressing issue - select cell of no descendant selected. I find it a bit weird why we couldn't do that in a first place, but leaving original logic in place to not break whole Lexical ;) 
https://github.com/facebook/lexical/assets/5208565/bfaf26f9-bbdf-4e80-b53b-ab1a89d53030

Select original cell if empty

---

packages/lexical/src/LexicalSelection.ts

closes https://github.com/facebook/lexical/issues/5144
- mutations to the end text node were too permissive
- splicing of text on removing an element (insert empty) should only impact text selections

Fixed delete removing link node text when on linebreak

---

.github/CODEOWNERS

I'm still reviewing PRs, but I want to prevent myself from constant GitHub pings.

Remove codeowners to prevent unnecessary pings

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx

in #4378 tables had an issue to make column headers in rows that had less cells than we wanted to highlight.
When we merge cells across rows and columns we are making single cell to most up/left cell that makes all other columns and rows be unaware of how many cells they actually have in a given row/column, as we checked against it - error was thrown.
To fix this issue I've moved check on min/max cell selected up from the loop - as it doesn't make sense to check it on each row, and if we have a row where we don't have needed column - we simply don't highlight it.
This is not the first problem like this in a codebase, for example similar issue was fixed here https://github.com/facebook/lexical/pull/5141
Considering that we had ~15 issues with tables here and there - I wouldn't say that …

Fixed column header on merged cells

---

packages/lexical-selection/src/utils.ts

Addresses #5270
Changes Made:
* Modified `getStyleObjectFromRawCSS` to validated key and value before calling `trim`

Fix: Resolve "Cannot read properties of undefined (reading 'trim')" issue in $getSelectionStyleValueForProperty

---

package-lock.json
packages/lexical-playground/package.json
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.tsx
packages/lexical-playground/vite.config.js
packages/lexical-playground/vite.prod.config.js

As per: https://github.com/excalidraw/excalidraw/releases/tag/v0.17.0 there are a few breaking changes in the Excalidraw API, for ViteJS and moving away from refs. Updating respectively so we can move to 0.17 and keep the dependency up to date.

Move to new Excalidraw APIs for 0.17 update

---

packages/lexical-react/src/LexicalNestedComposer.tsx

We were overriding the _nodes property for nested editors in LexicalNestedComposer, which meant that the HTML overrides weren't being passed through as expected.
I'm honestly not sure this conditional logic for copying over the nodes from the parent if initialNodes doesn't exist is correct - it seems like we'd want to check for any nodes already registered on the passed-in Editor instance before we just copy from the parent, but I'm not sure what other issues changing that may cause.
This adds support for copying over those overrides in either path. Note that to make this work for nested editors that specify different nodes than the parent, you need to define the initialNodes prop on LexicalNestedComposer.

Support HTML export overrides from config for nested editors.

---

packages/lexical-playground/src/plugins/CollapsiblePlugin/Collapsible.css

Nested collapsible sections' chevron do not rotate when its collapsible section is collapsed/uncollapsed.
Issue:
Fixed:

Fixing nested collapsible section chevron

---

packages/lexical/src/LexicalEvents.ts

Fix for issue: https://github.com/facebook/lexical/issues/5274

fix: backspace in Android not deleting first character

---

packages/lexical-react/src/LexicalClickableLinkPlugin.tsx

Even though URLs undergo sanitization when the Link Node generates the DOM, when someone clicks a link using the ClickableLinkPlugin, the link isn't sanitized.
This pull request resolves the issue by sanitizing the URL within the event handler.

URL sanitization ClickableLinkPlugin

---

packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical/src/LexicalSelection.ts

From Discord:
> there's 1 or 2 potential issues that we to iterate on asap or revert the commit and take a look at carefully.
> 
> This error has been reported multiple times among employees on clipboard paste before we reverted:
> 
> Cannot read properties of null (reading 'append')
> 
> Based on the trace this is pointing to:
> lastInsertedBlock.append(...insertedParagraph.getChildren());
> 
> Second and not yet sure if connected, when there's a new line at the end it crashes before the selection is lost (the line break node is removed before so we can't restore to it).
cc @zurfyx 
this replace https://github.com/facebook/lexical/pull/5324

Fix insertNodes bugs

---

packages/lexical/src/LexicalEvents.ts

resolve #5202 
change code to keep selection style when clicking editor which has empty content.
`before`
https://github.com/facebook/lexical/assets/78121870/c2198c28-e190-4efe-886c-03ed20e4be80
`after`
https://github.com/facebook/lexical/assets/78121870/01f0deb7-5b65-4e01-b77a-cdaf16a85bc1

keep selection style when clicking empty editor

---

packages/lexical/src/LexicalUtils.ts
packages/lexical/src/nodes/LexicalTextNode.ts
packages/lexical/src/nodes/__tests__/unit/LexicalTextNode.test.tsx

Closes https://github.com/facebook/lexical/issues/5303

Make subscript and superscript text formats mutually exclusive

---

packages/lexical-website/docs/concepts/serialization.md

Added the exportJSON function to solve the problem of errors when calling the `editor.getEditorState().toJSON()` method when using official documents.

docs: added exportJSON function to the ExtendedTextNode plugin code

---

packages/lexical-playground/src/index.css

When screen size gets smaller, dropdown text becomes invisible so, editor toolbar buttons stay visible.
But dropdown input element text become invincible too.
I fixed this problem by checking if it is a dropdown that isn't in editor and make it visible again.
BEFORE
---
AFTER
Chrome: 119.0.6045.200 
Windows: 22H2 OS Build 19045.3758

dropdown text visibility problem fixed for medium and smaller screens

---

packages/lexical-website/docs/concepts/nodes.md

I noticed the examples for CustomParagraph had incorrect types on constructor and few imports were also missing in [Nodes](https://lexical.dev/docs/concepts/nodes) page. Since those are copy paste sample, the examples should just work without any modification. Corrected the types and added the missing import in them.

docs: correct custom node examples

---

packages/lexical-list/src/utils.ts

Refactored findNearestListItemNode using $findMatchingParent for improved clarity and conciseness.
Refactor was based on TODO comment anchor in lexical-list/utils

 Refactored findNearestListItemNode using $findMatchingParent

---

packages/lexical/src/LexicalUtils.ts

https://github.com/facebook/lexical/pull/5363 parity for canInsertAfter (see the other PR and https://github.com/facebook/lexical/issues/5162 for more details). On the playground, hashtags can be written after so I switched it to `false` to test.
Before
https://github.com/facebook/lexical/assets/193447/9c00e7f5-5dd7-441f-a587-767124793c2f
After
https://github.com/facebook/lexical/assets/193447/73969e80-0eba-498e-bf6e-0073d33be1a8

canInsertTextAfter exception for composition

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/LinksHTMLCopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/regression/5251-paste-into-inline-element.spec.mjs
packages/lexical/src/LexicalSelection.ts

This restores the behavior that changed in #5002 particularly when
pasting into links and other inline elements.
Fixes facebook#5251.

Fix insertNodes when inserting into inline elements

---

packages/lexical-selection/src/lexical-node.ts

Code was using default of the current selection when it should be using the selection that is passed through

fix: adding missing argument for $sliceSelectedTextContent

---

packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

Inserting hyperlink through toolbar doesn't open floating editor in edit mode

---

packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts

There are same test codes here:
https://github.com/facebook/lexical/blob/9d247acc42998b4de3ed079069584ebde701640b/packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts#L160-L167

Remove duplicated test codes

---

packages/lexical/src/LexicalEvents.ts

fixes #5259
PR #5077 added a fix for the android backspace bug where pressing backspace delete two characters at once, by setting the `compositionKey` to `selection.anchor.key` when on Android. However, in cases where the `anchor.key` and `focus.key` are different, the `compositionKey` isn't cleared causing an issue where the selection wouldn't go away as described in #5259.

fix: Reset compositionKey when backspacing a selection on Android where anchor and focus keys are different

---

packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx

this fixes #5351
Here is a screen recording of the bug:
https://github.com/facebook/lexical/assets/2135071/bf5df3e1-d4c4-43a6-a119-4871062e84d4
Here is a screen recording after the fix:
https://github.com/facebook/lexical/assets/2135071/c2940716-468e-4827-8468-a641482dd27b

Bug: Editing a link and changing selection shows wrong link value

---

packages/lexical/src/nodes/LexicalTextNode.ts

Without this, using this parameter in a subclass leads to:
```
Property 'createDOM' in type 'MyTextNode' is not assignable to the same property in base type 'TextNode'.
Type '(config: EditorConfig, editor: LexicalEditor) => HTMLElement' is not assignable to type '(config: EditorConfig) => HTMLElement'.
Target signature provides too few arguments. Expected 2 or more, but got 1.ts(2416)
```
Or is it intentional and for some reason text nodes shouldn't use `editor` in `createDOM`?
I made it optional in order not to break existing `super.createDOM(config)` calls in subclasses.

Fix TextNode#createDOM types: allow editor parameter in subclasses

---

packages/lexical-playground/src/nodes/InlineImageComponent.tsx

`InlineImageComponent` makes two of floating link editor toolbar element and it's triggering some bugs.
before:
https://github.com/facebook/lexical/assets/40269597/f71da3f7-3d69-4eb8-99bb-81296ffc9587
after:
https://github.com/facebook/lexical/assets/40269597/2f5487bd-3a18-472f-8a36-6f6ded32478d

Fix floating link editor on inline image caption

---

packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx
packages/lexical/src/__tests__/unit/LexicalEditorState.test.ts
packages/lexical/src/__tests__/unit/LexicalListPlugin.test.tsx
packages/lexical/src/__tests__/unit/LexicalNode.test.ts
packages/lexical/src/__tests__/unit/LexicalNormalization.test.tsx
packages/lexical/src/__tests__/unit/LexicalUtils.test.ts
packages/lexical/src/__tests__/utils/index.tsx
packages/lexical/src/nodes/__tests__/unit/LexicalElementNode.test.tsx
packages/lexical/src/nodes/__tests__/unit/LexicalGC.test.tsx
packages/lexical/src/nodes/__tests__/unit/LexicalParagraphNode.test.ts
packages/lexical/src/nodes/__tests__/unit/LexicalRootNode.test.ts
packages/lexical/src/nodes/__tests__/unit/LexicalTabNode.test.tsx
packages/lexical/src/nodes/__tests__/unit/LexicalTextNode.test.tsx
tsconfig.json

~~I noticed the unit tests are excluded from typechecking. Tried including them and saw multiple issues. I fixed some of them and this might already be mergeable, but it's a bit too early to enable typechecking for the tests. 1153 errors in 34 files =)~~
Okay. Fixed only the tests in the `lexical` package and enabled typechecking for them. I'm not going to fix other packages in this PR.
Also noticed:
- Prettier needs to be updated to use newer TS features like `satisfies`
- ts-jest displays warnings about the TS version. Needs to be updated too or probably replaced with a faster transform like esbuild.

Fix typechecking issues in unit tests

---

.lintstagedrc.js
.prettierignore
packages/lexical-code/flow/LexicalCode.js.flow
packages/lexical-hashtag/flow/LexicalHashtag.js.flow
packages/lexical-link/flow/LexicalLink.js.flow
packages/lexical-list/flow/LexicalList.js.flow
packages/lexical-mark/flow/LexicalMark.js.flow
packages/lexical-overflow/flow/LexicalOverflow.js.flow
packages/lexical-react/flow/LexicalDecoratorBlockNode.js.flow
packages/lexical-react/flow/LexicalHorizontalRuleNode.js.flow
packages/lexical-rich-text/flow/LexicalRichText.js.flow
packages/lexical-table/flow/LexicalTable.js.flow
packages/lexical/flow/Lexical.js.flow

According to a recent Flow lint warning, `%checks` is going to be deprecated from Flow in favour of type guards: https://flow.org/en/docs/types/type-guards. 
This diff removes the use of `%checks` and migrates the Flow signatures to type guards instead.

Remove depecated usage of `%checks` from Flow types

---

packages/lexical/src/LexicalSelection.ts

This PR fixes the issue with the lexical editor crashing when we do a multi line backward selection and try to convert it to a codeblock.
Before:
After:

Fix multiline conversion to codeblock

---

packages/lexical/flow/Lexical.js.flow

These shouldn't be `mixed` by default, but should accept a generic to specify the actual return type.

Fix small issue with DecoratorNode type guards

---

packages/lexical-playground/src/plugins/LayoutPlugin/LayoutPlugin.tsx

The current update command for the columns layout is broken when going to a lower column count. The current method instead of deleting, actually appends and gets the node in an invalid state. This fixes the update operation, so when going from 3 columns to 2, it will delete the last column and preserve the content as is in the first 2.

Fix columns layout update command

---

packages/lexical-playground/src/plugins/CollapsiblePlugin/index.ts

At the moment there's a logic that when the collapsible section is the very last node, pressing ArrowDown will append a paragraph below to escape the section. This only worked when the section is expanded, since the logic only applied on exiting the content node of the container, but when the section was collapsed, you exit from the title node, so the logic didn't kick in. 
Extending the logic to check for either fixes the issue.
This was only an issue for the "Escape down", since "Escape up" is always going from the title, irrespective if expanded or collapsed.

Fix escape down for collapsible section when collapsed

---

packages/lexical-react/src/LexicalContextMenuPlugin.tsx
packages/lexical-react/src/LexicalNodeMenuPlugin.tsx
packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx
packages/lexical-react/src/shared/LexicalMenu.ts

When Lexical is embedded in other web apps mounting the menus on `document.body` can be problematic. This PR allows passing a parent element on which the menus are mounted.

Adding ability to mount LexicalMenus to arbitrary divs

---

packages/lexical-code/src/CodeHighlightNode.ts
packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs
packages/lexical-playground/src/images/icons/add-sign.svg
packages/lexical-playground/src/images/icons/minus-sign.svg
packages/lexical-playground/src/plugins/ToolbarPlugin/fontSize.css
packages/lexical-playground/src/plugins/ToolbarPlugin/fontSize.tsx
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-selection/src/lexical-node.ts
packages/lexical/src/nodes/LexicalTextNode.ts

This PR replaces the font size drop down with an font size entry component.  This will allow the user to add custom font sizes ranging from `8`to `72`. There are also increment and decrement buttons, which allow font size update relative to the current size.
For font sizes:
- 8-12: Step size is 1
- 12-20: Step size is 2
- 20-36: Step size is 4
- 36-72: Step size is 12
This PR also fixes the issue where the user can format the codeblock if the selection begins outside the codeblock. The issue is illustrated below:

Replace font size dropdown with font size entry component

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-selection/src/range-selection.ts

closes https://github.com/facebook/lexical/issues/5369
This is a result of the larger insertNodes changes in v0.12.3+.
Causal code:
https://github.com/facebook/lexical/pull/5002/files#diff-33353db27f56a5d74e7281df0a8a2fc223eef41e9dc2efc723a412560a0148c9R561-R563
`INTERNAL_$isBlock` is treating (non-inline) `DecoratorNode`s as block elements, causing `ElementNode` methods being called on decorator nodes that result in broken functionality.
While someone could extend the decorator node class to have the indent and format properties, they are generally not elements and should not be treated as such.

Fix `DecoratorNode`s being treated as block elements

---

packages/lexical-react/src/LexicalComposer.tsx

This change updates the TypeScript type of the `children` prop of the `LexicalComposer` component in `lexical-react`. This change is in line with typical React usage, and essentially widens the type of `children`, making this a non-breaking change.

Use correct prop type for children in LexicalComposer

---

packages/lexical-markdown/src/MarkdownExport.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts

Fixes #5319 
Fixes #4931
Currently we uses `replace` in `exportTextFormat`:
```ts
function exportTextFormat(...) {
// ...
return textContent.replace(frozenString, output);
}
```
The issue happens when `output` has `$&`, `$$`, .... 
It is because there are [special replacement sequences](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_the_replacement) beginning with `$`: 
A workaround for this: https://stackoverflow.com/questions/9423722/string-replace-weird-behavior-when-using-dollar-sign-as-replacement
before:
https://github.com/facebook/lexical/assets/40269597/698381e9-08b0-4f6f-ae00-ac7a94124b96
after:
https://github.com/facebook/lexical/assets/40269597/e4f2f79e-ae20-447a-b9c6-82af6499863f

Fix exportTextFormat to keep dollar sign

---

packages/lexical-website/docs/concepts/serialization.md

I think to align it with general Node best practices, from what I understand, I added `$isExtendedTextNode` & `$createExtendedTextNode`, which I think are really useful to have and helpful to newcomers.
Please just close if if's not a fit

docs(serialization): add node helpers to ExtendedTextNode example

---

packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx

Set all buttons in TableActionMenuPlugin to `type="button"` so that when the editor is placed within a CMS form, it does not automatically submit.

fix: set button type=button in TableActionMenuPlugin

---

packages/lexical-list/src/LexicalListNode.ts
packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/ListsHTMLCopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/List.spec.mjs
packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts
packages/lexical/src/LexicalEditor.ts

Right now there's no easy way to style the list element of a checklist specifically since it uses the same className as a `ul` and doesn't have something like a data attribute that could be used as a selector. This PR allows setting a className to a checklist specifically.

Allow setting className for checklist in theme

---

.github/workflows/test.yml

Node 16 has been deprecated since September 2023, bumping the NodeJS version the test suite is using

Bump Node to 18.18.0

---

packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs
packages/lexical/src/LexicalEvents.ts

Extending #5126 to exclude all empty text nodes as well as the resulting from the user's selection (which may not span the entire TextNode).

Combined selection format to ignore empty text nodes

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/regression/4661-insert-column-selection.spec.mjs
packages/lexical-table/src/LexicalTableUtils.ts

Currently, when a row/column is inserted the cells are added without the header styles. Further, removing the header style leaves the row/column with incorrect header styling. 
This PR fixes this issue by allowing row/column insertion with correct header styles.

Add row/column with correct header styles

---

packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx

This PR fixes #4202 as well as satisfies @zurfyx request in #4203 to have the AutoLinkNode be converted to a LinkNode once modified in the floating link editor toolbar.
I saw multiple closed PR's for this and it looked like it was still an issue no one was currently working on. 
Please let me know if there's anything I need to change, I know the conversion logic is kind of ugly.

Floating link editor for AutoLinkNode and conversion to LinkNode once modified.

---

packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts

Partially implements feature request #5333
Submit a pull request and waiting for the team's opinion.
By the way, do we have any bot that builds this commit online so that I can directly install this commit via npm? Need this one to access parent editor during `importJSON` for my own purpose.

feat: Expose getActiveEditor and getActiveEditorState

---

packages/lexical-website/docs/react/plugins.md

Fix a wrong component name in docs.

docs: correct react plugin name

---

packages/lexical-markdown/src/MarkdownImport.ts

fixes #5516
after:
https://github.com/facebook/lexical/assets/40269597/0e1e970f-f91f-499a-a33c-9ebb6a81979b

Allow an empty paragraph child on converting from markdown

---

packages/lexical-code/src/CodeNode.ts

On exporting, `CodeHighlightNode` and other many `ElementNode` have same class as on created. However, `CodeNode` skips to add class to it, so on the page that uses exported HTML, the CSS for theming `code` should be duplicated for `pre`. So I'm utilizing `htmlConfig` as a workaround for now. 
before:
I'm aware of `exportDOM` and `createDOM` of `CodeNode` return different semantic but still they could have same class.

Fix: add class to elements exported from CodeNode

---

packages/lexical-playground/src/nodes/ImageNode.tsx

I don't think we ever want to import a `file:///` as we will have no system permission.
On top of that, we should implement some UI that shows when an image can't be loaded (i.e. network connection, page down, etc.) https://github.com/facebook/lexical/issues/5564
Closes https://github.com/facebook/lexical/issues/5316 (thanks @mok419 for the research!)

Prevent file:/// img conversion

---

packages/lexical-website/docs/getting-started/react.md

Added missing `return null` and custom plugin rename.
The documentation aligns with the tutorial https://www.youtube.com/watch?v=qIqxvk2qcmo&t=1s.v=qIqxvk2qcmo&t=1s

Update react documentation

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx
packages/lexical-playground/src/nodes/ImageComponent.tsx
packages/lexical-playground/src/nodes/InlineImageComponent.tsx
packages/lexical-playground/src/nodes/PollComponent.tsx
packages/lexical-react/src/LexicalBlockWithAlignableContents.tsx
packages/lexical-react/src/LexicalHorizontalRuleNode.tsx

A couple of nodes didn't `return true` on backspace deletion, leading to deleting an extra node before them. I guess someone forgot the `return true` for one `onDelete` implementation in a node and then by virtue of copy-pasting the bug made its way to multiple nodes, most notably the 'Image', 'Horizontal Line' and 'Block With Alignable Contents'.
Fixes: [#5249](https://github.com/facebook/lexical/issues/5249) and I believe #3707 was referring to this behaviour as well

Fix Double Deletion on Backspace

---

packages/lexical-playground/__tests__/regression/5583-select-list-followed-by-element-node.spec.mjs
packages/lexical/src/LexicalNode.ts

Before:
https://github.com/facebook/lexical/assets/7893468/c42aefe5-9842-44db-b72c-9787a7a45766
After:
https://github.com/facebook/lexical/assets/7893468/8e295d84-ebf0-4fb4-952c-7377cb37c14c
Fixes: https://github.com/facebook/lexical/issues/5581

Fix list selection when first node followed by an element node

---

packages/lexical-playground/src/plugins/ToolbarPlugin/fontSize.css

This is how the playground looks **in Firefox**:
The little piece of CSS taken from [here](https://www.w3schools.com/howto/howto_css_hide_arrow_number.asp) fixes it to:

fix: hide Firefox's text size buttons

---

packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

This pull request is related to #5560.
In `packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx`, `iconRTL` for `right` ELEMENT_FORMAT_OPTIONS should be `right-align`.

Bug: Right Align in Toolbar for RTL direction shows Left Align Icon

---

packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical-list/src/LexicalListNode.ts
packages/lexical-list/src/formatList.ts

The algorithm used to update `ListItemNode` values was quadratic when called in a loop as it interrogated all previous siblings. Calculating all expected values from the `ListNode` ahead of time is simpler and much more performant.
Since a transform was already in place for `ListItemNode` it seemed reasonable to implement one for `ListNode` and consolidate all of the `updateChildrenListItemValue` usage there to avoid repeating the same list traversals for each item. This also lead the way to removing code from other places that attempted to renumber lists at each mutation where that might be necessary.
RE #5589

fix: Improve performance of updateChildrenListItemValue

---

packages/lexical-markdown/src/MarkdownShortcuts.ts

This PR fixes an issue where Markdown transformations could be triggered simultaneously in collaborative editors, leading to duplicated nodes.
https://github.com/facebook/lexical/assets/59686138/19c14981-27f5-4e72-b826-8cc72d27f12c
https://github.com/facebook/lexical/assets/59686138/8425d148-052b-47d0-844d-e688c426d51d

fix: disable markdown shortcuts for collaboration

---

packages/lexical-react/src/shared/LexicalMenu.ts

Reverting as the menu does not work correctly when the page is scrolled. If you scroll down the entire viewport, the menu doesn't even show.
https://github.com/facebook/lexical/assets/193447/018b9e18-5b0f-4b8b-9647-fc12e7850472
@ebads67 can you share more details on your use case and we can follow up in a separate PR?
This reverts commit 0ebb41307624af16cb2cdd48e9804ccb96edd32c.

Revert "Fixed position for lexical menu (#5602)"

---

packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Before:
[table-sequence-selection-before.webm](https://github.com/facebook/lexical/assets/88986106/09853d27-ab1d-4e54-bc36-1ae5d6ab1d28)
After: 
[table-sequence-selection-after.webm](https://github.com/facebook/lexical/assets/88986106/f2b6c445-87ba-4142-b92f-85d0ec0c2ab8)
Fixes #5616.

Fix shift+arrow down selection for tables in sequence.

---

packages/lexical-playground/__tests__/e2e/Hashtags.spec.mjs
packages/lexical-playground/__tests__/e2e/Headings/HeadingsTransformToHeadings.spec.mjs
packages/lexical-react/src/LexicalHashtagPlugin.ts

Fixes #5366
This prevents multiple hash chars on hashtag, which blocks transformation to heading.
before:
https://github.com/facebook/lexical/issues/5366#:~:text=The%20current%20behavior-,before,-%2Dheading%2D01.mov
after:
https://github.com/facebook/lexical/assets/40269597/d7804367-57fe-4188-b21c-8ea906f21921

Fix hashtag regex blocking transform to heading

---

packages/lexical-table/src/LexicalTableNode.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/nodes/LexicalElementNode.ts

Was meant to be since 0.10, the method was defined only on TableNode and unused anywhere else. Should be safe to remove, since nobody should be relying on this externally.

[0.14] Remove unused canExtractContents

---

package-lock.json
package.json
packages/lexical-playground/__tests__/utils/index.mjs

Since Node 14, 'uuid' is a NodeJS built-in from the 'crypto' package. Removing it as a direct dependency.
More here:
https://dev.to/pierre/you-should-ditch-uuid-node-has-you-covered-10i3

Move to native UUID

---

.flowconfig
jest.config.js
packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical-list/src/LexicalListNode.ts
packages/lexical-utils/src/__tests__/unit/LexicalElementHelpers.test.ts
packages/lexical-utils/src/index.ts
packages/lexical/src/LexicalReconciler.ts
packages/lexical/src/LexicalUtils.ts
packages/shared/src/normalizeClassNames.ts
tsconfig.json

When the class names from a theme were blank or contained multiple spaces there were edge cases in the existing implementation that was a naive `classNames.split(' ')`. I think this sort of issue is common for people applying tailwind classes and using extra spaces (or spaces other than `' '`) for readability.
I chose to put this in shared because the reconciler in the lexical package does class splitting. That package doesn't have any existing dependencies and I didn't think this needed to be in the public API. People should probably depend on something like clsx or rely on the `addClassNamesToElement` / `removeClassNamesFromElement` functions.

fix: unify class name splitting/filtering with normalizeClassNames

---

packages/lexical-playground/src/themes/PlaygroundEditorTheme.css

Before:
https://github.com/facebook/lexical/assets/7893468/6f3a3463-dbef-4109-9ccf-ddf84f51ff9b
After:
https://github.com/facebook/lexical/assets/7893468/c1b852bf-5877-447e-b73a-9c63c6e8fb74
This is a fix for https://github.com/facebook/lexical/issues/3999 technically.
Applying this on 'ul' level, I verified it behaves correctly in Safari as well.

Preserve bullet item indent on newline

---

examples/vanilla-js/README.md
examples/vanilla-js/index.html
examples/vanilla-js/package-lock.json
examples/vanilla-js/package.json
examples/vanilla-js/src/main.ts
examples/vanilla-js/src/prepopulatedRichText.ts
examples/vanilla-js/src/styles.css
examples/vanilla-js/src/vite-env.d.ts
examples/vanilla-js/tsconfig.json
packages/lexical-website/docs/getting-started/quick-start.md
packages/lexical-website/src/components/HomepageExamples/index.js

At this moment Vanilla JS documentation lacks complete example that user can simply "copy-paste" or fork and run locally within seconds. This is especially important considering that Lexical can't be bootstrapped with just a few lines of code, while playground example we have for React is quite overwhelming (especially for less experienced engineers).
Additionally this fixes #5671
Here the proposal is to utilize StackBlitz that allow to run dev environment locally in user browser. For example `react-router` also [uses it](https://github.com/remix-run/react-router/blob/main/examples/basic/README.md).
If this diff goes through - I'll do same minimalistic example for React.
Additionally I didn't create any tests for it intentionally for 2 reasons:
1. I don't want to spend extra time on tests …

docs: Interactive Vanilla JS example

---

packages/lexical-playground/__tests__/e2e/HorizontalRule.spec.mjs
packages/lexical-playground/__tests__/e2e/Images.spec.mjs
packages/lexical-playground/__tests__/e2e/Keywords.spec.mjs
packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs
packages/lexical-playground/__tests__/e2e/Tab.spec.mjs
packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs

Few root causes here:
1. Caused by special handling for Webkit in tests. Apparently now it's fine to remove it
2. Selection in Webkit still works somehow differently to other browsers but in tests that are not related to selection it's OK to remove this extra check as it brings not value but causes flakiness
3. CDP session is only available in Chromium

fix: Fix E2E tests in Safari (Webkit)

---

packages/lexical-website/docs/concepts/serialization.md

Fixes #5660 
Also, I think it might be reasonable to copy/adapt the [discrete update section of @DaniGuardiola's article](https://dio.la/article/lexical-state-updates#discrete-updates) into the docs. Applying `discrete: true` sounds like a common use case in a headless context.

docs: add a tip about discrete state update

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-rich-text/src/index.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

The added support allows text alignment across multiple cells simultaneously by selecting those cells. Fixes #5638.
Before:
[before-text-alignment.webm](https://github.com/facebook/lexical/assets/88986106/74ee321e-b55e-4834-aa7d-0bc9613055c9)
After:
[after-text-alignment.webm](https://github.com/facebook/lexical/assets/88986106/629324cb-4619-4b35-af7a-bb9c6a05a6ff)

Add support for grid selection in text alignment.

---

packages/lexical-website/docs/getting-started/react.md
packages/lexical-website/src/components/HomepageExamples/index.js

chore(docs): Changed stackblitz.com links to point at this repo

---

packages/lexical-table/src/LexicalTableCellNode.ts
packages/lexical-table/src/__tests__/unit/LexicalTableCellNode.test.ts
packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.ts
packages/lexical-table/src/__tests__/unit/LexicalTableRowNode.test.ts

Fixes https://github.com/facebook/lexical/issues/5662
When copy/pasting a table from external sources (google doc, google spreadshet, e.g.), an empty cell is created with no child node :
Return `after` callback in `convertTableCellNodeElement` to insert paragraph if the cell is empty :

fix(tables): Add missing paragraph node when copying empty cells from external resources

---

packages/lexical-playground/src/nodes/LayoutContainerNode.ts
packages/lexical/src/LexicalSelection.ts

Forward word deletion (Ctrl + Del on Windows) would destroy composite element nodes (tables, columns layout).
The logic to handle this was already implement inside Delete Character, so extracted it to helper and reused it inside Delete Word as well.
Before: 
https://github.com/facebook/lexical/assets/7893468/2419b44b-2b76-4256-b185-581c739dc8e3
https://github.com/facebook/lexical/assets/7893468/ebdace55-1fb3-447c-8c4b-cd8c5c488909
After:
https://github.com/facebook/lexical/assets/7893468/1e8ebefb-49ed-4e70-99c3-4e1454bf234c
https://github.com/facebook/lexical/assets/7893468/d9cf00f3-ec10-490d-97bb-2f5503968855

Fix forward word deletion destructing element nodes

---

packages/lexical-react/src/LexicalEditorRefPlugin.tsx

fixes #5700 
Currently, passing editorRef callback containing setState() throws an warning.
And using that state triggers endless update, which throws an error.
more details in #5700

Fix endless renders with editorRef callback

---

packages/lexical-list/src/formatList.ts
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

Partial fix for: #5698
When selection is NodeSelection, not a range one nodes like Image, Poll, etc. are not bulleted correctly.
Unbulleting doesn't work, but as the full proper fix will be quite involved - introducing a proper REMOVE_LIST_ITEM_COMMAND that unbulleting any node, just doing this part for the first half.
Review with hiding the whitespace, it's only 3-4 lines changes, but deindenting, makes it look as larger change.

Fix Bulleting a Node Selection

---

packages/lexical-table/src/LexicalTableRowNode.ts

Fixes: #5688
Interestingly, this we exported in DOM but not in JSON. Fixed.

Export table row height in JSON

---

packages/lexical/src/LexicalEvents.ts
packages/shared/src/environment.ts

Because `preventDefault` doesn't actually do anything on the `beforeinput` event on Chromium Android, `deleteContentBackward` will actually delete things twice, once by Lexical and once by the browser. This is the cause of issues like #4941 and #5538.
The issue with backspace deleting two characters at once was patched in #5077 by pretending to be in composition mode so that the else statement with the `DELETE_CHARACTER_COMMAND` line wouldn't be triggered. This patched the issue but in turn caused issues #5274 and #5259.
#5274 was fixed in #5282 by adding new logic to actually trigger the `DELETE_CHARACTER_COMMAND` if the current node had the length `<= 1`. #5259 was fixed in #5389 by resetting the compositionKey if the keys of the anchor and focus nodes is different.
The changes in this …

Fix deletion issues when using Chromium Android

---

packages/lexical/src/LexicalEvents.ts

Right now only a SELECTION_CHANGE_COMMAND is passed when the editor is in read-only mode. Which makes sense, since we don't want to allow copy, paste, etc when contenteditable doesn't have true 'readonly' mode. 
However, I stumbled upon a situation where this logic disabled the 'click' event not firing the CLICK_COMMAND at all when in read-only, which is needed if you want to have any interactivity even in read-only when a non-editing user needs to interact with the widget, eg open a popup on a double click to view something for example. So passing this event through irrespective of editor editability.
Before:
https://github.com/facebook/lexical/assets/7893468/92e832d1-6b61-4a93-a91d-3e866930ceb3
After:
https://github.com/facebook/lexical/assets/7893468/fe741a9c-9ba8-4923-ba75-3a09af6d1781 …

Send click event in read-only editor

---

packages/lexical-website/docs/react/plugins.md

Adding missing code snippets for ClearEditorPlugin and MarkdownShortcutPlugin in react plugin.md and fixing typo in same file

Add code snippets for ClearEditorPlugin and MarkdownShortcutPlugin

---

packages/lexical-react/src/LexicalCharacterLimitPlugin.tsx

Currently the UI for CharacterLimitPlugin is not customizable. And mimicking this plugin our own is not easy since `useCharacterLimit` is not exported. Is this my misunderstanding ? in any case, I believe this is still useful change.
Allowing to pass custom renderer, we can easily render own UI or do some state or effect manipulation depending remainingCharacters. (i.e. deactivating some actions ... )
For compatibility, I made existing JSX as DefaultRenderer.
The easiest and common use case with this:
https://github.com/facebook/lexical/assets/40269597/bd46c404-8724-47bf-9d9f-219088bc2b04
Edit: OR we just can convert `useCharacterLimit` to public API (as `useLexicalCharacterLimit` ?) to give some more flexibility what do you think ?

Update CharacterLimitPlugin to support custom renderer

---

packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts

fixes #5704 
Currently it considers a tab (`\t`) as same as one space to count a level of indentation.
So when user inputs one tab (`\t`) expecting one indentation in markdown, it might end up feeling incorrect.
Not sure it's intentional though ...
This PR fixes to count \t and space separately.
before:
https://github.com/facebook/lexical/assets/40269597/0abb42fe-cbdd-4da6-9b10-25dc90d5d870
after:
https://github.com/facebook/lexical/assets/40269597/944eb994-e9be-432b-b5e9-39e8cd12ccb5

Fix to count tabs as list indentation on importing markdown

---

packages/lexical-playground/__tests__/e2e/Hashtags.spec.mjs

Add test for multiple leading "#" characters in a hashtag

---

packages/lexical/src/LexicalEditor.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

I didn't add this check, only fixed it.

Fix: don't call importDOM methods more than once

---

scripts/build.js

Haste doesn't work well with ESM modules, especially minified prod builds.

Update build script to exclude WWW from ESM modules

---

packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

Fix clear formatting in table

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/nodes/StickyComponent.tsx
packages/lexical-playground/src/plugins/DraggableBlockPlugin/index.tsx
packages/lexical-playground/src/plugins/TableCellResizer/index.tsx
packages/lexical-playground/src/ui/ColorPicker.tsx
packages/lexical-playground/src/ui/ImageResizer.tsx
packages/lexical-react/src/LexicalCheckListPlugin.tsx
packages/lexical-react/src/LexicalContextMenuPlugin.tsx
packages/lexical-utils/src/index.ts

Css `zoom` property affects the mouse position in `event`s. However, functions like `getBoundingClientRect` do not care about the css `zoom`. Hence, the calculations that use mouse positions and `getBoundingClientRect` return wrong values. In this PR those calculations are fixed to return the correct value when css `zoom` property is used.
Css `zoom` has only been implemented in Nightly version of Firefox. So the fix does not apply to Firefox.
In all the examples below the css `zoom` property is set to 2 on the body of the document..
Issue with checklist interactions:
Issue with drag handle:
Issue with context menu:

Respect CSS zoom

---

packages/lexical-table/src/LexicalTableObserver.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/index.ts

Making it possible to select content beyond the table when starting the selection from inside of the table. In this case the whole table becomes selected similar to the case when selection starts from outside of the table and goes inside. Table selection is replaced with the Range selection
Before:
After:
Allowing to drag a selection from one table to the other without crashing
Fixes the following error:

Fix selection started from inside of the table

---

packages/lexical/src/LexicalUtils.ts

fixed #5761
https://github.com/facebook/lexical/assets/111737064/4d6f94da-a90a-4810-b79f-7e463e8101cb
This happens inside an ElementNode, like MarkNode or LinkNode, where `canInsertTextAfter` or `canInsertTextBefore` is set to false. If a part of the internal TextNode is formatted to split it, and text that includes composing is inputted at the boundary, the composition is released, and the text is inputted twice.
The bug arise when the `CONTROLLED_TEXT_INSERTION_COMMAND` is unnecessarily triggered, even when `isComposition` is true at the node boundary.
Despite the fact that text insertion into the Node is already being behind elsewhere during composing, the `selection.insertText` function called by the command cause a repeated input.
This leads to the text being doubly entered.
To …

fix: Double input of text including composing, such as Japanese, at TextNode Boundaries with in a MarkNode #5761

---

packages/lexical-playground/vite.config.ts
packages/lexical-playground/vite.prod.config.ts
packages/lexical-playground/viteCopyEsm.ts

The /esm/ build of the playground added in #5618 was reverted by the #5744 vite config refactor. This adds it back using the same strategy of a sibling module to avoid code duplication.

fix: restore playground esm build

---

packages/lexical-website/docs/getting-started/creating-plugin.md
packages/lexical-website/docs/getting-started/quick-start.md
packages/lexical-website/docs/getting-started/react.md
packages/lexical-website/src/components/HomepageExamples/index.js

The stackblitz iframe steals focus after it loads when not using ctl=1. It's a jarring experience when reading the documentation or browsing the homepage because this focus-stealing also scrolls the iframe into view and they're below the fold.
Also uses the main branch here rather than feature branches in other repos that might be deleted later, I suspect this was just missed after merging the vanilla-js-plugin example by @StyleT (#5717)
To notice the difference, try comparing the UX between some of the docs pages (wait a few seconds for stackblitz to load on the before examples):
* homepage [before](https://lexical.dev/) | [after](https://lexical-p4z3hdol5-fbopensource.vercel.app/)
* quickstart [before](https://lexical.dev/docs/getting-started/quick-start) | …

Update stackblitz iframes to use ctl=1 to prevent focus stealing

---

packages/lexical-playground/__tests__/e2e/ClearFormatting.spec.mjs
packages/lexical-playground/__tests__/e2e/ElementFormat.spec.mjs
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-yjs/src/SyncEditorStates.ts

General improvements to the reliability of collab tests
* Fix a few statements where promises were not returned or awaited (particularly in beforeEach)
* Moved the yjs top-level paragraph conflict logic outside of the selection recovery condition
* Used more of the playwright locator methods that retry automatically (may not be strictly necessary but it was part of my exploration)
* Wait for both frames to be connected to collab during initialization
* Clean up a few instances where await and async functions were used for no reason
* Use a bit more of the helper functions to clean things up

fix: Address more flaky collab tests

---

packages/lexical-playground/src/plugins/ContextMenuPlugin/index.tsx
packages/lexical-react/src/LexicalContextMenuPlugin.tsx
packages/lexical-react/src/shared/LexicalMenu.ts

Expose a 'onWillOpen' method that passes the 'contextmenu' mouse event, so users can do their logic what items should end up in the context menu before it's rendered. Have added an example for 'Link node', that appends an item to 'Remove Link' when a link node is right-clicked. Also fixed wrong positioning of the context menu when the page is scrolled.

Node-aware Context Menu Items

---

packages/lexical-react/src/LexicalNestedComposer.tsx
packages/lexical/src/index.ts

**Before**:
see #5646 
**After**:
https://github.com/facebook/lexical/assets/19604232/d48f4880-364e-446b-91e1-44f47b0f2d3c
---
reason for failure: nested editor does not set the transforms of the nodes when creating the editor. This lead to updateChildrenListItemValue, which increments the value of `<li>` (ie, `1.`, `2`. ...), to not be called for nested editors.
- this is a short term fix
- did not add list plugin or markdown plugin to caption nested editor to keep size small
- the long term fix is something like https://github.com/facebook/lexical/tree/nestedsomething

Quick fix for #5754: Numbered list does not increment in ImageNode caption #5754

---

packages/lexical-playground/src/plugins/AutoEmbedPlugin/index.tsx

**Before fix**: 
**After fix**:

fix: avoid auto-embed menu overflowing off right side of page

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

This PR addresses several issues related to table selection and navigation within the editor. The following changes have been made:
- Pressing the "arrow left" key to exit the first cell moves selection directly to the previous sibling node, if exists. Before, the selection is placed after the table and then at the new node. (Video 1)
- Pressing the "arrow right" key to exit the last cell moves selection directly to the next sibling node, if exists. Before, the selection is placed before the table and then at the new node. (Video 2)
- Pressing the"arrow left" key at the start of a paragraph under the table moves selection to the last cell of the table. (Fix #5627) (Video 3)
- Pressing the "Enter" key, when the cursor is before the table on the same line, moves selection to a new preceding …

Improve table selection and navigation

---

README.md
packages/lexical-website/docs/concepts/editor-state.md
packages/lexical-website/docs/getting-started/react.md
packages/lexical-website/docs/intro.md

Add some clarifying documentation to the introductory pages:
* [README.md](https://github.com/etrepum/lexical/blob/doc-updates/README.md)
* [Intro](https://lexical-git-fork-etrepum-doc-updates-fbopensource.vercel.app/docs/intro)
* [Editor State](https://lexical-git-fork-etrepum-doc-updates-fbopensource.vercel.app/docs/concepts/editor-state)

docs: clarify read/update language in intro, readme & editor state

---

packages/lexical-list/src/LexicalListNode.ts
packages/lexical-list/src/formatList.ts
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs

Fix for issue 4618
**Before**
see #4618
**After**
https://github.com/facebook/lexical/assets/19604232/7c44c505-38dd-441d-b3ca-bce273777ca2
^list of same types merged
^ lists of different types not merged

#4618 combine list if next sibling is list node

---

packages/lexical-table/src/LexicalTableObserver.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Starting selection in front of the table didn't trigger adding event listeners for mouseMove and mouseUp. Fixing this.
Before:
After:

Table selection stuck fix

---

packages/lexical-website/i18n/en/docusaurus-theme-classic/footer.json

The copyright object in footer.json was overriding the copyright value set in docusaurus.config.js, where the year is correctly utilized. The removed copyright object in footer.json also had the year 2022 hardcoded.

fix: removed overwrite of copyright

---

packages/lexical-playground/src/Editor.tsx
packages/lexical-react/src/LexicalClickableLinkPlugin.tsx

The ClickableLinkPlugin needed a small refactor, because in its current implementation it cannot disable the clickability of links in read-only mode. Moving the activeness state to a prop and that prop replacing the internal isEditable, allows for full control on links behaviour in either editor state.

Refactor ClickableLinkPlugin

---

packages/lexical-utils/src/index.ts

<details>
<summary>Exports all of the `IS_*` and `CAN_*` environment constants from @lexical/utils.</summary>
```typescript
export {CAN_USE_DOM} from 'shared/canUseDOM';
export {
CAN_USE_BEFORE_INPUT,
IS_ANDROID,
IS_ANDROID_CHROME,
IS_APPLE,
IS_APPLE_WEBKIT,
IS_CHROME,
IS_FIREFOX,
IS_IOS,
IS_SAFARI,
} from 'shared/environment';
```
</details>
While browser detection isn't really the purview of Lexical, these constants (or copy-pasted equivalents) are often necessary when implementing lower level features or just working around browser quirks. I found them useful to copy when I was working on a project that blended the code from lexical/plain-text and lexical/rich-text, which I found easier to understand and maintain by creating an independent "registerCustomText" rather than picking one …

feat: export 'IS_' and 'CAN_*' environment constants from @lexical/utils

---

packages/lexical-clipboard/package.json
packages/lexical-code/package.json
packages/lexical-dragon/package.json
packages/lexical-file/package.json
packages/lexical-hashtag/package.json
packages/lexical-headless/package.json
packages/lexical-history/package.json
packages/lexical-html/package.json
packages/lexical-link/package.json
packages/lexical-list/package.json
packages/lexical-mark/package.json
packages/lexical-markdown/package.json
packages/lexical-offset/package.json
packages/lexical-overflow/package.json
packages/lexical-plain-text/package.json
packages/lexical-react/package.json
packages/lexical-rich-text/package.json
packages/lexical-selection/package.json
packages/lexical-table/package.json
packages/lexical-text/package.json
packages/lexical-utils/package.json
packages/lexical-yjs/package.json
packages/lexical/package.json
scripts/updateVersion.js

Webpack (and SWC?) produce some truly inscrutable error messages when you provide it with ESM that uses top-level await. Unfortunately, it also prefers to load "node" condition code over "default". In order to support both node ESM imports and webpack at the same time we need to add a separate "webpack" condition at a higher priority than "node".
Related reading: https://webpack.js.org/guides/package-exports/#conditions-preprocessor-and-runtimes
🤦 
Fix #5823

fix: webpack needs its own export condition

---

packages/lexical/src/LexicalEvents.ts

Refactored in #5070, this is introducing some subtle bugs internally.
We should be using the updated `documentRootElementsCount` before deciding whether or not to remove the selectionchange listener, to make the logic consistent with the old implementation.

Use updated docRoot count in removeRootElementEvents

---

packages/lexical/src/LexicalEvents.ts

The latter check should actually be for '0'.

Fix issue with removeing selectionchange correctly

---

packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

This PR fixes an issue found in the Playground. When you select a portion of a selected text with the format applied, it could wrongly remove the format to another portion of the sentence with the same format applied.
Reference:
https://github.com/facebook/lexical/assets/105524386/5d5b3470-3b07-4495-b9df-dd70865a402d

Playground - Clear Format button fix

---

packages/lexical/src/nodes/LexicalTextNode.ts

Turns out that Google Spreadsheets can return bold text in `font-weight=bold` that we weren't handling yet.
```
<span
style="font-size:10pt;font-family:Arial;font-style:normal;">df </span><span
style="font-size:10pt;font-family:Arial;font-weight:bold;font-style:normal;">dasdf</span>
```

TextNode support font-weight bold

---

packages/lexical-playground/src/plugins/ContextMenuPlugin/index.tsx
packages/lexical-react/src/LexicalAutoEmbedPlugin.tsx
packages/lexical-react/src/LexicalTreeView.tsx

Intern isn't happy with async arrows, we should follow up with a lint rule like we did with coalescent.

Replace async arrow with function

---

packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs
packages/lexical-table/src/LexicalTableCellNode.ts

Before:
https://github.com/facebook/lexical/assets/163521239/5d32198b-aa6b-4fd0-9d3c-b6f03b0eaa6f
After:
https://github.com/facebook/lexical/assets/163521239/bbddae10-bef6-472d-9dc5-26ab34bee24c
closes #5663

Fix #5663 styling from td not persisted on copy paste

---

packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs

Running 10 tests using 1 worker
✓  1 [chromium] › packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs:1124:5 › CodeBlock › Code block html paste: VS Code (3.6s)
✓  2 [chromium] › packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs:1124:5 › CodeBlock › Code block html paste: Quip (1.4s)
✓  3 [chromium] › packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs:1124:5 › CodeBlock › Code block html paste: WebStorm / Idea (1.5s)
✓  4 [chromium] › packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs:1124:5 › CodeBlock › Code block html paste: Postman IDE (1.5s)
✓  5 [chromium] › packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs:1124:5 › CodeBlock › Code block html paste: Slack message (1.6s)
✓  6 [chromium] › …

fix test failing after rebase on bug fix for multiple text nodes styles in a cell node

---

packages/lexical/src/nodes/LexicalParagraphNode.ts

Before
https://github.com/facebook/lexical/assets/163521239/6e2ae748-acb1-4108-bbee-0f33560a7d04
After
https://github.com/facebook/lexical/assets/163521239/7bfee8e1-f2e7-4ba2-b4c1-4c11a3e6d8e9
closes #4468

fix #4468 Preserv elemement text align format on new paragraph creation

---

packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx

As discussed at https://github.com/facebook/lexical/pull/5551#issuecomment-2032416573
I suspect the lengthy original conditional was attempting to capture the definition of a bad node:
- if we have either a focusLinkNode or a linkNode, it must match the other
- if we have either a focusAutoLinkNode or an autoLinkNode, it must match the other
so I rewrote the logic to say that.

fix(playground): wrong logic for FloatingLinkEditorPlugin bad node

---

README.md

Fix nested typo in README

---

packages/lexical-website/docs/concepts/node-replacement.md

Styling for the example on [node-replacement](https://lexical.dev/docs/concepts/node-replacement) is broken.

Fix broken style for node overrides example on docs

---

.github/workflows/nightly-release.yml
.github/workflows/pre-release.yml
.github/workflows/size-limit.yml
.github/workflows/version.yml

- Bump to checkout@v4 and setup-node@v4, remove explicit node version specification, ie. take latest LTS by default (20 right now)
- Disable the nightly script, which was just creating a branch, but never actually published
- Add an extra 'npm install' after version bump in the package.json's in the versioning script, since currently, it creates an inconsistent package-lock.json and requires a manual run of 'npm install' for when 'npm ci' is run to be correct when tests kick off in the version PR.

Bump publish scripts to v4

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

This was introduced in https://github.com/facebook/lexical/pull/3213 but wasn't cleaned up after a proper fix.
Currently this does not allow the removal of empty lines in a collapsible section inside of a table.
Before:
After:

Remove a special case in table deleteTextHandler

---

packages/lexical/src/LexicalEditor.ts

We should avoid implicit `any` type because it may cause problems in the future.
Explicitly setup the type of the `replace` and `replaceWithKlass` when creating them.
before

fix(lexical/createEditor): avoid implicit any type

---

scripts/updateVersion.js

We need to update the devDeps during the release branch action for now. I suspect we can find an easier way to deal with this later. (i.e., should these even be dev dependencies?).
Without this, the devDependencies in the devtools (not core) package don't get bumped, which causes a mismatch between the package-lock and the dev dependencies, which causes npm ci to fail (I think).

Fix version script

---

examples/react-rich/src/plugins/ToolbarPlugin.tsx

Should this be with $ prefix ?

Add $ prefix to updateToolbar on react-rich example

---

packages/lexical-playground/src/plugins/ListMaxIndentLevelPlugin/index.ts

Minor refactors for better readability:
- `type Props` doesn't need to be this verbose. It might have been auto-generated (?) during a migration to TS.
- `shouldPreventIndent` without negation is even more intuitive than `!isIndentPermitted`.

Minor refactor on ListMaxIndentLevelPlugin

---

packages/lexical-playground/__tests__/e2e/Extensions.spec.mjs
packages/lexical/src/LexicalEvents.ts

Inserting text from Grammarly fails to save the state when a full-text node is selected in the forward direction (from start to end).
https://github.com/facebook/lexical/assets/1575198/bc336023-2447-4524-9dda-a60530667d64
Check the selection direction when comparing inserted content.
https://github.com/facebook/lexical/assets/1575198/74d15054-e6c4-4707-9209-8e9dc453b867

Fix inserting text from Grammarly when full node is selected with forward selection

---

packages/lexical-react/src/LexicalDecoratorBlockNode.ts
packages/lexical-rich-text/src/index.ts

Closes #5650.
Ensure no errors appear when trying to indent a block decorator node.

Fix bug with block decorator nodes erroring on indent

---

packages/lexical-table/src/LexicalTableCellNode.ts
packages/lexical/src/nodes/LexicalTextNode.ts

Currently pasting text content (eg, from gDocs) with both underline and strikethrough formatting loses both these formatting styles. This PR fixes that issue.
The `text-decoration` property's value can be a string that's a combination of different values like underline and line-through (eg: `text-decoration: underline line-through;`), hence modified the logic accordingly.

Maintain text decoration styles on paste

---

packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical/src/LexicalSelection.ts

Issue: selection of table by cursor dragging also selects the image after the table
Fix: resolve selection focus to the beginning of the paragraph with an image, not the root element with offset
Before:
After:

Fix selecting table selects an image after

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

This change prevents the table cell selection from changing on vertical arrow keys while a typeahead menu is open (Fix #5819). 
Before
https://www.loom.com/share/92e75e1299434e62838bd40449b77083?sid=a82a72d8-03ea-42b9-ba46-d2431be5a2d2
After
https://www.loom.com/share/53579c647ae84429be68b264a44a50bf?sid=f7e29571-dfe1-45f7-bb02-b7ac2d211f33

Preserve selection in tables with open typeahead menu on vertical arrow key press

---

packages/lexical-devtools/src/element-picker/element-overlay.ts
packages/lexical-devtools/src/element-picker/element-picker.ts
packages/lexical-devtools/src/element-picker/index.ts
packages/lexical-devtools/src/element-picker/utils.ts
packages/lexical-devtools/src/entrypoints/devtools-panel/App.tsx
packages/lexical-devtools/src/entrypoints/devtools-panel/components/EditorInspectorButton.tsx
packages/lexical-devtools/src/entrypoints/devtools-panel/components/EditorsList.tsx
packages/lexical-devtools/src/entrypoints/injected/InjectedPegasusService.ts
packages/lexical-devtools/src/entrypoints/injected/utils/queryLexicalNodes.ts
packages/lexical-devtools/src/public/inspect.svg
packages/lexical-devtools/src/store.ts
packages/lexical-devtools/src/utils/isLexicalNode.ts

This adds interactive editor picker for Lexical extension
Most of the changes are coming from this library fork https://github.com/hmarr/pick-dom-element (as it was lacking a feature proposed in https://github.com/hmarr/pick-dom-element/pull/6)
https://github.com/facebook/lexical/assets/1125900/097f9c9d-ac0d-44b1-b88b-23da29674636

feat(@lexical/devtools): Added interactive editor picker

---

packages/lexical-markdown/src/MarkdownImport.ts
packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts

When triple backtick bloc code is prefix with tabs or spaces, the parser does not recognize text as a block code.
Not parsed:
```markdown
\```typescript
const a = 'hello';
\```
```
A concret use case, is when code block is under a list.
Example of markdown string to be loaded to lexical:
```
1. First step
\```bash
echo "hello"
\```
2. Second step
\```bash
echo "world"
\```
```
**Note:** `\` is only there to escape code block rendering. The real use case does not have the `\`
Change CODE Transformer & MarkdownImport regex to accept tabs or spaces in prefix.

fix: markdown import code block with prefix

---

packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleContainerNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleContentNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/index.ts
packages/lexical-react/src/LexicalClickableLinkPlugin.tsx

Collapsible Section Fixes

---

packages/lexical-devtools/src/entrypoints/background/ActionIconWatchdog.ts
packages/lexical-devtools/src/entrypoints/devtools-panel/App.tsx

Changes:
- [fix(@lexical/devtools): Fixed handling of the restricted pages in Edge](https://github.com/facebook/lexical/commit/f18c87665db35c93a7bf6448afbf3dc9270855f8)
- [fix(@lexical/devtools): Fixed handling of the restricted pages within devtools panel in Firefox](https://github.com/facebook/lexical/commit/afdcceea15bed2d20a8539e039875c0131237859)

fix(@lexical/devtools): Fix of the edge cases with restricted pages in Edge/FF

---

packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs
packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/TablesHTMLCopyAndPaste.spec.mjs
packages/lexical-table/src/LexicalTableCellNode.ts

This PR fixes pasting tables that have the copied html in such format:
```
...
<td>
<span> ... </span>
</td>
...
```
Pasting this results in the following node structure:
which causes the editor to freeze and eventually crash on enter key press, as the text node is not wrapped in a paragraph node.
This issue is similar to the one described [here](https://github.com/facebook/lexical/pull/5670#issuecomment-1978455980) and was fixed for the case when pasting empty cells.
This PR addresses the case when on paste the children of the `TableCell` node are not within a block element node. 
Another case to reproduce this issue is when we copy something with such html:
```
...
<td>
<a> ... </a>
</td>
...
```
This results in a link node inside a tablecell node which again crashes on enter key press. …

Fix TableCell child nodes on paste

---

packages/lexical-playground/src/plugins/TableCellResizer/index.tsx

Disabling table resizer when mouse button is pressed, instead of when the selection is of type `TableSelection`.
This makes ui slightly better in some cases:
1. Cursor doesn't change when starting the table selection
2. Cursor doesn't change when during range selection the cursor is over the table

Refactor table resizer rendering logic

---

packages/lexical-react/src/shared/LexicalMenu.ts

issue https://github.com/facebook/lexical/issues/5740 
Originally, the check doesn't consider the resolution height, but the resolution height is being used below to determine the style.top. This causes the element to overlap with the parent box, and in turn causes the menu to close onScroll, because of the check [here](https://github.com/facebook/lexical/blob/6e4f072ea194e7d3e631e488ad1ca1be79add50e/packages/lexical-react/src/shared/LexicalMenu.ts#L225).
Add the height check to the RHS of the > , so the menu won't be placed on the top if it cannot fit.
Taking a step back, I'm not sure why when the menu is placed on top of the cursor, it's `height` length away from the cursor, whereas when the menu is placed below the cursor, it's 0 length away from the cursor. In other words, we could …

Fix check for menu cannot fit on top

---

packages/lexical-devtools/src/components/EditorsRefreshCTA.tsx
packages/lexical-devtools/src/entrypoints/devtools-panel/App.tsx
packages/lexical-devtools/src/entrypoints/devtools-panel/components/EditorsList.tsx
packages/lexical-devtools/src/entrypoints/popup/App.tsx
packages/lexical-devtools/wxt.config.ts

Detailed changelog:
- Fixed work of the extension in Edge by adding "tabs" permission
- Now header within devtools tab is fixed to simplify work with many editors
- On interactive editor selection we now scroll to the respective state
https://github.com/facebook/lexical/assets/1125900/febb0f41-463e-4b80-b779-4a7fc5e94f82

fix(@lexical/devtools): Fixed permissions for Edge and improved devtools tab layout

---

.github/workflows/devtools-extension-publish.yml
packages/lexical-devtools/wxt.config.ts

Successful publish: https://github.com/facebook/lexical/actions/runs/8855583209/job/24320653231

fix(@lexical/devtools): Fixed publish pipeline

---

.github/pull_request_template.md

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

Documentation: add PR template

---

packages/lexical-react/src/__tests__/unit/LexicalComposer.test.tsx
packages/lexical-react/src/__tests__/unit/PlainRichTextPlugin.test.tsx
packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
packages/lexical-table/src/__tests__/unit/LexicalTableSelection.test.tsx
packages/lexical-utils/src/__tests__/unit/LexicalEventHelpers.test.tsx
packages/lexical/src/__tests__/unit/LexicalListPlugin.test.tsx

refactor: cleanup unused react imports in tests files

---

packages/lexical-playground/src/plugins/TableCellResizer/index.tsx

Skip auto-scrolling on table row or column resize.
scrolls back to cursor
no auto-scroll

[lexical-playground] Bug Fix: skip auto-scrolling on table resize

---

packages/lexical-devtools-core/src/generateContent.ts

[TreeView][Minor enhancement]
Add option to obfuscate the text to be used for Logging tree view for debugging

[TreeView] Minor enhancement: Add option to obfuscate text in the TreeView plugin

---

scripts/www/rewriteImports.js

rewriteImports regression caused some flow modules not to get rewritten. Working theory is that the in-place update only had an effect if a module was also rewritten, and some modules do not have dependencies (such as packages/lexical/dist/Lexical.js.flow)
build-www outputs some flow modules in dist without rewriting their comments
build-www outputs all flow modules in dist with rewritten comments

fix(build): fix build-www rewriteImports to always rewrite flow modules

---

packages/lexical-react/src/LexicalTableOfContents.tsx
packages/lexical-utils/src/index.ts

Fixes following issues with table of contents:
- The order in table of contents is wrong for heading inside tables and collapsible sections.
- The heading is duplicated when resizing parent table cell
Now on each heading update dfs is used to get all headings and create a new TOC from scratch. It might take more time, but the change shouldn't be noticeable
Before:
After:

Fix table of contents for headings in tables and collapsible sections

---

packages/lexical/src/LexicalEvents.ts

Element precendence https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence
Additive > logical or
For reference, the second time
```
> 1 || 0 + 1
1
```

Fix add root element count

---

scripts/www/__tests__/unit/transformFlowFileContents.test.js
scripts/www/rewriteImports.js
scripts/www/transformFlowFileContents.js

Follow-up to #5995, while this fix worked it was not as clean as it should be and probably shouldn't pass flow type checks if it was analyzed. I did a little more digging and I found a more correct incantation, but it could probably still use some improvement if there is a hermes-transform expert around.
node ./scripts/www/rewriteImports.js rewrites flow files correctly (using sketchy code)
node ./scripts/www/rewriteImports.js rewrites flow files correctly (using slightly better code)

fix(build): clean up of build-www rewriteImports (follow-up to #5995)

---

packages/lexical-utils/src/__tests__/unit/LexicalNodeHelpers.test.ts
packages/lexical-utils/src/index.ts

Fix: #5976 Passing an empty ParagraphNode to $dfs incorrectly returns content from subsequent paragraphs

---

packages/lexical-website/docs/concepts/node-replacement.md
packages/lexical-website/docs/getting-started/creating-plugin.md
packages/lexical-website/docs/getting-started/quick-start.md
packages/lexical-website/docs/getting-started/react.md
packages/lexical-website/src/components/HomepageExamples/index.js

When playing with the examples on the website, clicking the "Fork on StackBlitz" button previously opened a blocked popup. With this sandbox flag, the popup loads without being blocked by cross-origin-opener-policy. Can reproduce with Chrome, Firefox and Safari on mac.
* Start an example from [the homepage](https://lexical.dev/) by clicking "Run Project" and then "Fork on StackBlitz"
* The pop-up will be blocked
* Start an example from [the preview site](https://lexical-git-fork-etrepum-fix-stackblitz-all-bba80e-fbopensource.vercel.app/) by clicking "Run Project" and then "Fork on StackBlitz"
* The pop-up will not be blocked

[lexical-website] Bug Fix: add allow-popups-to-escape-sandbox to iframe sandbox flags

---

packages/lexical-code/src/__tests__/unit/LexicalCodeNode.test.ts
packages/lexical-headless/src/__tests__/unit/LexicalHeadlessEditor.test.ts
packages/lexical-history/src/__tests__/unit/LexicalHistory.test.tsx
packages/lexical-list/src/__tests__/unit/LexicalListItemNode.test.ts
packages/lexical-list/src/__tests__/unit/LexicalListNode.test.ts
packages/lexical-react/src/__tests__/unit/Collaboration.test.ts
packages/lexical-react/src/__tests__/unit/CollaborationWithCollisions.test.ts
packages/lexical-react/src/__tests__/unit/LexicalComposer.test.tsx
packages/lexical-react/src/__tests__/unit/PlainRichTextPlugin.test.tsx
packages/lexical-react/src/__tests__/unit/useLexicalCharacterLimit.test.ts
packages/lexical-react/src/__tests__/unit/useLexicalIsTextContentEmpty.test.tsx
packages/lexical-react/src/__tests__/unit/utils.tsx
packages/lexical-rich-text/src/__tests__/unit/LexicalHeadingNode.test.ts
packages/lexical-rich-text/src/__tests__/unit/LexicalQuoteNode.test.ts
packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical-selection/src/__tests__/utils/index.ts
packages/lexical-table/src/__tests__/unit/LexicalTableSelection.test.tsx
packages/lexical-utils/src/__tests__/unit/LexicalEventHelpers.test.tsx
packages/lexical-utils/src/__tests__/unit/LexicalNodeHelpers.test.ts
packages/lexical-utils/src/__tests__/unit/LexicalUtilsSplitNode.test.tsx
packages/lexical-utils/src/__tests__/unit/LexlcaiUtilsInsertNodeToNearestRoot.test.tsx
packages/lexical-website/docs/faq.md
tsconfig.json
tsconfig.test.json

Mostly just adding non-null assertions and adding types where inference fails. I did refactor a few list reduces that do a concat (which is also quadratic time) to use flatMap which is easier for TypeScript to infer.
I added some docs to the FAQ relevant to reconciliation and how the tests are written https://lexical-git-fork-etrepum-fix-test-types-fbopensource.vercel.app/docs/faq#when-does-reconciliation-happen

fix: allow tsc to typecheck tests, fix type issues in those tests

---

packages/lexical-utils/src/__tests__/unit/LexicalNodeHelpers.test.ts

PR #5977 adds code which fails `npm run ci-check`, due to typing issues
fix the typing issues so `npm run ci-check` passes and integrity test will pass again on main branch
**Closes:** #nothing, fix integrity test
https://github.com/facebook/lexical/actions/runs/8933219843/job/24538272365
on local:
waiting for workflow integrity test to pass

[lexical-utils] ci: fix typing to fix integrity test

---

package.json
packages/lexical-playground/package.json

`npm run dev` (and associated `npm run start`) used to start on port 3000, which was the old vite default. The default changed to 5173, but no reason we can't keep the previous behavior https://github.com/facebook/lexical/pull/6018#pullrequestreview-2039349437
`npm run dev` listens on port 5173 (after #6018 was merged)
* `npm run dev` listens on port 3000
* tests and other commands that also specify a port still get the desired choice

[playground] Bug Fix: change default dev port to 3000

---

.github/workflows/devtools-extension-publish.yml
.github/workflows/e2e-test.yml
.github/workflows/nightly-release.yml
.github/workflows/pre-release.yml
.github/workflows/test.yml
.github/workflows/version.yml
.size-limit.js
packages/lexical-devtools/wxt.config.ts

We have a lot of test workflow. The workflows could get in various states where the cache was poisoned. 
The cache correctness related changes:
* Use the actions/setup-node@v4 `cache: npm` option which also considers the node version, and should in theory do the right thing (the actions/cache docs recommend to [not cache node_modules](https://github.com/actions/cache/blob/main/examples.md#node---npm) as we were doing)
* Use `npm ci`. Maybe a little slower than caching node_modules, takes about 30s, but the global artifacts should be cached and we have a postinstall action to run for wxt with the lexical-devtools package which was the cause of some of the problems.
* Move playwright caching to its own step which a cache key that includes all the things
* Add a reusable e2e-test workflow to …

[CI] Refactor: clean up github workflows for cache correctness

---

packages/lexical-react/src/shared/useCharacterLimit.ts
packages/lexical/src/LexicalUtils.ts

So I was just minding my business adding this plugin https://github.com/facebook/lexical/pull/6025 when I found one bug leading to another... I won't fix this one now but at least I'm providing a workaround here and a tracking issue.
The root cause here appears to be element selection, which needs to be recomputed when nodes are removed and currently neither `insertBefore` nor `removeFromParent` do it. #6031

CharacterLimit prefer replace over insertBefore

---

packages/lexical/src/LexicalSelection.ts

Browser can throw this at points, but on a development setup, this error is likely a result from our reconciliation logic. Having it showing on console certainly makes development easier.

Dev warning for failed DOM selection

---

.github/workflows/e2e-test.yml
package-lock.json
package.json

I misinterpreted the scope of the breaking change in actions/upload-artifact@v4 in #6029 - looks like we do need to change the name to include the matrix.
If a build has more than one e2e test job that fails, uploading the artifacts for that job will fail
All e2e failure artifacts should be uploaded

[build] Bug Fix: ensure unique artifact name for e2e tests

---

packages/lexical-devtools-core/flow/LexicalDevtoolsCore.js.flow

Add flow declaration in LexicalDevtoolsCore.js.flow

Add flow declarations in LexicalDevtoolsCore.js.flow

---

packages/lexical-plain-text/src/index.ts

Adds the same escape key handler to the plain text package as exists in lexical/richtext.
**Closes:** #5922
In the plaintext playground, pressing `Esc` doesn't blur the editor.
https://github.com/facebook/lexical/assets/55211974/a34cdd6e-d0a4-483e-ae46-f80759b39340
In the plaintext playground, pressing `Esc` blurs the editor.
https://github.com/facebook/lexical/assets/55211974/3a219753-03c5-4c92-9eeb-d44ce421d112

[lexical-plaintext] Feature: add escape key handler

---

packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-selection/src/range-selection.ts

This PR fixes the issue with font size not updating with the +/- buttons when there's a table selection with the cells having text with the same font size.
The `$getSelectionStyleValueForProperty` method was not returning the correct updated font size for table selection hence the size updates didn't apply correctly.

Fix font size update in table selection

---

packages/lexical-playground/__tests__/e2e/Hashtags.spec.mjs
packages/lexical-text/src/registerLexicalTextEntity.ts

- while transforming the hashtag text entity, 
- if we are skipping a text entity we are not adding the skip length to the next hash tag entity found in the transform logic for the text entity resulting into wrong split and infinite loop
- Fix to add the previous match length to the next match start and end offset before splitting the text node for the next match 
Closes #5703 and #3468 as well
https://github.com/facebook/lexical/assets/163521239/3482f35c-5f71-4142-b746-79486aa21f3b
https://github.com/facebook/lexical/assets/163521239/56130eb3-3cc9-4905-bc0e-6be4922bc630

Fix #5703 Infinite loop on hashtag transform

---

packages/lexical-playground/__tests__/e2e/Hashtags.spec.mjs
packages/lexical-text/src/registerLexicalTextEntity.ts

`prevMatchLengthToSkip` is introduced in #6045 to handle invalid previous match.
So I believe we should let `prevMatchLengthToSkip` do its job instead of early returning `$textNodeTransform` when the next match is followed.
https://github.com/facebook/lexical/assets/40269597/f5f4637d-4d29-4a23-a294-017f61b5e531
https://github.com/facebook/lexical/assets/40269597/faa609ab-aa7e-4492-bbdf-d0b600c46e8a

[lexical-playground][lexical-text] Bug Fix: handling hashtag following multiple invalid matches

---

packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Prevents table selection from being stuck.
The problem is wrong order of handling the mouse events. `mouseup` can happen before `mousedown` handler added a handler for  `mouseup`. This leaves the editor in a state of selecting. 
This PR adds clean up logic into `mousemove` to prevent selection being stuck
The modification of `dragMouse` is required for tests to pass, as it seems that this bug contributed to the successful execution of some test

[lexical-table][lexical-playground] Bug Fix: Table selection stuck 

---

packages/lexical-markdown/flow/LexicalMarkdown.js.flow

Update outdated flow file for LexicalMarkdown
add the missing  "node" param at the end of $convertFromMarkdownString and $convertToMarkdownString functions

[Lexical] Update outdated flow file for LexicalMarkdown

---

packages/lexical-playground/__tests__/e2e/AutoLinks.spec.mjs
packages/lexical-react/src/LexicalAutoLinkPlugin.ts

This PR fixes the issue with autolink nodes not having the same styles as the original text node.

Fix autolink styles on creation

---

packages/lexical-text/src/registerLexicalTextEntity.ts

- followup on #6053 #6056 
https://github.com/facebook/lexical/assets/163521239/e308dbce-1a40-4b43-93eb-661b8cb5afce

[Leixcal][Hashtag]  Fix prevSibling not getting updated after replacement of match as followup #6053

---

packages/lexical-html/src/index.ts
packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/LinksHTMLCopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/TablesHTMLCopyAndPaste.spec.mjs
packages/lexical-table/src/LexicalTableCellNode.ts

As discussed in the comments for #5951, reverting the changes to the TableCellNode importDOM as now we have a generic solution available through #5857.
Also, made additional changes in the `wrapContinuousInlines()` to correctly set the alignment as reverting the changes led to incorrect alignment within the table cells.

Revert importDOM changes from #5951

---

packages/lexical-playground/src/plugins/TestRecorderPlugin/index.tsx
packages/lexical-playground/src/plugins/TypingPerfPlugin/index.ts
packages/lexical-selection/src/__tests__/utils/index.ts
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalUtils.ts

Replace .keyCode with .code to follow new MDN API
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#browser_compatibility
**Closes:** #6051

Fix #6051 Deprecate keycode to code

---

packages/lexical-playground/__tests__/e2e/Hashtags.spec.mjs
packages/lexical-text/src/registerLexicalTextEntity.ts
scripts/error-codes/codes.json

~~#6053 deleted escape on adjacent next matches. but it turns out it was needed in different place (probably after replacement for current match has done ?)~~
~~without it, editor breaks on pasting or importing text that has adjacent matches.~~
=> #6067
And `nodeToReplace` can be `undefined` implicitly. Now it's the case. So I added null check for it. 
This could occur in other places especially around `TextNode.splitText()` unless we use `--noUncheckedIndexedAccess`.
https://github.com/facebook/lexical/assets/40269597/4f5b1756-a80a-428a-a919-b6075c754c9d
https://github.com/facebook/lexical/assets/40269597/362b301d-1793-4e4d-9903-cb634c08964e
https://github.com/facebook/lexical/assets/40269597/8763cd71-60f9-4d05-a490-050ec6cbdec1 …

[lexical-text] Bug Fix: for handling multiple matches on hashtags

---

packages/lexical-playground/__tests__/e2e/Collaboration.spec.mjs
packages/lexical-yjs/src/SyncEditorStates.ts
packages/lexical-yjs/src/Utils.ts

**Closes:** #6010, #4846
The current logic uses previous selection for calculating new cursor position, which does not work correctly, if the last action includes adding new text.

[lexical-yjs] Bug fix: Fix cursor position after undo in collab mode

---

packages/lexical/src/nodes/LexicalTextNode.ts

Currently, when importing textNode from outside sources (or read-only mode), `convertTextFormatElement` function is utilized for `i`, `em`, `strong`, ... 
However, this doesn't reflect their textFormat by style attributes unlike the handling of `span` in `convertSpanElement`.
So this PR extracts some logic from `convertSpanElement` and applies it to `convertTextFormatElement`.
https://github.com/facebook/lexical/assets/40269597/e389e072-a5f1-4731-82b2-1dd9ba9f60dd
https://github.com/facebook/lexical/assets/40269597/4ab55ca5-75a9-4ad0-8230-f5994b2af59c

[lexical][TextNode] Feature: improve supporting multiple format on importDOM of TextNode

---

jest.config.js
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx
packages/lexical/src/__tests__/unit/LexicalNode.test.ts
packages/shared/src/__mocks__/invariant.ts

Based on issues that several people have run into, it seems useful to add some additional invariant checking around node keys.
See also: [discord message](https://discord.com/channels/953974421008293909/953974421486436393/1235675644726083745)
- Adds a stub implementation of shared/invariant for use under jest to make development easier
- Adds a `__DEV__` check to make sure that if a new Node is created with an explicit existing key, that the type of the node did not change
Bad things will silently happen if you accidentally re-use node keys, such as with a subtly incorrect node replacement function:
```js
const config = {
// ...
nodes: [
EdifactTextNode,
{
replace: TextNode,
with: (node) => {
return new EdifactTextNode(node.text, node.__key)
},
},
],
}
```
An error message is shows up …

[lexical] Feature: error checking for node key re-use with type mismatch in __DEV__

---

packages/lexical-playground/src/plugins/TableCellResizer/index.tsx

Shift the selection rectangles to the center of the edge, instead of being outside the cell. This makes for a more intuitive user experience as the user will try to select the edge, not the outside of the table cell.
(briefly visualized the areas so that the change can be seen)

[lexical-playground][TableCellResizer] Feature: Center the drag zone over the edge of the cell

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/TextFormatHTMLCopyAndPaste.spec.mjs

This PR adds test for #6087
And for the further improvement, It would be nicer if importDOM supports font size or colors. So I added todo about this.
recording of the manual reproduction of added test:
https://github.com/facebook/lexical/assets/40269597/1cd61730-892b-4590-bb75-42e61c0c4829

[lexical][TextNode] Feature: Add test for #6087

---

packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs
packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.ts

- Move test from e2e to unit as followup on #5855 
- e2e tests are expensive and should be avoided unless we have something to run on various browsers and its difficult to cover with unit tests
- Test generated formatting from unit test:

[Lexical][Table Formatting Copy Paste] Move test from e2e to unit as followup on #5855 

---

.github/workflows/call-core-tests.yml
.github/workflows/call-e2e-all-tests.yml
.github/workflows/call-e2e-canary-tests.yml
.github/workflows/call-e2e-test.yml
.github/workflows/size-limit.yml
.github/workflows/tests-extended.yml
.github/workflows/tests.yml
.lintstagedrc.js
CONTRIBUTING.md
README.md

Avoid running the entire suite of (expensive) e2e tests on every PR that is opened or updated. Only run if PR is approved.
Reference: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved

Only run CI e2e tests on approved PRs

---

packages/lexical-playground/src/plugins/EmojiPickerPlugin/index.tsx

Menu items in the emoji picker weren't getting the expected border radius styles on selection. This PR removes the `div` that wrapped emoji menu items so the global `li` pseudo selectors can target the items.

[lexical-playground] Bug Fix: Emoji menu item not getting targeted styles

---

packages/lexical-devtools/wxt.config.ts

Reduce requested permissions as we don't use `scripting` or `storage` atm. This is a blocker to submit extension to the Chrome Webextension Store
Manual regression was done here, E2E tests to be created as a part of the extension project.

[@lexical/devtools] Bug Fix: Reduce requested permissions as we don't use them atm

---

.github/workflows/tests-extended.yml

- Follow up on #6097  run extended tests on merge group event
- This is to ensure :
- No branch is merged without running e2e tests successfully
- e2e tests are run every time on merge not just if a label is added manually by facebook owner.
- will need the Merge Queue settings to be enabled 1st before we we could test this

[Lexical] #6097 run extended tests on merge_group event

---

packages/lexical-devtools/src/entrypoints/devtools-panel/components/EditorInspectorButton.tsx
packages/lexical-devtools/src/entrypoints/devtools-panel/main.tsx
packages/lexical-devtools/src/entrypoints/injected/InjectedPegasusService.ts
packages/lexical-devtools/src/store.ts

`EditorInspectorButton` reflects pickerActive state on UI.
**Closes:** #6068
https://github.com/facebook/lexical/assets/40269597/dec0b200-d955-4c04-8d3a-d04096f583bb
https://github.com/facebook/lexical/assets/40269597/9ec3152e-75be-4722-9257-e6d5eee087f8

[lexical-devtools] Feature: Reflect picker state on inspector button ui

---

.github/workflows/add-label-on-approve.yml
.github/workflows/add-label-run-extended-tests-approve.yml
.github/workflows/tests-extended.yml

- Add label and run extended test on approve
- followup on https://github.com/facebook/lexical/pull/6080
- Fixes https://github.com/facebook/lexical/issues/6097

[Lexical] Add label to run e2e tests on approve

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/HTMLCopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/ListsHTMLCopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/HorizontalRule.spec.mjs
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs
packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-playground/src/index.css
packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts
packages/lexical-react/src/LexicalHorizontalRuleNode.tsx
packages/lexical/src/LexicalEditor.ts

This PR adds theme class support to `HorizontalRuleNode` so that it can be targeted from the theme object in the editor config instead of through CSS workarounds. The `selected` class is still added/removed upon selecting the HR node and relevant tests have been updated to include the theme class.
**Closes:** https://github.com/facebook/lexical/issues/4336

[lexical-playground][lexical-react][lexical] Feature: Theme class added to horizontal rule node

---

packages/lexical-markdown/src/MarkdownExport.ts
packages/lexical-markdown/src/MarkdownImport.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-markdown/src/index.ts
packages/lexical-markdown/src/utils.ts
packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/Settings.tsx
packages/lexical-playground/src/appSettings.ts
packages/lexical-playground/src/plugins/ActionsPlugin/index.tsx

option to make the number of blank lines consistent between markdown and the rendered markdown
**Closes:** #
To enable:
```
$convertFromMarkdownString(
...,
true // shouldPreserveNewLines -> set to true,
)
$convertToMarkdownString(
...,
true // shouldPreserveNewLines -> set to true,
);
```
These flags are optional. Defaults to old behavior of removing newlines on import and delimiting with newlines on export.
https://github.com/facebook/lexical/assets/19604232/108fdd80-0cde-4678-b4dd-b301132082fa
blank lines are ignored and removed
https://github.com/facebook/lexical/assets/19604232/b8ce7e72-e1c2-4b60-9b96-c92a95791faf
number of blank lines consistent between markdown and rendered markdown
--- …

[lexical-markdown][lexical-playground] Feature: Option to include blanklines in markdown render

---

packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs
packages/lexical-playground/src/plugins/TestRecorderPlugin/index.tsx
packages/lexical-playground/src/plugins/TypingPerfPlugin/index.ts
packages/lexical-selection/src/__tests__/utils/index.ts
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalUtils.ts

Replace code with key to check KeyboardEvents
Before:
https://github.com/facebook/lexical/assets/163521239/dc711375-2e55-4115-80a5-366af49e4129
https://github.com/facebook/lexical/assets/163521239/b4976cc2-4010-4550-bb09-2c4f03472694
After:
https://github.com/facebook/lexical/assets/163521239/355ec910-b3fb-4b04-b071-67f48d0e611a
https://github.com/facebook/lexical/assets/163521239/15c95677-ad6f-498d-8928-b2eea351950d
https://github.com/facebook/lexical/assets/163521239/0d22af12-8af0-4b4e-81dc-9993377b4e52

[Lexical] Replace code with key to check KeyboardEvents

---

packages/lexical-eslint-plugin/flow/LexicalEslintPlugin.js.flow
scripts/update-flowconfig.js

[Lexical] Add flow for eslint

---

scripts/build.js

Changes are based on the https://github.com/facebook/lexical/pull/6048/commits/492816e0e9512f59976965be93190bc61bb28d08 by @etrepum
**Closes:** #6132

fix(lexical): #6132 react build size regression from #6088

---

.github/workflows/size-limit.yml

- Fix size limit workflow git hub action bot not able to create comment for PRs from fork
- Follow React Native Repo example : https://github.com/facebook/react-native/blob/044aadbaf6830b21aab821804dc5a7989010022e/.github/workflows/danger_pr.yml#L4
Fixes #6131

[Lexical] Fix size limit workflow git hub action bot not able to create comment for PRs from fork

---

scripts/build.js

- Use classic mode for jsx runtime for meta build
- fix build getting exception for react/jsx-runtime module doesn't exist, use classic mode for the build

[Lexical] Use classic mode for jsx runtime for meta build

---

packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Pressing the left-arrow key in the first table cell with a decorator node or the right-arrow key in the last table cell with a decorator node previously moved the selection outside the table instead of selecting the node.
Added a check for `DecoratorNode` when moving horizontally through a table.
**Closes:** #6128 
https://www.loom.com/share/98a1761d09574eb895290b80bfcf85ef?sid=134ed533-67b9-42da-bf2d-06d12bb053a8
https://www.loom.com/share/9a2d3376839b4c48b0a672a0ee0207c3?sid=6b6d2918-d603-4974-a314-17063571c492
https://www.loom.com/share/269473b64fbb4c7eb34f5aca0a9d1ee5?sid=bdaa7cad-ecc8-4841-a844-932b8e72621c

Bug Fix: Add check for `DecoratorNode` for horizontal table navigation.

---

.github/workflows/call-e2e-all-tests.yml

Remove `legacy-events` from the e2e test matrix for all OS and browsers except `chromium` on `windows`. I think this removes 12 e2e test runs.
The `legacy-events` version of e2e tests was [adding in Oct 2021](https://github.com/facebook/lexical/pull/750) and tests for when `beforeinput` is not available. But the browser support for that event is quite broad these days, mostly in line with the lowest versions of Chrome Meta supports (in practice) internally. So the need to test not-`beforeinput` doesn't appear to be significant. I thought we'd keep chromium-windows for now, because Windows is the only OS where we see the oldest versions of Chrome (where `beforeinput` is not supported) being used.

Remove 'legacy-events' from mac & linux e2e matrix

---

packages/lexical-react/src/LexicalErrorBoundary.tsx

- #6088 removes 
> import * as React from 'react'; 
from LexicalErrorBoundary.tsx 
- but in generated file LexicalErrorBoundary.dev.js / LexicalErrorBoundary.prod.js  this import was needed,
-  would need further investigation whats going wrong, but this should fix the WWW sync causing some e2e tests to fail with the issue replicable on trying the steps manually as well

[Lexical] Fix meta sync build failing due to recent changes in LexicalErrorBoundary.tsx

---

packages/lexical-playground/src/images/image-broken.svg
packages/lexical-playground/src/nodes/ImageComponent.tsx

Currently, if an image fails to load because of a network error, the page is down, etc. the Node is silently inserted but no UI is shown.
Adding a fallback image that would substitute an original image if it fails to load due to a network failure etc. 
**Closes:** #5564
https://github.com/facebook/lexical/issues/5564#issuecomment-2040647027
1. Open https://playground.lexical.dev/ in a browser
2. Insert an image and block the image load request via the dev tools.
3. Try to insert the image once again.
4. See that a fallback image is loaded instead.
https://github.com/facebook/lexical/assets/5062807/8501bb84-ba14-4f63-be25-dc44d0fc65c9
https://github.com/facebook/lexical/assets/5062807/a35980d7-4358-4eca-8806-626b36e10be5

[lexical-playground][image-node] Bug Fix: Load image error UI

---

packages/lexical-table/src/LexicalTableSelectionHelpers.ts

The current logic for checking if a selection is at a table's edge fails when the table is inside a collapsible section, as it compares against the root element. This PR fixes the issue by comparing against the table's parent element instead.
**Closes:** #6157 
[screencast-playground.lexical.dev-2024.05.21-10_16_24.webm](https://github.com/facebook/lexical/assets/88986106/b3dc740d-20b2-4b61-b21c-40cb4533d9bc)
[screencast-localhost_3002-2024.05.21-10_18_35.webm](https://github.com/facebook/lexical/assets/88986106/bf3d5705-1a27-4c65-8c1f-71ac38503144)

Bug Fix: Insert paragraph at table's edge inside a collapsible

---

packages/lexical-table/src/LexicalTableObserver.ts

I ran into an issue when I tried to create table like:
```html
<table>
<colgroup>
.....
</colgroup>
<tbody>
....
</tbody>
</table>
```
I created one ElementNode with <table>
one TextNode with <colgroup>
and TableNode with <tbody>
but it didn't update values in TableObserver and table didn't work correctly.
This PR fixes it.

Add tbody and thead tags to TableObserver

---

packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
packages/lexical/src/LexicalSelection.ts

It is currently only possible to format token nodes by selecting them entirely. They won't be formatted if they are in the middle of the range selection. Also, if the selection offset is in the middle of the node, it will split the node.
This PR ensures middle nodes are formated, just like when selecting them entirely. Also, it prevents breaking segmented or token nodes in the middle of the text where they shouldn't be allowed.
https://github.com/facebook/lexical/issues/6059
Added unit tests to the PR. See LexicalSelection.test.tsx.
- Formatting text in the middle of a segmented or token text node was splitting the node.
- Formatting range selection with a segmented or token node in the middle was not formatting the node.
- Formatting text in the middle of a segmented or token text node …

[lexical-selection] Bug Fix  /  Fixes text formatting with segmented and token nodes #6059

---

packages/lexical-markdown/flow/LexicalMarkdown.js.flow

followup to https://github.com/facebook/lexical/pull/6020 , which introduces shouldPreserveNewLines flag . update the flow file to be in sync

[lexical-markdown] Bug Fix: add missing shouldPreserveNewLines to markdown flow

---

.github/workflows/after-approval.yml

- #6136  adds ```pull_request_target``` action but it doesn't get triggered on approve so its not helpful right now to use as is, hence could be removed to avoid confusions.
using my fine grain access PAT to trigger the workflow for add label
- it only has read/write access to PR and
- read access to content
Test Plan
- tested in https://github.com/facebook/lexical/pull/6168
TODO
- will replace my PAT with lexical-bot PAT once setup is done

[Lexical] Attempt to fix after approval workflow

---

scripts/build.js

Changes www builds to use automatic jsx runtime with the react/jsx-runtime module aliased to react.
As far as I can tell react's [index.fb.js](https://github.com/facebook/react/blob/c325aec1ee5ae970ea70efc9b19574aa0e72c9a1/packages/react/index.fb.js#L60) is used as the module's entrypoint for fb builds and it includes the JSX runtime (Fragment is already present in the react module).
This should solve the problems that #6134 and #6140 are trying to work around in a more systematic and future-compatible way.
Someone with access to intern will have to do a sync and make sure that this does indeed work.

[lexical-react] Bug Fix: Use automatic jsx runtime with react/jsx-runtime -> react alias in www

---

README.md

it was showing 
^ repo or workflow not found
reflect the build status

[CI] fix: status badge

---

packages/lexical-website/docs/testing.md

docs: explain installing browsers for e2e tests

---

packages/lexical-website/docs/getting-started/react.md

Title:
[lexical-docs] Bug Fix: Uncommented Code in Getting Started with React Docs
Description
The current behavior includes uncommented code sections in the "Getting Started with React" documentation on the Lexical website, which can lead to confusion and potential errors for users following the guide.
This pull request addresses the issue by commenting out the placeholder code sections to ensure the code snippet is clear and functional.
Closes #6142

Fixed Uncommented Code in Getting Started with React Docs

---

packages/lexical-devtools-core/src/generateContent.ts
packages/lexical-devtools-core/src/useLexicalCommandsLog.ts

I always get confused which way the commands list is flowing in the debug view, so adding an index to show that clearly
it also helps show that commands listed are jumped if > 10 commands get updated in the list
https://github.com/facebook/lexical/assets/19604232/003f0876-027c-40ba-9b21-188f816712bc
^ not clear which direction commands are flowing
https://github.com/facebook/lexical/assets/19604232/7a04cab5-13f9-4af7-a0b7-27f4c444b7b1
^ with index the list is clearer

[lexical-dev-tools-core] Feature: Index tree view cmds

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical/src/LexicalSelection.ts

This PR fixes line deletion operation via *CMD (⌘) + Backspace* combination on MacOS for cases when the current selection has an anchor of type `element`.
This is an extension of [this PR](https://github.com/facebook/lexical/pull/2813) which originally limited line deletion for `text` based selections only.
**Closes:** #6047
1. Open https://playground.lexical.dev/
2. Type some text and then insert a sample image or any other element
3. Press "CMD (⌘) + Backspace"
4. Observe that the whole line is deleted
https://github.com/facebook/lexical/assets/3491275/8bf8415d-fe2a-4c6a-9f1f-af26be31c996
https://github.com/facebook/lexical/assets/3491275/9d413b33-d028-4720-b459-9721a786655f

[lexical] Bug Fix: delete line for selections ending with elements

---

packages/lexical-plain-text/src/index.ts

Reverts facebook/lexical#5991
This was actually an unintended breaking change that prevented "close on Esc" and [other use cases](https://github.com/facebook/lexical/pull/5991#issuecomment-2132094564) from working correctly.

Revert "[lexical-plaintext] Feature: add escape key handler"

---

packages/lexical-playground/src/plugins/EmojisPlugin/index.ts

This logic for just 4 emojis doesn't bring any value and the `slice(i, i + 2)` is unintentionally cutting emojis in half
https://github.com/facebook/lexical/assets/193447/2aecb625-476a-45c3-905a-80c7ab12b5c0

Remove emojis from emoticons plugins

---

packages/lexical-playground/__tests__/e2e/Mentions.spec.mjs

add an e2e test for pasting over mentions. part of a sev followup task for lexical crashing when pasting over mentions. fix was in #5954
npm run start & npm run test-e2e-chromium

[lexical-playground] Chore: add test for pasting over mentions

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleContainerNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleContentNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleUtils.ts

_Memorial day pair coding with @ivailop7 👯_
Turns out that `details` is broken on Chrome. More details on the issue https://github.com/facebook/lexical/issues/5582
Selection now works well on Chrome:
https://github.com/facebook/lexical/assets/193447/e5e15246-0ef9-4853-aa5e-df018a9df373
Find still works
https://github.com/facebook/lexical/assets/193447/840b20e1-6a43-42eb-b72c-bb32212d10f2

Collapsible as div

---

packages/lexical/src/nodes/LexicalTextNode.ts

noticed that [`DOMConversionFn<HTMLElement>`](https://github.com/facebook/lexical/blob/9a73b2486f1fbd99b1ce7c9657f4990a5a7967fb/packages/lexical/src/LexicalNode.ts#L124) -> it takes in a `HTMLElement` as input, but quite alot of conversion fn implementations have the input type as `Node`, and then later cast it as a `HTMLElement` (or its child classes).
seems redundant as we can directly have the input type as the HTMLElement
npm run ci-check

[LexicalTextNode] Refactor: remove unnecessary type casting

---

.github/workflows/size-limit.yml
.size-limit.js
package.json

- Remove noisy running time signal mentioned in #6137 for now, as its NOT useful
- Remove duplicate triggers for pull-request-target and pull-request
the given PR workflow "comments" updated to have "running-time" as we are using pull-request-target instead of pull-request, it runs workflow against main branch not current branch. Tested the change locally using pull-request workflow trigger and updated the screenshot below
Before:
After:

Remove noisy running time signal mentioned in #6137

---

packages/lexical-code/src/CodeNode.ts

same as https://github.com/facebook/lexical/pull/6201

[lexical-code] Refactor: remove unnecessary type casting

---

packages/lexical-devtools/safari-xcode/Lexical Developer Tools/Lexical Developer Tools/ViewController.swift
packages/lexical-website/docs/getting-started/devtools.md

- Fix: When clicked on ”Quit and Open Safari Extensions Preferences”, it quits the app but did not launch Safari Extensions Preferences Panel.
- Added devtools extension specific support section to Lexical website as per Apple's requirements
See website preview

[lexical-devtools] Chore: Safari App Store review fixes

---

package-lock.json
package.json
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-website/docs/collaboration/react.md
packages/lexical-website/docusaurus.config.js
packages/lexical-website/src/components/HomepageExamples/index.js
scripts/__tests__/unit/stackblitz.test.js

Sometimes we publish stackblitz URLs that point to a branch and don't change it back to main after review, which means examples can go stale or break if that branch is deleted.
To make PR review of stackblitz URLs easier, and to make the examples stable (relevant to #6144), this also adds docusaurus markdown preprocessor to rewrite these URLs on build to point to a specific commit (for PRs) or release branch.
stackblitz URLs could point to branches other than main
Tests fail if a stackblitz URL does not point to main
Stackblitz URLs reference a specific commit for PRs so they can be tested in situ

[lexical-website] Documentation Update: Validate stackblitz URLs in documentation

---

packages/lexical/src/LexicalEditorState.ts

[lexical] Refactor: Change import paths syntax in LexicalEditorState
Description
The current behavior implements not consistent import approaches which can lead to confusion.
This pull request addresses the issue by using consistent import syntax to make it easier to understand
which module is from where imported.

Refactor import paths in LexicalEditorState

---

.github/workflows/tests-extended.yml
.size-limit.js
package.json

follow up on #6137 
- Measure both cjs/esm build combinations for size checks
- Also ignore size-limit file from triggering extended tests run
- Current regression checks meaure only cjs checks, enhance to check both cjs/esm changes.
- Not needed to run e2e tests for size-limit workflow updates
```
sahejk@sahejk-mbp lexical % npx size-limit
✔ Adding to empty webpack project
✔ Running JS in headless Chrome
lexical - cjs
Size:         22.5 kB with all dependencies, minified and brotlied
Loading time: 440 ms  on slow 3G
lexical - esm
Size:         22.97 kB with all dependencies, minified and brotlied
Loading time: 449 ms   on slow 3G
@lexical/rich-text - cjs
Size:         33.25 kB with all dependencies, minified and brotlied
Loading time: 650 ms   on slow 3G
@lexical/rich-text - esm
Size: …
```

[Lexical][Size-Checks] Measure both cjs/esm builds for regression checks

---

.prettierignore
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-website/plugins/package-docs/index.js
scripts/__tests__/integration/prepare-release.test.js
scripts/__tests__/unit/build.test.js
scripts/npm/prepare-release.js
scripts/override-react.js
scripts/shared/packagesManager.js
scripts/update-tsconfig.js
scripts/validate-tsc-types.js
scripts/www/rewriteImports.js

Upgrading glob in #6215 changed its behavior on Windows, since it now expects you to specify paths that use '/' as the path separator so that '\\' can be used for escaping glob characters unless the windowsPathsNoEscape option is specified which disables escaping of glob characters (a feature we do not use).
Hopefully #6198 works and lands soon so that this type of regression can be avoided in the future
Please add the extended-tests label to this PR so that we can confirm that it works before merging
Windows e2e tests failed
Windows e2e tests should succeed

[*] Fix: Resolve Windows regression caused by upgrading glob

---

.size-limit.js

For some reason the default configuration of size-limit for @lexical/plain-text caused nearly the whole module to be tree shaken, so nothing of interest was measured. This makes sure to test the full size of every package we are measuring.
Closes #6233
size-limit would report a 225 bytes for @lexical/plain-text esm
```
@lexical/plain-text - esm
Size:         225 B with all dependencies, minified and brotlied
Loading time: 10 ms on slow 3G
```
size-limit should report a meaningful number for @lexical/plain-text esm
```
@lexical/plain-text - esm
Size:         24.44 kB with all dependencies, minified and brotlied
Loading time: 478 ms   on slow 3G
```

[*] Fix: size-limit report for esm modules

---

packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical-playground/__tests__/e2e/List.spec.mjs
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs
packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs
playwright.config.js

- Add ||ism in slow test files by changing test.describe to test.describe.parallel 
- Add ||ism in workers - in CI we were using just 1 worker while in local dev machines we use 4 workers, change to 4 workers in CI as well to make the tests run faster
https://playwright.dev/docs/test-parallel
- Lower the running time for github workflows related to e2e tests and hence lower the spend
Before: https://github.com/facebook/lexical/actions/runs/9342978263/usage?pr=6198 
~6h 
After:   https://github.com/facebook/lexical/actions/runs/9344275667/usage?pr=6237
~3h 45min

[Lexical][CI] Add more ||ism in e2e tests to decrease overall run time

---

packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs

https://github.com/facebook/lexical/actions/runs/9294132717/job/25578693971?pr=6201
^ this e2e collab test fails occasionally on the CI due to flakiness. the output is an extra `<p></br><p>`
add a callback to modify actual html. this callback is useful to adjust for flaky html outputs
Closes #6241
```
npm run start & npm run test-e2e-collab-chromium
```
✓  1 [chromium] › packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs:37:8 › Toolbar › Insert image caption + table (2.5s)

[lexical-playground] CI: fix flaky collab test

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/TableCellResizer/index.tsx
packages/lexical-table/src/index.ts

- the CI for e2e tests signal was missing on https://github.com/facebook/lexical/pull/6200 hence it got reverted in https://github.com/facebook/lexical/pull/6224 when e2e test failed on main
- remerge [[PR](https://github.com/facebook/lexical/pull/6200)](https://github.com/facebook/lexical/pull/6200) with test fix from https://github.com/facebook/lexical/pull/6228
Credits for the fixes goes to @AlexanderReznik , im just helping to remerge the changes
added a fix for the flaky table resize test in collab mode. sometimes, the height is 87px, sometimes it is 88 px.
using the actual html modification call back introduced in https://github.com/facebook/lexical/pull/6240/commits, accept either 88 or 87 px as html output
Closes #6241
```
npm run start &  npm run test-e2e-chromium
```
2 flaky …

[lexical-table] CI: Remerge PR 6200 Resizing table with merged cells

---

packages/lexical-playground/__tests__/e2e/Headings/HeadingsEnterAtEnd.spec.mjs

test failing at random because enter key is pressed too soon after the last move right key press. add a 500 ms delay to fix that
Closes #6241
npm run start & npm run test-e2e-collab-chromium  
```
- Expected  - 2
+ Received  + 2
<h1 class="PlaygroundEditorTheme__h1 PlaygroundEditorTheme__ltr" dir="ltr">
-   <span data-lexical-text="true">Welco</span>
+   <span data-lexical-text="true">Welc</span>
</h1>
<h1 class="PlaygroundEditorTheme__h1 PlaygroundEditorTheme__ltr" dir="ltr">
-   <span data-lexical-text="true">me to the playground</span>
+   <span data-lexical-text="true">ome to the playground</span>
</h1>
1 failed
[chromium] › packages/lexical-playground/__tests__/e2e/Headings/HeadingsEnterAtEnd.spec.mjs:22:6 › Headings - stays as a heading when you press enter in the middle of a …
```

[lexical-playground] CI: fix flaky headings e2e test

---

packages/lexical-playground/__tests__/e2e/Headings/HeadingsEnterAtEnd.spec.mjs
packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical-playground/__tests__/keyboardShortcuts/index.mjs

credits to @Sahejkm for pointing out that 100ms is workable as a delay https://github.com/facebook/lexical/pull/6245/files#r1625266582
introducing `const STANDARD_KEYPRESS_DELAY_MS`
- setting 100ms as a standard keypress delay const, so it can be reused and developers dont need to waste time through trial an error to find an optimal delay value
- the goal of this standard delay is to provide a delay value that is short enough yet not too short such that keypresses still override each other thus leading to flakiness
- this standard should work for most test cases. if there are outliers, a custom value can be passed as the delay instead
- open to adjusting this standard value overtime  
Closes #
npm run start & npm run test-e2e-collab-chromium 
```
Slow test file: [chromium] › …
```

[lexical-playground] CI: standardise key press delay

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs

New Table tests around "Resize merged cells height/width" added as part of #6200 , initially reverted due to failures on CI and later re-merged  as part of #6235 are still not very stable and failing occasionally in Linux/Collab/Firefox mode right now in the past runs causing CI failures.
hence disable them in Linux/Collab/Firefox for now.
fix unstable CI 
https://github.com/facebook/lexical/actions/runs/9364458870
https://github.com/facebook/lexical/actions/runs/9352693358/job/25755810388?pr=6243
```
Running 42 tests using 4 workers
✓  1 [chromium] › packages/lexical-playground/__tests__/e2e/Tables.spec.mjs:203:5 › Tables › Can exit tables with the horizontal arrow keys › Can exit the last cell of a non-nested table (1.3s)
✓  2 [chromium] › …
```

[Lexical] Skip newly added flaky "Resize merged cells height/width" tests for linux/collab/firefox mode

---

scripts/build.js

Using the @lexical/eslint-plugin as a configuration in an external project is currently difficult in v0.16.0 because eslint won't resolve through a default property when processing "plugin:@lexical/recommended".
This happens because the compiled index.ts wrapper will always produce `exports.default = plugin` where what we want is `module.exports = plugin` due to the rollup/esbuild setting of 'named' exports (which we must use for some other modules which mix default and named exports).
Closes #6251
Try and add @lexical/eslint-plugin to an external project per the docs https://lexical.dev/docs/packages/lexical-eslint-plugin
```
❯ ./node_modules/.bin/eslint . && echo 0
Oops! Something went wrong! :(
ESLint: 8.57.0
ESLint couldn't find the config "plugin:@lexical/recommended" to extend from. …
```

[lexical-eslint-plugin] Fix: Use cjs compatible export from built version

---

packages/lexical-devtools/safari-xcode/Lexical Developer Tools/Lexical Developer Tools Extension/SafariWebExtensionHandler.swift
packages/lexical-devtools/safari-xcode/Lexical Developer Tools/Lexical Developer Tools/AppDelegate.swift
packages/lexical-devtools/safari-xcode/Lexical Developer Tools/Lexical Developer Tools/Resources/Style.css
packages/lexical-devtools/safari-xcode/Lexical Developer Tools/Lexical Developer Tools/ViewController.swift
packages/lexical-devtools/src/entrypoints/devtools-panel/App.css
packages/lexical-devtools/src/entrypoints/popup/style.css
packages/lexical-playground/src/nodes/PageBreakNode/index.css
packages/lexical-playground/src/plugins/CodeActionMenuPlugin/index.css
packages/lexical-playground/src/plugins/FloatingTextFormatToolbarPlugin/index.css
packages/lexical-playground/src/plugins/TableOfContentsPlugin/index.css
packages/lexical-playground/src/plugins/ToolbarPlugin/fontSize.css
packages/lexical-playground/src/ui/Dialog.css
packages/lexical-playground/src/ui/Select.css
scripts/__tests__/integration/fixtures/lexical-esm-astro-react/astro.config.mjs
scripts/__tests__/integration/fixtures/lexical-esm-astro-react/playwright.config.ts
scripts/__tests__/integration/fixtures/lexical-esm-astro-react/tests/test.ts
scripts/__tests__/integration/fixtures/lexical-esm-nextjs/app/layout.tsx
scripts/__tests__/integration/fixtures/lexical-esm-nextjs/app/page.tsx
scripts/__tests__/integration/fixtures/lexical-esm-nextjs/next.config.mjs
scripts/__tests__/integration/fixtures/lexical-esm-nextjs/playwright.config.ts
scripts/__tests__/integration/fixtures/lexical-esm-nextjs/postcss.config.js
scripts/__tests__/integration/fixtures/lexical-esm-nextjs/tailwind.config.ts
scripts/__tests__/integration/fixtures/lexical-esm-nextjs/tests/test.ts
scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/playwright.config.ts
scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/src/app.d.ts
scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/svelte.config.js
scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/tests/test.ts
scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/vite.config.ts

Fix ```missing  copyright headers in source file``` issue generated via the Automated Meta Open Source Checks script
Every project specific source file must contain a doc block with an appropriate copyright header. Unrelated files must be listed as exceptions in the Copyright Headers Exceptions page in the repo dashboard.
A copyright header clearly indicates that the code is owned by Meta. Every open source file must start with a comment containing "Meta Platforms, Inc. and affiliates"
check how to auto include more paths to .eslintrc for copyright headers
https://github.com/facebook/lexical/blob/96bdfb1c859d4d38a19064063bf89958b646ab54/.eslintrc.js

[Lexical] Fix missing meta copyright headers in files 

---

packages/lexical-utils/src/__tests__/unit/mergeRegister.test.ts
packages/lexical-utils/src/mergeRegister.ts

While it doesn't ever matter for the typical use case of `mergeRegister` (calling cleanup functions from Lexical listeners), semantically the mergeRegister cleanup functions should be called in reverse order (LIFO) in case there are any inter-dependencies.
For example, in `mergeRegister(A,B,C)`, logically C can have access to A when it is "acquired" so it should also have access to A when it's "released" so C must be cleaned up before A.
There should be no observable difference to most users, because there are generally no ordering or interdependency requirements. If a user did have ordering dependencies they have probably already written their own version that does it "correctly" since it is simple to do and a lot less awkward than something like `mergeRegister(...[A,B,C].reverse())`.
It …

[lexical-utils] Fix: mergeRegister should call cleanup functions in reverse order

---

packages/lexical-playground/__tests__/e2e/MaxLength.spec.mjs

`&nbsp;` appears randomly thus making test flaky, add keypress delays when typing to prevent that
add `--reporter=html --repeat-each=10` to "test-e2e-collab-firefox": "cross-env E2E_BROWSER=firefox E2E_EDITOR_MODE=rich-text-with-collab playwright test --project=\"firefox\"", in build script
then run `npm run start & npm run test-e2e-collab-firefox`
```
npm run start & npm run cross-env E2E_BROWSER=firefox E2E_EDITOR_MODE=rich-text-with-collab playwright test --project="firefox" --reporter=html --repeat-each=10
> @lexical/monorepo@0.16.0 test-e2e-collab-firefox
> cross-env E2E_BROWSER=firefox E2E_EDITOR_MODE=rich-text-with-collab playwright test --project="firefox" --reporter=html --repeat-each=10
> @lexical/monorepo@0.16.0 start
> cross-env NODE_ENV=development concurrently "npm:collab" …
```

[lexical-playground] CI: fix flaky MaxLength emoji e2e test

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/src/LexicalTableUtils.ts

fix crash on backward column deletion
currently forward multiple column deletion works, backward multiple column deletion crashes, add handling for the same.
Before:
#6221
After:
https://github.com/facebook/lexical/assets/163521239/0ed169c8-eacd-473d-ac70-63470a1cd695
Closes #6221

[Lexical] Fix #6221  delete multiple column table crash 

---

packages/lexical/src/LexicalSelection.ts

Fix bug related to a lost autolink styling. Right away after autolink is created during the user input, the following symbols are inserted without a proper style. This PR fixes that by keeping the style of the newly inserted text node.
Closes #6155
1. Open https://playground.lexical.dev/
2. Clear the editor
3. Set font size to anything other than the default 15
4. Start typing "www.github.com"
5. See an autolink is created with proper styles.
See https://github.com/facebook/lexical/issues/6155
https://github.com/facebook/lexical/assets/5062807/ba07fa54-37d6-45d6-90e6-9ab2e315910f

[lexical-selection] Fix lost autolink styling

---

.github/workflows/call-increment-version.yml
.github/workflows/call-npm-publish.yml
.github/workflows/nightly-release.yml
.github/workflows/pre-release.yml
.github/workflows/version.yml
.prettierignore
package.json
packages/lexical-website/docs/maintainers-guide.md
scripts/npm/increment-version.js
scripts/npm/postversion.js

Refactor release workflow to use reusable workflows so the work can be shared
Add a nightly workflow to create a release every night in the nightly channel
Maintain release channel branches (`latest__release`, `nightly__release`) so that we will have the option to build the docs site from the latest released version instead of or in addition to main (#6144)
Closes #6169
* Try creating a release to make sure that still works
* See if it works when the cron job runs?
* I created very similar workflows and scripts in this repo to see if it *should* work and it did https://github.com/etrepum/lexical-builder
* Fix release process to use the same tag for both GitHub and NPM releases (the nightly release does not have this issue, only manual workflow_dispatch releases with a PR)
* Do not do a …

[*] Feature: Automated nightly releases

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/src/LexicalTableUtils.ts

fix crash on forward column deletion at the end of the table
currently backward multiple column deletion **at the end of the table** works, forward multiple column deletion crashes, add handling for the same.
https://github.com/facebook/lexical/assets/163521239/4b04bdbf-8f44-4e38-97af-1b35cb2b8f33
https://github.com/facebook/lexical/assets/163521239/0904b649-cd2b-4c61-8077-2845eb44f2d0

[Lexical][Tables] Follow up on #6267 handle multi column delete crash on forward selection at end of the table

---

package-lock.json
packages/lexical-devtools/package.json
packages/lexical-playground/package.json

A few modules used in the vite/wxt builds were missing as explicit devDependencies in lexical-playground and lexical-devtools. This adds them to package.json. There shouldn't be any observable difference in behavior, unless you are trying to extract these projects out of the monorepo or maybe trying to use more strict dependency management tool than npm.
Closes #6280
I don't think you could run into any problems with the status quo without doing something unsupported, e.g. #6280, because npm/node will happily just use whatever happens to be present in the workspace root's node_modules.
All known dependencies are in the respective package.json files. This probably means that these packages are a bit easier to extract (but there are other "unique" build dependencies like the shared package …

[lexical-playground][lexical-devtools] Fix: Add missing explicit devDependencies for vite config

---

packages/lexical-playground/src/nodes/ImageComponent.tsx
packages/lexical-playground/src/nodes/ImageNode.tsx
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-utils/src/index.ts

Context:
Now users are able to insert an image/GIF/table etc, into another image's caption. 
Solution:
This PR limits what the users can insert into the image caption and its nested editor. Excluding some controls from the toolbar if the selection is inside the nested editor that belongs to the image caption.
Closes #6109
1. Open https://playground.lexical.dev/
2. Insert a sample image with a caption.
3. Focus on the caption.
4. Insert a sample image/table/GIF etc.
https://github.com/facebook/lexical/assets/5062807/5e0ad65e-00ee-4fbf-9f2c-22359f37a7f2
https://github.com/facebook/lexical/assets/5062807/63b175ec-976e-4ab0-b05f-3ec18be8b93e

[lexical-playground] Fix bug: Insert an image inside another image's caption (#6109)

---

.github/workflows/after-approval.yml
.github/workflows/tests-extended.yml

Fix some issues in Lexical CI job  after observing past runs :
- path-ignore for e2e tests not working due to warning on wrong keyword, should be replaced by path_ignore 
- flaky-test notice not working on "PRs from forks"
https://github.com/facebook/lexical/actions/runs/9506494216/job/26204471038?pr=6274
- concurrent-workflow skipping all concurrent workflows running on multiple PRs rather just for the PR in focus, - change settings from 'always' to "same_content_newer".
#6308

[Lexical][CI] Fix issues in after_approval workflow

---

packages/lexical-website/docusaurus.config.js
packages/lexical-website/src/components/GalleryPage.js
packages/lexical-website/src/pages/gallery.md

-  add option to add gallery content in Meta Intern only
- Building a prototype for UI Gallery in Meta intern 1st before starting in Open Source.
> Meta Build
> Lexical Build remains Not impacted 
https://lexical-git-lexicalgallerywip-fbopensource.vercel.app/

[Lexical][Gallery] add option to add gallery content in Meta Intern only

---

packages/lexical-link/src/__tests__/unit/LexicalAutoLinkNode.test.ts
packages/lexical-link/src/index.ts
packages/lexical-playground/__tests__/e2e/AutoLinks.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx
packages/lexical-react/src/LexicalAutoLinkPlugin.ts

This PR fixes a bug where a user cannot remove link formatting (unlink) from links created by AutoLinkNode. However, it works for links created by LinkNode. The proposal is to add a flag property in AutoLinkNode to indicate if the link was unlinked. If so, render the link as regular text, keeping styles. The hidden auto-link can become a link again via the Toolbar Link button.
Closes #5607
1. Open https://playground.lexical.dev/
2. Input to the editor "www.facebook.com".
3. Check the auto-link is created.
4. Focus on the link.
5. Click the delete button on the popup.
6. The link should transform to the regular text "www.facebook.com".
https://github.com/facebook/lexical/assets/5062807/4687fd1e-b469-4546-9602-361023a9602c
https://github.com/facebook/lexical/assets/5062807/37492852-bc42-4dc3 …

[lexical-link] Fix bug when can't remove link formatting from autolink

---

packages/lexical/src/index.ts

Exports the `EditorUpdateOptions` type which is used in the public API for `LexicalEditor.update`
Closes #6331
Third party packages couldn't easily reference the `EditorUpdateOptions` type
Workaround:
```ts
import type {LexicalEditor} from 'lexical';
type EditorUpdateOptions = NonNullable<Parameters<LexicalEditor['update']>[1]>;
```
Now they can since it is exported
```ts
import type {EditorUpdateOptions} from 'lexical';
```

[lexical] Bug Fix: Export type EditorUpdateOptions

---

packages/lexical-devtools-core/src/generateContent.ts

- When debugging using TreeView, the selection indicator under the text in debug TreeView pane below the editor is 1 position too far to the right.
- This PR fixes this bug. See the screenshots below.
- fix after PR #6180 - sorry I didn't notice this issue with that PR.
Tested in the Lexical Playground.

[lexical-react][lexical-dev-tools-core] Bug Fix: TreeView selection indicator

---

packages/lexical-headless/README.md

This is a minor change. I have updated the @lexical/headless/README.md document to replace 'await' with 'async'.

Replace 'await' with 'async' in lexical-headless/README.md

---

scripts/build.js

replace mapping for react-dom to ReactDOM from ReactDOMComet
ReactDOMComet was deprecated 5 days ago to ReactDOM in Meta intern builds

[Lexical] Fix broken sync due to deprecation of ReactDOMComet to ReactDOM

---

packages/lexical-playground/src/nodes/PollNode.tsx

When lexical parse PollNode, you get error `Cannot get getWritable of undefined`.
The reason is that `this` is equal to undefined because of passing addOption function as an argument.
Add a poll to initial state
Get error on init, no poll content inside

[lexical-playground][lexical-poll] Bug Fix: Fixes undefined context inside Poll add option

---

packages/lexical-playground/src/nodes/PollNode.tsx

Reverts facebook/lexical#6361 Sorry, didn't see the CLA wasn't signed. Apologies. Reverting.

Revert "[lexical-playground][lexical-poll] Bug Fix: Fixes undefined context inside Poll add option"

---

packages/lexical-markdown/src/MarkdownImport.ts

Issue #6325 is about inconsistent conversion regarding whitespace trim.
markdown -> string: does not trim whitespace
string -> markdown: trims whitespace
the whitespace trim was introduced in https://github.com/facebook/lexical/pull/2519 , which has a bunch of other markdown improvements.
One goal listed in PR2519 is to make markdown a bit closer to commonmark spec. checking commonmark, it doesnt trim whitespaces on string -> markdown conversion. same behavior for markdown on github. so i guess, it would be more commonmark-ish to not trim whitspaces.
hi @fantactuka ! May i check with you if theres any dangers to not trim whitespaces?
Closes #6325
https://github.com/facebook/lexical/assets/19604232/2758640c-c63f-46da-bebe-81fa21c7fef6
string -> markdown: trims whitespace …

[lexical-markdown] Feature Change: Dont trim whitespaces on convertFromMarkdownString

---

packages/lexical-devtools/src/serializeEditorState.ts
packages/lexical-table/src/LexicalTableUtils.ts
packages/lexical-website/docs/concepts/selection.md

The selection docs, some invariants, and comments still referenced the old GridSelection. This updates them with the new TableSelection.
Closes #5899
No change in behavior is expected, although some invariant error messages will change.

[lexical][lexical-table] Chore: Replace references to old GridSelection with TableSelection

---

packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/plugins/TableHoverActionsPlugin/index.tsx
packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts

Recreate the Experimental Table Hover Action Buttons for the Classic Table as a standalone playground plugin.
Clean up some of the remnants from the original implementation that was deleted a year ago.
https://github.com/facebook/lexical/assets/7893468/cf12e22b-687d-4988-a2f5-2ec251178b9c

[lexical-playground] Table Hover Action Buttons

---

packages/lexical-website/src/components/Gallery/Card.js
packages/lexical-website/src/components/Gallery/pluginList.js
packages/lexical-website/src/components/Gallery/styles.module.css

- Add description in the gallery card, 
- Add option in plugin list config to render preview card at run time if no image
- Add collab example

[Lexical][Gallery] Add description in the card, option to render preview card at run time if no image

---

packages/lexical-playground/src/plugins/TableHoverActionsPlugin/index.tsx

Had an annoying bug in the Table Hover Actions plugin, where when one hovers over one of the buttons but then clicks the other one, the state was not correct. Fixed.
Before:
https://github.com/facebook/lexical/assets/7893468/2e7f6948-2bf0-4122-ac4f-7ad5374166ef
After: 
https://github.com/facebook/lexical/assets/7893468/5b74cee0-ba2b-407c-b6d9-24803c79403a

[lexical-playground] Fix Table Hover Actions Noclick Bug

---

examples/react-plain-text/src/App.tsx
examples/react-rich/src/App.tsx

Looks like #6088 missed rewriting two default imports of LexicalErrorBoundary in the react examples (or there was a regression?)
See also #6253
The react-plain-text and react-rich examples should still work.

[examples] Chore: Use named export of LexicalErrorBoundary in the examples

---

packages/lexical-utils/src/__tests__/unit/LexicalEventHelpers.test.tsx
packages/lexical/src/nodes/LexicalLineBreakNode.ts

On copy past of text with content type `text/html` (e.g. from google docs), line breaks inside of paragraphs are ignored. The HTML looks like this (I removed styling attributes for better overview):
```html
<html>
<body>
<meta charset="utf-8">
<b>
<br />
<p dir="ltr">Test1</span><span><br /></span><span>Test2</span></p>
<p dir="ltr">Test3</span></p>
</b><br class="Apple-interchange-newline">
</body>
</html>
```
The first line break (before p tag) is recognized correctly.
The second line break (which is embedded between Test1 and Test2 in the first paragraph) gets lost.
The line break is inserted correctly, no matter where it was placed.
Closes [#5592](https://github.com/facebook/lexical/issues/5592)
https://github.com/facebook/lexical/assets/10629407/f1482eec-b412-4308-b441-5d386d82a807 …

[lexical][lexical-playground] Bug Fix: Create line break on paste of content type text/html

---

packages/lexical-playground/src/plugins/TableHoverActionsPlugin/index.tsx

For some reason, this isn't breaking in main but it breaks for me in #6384. The error seems clear though.

Fix integrity test

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/regression/4697-repeated-table-selection.spec.mjs

Tagging untagged tests in [flaky test tracker](https://github.com/facebook/lexical/discussions/6289)
These are tests that failed on the ci due to flakiness
only added 
```
{
tag: '@flaky',
},
```
rest are due to formatting changes

CI: tag flaky tests

---

packages/lexical-react/src/shared/LexicalContentEditableElement.tsx
packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

When we introduced the `if` condition in https://github.com/facebook/lexical/pull/5070 we missed the `null` case.

Fix clear rootElement on React

---

packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Fixes an issue where Shift + Down Arrow selects only the first table in a table sequence. The fix ensures that the selection extends to include the next table(s) in sequence.
Shift + Down Arrow selects only the first table.
https://www.loom.com/share/05d1f521688f48098dc4aa63eb4060f0?sid=46796142-ba1f-45f8-aef9-ff9a0ec44074
Shift + Down Arrow includes the next table in the selection.
https://www.loom.com/share/b01ca74cfb6940e78fc321dbe794a67e?sid=c45fd210-7b36-48d4-b9c5-d13e794a8dbb

[lexical-playground][lexical-table] Bug Fix: Fix `Shift`+ `Down Arrow` regression for table sequence.

---

packages/lexical-html/src/index.ts
packages/lexical-utils/src/__tests__/unit/LexicalEventHelpers.test.tsx
packages/lexical/src/__tests__/unit/HTMLCopyAndPaste.test.ts

An empty block node (eg. `<div></div>`) in between 2 inline nodes in html places the next inline node on the next line, acting as a linebreak. lexical currently doesnt handle pasting empty block nodes, so there is a missing line break where the empty block node should be.
see test plan for demo.
test cases are added as unit tests 
```
<div>
1
<div></div>
2
</div>
```
---
```
<ol>
<li>1
<div></div>
2
</li>
<li>
</li>
<li>3</li>
</ol>
```

[lexical-html] Feature: support pasting empty block nodes

---

packages/lexical-utils/src/__tests__/unit/LexicalEventHelpers.test.tsx
packages/lexical/src/nodes/LexicalLineBreakNode.ts

Improve br pasting
- ignore only child br in block nodes and not just `<p>`. fixes extra br in `<li>` paste
- ignore last br in block node, since thats what html is doing ([src](https://stackoverflow.com/questions/61907540/when-are-br-elements-ignored-when-within-a-paragraph#:~:text=All%20br%20elements%20at%20the,elements%20has%20to%20be%20ignored.)) 
---

[lexical] Bug Fix: more accurate line break pasting

---

packages/lexical/src/LexicalEditor.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

Restores the null call I removed in #6389, unfortunately it's a breaking change. Products are using this to do the teardown. For example:
```
if (prevElement !== null) {
prevElement.removeEventListener('click', handleClick);
prevElement.removeEventListener('pointerdown', handlePointerDown);
}
```
We may need to introduce a new function/signature and always migrate to it. If we were to mimic React this would be intuitive and wouldn't need to return a fake `null` `rootElement`:
```
registerRootListener(prevElement, nextElement) {
return () => {
if (prevElement !== null) {
prevElement.removeEventListener(...);
}
```

Restore registerRootListener null call

---

packages/lexical/src/LexicalUtils.ts

A spread with a Map/Set won't transpile well internally.

Fix transpile nodesOfType

---

.github/workflows/call-e2e-all-tests.yml

to see if putting flaky test in a less crowded run helps with the flakiness since most of the flaky tests are on firefox
wait for CI to run, there should be a FF job for flaky test

CI: run flaky tests on firefox browsers

---

.github/workflows/call-integration-tests.yml

This updates node version to the latest LTS `20.15.1` on integrations tests workflow due to the regression in the latest astro `4.11.6`.
Should other tests be updated as well now?
Closes #6413 
run integrations tests

CI: fix build failure on astro integration tests

---

packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx
packages/lexical/src/__tests__/utils/index.tsx

If the `discrete` flag was part of a nested update it was being ignored. Instead, the correct behavior is that this update and the previously computed updates should be flushed.

Fix discrete nested updates

---

packages/lexical-website/docs/collaboration/react.md

Replace "borwsers" with "browsers."

fix(docs): correct typo in Lexical collaboration guide

---

packages/lexical-website/docs/intro.md

docs: fix typo in editor.registerCommand() usage

---

packages/lexical-playground/src/plugins/DraggableBlockPlugin/index.tsx
packages/lexical-react/flow/LexicalDraggableBlockPlugin.js.flow

[lexical-react] update flow typing for draggable block plugin

---

packages/lexical-playground/src/plugins/TableCellResizer/index.tsx

The `TableCellResizer` plugin registers mouse events on the document, but if there are multiple editors on the page they all receive events causing the inactive editors to throw `TableCellResizer: Table cell node not found.` errors and leading to the inactive editors becoming unresponsive.
Changed the plugin to register events on the editors root element so that events are only raised and handled by the editor the mouse is over.

[lexical-playground][TableCellResizer] Bug Fix: Register event handlers on root element

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical-history/src/__tests__/unit/LexicalHistory.test.tsx
packages/lexical-history/src/index.ts
packages/lexical-html/src/index.ts
packages/lexical-react/src/LexicalContentEditable.tsx
packages/lexical-react/src/LexicalHistoryPlugin.ts
packages/lexical-selection/src/__tests__/unit/LexicalSelection.test.tsx
packages/lexical-selection/src/index.ts
packages/lexical-selection/src/lexical-node.ts
packages/lexical-utils/src/index.ts
packages/lexical-website/src/components/Gallery/utils.tsx
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalNode.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts

* Targeted fix for lexical-history's `TextNode` change detection when only one text leaf is dirty but unchanged
* Add delay option to HistoryPlugin
* Fix `$cloneWithProperties` - the previous implementation did not correctly handle `__textFormat` from `ParagraphNode`. Also updated the very incorrect doc string.
* Clean up lint and test warning issues elsewhere
* Move `$cloneWithProperties` to the lexical package because the correct implementation was already inlined in `LexicalNode.getWritable()`
A more general fix may be possible, it's unclear whether this hack is really necessary for MaxLengthPlugin but other text node transforms may have similar issues so removing the hack could be backwards incompatible.
Closes #6409
History's TextNode change detection did not work correctly for …

[lexical-history][lexical-selection][lexical-react] Fix: #6409 TextNode change detection

---

packages/lexical-selection/src/__tests__/unit/LexicalSelectionHelpers.test.ts
packages/lexical-selection/src/lexical-node.ts
packages/lexical/src/index.ts

There is an issue in Lexical where token and segmented text nodes are not correctly handled during text styling operations. This results in improper formatting / node splitting, leading to unexpected behaviour.
After some debugging, I saw that it is handled correctly in the `RangeSelection` class, but not in the helper method used to patch the text style.
https://github.com/facebook/lexical/blob/2c90ee08e6cb9a073ed4cb7a9fca3c8f273d9f47/packages/lexical/src/LexicalSelection.ts#L1136-L1182
Closes #6427 
1. Added `$isTokenOrSegmented` to the list of exported utilities.
2. Updated `$patchStyleText` function: Adjusted logic to prevent splitting of token/segmented nodes

[lexical][lexical-selection] Bug Fix: Respect mode when patching text style

---

.github/workflows/after-approval.yml
.github/workflows/tests-extended.yml
.github/workflows/tests.yml

- ignore running unit/integerity/e2e tests on examples folder code
- examples are not impacting the real package code and shouldn't be triggering running of e2e/unit tests, similar to website

[Lexical][CI] ignore running unit/integerity/e2e tests on examples folder code

---

packages/lexical-website/src/components/Gallery/pluginList.tsx

add tablePlugin example to gallery

[Lexical][Gallery] Add tableplugin example to gallery

---

packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

Follow-up to #6357
When an editor is still initializing the this._editorState may be writable but will only have the 'root' entry. We need to special case this to prevent an exception if a mutation listener with initialization is registered before the first reconciliation.
The unit test covers this case and will fail without the change

[lexical] Bug Fix: getCachedTypeToNodeMap should handle a empty and writable EditorState

---

.github/workflows/call-e2e-test.yml

see https://github.com/facebook/lexical/actions/runs/10090883909/job/27901243336?pr=6458 as example
when a flaky job fails, a cancel signal is sent out to other jobs. the tests in flaky job are likely to fail due to flakiness so we should not let that cancel other job runs.
(also hoping flaky job failures would not fail the overall PR check signal but lets see)
context on flaky job: it should be a non blocking job to isolate known flaky test. it gives clearer signal if a test is failing due to a known flaky test
see how the ci goes.
when one flaky job fail it should not trigger a cancel signal for other jobs

CI: dont cancel other test runs if e2e flaky job fails

---

packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalNode.ts
packages/lexical/src/__tests__/unit/LexicalNode.test.ts
packages/lexical/src/nodes/LexicalDecoratorNode.ts
packages/lexical/src/nodes/LexicalElementNode.ts
packages/lexical/src/nodes/LexicalTextNode.ts

Allows `getTopLevelElement` to return a `DecoratorNode` from `LexicalNode`, and uses declaration merging to return a more specific type when called from an `ElementNode`, `TextNode`, or `DecoratorNode`. I couldn't get it to work in a "cleaner" way than declaration merging.
With TypeScript I was able to get the type to be exactly `this | ElementNode | null` for `DecoratorNode.getTopLevelElement` but with Flow it's just `DecoratorNode<mixed> | ElementNode | null`. Flow claimed that `DecoratorNode<mixed>` wasn't compatible with `DecoratorNode<T>` but it really should be in return position like that, and I don't have enough recent flow experience to track down why or if it's possible to get it to return the more precise result.
This PR also applies the fix at the value and type level to …

[lexical] Bug Fix: Allow getTopLevelElement to return a DecoratorNode

---

.github/workflows/call-e2e-all-tests.yml

- run extended tests for safari in mac-os and chrome/firefox in linux/windows
- follow up on suggestion in discord 
https://discord.com/channels/953974421008293909/1179904979587301387/1266354720356827170
- run only safari tests in mac-os
- for tests like react-beta, etc which are only run in mac-os/chrome change to ubuntu/chrome

[Lexica][CI] run extended tests for safari in mac-os and chrome/firefox in linux/windows

---

packages/lexical-table/src/LexicalTableObserver.ts

Now table observer doesn't listen to table DOM element attibutes updates. So when attempting to extend table node with features that require table element attibute updates (for example adding/remoing classes to table element) it won't re-render table.
This change will enable observer to listen to attibutes changes as well as to changes in children.
Closes #6410
Here's documentation about mutation observer: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe
[attributes](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe#attributes) is set to `false` by default and setting it to `true` will watch for changes to the value of attributes on the node or nodes being monitored.
In case we can't enable all attibutes, it should be possible to upgrade …

[lexical-table] Bug Fix: Enable observer updates on table elements attributes change

---

packages/lexical-playground/src/index.css

fix lexical PlaygroundEditor Theme  blockCursor show
RE #6459
not need test
not need test

[@lexical/playground] fix: block cursor show horizontal

---

packages/lexical-playground/src/index.css

Reverts facebook/lexical#6486
RE #6459
The horizontal cursor is desired in cases where the selection would otherwise be visually ambiguous. This can be reproduced by clearing the editor, creating a table node, selecting before the table node, and pressing up to get a selection at the root node.
Before revert:
https://github.com/user-attachments/assets/5ffdc126-0d8b-47c3-8c94-6d3ad9473b88
After revert:
https://github.com/user-attachments/assets/16c41142-26e2-47ab-9235-1a4d4e61d748

Revert "[@lexical/playground] fix: block cursor show horizontal"

---

packages/lexical-devtools-core/src/generateContent.ts
packages/lexical-devtools/src/utils/isLexicalNode.ts
packages/lexical-playground/vite.config.ts
packages/lexical-playground/vite.prod.config.ts
packages/lexical-react/src/LexicalCheckListPlugin.tsx
packages/lexical-website/docs/concepts/listeners.md
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts
scripts/__tests__/integration/fixtures/lexical-esm-astro-react/package.json
scripts/__tests__/integration/fixtures/lexical-esm-nextjs/package.json
scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/package.json
scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/tests/test.ts
scripts/__tests__/integration/setup.js
scripts/build.js
scripts/updateVersion.js

New `LexicalEditor.version` static to help users diagnose installation issues.
Also refactors other `__lexicalEditor` code to avoid conflicts with multiple lexical builds on the page (RE #6481)
Inspecting the lexical editor's version can be done as follows (example assumes exactly one editor on the page):
```
> document.querySelector('[contenteditable]').__lexicalEditor.constructor.version
'0.17.0+dev.esm'
```
It does not have support for coming up with special build identifiers for the versions of lexical we build in CI and for the website that do not correspond to npm versions.
Closes #6145
Closes #5996
There's an integration test that checks to make sure the version is set and accessible from the editor instance
```
> oldLexical.createEditor().constructor.version
undefined
> …
```

[lexical] Feature: Add version identifier to LexicalEditor constructor

---

packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

The tooltip previously displayed the wrong keyboard shortcut for redo
Closes #6495

[lexical-playground] Bug Fix: Update tooltip for redo button with correct macOS shortcut

---

packages/lexical/src/nodes/LexicalTextNode.ts
packages/lexical/src/nodes/__tests__/unit/LexicalTextNode.test.tsx

When `splitText` is run on a Node with no parent it crashes. I don't see any obvious reason why this function should only work on attached nodes and there are some valid cases when you'd want to attach the resulting nodes later and leverage `splitText` to preserve the styling and format.

Fix splitText when detached

---

packages/lexical/src/LexicalNode.ts
packages/lexical/src/__tests__/unit/LexicalNode.test.ts

The fix in #5948 introduced a crashing regression because the logic doesn't short-circuit when an empty element is encountered.
Closes #6506
Crash happens after these conditions:
* Clear playground
* Insert blank line (creating empty paragraph node)
* Insert image (in a second paragraph)
* Select all
[sample url - must select all after clicking this](https://playground.lexical.dev/#doc=H4sIAAAAAAAAE72Qy2rDMBBF_-WuRaIkpC7aFroOuNBF6WKwJpZAtoQ0zoPgfy-J05Jm1ULpahiYM_dwT2DrJeZaSBjmhByjnGfjfLCZe5i3b8u7gvWZG_Gxh-mHEBS2MXckMICC7y33AqMV5JgYBokytZmSg8KOc7mACwXhgzxfST2ttRzDGcGo7gwoyAsfrhkNpSn-9AP73wtfnty6juOo4Ni3brrr6PDqrTiYtdYKxcX906fSlkJhhZIbGDiRVMx8nnxThm6WXJRY5kut8RXmO2r5rpn99FyP_1T2n1SkEKhITTu2MItquVo-VOtV9VhVCiUOuTlzm0DHNseht7c09GxRzTTGD_nMaJKOAgAA)
<details>
<summary>
example exception …

[lexical] Bug Fix: Fix decorator selection regression with short-circuiting

---

packages/lexical/src/LexicalReconciler.ts

since 25 jul, observing a high number of `The node to be replaced/removed is not a child of this node` errors, at the following 2 lines where im adding logging. These errors spiked on 6 Aug but have since died down (on its own) to ~ 2 errors a daily
i've not been able to reproduce those errors so surfacing more details in the error msg to get more clues
i made sure to only surface privacy safe details in the error
fix attempt: https://github.com/facebook/lexical/pull/6513
threw a new error there to emulate the error. 
to trigger that line, replace an entire paragraph node, eg. pasting over the entire paragraph node

[lexical] surface more error details in reconciler

---

packages/lexical-website/docs/concepts/nodes.md
packages/lexical-website/docs/concepts/serialization.md
packages/lexical/src/LexicalNode.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/__tests__/unit/LexicalNode.test.ts
packages/lexical/src/nodes/LexicalElementNode.ts
packages/lexical/src/nodes/LexicalParagraphNode.ts
packages/lexical/src/nodes/LexicalTabNode.ts
packages/lexical/src/nodes/LexicalTextNode.ts

The code path for cloning lexical nodes is a bit weird with some branching for different node types and no extensibility. We can clean it up by moving that part of the clone process to an instance method.
Unlike #3920 this does not try and make a generic clone method, the boilerplate is still there – but all for good reason. It's at least 2-3x faster to have the boilerplate than to use `Object.create`, `Object.assign`, etc. presumably due to JIT de-optimization reasons. Using the constructor in this way (the status quo) also prevents sharing of mutable objects that could happen unintentionally with a shallow clone of all properties.
This changes the `$cloneWithProperties` function to first call `latestNode.constructor.clone(latestNode)`, then call `mutableNode.afterCloneFrom(latestNode)` …

[lexical] Refactor: [RFC] LexicalNode.afterCloneFrom to simplify clone implementation

---

.eslintignore
.prettierignore
packages/lexical-react/flow/LexicalComposer.js.flow
packages/lexical-react/flow/LexicalContentEditable.js.flow
packages/lexical-react/src/LexicalComposer.tsx
packages/lexical-react/src/LexicalContentEditable.tsx

The `editor__DEPRECATED` prop has been deprecated for two years (#1407), this PR removes it.
There were no tests for this feature, and its absence does not need new tests.

[lexical-react] remove editor__DEPRECATED that has been deprecated for two years

---

packages/lexical-overflow/src/index.ts

Reverts facebook/lexical#6027
OverflowNode causes problems with LineBreakNode with this configuration change, causes the tests to fail in plain text mode (the insertion point always ends up *before* the trailing LineBreakNode) but the same strange behavior comes up if you press shift-return to insert a LineBreakNode into a ParagraphNode in rich text mode. I think we will need to revisit #6027 with additional tests.
Closes #6534
/cc @zurfyx @ivailop7

Revert "Fix OverflowNode configuration"

---

packages/lexical-table/src/LexicalTableNode.ts

Quickfix for #6515
As described in the issue currently changing the selection using the arrow keys can throw an error that crashes the editor.
(Error: `Uncaught Error: Node at cords not TableCellNode.`)
- Closes #6515
- Closes #6519 (duplicate)
This quickfix works quite well for merged cells at the end of a row (most common cases imo)
For merged cells at the beginning or the middle of a row this simple approach creates some unexpected cursor jumps. But instead of crashing the user can be easily adapt the position and the editor won't break.
(For a full fix the positions would need to consider the colspan everywhere in the table plugin, that would be a bigger refactoring I guess).
I did check where this function is used and did some manual …

[lexical-table] Bug Fix: Selection in tables with merged cells

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/lexical/ListsCopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/HorizontalRule.spec.mjs
packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-playground/__tests__/e2e/Tab.spec.mjs
packages/lexical-playground/__tests__/e2e/TextFormatting.spec.mjs
packages/lexical-playground/__tests__/regression/429-swapping-emoji.spec.mjs

We still have a lot of tests that are flaky, which is a considerable burden on contributions and reviewing them. This is just the ones that flaked in #6535 on this particular run https://github.com/facebook/lexical/actions/runs/10481362302/job/29033662935
```
9 flaky
[chromium] › packages/lexical-playground/__tests__/e2e/CopyAndPaste/lexical/ListsCopyAndPaste.spec.mjs:111:3 › Lists CopyAndPaste › Copy and paste of partial list items into the list 
[chromium] › packages/lexical-playground/__tests__/e2e/HorizontalRule.spec.mjs:30:3 › HorizontalRule › Can create a horizontal rule and move selection around it 
[chromium] › packages/lexical-playground/__tests__/e2e/Links.spec.mjs:1926:3 › Links › Can handle pressing Enter inside a Link 
[chromium] › …
```

[*] Chore: Mark additional tests as flaky from #6535 test runs

---

packages/lexical-devtools-core/src/TreeView.tsx
packages/lexical-react/src/LexicalTreeView.tsx

The `<TreeView />` component is primarily intended for debugging, but currently, all of its props are required. It would be more convenient if the className prop were optional.

Chore: change className props in TreeView component to optional

---

packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Fixes #5656
Upon pasting a cells selection in a table when the target area is not a cells selection inside a table, it would select the whole table after the paste event. It worked correctly (not select the whole table) if the selected area to paste to was a cells selection.
Before:
https://github.com/user-attachments/assets/b6e75f2e-2ede-4da4-8ba4-2839c0b194c3
After:
https://github.com/user-attachments/assets/87d209f3-0feb-4833-a7b1-34193852d1f2

[lexical-table] Stop selecting the whole table after pasting cells

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Triple-clicking may seem esoteric at first but it's a relatively common interaction for quickly selecting whole blocks. For example, triple clicking a paragraph selects the entire paragraph (at least on macOS).
We were seeing a strange issue for some of our users: their entire document would go missing. When we worked with some of these users, we found that previous revisions of their doc showed that it consisted of only a single large table.
After it happened to one of our team members, we found that it was very easy, particularly on mobile, to accidentally select the entire table while trying to tap a single cell to edit. It's my theory that when tapping very rapidly on mobile, a triple-click event gets processed.
Nonetheless, it's easy to replicate this issue on desktop in the …

Bug Fix: Fix issue where triple-clicking a cell would dangerously select entire document

---

.github/workflows/call-e2e-test.yml
packages/lexical-playground/__tests__/e2e/Selection.spec.mjs

Fix firefox e2e test regression at packages/lexical-playground/__tests__/e2e/Selection.spec.mjs:651:3 (added in #6542, unclear what else in the merge queue caused this to happen?)
e2e tests fail in unrelated PRs
e2e tests pass

[lexical-playground] Bug Fix: Fix firefox e2e test regression in Selection.spec.mjs

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical-clipboard/src/index.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

`@lexical/clipboard`:
* Added new `type LexicalClipboardData`, `$getClipboardDataFromSelection` and `setLexicalClipboardDataTransfer` to make it possible to serialize a selection outside of the async event handling flow
* Added optional `selection` parameter to `$getHtmlContent`, `$getLexicalContent`
* Added optional `data` parameter to `copyToClipboard` so that `$getClipboardDataFromSelection` can be called to capture the selection's clipboard data at the right time
`@lexical/table`:
Fix race condition in `CUT_COMMAND` listener where the selection was deleted before the contents are copied, using the new `@lexical/clipboard` functionality to ensure that the clipboard data is captured before asynchronous processing of the copy event in `copyToClipboard`
Closes #6544
See #6544, this solves …

[lexical-table][lexical-clipboard] Bug Fix: Race condition in table CUT_COMMAND

---

packages/lexical-table/src/LexicalTableSelection.ts
packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx

Fixes #6541
Before:
Double pasting incorrectly, since it was reading all nodes - rows and cells.
https://github.com/user-attachments/assets/8ddb613e-1a6b-4985-8052-ff51b9b20982
After:
Pasting correctly, since reading only cells.
https://github.com/user-attachments/assets/c1484903-388a-4f96-86f7-fb97322cd8cc

[lexical-table] Fix table selection paste as plain text

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/src/LexicalTableUtils.ts

ParagraphNodes(p tag) are missing in the unmerged cells, except fot the first one.
Some behaviors like pasting or inserting a new line in the cells do not work. This fix appends a ParagraphNode to each cell when unmerging.
Closes #6552 
https://github.com/user-attachments/assets/01b4427a-498c-49ce-a068-151c1789ee70
https://github.com/user-attachments/assets/d95245ea-0120-49a8-abce-a37cbad4286e

[lexical-table] Bug Fix: Append a ParagraphNode to each cell when unmerging

---

packages/lexical-playground/src/commenting/index.ts
packages/lexical-playground/src/plugins/CommentPlugin/index.tsx

When adding collaborative comments in the playground, the comment timestamps are now consistent even in different window contexts.
Closes #6554
Follow the reproduction steps in issue #6554 and see that the comment timestamps are now the same.
Comment timestamps are inconsistent in different window contexts.
Comment timestamps are the same in different window contexts.
There are other uses of `performance.now()` in this repo that might need to be reviewed.

[lexical-playground] Bug Fix: fix comment timestamps

---

packages/lexical-table/package.json

0.17.1 added a @lexical/clipboard dependency in @lexical/table but it was not declared in package.json
Closes #6569
Undeclared dependencies in @lexical/table could potentially cause a package manager to generate an incorrect lockfile
It should no longer be possible for that error to occur

[lexical-table] Bug Fix: Add @lexical/clipboard as a direct dependency of @lexical/table

---

packages/lexical-react/src/shared/LexicalMenu.ts

https://github.com/facebook/lexical/pull/6510 is correct but it broke implementations internally
hence it got reverted to mitigate the internal emergency: https://github.com/facebook/lexical/pull/6558
here, https://github.com/facebook/lexical/pull/6510 is reintroduced but gated behind the shouldIncludePageYOffset option to aid investigations internally and to fix internal to be compatible 
shouldIncludePageYOffset = true
https://github.com/user-attachments/assets/8721cc41-3486-4b0b-83c3-008b3ec4c173
---
shouldIncludePageYOffset = false
https://github.com/user-attachments/assets/db950846-7989-4489-9a33-36ef59cd0ceb

[lexical-react] menu positioning: Unrevert PR6510 but with gating

---

packages/lexical-yjs/package.json
scripts/build.js

It's easy to add inter-package dependencies in the monorepo that can cause problems for npm users.
Closes #6572
Packages could have undeclared inter-package dependencies that go unchecked
The build fails when these inter-package dependencies are not declared
```
❯ npm run build
> @lexical/monorepo@0.17.1 build
> node scripts/build.js
Error: packages/lexical-yjs/src/SyncCursors.ts has an undeclared dependency in its import of @lexical/selection.
Add the following to the dependencies in packages/lexical-yjs/package.json: "@lexical/selection": "0.17.1"
```

[*] Feature: Check undeclared dependencies in build

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/TablesHTMLCopyAndPaste.spec.mjs
packages/lexical-react/src/LexicalTablePlugin.ts

This PR fixes the issue with empty cells getting incorrectly added to a table upon paste.
When a table with rows with unequal sizes and merged cells is pasted, we add the empty cells in the wrong row.
For example, a table like this: 
Empty cells are now added to the correct row.

[lexical-react]: Fix incorrect addition of empty cells on table paste

---

.github/workflows/call-e2e-test.yml

Playwright test results on Windows are not being uploaded to GitHub artifacts when a test fails.
```
Run actions/upload-artifact@v4
Warning: No files were found with the provided path: ~/.npm/_logs/. No artifacts will be uploaded.
```
It was refactored here: https://github.com/facebook/lexical/pull/6029
You can see examples of failed tests not uploading the .webm files here:
- https://github.com/facebook/lexical/actions/runs/10533193071/job/29188769482#step:11:96
- https://github.com/facebook/lexical/actions/runs/10668949805/job/29569803459?pr=6579#step:11:19
The playwright run log shows it's saving the video to `test-results/` and not `~/.npm/_logs/`
attachment #1: video (video/webm) ────────────────────────────────────────────────────────────── …

Fix test results CI path on Windows

---

packages/lexical-table/src/LexicalTableSelectionHelpers.ts

[lexical-table] Fix Table Cut Event Handling

---

packages/lexical-code/src/CodeHighlighter.ts
packages/lexical-playground/__tests__/e2e/Tab.spec.mjs

Steps to replicate:
1. Type `Foo` in editor
2. Press Tab key on keyboard
3. Press cmd/ctrl + left arrow to go to start of line (note: left arrow and _not_ backspace)
Result:
> Uncaught Error: Expected a valid Code Node: CodeHighlightNode, TabNode, LineBreakNode
(In prod environments: `A lexical error occurred Error: Minified Lexical error #167; visit https://lexical.dev/docs/error?code=167`)
In our application, we show a blocking modal whenever a Lexical editor exception is caught, so that the user does not corrupt their document, particularly in a collaborative context, where we do not want to sync up corrupt state to other users.
It's not clear why the [getStartOfCodeInLine](https://github.com/facebook/lexical/blob/main/packages/lexical-code/src/CodeHighlighter.ts#L80) function requires …

Fix issue where cmd/ctrl + left arrow after a tab character would cause exception

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-table/flow/LexicalTable.js.flow
packages/lexical-table/src/LexicalTableCellNode.ts
packages/lexical-table/src/LexicalTableSelection.ts
packages/lexical-table/src/LexicalTableUtils.ts

* Ensure that `TableSelection.getNodes` returns each node at most once, which fixes logic errors in merge code when the "first cell" shows up multiple times due to merge
* Account for `colSpan` and `rowSpan` in `TableSelection.getShape`
* Fix some inconsistencies with the implementation of `TableCellNode`
* Use a heuristic for setting table cell styles when unmerging cells
* Add a mask for TableCellNode.setHeaderStyles so that the row or column style can be explicitly set without affecting the other setting
* Remove restriction on merging "weird shapes" of table cells, all selections are rectangular and can be merged
* Workaround in `$computeTableMapSkipCellCheck` for non-rectangular tables with rowSpan below the last `<tr>` in the table. Someone who cares more about these edge cases with …

[lexical-table][lexical-playground] Bug Fix: Fix merged cell related edge cases

---

packages/lexical-playground/src/nodes/PollNode.css

Poll option was not clickable after the checked state due to pseudo after element. Added `pointer-events:none` to let the events pass through the pseudo elements on checkbox change 
Closes #6551 
https://d.pr/i/vHvKcU
https://github.com/user-attachments/assets/87bf261d-9bff-4f5a-a76f-5f48bfd1eae2

[lexical-playground] Fix: Poll Option not clickable at some place after checked state

---

packages/lexical-selection/flow/LexicalSelection.js.flow
packages/lexical-selection/src/index.ts

There is a need to use `getCSSFromStyleObject` together with `getStyleObjectFromCSS` in order to change a specific style that is applied to a node with `setStyle`. 
`getStyleObjectFromCSS` is available in the @lexical/selection package but not `getCSSFromStyleObject` even though the function exists in the utils file. 
This PR is simply exposing this function that already exists.

Expose getStyleObjectFromCss in @lexical/selection

---

packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-markdown/src/index.ts
packages/lexical-markdown/src/utils.ts
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs

In markdown, the concept of "empty paragraphs" does not exist.
Blocks must be separated by an empty line, and non-empty adjacent lines must be merged.
Let's take this markdown as an example:
```md
one
two
three
```
Currently, it is converted to the following (incorrect):
```html
<p>one<br>two</p>
<p>three</p>
```
When in fact, the correct output should be this ([proof](https://github.com/payloadcms/payload/issues/8049)):
```html
<p>onetwo</p>
<p>three</p>
```
For context, we are trying to import real `mdx` files into Lexical, and because of this issue, the current output contains some errors, such as [this one here](https://github.com/payloadcms/payload/issues/8049).
At first I thought it would be enough to remove all single line breaks (`\n`), which were not accompanied by further …

[lexical-markdown] Fix: normalize markdown in $convertFromMarkdownString to comply with CommonMark spec

---

packages/lexical-website/docs/concepts/node-replacement.md
packages/lexical-website/docs/concepts/serialization.md
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/__tests__/unit/LexicalUtils.test.ts

Specifying the key argument incorrectly in a replacement function is a common mistake. This PR adds a helpful invariant and improves the error messages in the existing invariants for `$applyNodeReplacement`.
It was possible to write code that behaves incorrectly in subtle ways without a clear error message if you wrote a replacement function that preserved a node's `__key` incorrectly, e.g. https://discord.com/channels/953974421008293909/1278046226100654243
Invariants will throw an error early if this type of mistake is made with enough information to fix it.

[lexical] Chore: Add more helpful invariants to $applyNodeReplacement

---

packages/lexical-markdown/flow/LexicalMarkdown.js.flow
packages/lexical-markdown/src/MarkdownShortcuts.ts
packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-markdown/src/utils.ts

to be consistent with other types like `text-match`, `text-format`
see automated tests

[lexical-markdown] Breaking Change: rename 'multilineElement' to 'multiline-element'

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

This fixes a [regression](https://github.com/facebook/lexical/pull/6542#issuecomment-2318374970) caused by [this PR](https://github.com/facebook/lexical/pull/6542).
The PR above aimed to solve a destructive issue where triple-clicking in a table could inadvertently select the entire document. The solution caused a regression where dragging out from inside a table wouldn't select the entire table, even though the highlight made it seem like it was selected.
I spent a bit of time trying to fix both the regression and the original triple-click issue but unfortunately had to reach a compromise where I could fix the regression, and fix the triple-click issue, with the compromise that triple-clicking the last cell would end up selecting the first cell (rather than the whole document). That's …

Bug Fix: Fix issue where selecting a cell then dragging outside of table would not select entire table

---

package-lock.json

https://github.com/advisories/GHSA-952p-6rrq-rcjv?fbclid=IwZXh0bgNhZW0CMTEAAR1-F3hq4wRW-qOIChOFDGEzEyBnb8xYVe6tgWjuAzkJUZSwTvlR8d7NjuA_aem_miRrWL4kXpjCaEqbmreXgA
update to version 4.0.8 to address vulnerabliity
ran `npm update micromatch` 
see automated tests

address micromatch vulnerability

---

packages/lexical-react/src/shared/useYjsCollaboration.tsx

`connect` can be an asynchronous function, and we don't take this into account when disconnecting, meaning that it is possible to disconnect without completing the connect. 
I think this can lead to various side effects, such as being disconnected but still in the connect state.
In my case, this happened in `React.StrictMode`, which is a bit unusual.
It's a simple code change, so I don't think test code is necessary.

[lexical-react] Refactor: Ensure disconnect is called after connection is established in useYjsCollaboration

---

packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-markdown/src/index.ts
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs

This reverts commit 8123ca7c5aef4d35ede68457f1799f7315b80bd1.  
[The PR](https://github.com/facebook/lexical/pull/6608) introduced a regression in converting tables <-> markdown
sorry @GermanJablo , hope it is alright with you if we revert this for now to patch the regression asap. happy to remerge https://github.com/facebook/lexical/pull/6608 once there is a fix for the table <-> markdown conversion
https://github.com/user-attachments/assets/160f8f6a-3cb4-475f-a3e4-34de0a12580c
https://github.com/user-attachments/assets/1321c45f-55e7-4f00-9109-025765701b5a

Revert "[lexical-markdown] Fix: normalize markdown in $convertFromMarkdownString to comply with CommonMark spec (#6608)"

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/src/plugins/TableCellResizer/index.tsx

When table cells are merged (either vertically or horizontally) and you try to resize them, it resizes the row or column of the top/left cell.
Update the index to account for colspan and rowspan so the correct column/row is resized.
Closes #6623
https://github.com/user-attachments/assets/75333ad5-c0fa-4800-b3c6-25d932d8b8df
https://github.com/user-attachments/assets/473d6d33-f467-4e16-afbb-8bc947367c7d

[lexical-playground] Bug Fix: Fix table row/column index when resizing merged cells

---

packages/lexical-table/src/LexicalTableObserver.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/nodes/LexicalParagraphNode.ts

*Apply format change to empty paragraphs. Before it was only applied to text nodes*
Closes #[6583](https://github.com/facebook/lexical/issues/6583)
Formatting is not applied to empty paragraphs
Formatting is applied to empty paragraphs

[lexical-table]  Bug: Table formatting and styling not persisting for empty cells

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawImage.tsx
packages/lexical-playground/src/nodes/ExcalidrawNode/index.tsx

When resizing an Excalidraw image within the Lexical editor, the new dimensions are not preserved after certain editor actions. For example, try moving the cursor just to the left of the image and pressing Enter. This will cause the image to revert to its original size and a mismatch between the resize box and the image.
1. Updated updateDOM method to ensure than when node is updated the dom reflects the new width and height
2. Update $createExcalidrawNode function to take in data, width, height
1. Retrieved width and height from the node using the new getter methods.
2. Pass width and height to ExcalidrawImage
1. Accepted width and height as props.
2. Apply the dimensions to the container's style
1. Insert an Excalidraw image into the editor.
5. Resize the image to make it larger.
6. …

[lexical-playground][ExcalidrawNode] Bug Fix: Preserve Excalidraw image dimensions after resizing

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/TablesHTMLCopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/Indentation.spec.mjs
packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/e2e/Toolbar.spec.mjs
packages/lexical-playground/__tests__/regression/4661-insert-column-selection.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/TableCellResizer/index.tsx
packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical-table/src/LexicalTableUtils.ts
packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx

This PR adds an optional `colWidths` property to TableNode, which renders a `<colgroup>` element within tables. 
Defining the column widths has 2 main advantages:
1. We can simplify table resizing logic, particularly around merged cell cases.
2. It enables better control of tables with the style `table-layout: fixed`
If using `table-layout: fixed`, you must set a table width. Lexical playground uses `max-content` which masks some issues. If you want to truncate text within the table, the best way is to change the table width to `fit-content` (and add css to truncate). 
However, without a `<col>` element, a table with layout `fixed` will use the first row to determine column widths for the rest of the table. If there are merged cells in the first row, this makes it impossible to correctly …

[lexical-table][lexical-playground] Feature: Add column widths to TableNode

---

packages/lexical-website/docs/intro.md

The word 'nest' shows twice in this sentence and one should be removed:
from: nest nest 
to: nest
Closes #

Grammar Issue - Repeated Word

---

packages/lexical-react/src/shared/useYjsCollaboration.tsx

The PR in #6619 created a regression for local collab development by introducing a timing change in when disconnect was called. When reviewing the PR I didn't think it caused an issue because the deployed playground and CI tests worked fine, but when running the playground locally with vite dev mode it does cause an issue. 
https://github.com/facebook/lexical/pull/6619#discussion_r1754903692
Closes #6640
```
npm run start
npm run test-e2e-chromium # from another terminal
```
All tests fail.
Can also reproduce collab not working at http://localhost:3000/split/?isCollab=true
Note that this only happens when running locally with vite dev, it does not cause any problems in CI or in production.
It all works as expected.

[lexical-react][lexical-playground] Bug Fix: Workaround for yjs disconnect race in React StrictMode

---

packages/lexical-code/package.json
packages/lexical-code/src/CodeHighlightNode.ts
packages/lexical-code/src/CodeHighlighter.ts
packages/lexical-code/src/CodeHighlighterPrism.ts
scripts/__tests__/integration/fixtures/lexical-esm-astro-react/package-lock.json
scripts/__tests__/integration/fixtures/lexical-esm-astro-react/package.json
scripts/__tests__/integration/fixtures/lexical-esm-astro-react/src/env.d.ts

The change in #6562 appears to have triggered an issue with astro's rollup configuration which will treeshake Prism out of @lexical/code, since it is only an import side-effect. Marking the package.json as having sideEffects is sufficient to fix it.
Note that #6650 currently has this commit included so the integration tests pass, but I made it a separate PR in case we want to review/merge separately.
Integration tests in #6650 were failing
Integration tests pass

[lexical-code] Bug Fix: Annotate @lexical/code as having side-effects for Prism

---

packages/lexical-markdown/flow/LexicalMarkdown.js.flow
packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-markdown/src/index.ts

normalize markdown was introduced in https://github.com/facebook/lexical/pull/6629 . one of the significant behavior change this introduced is merging adjacent non empty lines, according to commonmark spec: https://spec.commonmark.org/0.24/#example-177
it is a welcomed change since that brings lexical's impl closer to commonmark. However to avoid breaking current callsites, im making the normalizedMarkdown an option default to true, so it is easier to rollback incase this new behavior causes a regression somewhere downstream
ultimately, if there is no known usecase to have shouldMergeAdjacentLines = false, will look to deprecate  shouldMergeAdjacentLines and have it always be true.
shouldMergeAdjacentLines = true
https://github.com/user-attachments/assets/5ec217e7-49a5-4119-b4c2-7466366fce …

[lexical-markdown] shouldMergeAdjacentLines as an option

---

packages/lexical-playground/src/plugins/ActionsPlugin/index.tsx

when converting an empty editor to markdown codeblock, the codeblock isnt focused and typing puts chars into the editor root instead of the codeblock. does not happen if codeblock is not empty
https://github.com/user-attachments/assets/72495357-304f-45a2-b79b-4f3b28be998d
https://github.com/user-attachments/assets/ce9b595f-ae45-48fb-88ba-ad9ef2ee8b8d

[lexical-playground] Bug Fix: empty code block not focused

---

packages/lexical-markdown/src/MarkdownExport.ts
packages/lexical-markdown/src/MarkdownImport.ts
packages/lexical-markdown/src/MarkdownShortcuts.ts
packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-markdown/src/utils.ts

In my project, I have a `TextMatchTransformer` that I use solely for  node => markdown string exports. For markdown string => node imports I'm using Multiline markdown transformers.
In order to accommodate this without having to pass fake stub properties to the `TextMatchTransformer`, this PR makes all properties optional.
Also added some much-needed JSDocs for this interface

[lexical-markdown]: Refactor: allows omitting certain properties from TextMatchTransformers, adds jsdocs

---

packages/lexical-playground/src/nodes/ExcalidrawNode/index.tsx

In PR #6634, I made a mistake in how the ExcalidrawNode handles DOM creation and updates. I incorrectly added inline styles for width and height directly in the `createDOM` and `updateDOM` methods.
I am reverting the incorrect changes I made.
- After the first resize, for subsequence resizes, the handles don't update onDrag and only update on release.
https://github.com/user-attachments/assets/398cf56b-c573-45dd-9949-686ec7834567
- The resize handles work as expected
- The bug from PR #6634 is still fixed
https://github.com/user-attachments/assets/e5c3b8ce-38cf-4ed0-9e49-ec863fa08d9e

[lexical-playground] Bug Fix: Correct ExcalidrawNode DOM handling for proper resizing

---

packages/lexical-link/src/index.ts

At the moment it is possible to delete LinkNode only when children are TextNode. But if there is another node inside the link above the text, deletion will not work.
With this PR I fix this behavior and show how it works using the MarkNode example (via adding a comment) in lexical-playground
https://github.com/user-attachments/assets/669a5ed9-926d-477c-9f7b-14c2a72d6577
https://github.com/user-attachments/assets/6a56895c-2b08-4862-8787-ba0cef492d2d

[lexical-link] Bug Fix: Removing a link from descendants

---

packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-markdown/src/index.ts
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs

For backwards compatibility, setting default shouldMergeAdjacentLines = false to not introduce breaking change from the previous npm release. 
Github Flavoured Markdown has the same behavior as shouldMergeAdjacentLines = false:
https://github.com/user-attachments/assets/c3dabbf7-d666-44dc-a586-2d03c0a01cec
npm run test-unit
npm run test-e2e-chromium

[lexical-markdown] set shouldMergeAdjacentLines default to be false 

---

packages/lexical-utils/flow/LexicalUtils.js.flow
packages/lexical-utils/src/__tests__/unit/LexicalNodeHelpers.test.ts
packages/lexical-utils/src/index.ts

`$dfs` is handy but not very flexible. The fact that it computes the entire array every time means that it's either all or nothing.
A common use case for a DFS is data format conversion, and data conversion formats that are modular will delegate the processing of a part of the tree to the responsible modules. An iterable version of `$dfs` makes it possible to stop and resume the iteration without paying the redundant cost.
Iterable is not just limited to this one use case, I'm confident that this small addition to the utils library is not a one-off.
This is how the application of this looks like in the wild (not a one-liner but I also don't think we want to overoptimize in one use case).
```
const initialDepth = $getDepth(node);
let iterator = $dfsIterator(initialNode);
let …
```

Iterable $dfs

---

packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-table/src/LexicalTableSelection.ts

Make style buttons in toolbar active for TableSelection
Styles indicators don't change
Styles indicators change when selection includes styled text

[lexical-table][lexical-playground] Bug Fix: Make style buttons in toolbar respect table selection

---

packages/lexical-react/src/__tests__/unit/LexicalCollaborationPlugin.test.tsx
packages/lexical-react/src/__tests__/unit/utils.tsx
packages/lexical-yjs/src/index.ts

The current type definition doesn't include the `setLocalStateField` method, which can lead to TypeScript errors when using this method and prevents proper code completion in IDEs. This change improves type safety and developer experience when working with the `lexical-yjs` package.
This PR adds the missing `setLocalStateField` method to the `ProviderAwareness` type in the `lexical-yjs` package([ref](https://github.com/yjs/y-protocols/blob/master/awareness.js#L141)). This method is present in the actual implementation of awareness providers but was not reflected in the TypeScript type definition.
--
--

[lexical-yjs] Bug Fix: Add missing setLocalStateField method to ProviderAwareness type

---

packages/lexical/src/LexicalSelection.ts
packages/lexical/src/__tests__/unit/LexicalSelection.test.ts

The #6456 removeText rewrite introduced a regression in token mode behavior where it behaved too similarly to segmented nodes, it would be split and replaced with a plain TextNode instead of being deleted in full. This takes the simple approach of just expanding the selection outwards if the focus or anchor node contains any content from a token node.
Closes #6687
There were no tests to show that token TextNode should be deleted in full by removeText
Now there are tests that cover removeText behavior for token TextNode

[lexical] Bug Fix: TextNode in token mode should not be split by removeText

---

packages/lexical-playground/src/plugins/ToolbarPlugin/fontSize.tsx

Closes #6694.
https://github.com/user-attachments/assets/9c05a8a2-dbc1-4b16-8f66-c31e0c6bdc2e
https://github.com/user-attachments/assets/2b4d2483-5269-4595-9f5e-5e9a030a7571

[lexical-playground] Bug Fix: toolbar font size input keyboard accessibility

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx
packages/lexical-playground/src/nodes/ExcalidrawNode/index.tsx

Excalidraw resizing actions are not tracked. My understanding of this is that because the component is fetching width and height from the editor state rather than receiving them as props, React didn't detect the changes to width and height, preventing the component from rerendering on resizing. And as a result, Lexical did not record these transactions in its history stack.
I am now passing in the width and height properties as props into ExcalidrawComponent, similar to what is done in ImageNode. And I got rid of useMemo.
https://github.com/user-attachments/assets/4d120470-4ef1-4a87-9400-fd8de21c4d7b
https://github.com/user-attachments/assets/5b8b8741-a7ee-4722-a400-8038e192293e
Tested in collab mode as well.

[lexical-playground] Bug Fix: Track Resizing Actions for Excalidraw in History Stack

---

packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/__tests__/unit/LexicalSelection.test.ts

Closes #6701 
Constructing a document where the children of RootNode are inline ElementNode causes a crash on `selection.insertNodes(…)` (as in paste) because there is an assumption with no runtime invariant that all children of the root are block nodes.
A runtime invariant was added to prevent that, and the incorrect type assertions were removed. A unit test is added to cover this particular case.

[lexical] Bug Fix: Insertion into inline ElementNode should not crash

---

packages/lexical-list/src/LexicalListNode.ts
packages/lexical-playground/__tests__/unit/docSerialization.test.ts
packages/lexical-rich-text/src/index.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts
packages/lexical/src/nodes/LexicalElementNode.ts
packages/lexical/src/nodes/LexicalParagraphNode.ts

This PR ensures that the indent property is preserved when importing and exporting HTML.
Closes #6082
Additionally, the following bugs are fixed:
- in `ParagraphNode.exportDOM` the correct default value is used. It was set to an old value.
- in `ParagraphNode.exportDOM` the indent is exported using the `padding-inline-start` property as used in the editor, instead of `text-indent`. Apparently, the person who set that did so because `padding-inline-start` has poor support in email clients. However, `text-indent` is a first-line indent, different from the lexical indent which encompasses the entire block. If someone needs to export for use in email, they should probably create their own converter.
This PR does not include serialization of custom indent values ​​defined in the …

[lexical][lexical-list][lexical-rich-text]: Fix: Preserve indentation when serializing to and from HTML

---

packages/lexical-yjs/src/SyncCursors.ts
packages/lexical-yjs/src/index.ts

When syncing Lexical selection to Yjs, custom fields in the local state were being dropped. This commit ensures all custom fields are preserved during the sync process, maintaining data integrity in collaborative editing scenarios.
Updated syncLexicalSelectionToYjs to include ...customFields Ensures backwards compatibility with existing implementations Improves reliability of custom data persistence in collaboration
prev [PR](https://github.com/facebook/lexical/pull/6683) where ProviderAwareness  type was extended with `setLocalStateField `

fix: preserve custom fields in Lexical-Yjs sync

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/ToolbarPlugin/fontSize.css

Closes #6697 
https://github.com/user-attachments/assets/0c1cba0c-0b5d-475c-afbd-4d58aefe78cb
https://github.com/user-attachments/assets/efd1bd53-da3c-4494-8f73-ab364f0001a8

[lexical-playground] Bug Fix: match toolbar font size input with the rest of toolbar items in Read-Only mode

---

.github/workflows/close-stale-pr.yml

Spring cleaning since the number of stale PRs are growing
1. add "stale-pr" label
2. this PR closes with a comment

Chore: add workflow to auto close stale pr based on label

---

packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/plugins/TableHoverActionsPlugin/index.tsx

- Fix up the anchoring logic for the relative add row/column buttons (Fixes for when the editor is an embedded widget)
- Fix the overlap of text entry when the buttons are displayed (videos below)
Before
https://github.com/user-attachments/assets/e98d44fd-39a0-4d8a-ad64-b7bbb2618842
After
https://github.com/user-attachments/assets/336bc756-ab66-449c-b60d-b919e1bb9176

[lexical-playground] Table Hover Actions Layout Fixes

---

.github/workflows/call-e2e-all-tests.yml

The react-beta CI job has been stalling on some PRs. It's not really feasible to do much debugging on the GitHub Actions runners and it passes locally so I'm not really sure what else to do about it. We got most of the value from it already, I don't think it will matter much until there's another set of major changes in React.
react-beta job intermittently runs for over an hour and times out
react-beta job no longer runs

[*] Chore: Disable react-beta test job for now

---

packages/lexical-code/src/CodeHighlighterPrism.ts

When investigating https://github.com/facebook/lexical/pull/6731#discussion_r1801368555 it was reported that `npm run ci-check` failed locally due to a type error. It's unclear why this failure doesn't also happen in CI, but I was able to reproduce it locally. The root cause probably has something to do with `@types/prismjs` and how the CI installs things?
All this does is add some type annotations to make it pass.
```
$ npm run tsc
> @lexical/monorepo@0.18.0 tsc
> tsc
packages/lexical-code/src/CodeHighlighterPrism.ts:28:59 - error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.
28 export const Prism: typeof import('prismjs') = globalThis.Prism || window.Prism;
~~~~~
packages/lexical-code/src/CodeHighlighterPrism.ts:28:75 - error …
```

[lexical-code] Bug Fix: Add global type declarations for Prism

---

packages/lexical-playground/src/nodes/ImageComponent.tsx
packages/lexical-playground/src/nodes/InlineImageNode/InlineImageComponent.tsx

Currently, the image and inline image components can still be focused in read-only mode, and the buttons to add caption and edit are still shown.
- Prevent focusing on images in read-only mode
- Hide interactive elements in read-only mode
https://github.com/user-attachments/assets/973b7731-450d-44ae-bef9-e41454ac749f
https://github.com/user-attachments/assets/797d7057-6d3c-45fc-aace-2e42c2d2adda

[lexical-playground] Bug Fix: Disable image and inline focusing, adding caption and editing in read-only mode

---

packages/lexical-playground/src/nodes/EquationComponent.tsx

Currently, the equation component allows editing equations even in read-only mode. 
- Prevent double clicking from showing the equation editor in read-only mode.
- Adjust event handlers that open the equation editor or handle selection changes to be disabled when in read-only mode
https://github.com/user-attachments/assets/0090223c-f251-41b8-a276-7750e551b2fa
https://github.com/user-attachments/assets/67f22f04-4fac-4293-bf14-114e03f009b6

[lexical-playground] Bug Fix: Disable equation editing in read-only mode

---

packages/lexical-table/flow/LexicalTable.js.flow
packages/lexical-table/src/LexicalTableUtils.ts

Currently, the `$insertTableRow__EXPERIMENTAL` function doesn't return anything, so if you want to insert a table row using it and do something with the inserted row, you'll have to do all the calculations again to find the inserted row.
With this PR, the function will return the inserted row node if it was successful and undefined if not. This removes the need for rewriting all the logic regarding spans just to find the inserted row.
Also returns the first inserted cell from `$insertTableColumn__EXPERIMENTAL`

[lexical-table] Return inserted node from `$insertTableRow__EXPERIMENTAL` and `$insertTableColumn__EXPERIMENTAL`

---

packages/lexical-playground/src/plugins/TableHoverActionsPlugin/index.tsx

Currently, the table hover actions allows users to add new rows and columns by hovering over the edges of the table, even when the editor is in read-only mode. Specifically the problems are: hover buttons are visible, interactions with the buttons are allowed, and the event handlers are active all while in read-only mode.
- The hover buttons for adding rows and columns are hidden when the editor is in read-only mode and users cannot trigger hover actions in read-only mode.
- Disabled event listeners in read-only mode
- The `TableHoverActionsContainer` component returns null when the editor is not editable
https://github.com/user-attachments/assets/392cd48f-b507-4fc0-afc7-b61ad712cf20
https://github.com/user-attachments/assets/f327a4a2-ccbe-4494-9b1f-5f7efff822d5

[lexical-playground] Bug Fix: Disable table hover actions in read-only mode

---

package-lock.json
package.json
packages/lexical-clipboard/src/clipboard.ts

Modern sites enforce trusted HTML. `DOMParse.parseFromString` will fail because the clipboard is not a trusted type. Given that we already post-process the HTML instead of blindly exposing it to the DOM I think it's safe to trust it here.

Trust HTML for rich text clipboard

---

packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/Settings.tsx
packages/lexical-playground/src/appSettings.ts
packages/lexical-playground/src/plugins/LinkPlugin/index.tsx
packages/lexical-react/src/LexicalLinkPlugin.ts

Add attributes when pasting a link into a text.
Can not add `target`
https://github.com/user-attachments/assets/175b85a0-8993-42b7-aa4b-7e0325536fe3
Can add `target`
https://github.com/user-attachments/assets/c1a67866-8951-4f9d-acdf-c1750c4bd5eb

[lexical-react] Feature: add attributes in LinkPlugin

---

packages/lexical/flow/Lexical.js.flow

these commands are missing in the flow api. added them. 
copied changes to www and ran flow. no errors

[lexical] Add missing commands to Lexical.js.flow

---

package-lock.json
package.json
packages/lexical-clipboard/src/clipboard.ts

these dependency vulnerabilities flagged by github:
- rollup:
Affected versions: >= 4.0.0, < 4.22.4
Fixed in version: 4.22.4
https://github.com/rollup/rollup/security/advisories/GHSA-gcx4-mw62-g8wm?fbclid=IwZXh0bgNhZW0CMTEAAR3JcDL-xLDAA3vmk38x0rkpUSC0Lxv4VTFp57mm0CeSl-aD01HQaf_BWGs_aem_NiBB9VS_kGm-TPqleMHsUQ
- http-proxy-middleware
Affected versions: < 2.0.7
Fixed in version: 2.0.7
https://github.com/advisories/GHSA-c7qv-q95q-8v27?fbclid=IwZXh0bgNhZW0CMTEAAR0uOXLCKQrjcsYsZBQB8o92wjomNp8Eyssvb5F_8bKYJezklS_eo_n2RBo_aem_-dfCjx_Jhy0wpprvl4SC9w
if dependency defined in package.json, bump the version and ran npm install to update the package-lock.json
i also ran `npm upgrade <dependency>` to generate the package-lock.json file

update dependencies to address security vulnerabilities

---

packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/__tests__/unit/LexicalUtils.test.ts
packages/lexical/src/index.ts

Adds `$onUpdate(fn)` to allow an in-progress update/command to append a function to the `_deferred` stack.
Closes #6767
This functionality did not exist. Calling `editor.update` with an `onUpdate` function was the only way to perform an action after an update.
Performing an update such as:
```ts
editor.update(() => {
// perform updates
$onUpdate(() => {
console.log('second onUpdate);
});
}, {
onUpdate: () => {
console.log('first onUpdate');
}
});
```
would emit `first onUpdate`, followed by `second onUpdate`, once the updates were flushed. This is essentially what the unit test does.

[lexical] Feature: Add onUpdate function during update with $onUpdate (correct baselline)

---

packages/lexical-markdown/src/MarkdownShortcuts.ts
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs
packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts

Issue #6768 happens because of emoji markdown shortcut. It has conditional replacement which was not really supported for shortcuts:
https://github.com/facebook/lexical/blob/07ca5c83c2f512734976504ef9fae5d39b6072ae/packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts#L105-L108
1. Quick option is to disable it from list of shortcut transformers: 
https://github.com/facebook/lexical/blob/07ca5c83c2f512734976504ef9fae5d39b6072ae/packages/lexical-playground/src/plugins/MarkdownShortcutPlugin/index.tsx#L15
2. Another alternative would be to update emoji RegExp to match exact emoji names and instead of having `:([a-Z0-9]):` it'd be `:(smile|sad|happy|...|joy):`. The problem is that with current emoji-list that regex is 23kb long.
3. Enable conditional replacement (this PR). The …

#6768 fix to avoid infinite markdown shortcut matchers run

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/ToolbarPlugin/fontSize.css

This pr aims to fix #6785 
The changes I made aims to fix the hidden fontsize button when you resizing the browser tab(to a smaller size) of the lexical playground, 
Closes #6785

[lexical-playground] Fix: the placement of the fontSize button in the ToolbarPlugin  and hide the vertical scroll (Bug Fix)

---

packages/lexical-clipboard/flow/LexicalClipboard.js.flow

TSIA -- the implementation has an optional selection argument that defaults to `$getSelection()`
Closes #

Add optional selection argument to $getHtmlContent flow type

---

packages/lexical/src/index.ts

In the current setup, the `DOMExportOutputMap` type is not exported from the Lexical core, making it challenging for developers to define custom export configurations in the `html` property of `CreateEditorArgs` without re-creating this type from scratch. This process can lead to redundant code and a higher risk of type errors, particularly for configurations that customize DOM export logic.
This PR exports `DOMExportOutputMap` directly from the Lexical core, allowing developers to use this type immediately in any html.export configurations, which:
1. Reduces redundant type definitions.
2. Improves code readability and reusability.
3. Enhances type safety for custom DOM export setups.
Closes #6802
Developers needed to manually define `DOMExportOutputMap`, increasing the risk of type …

[lexical] Chore: Add export of DOMExportOutputMap from lexical

---

packages/lexical-mark/src/MarkNode.ts

In this PR creation of a new `__ids` array is avoided in the clone function of the MarkNode, and the cloned MarkNode will have the same reference to` __ids` array of the original node. This has made an issue in the `syncPropertiesFromYjs` function where we [compare](https://github.com/facebook/lexical/blob/76f8569211780ee7e913176d99d23eddd1cd3b6c/packages/lexical-yjs/src/Utils.ts#L282C5-L282C35
) the old and new nodes' properties, and only make an update to ydoc if the properties are changed. In the case MarkNodes, because the clone function deep-copies the `__ids` array the property comparison detects a change, despite the arrays being identical.
The fix is keeping the same `__ids` array in the cloned node, and only creating new `__ids` array when the array is modified.

[lexical-mark] Bug Fix: Stop MarkNode __ids array deep copy in clone

---

packages/lexical-list/src/LexicalListNode.ts

Currently, `ListNode.append` will always convert an element node into a text node, even if the element node is inline and can be appended as a whole which can end up removing formatting and unwrapping things like links.
While this is rarely hit, since most of the code in the lexical codebase accounts for appending to a child list item instead of the list directly, I think it still makes sense for this to be correct.

[lexical-list] Bug Fix: Handle appending inline element nodes in ListNode.append

---

packages/lexical-plain-text/src/index.ts
packages/lexical-rich-text/src/index.ts

related to #5841, #3305.
based on #4814,
- adds follow-up commits to resolve side effect caused by blocking `isCollapsed` handling.
- adds same workaround to plain text plugin.
while we don't have `e2e-ios` tests, I checked the fix without `if (navigator.language === 'ko-KR' && IS_IOS)` passed tests on my local.
please include @Deadintegral as a co-author since it contains his work. 
Closes #4814
https://github.com/user-attachments/assets/c9483f3c-a8b9-4aa9-96b3-663d46d3d2e9
https://github.com/user-attachments/assets/c294d341-bac4-4bed-af6a-15e094e33372

[lexical-rich-text][lexical-plain-text] workaround for Korean IME issue on iOS

---

examples/react-rich/package-lock.json
examples/react-rich/src/App.tsx

To use the html export configuration in LexicalComposer, users must manually create a custom type definition for DOMExportOutputMap. This is due to the type not being available for direct import from the Lexical core.
Closes #6825 
DOMExportOutputMap should be directly exportable from the Lexical core, enabling users to import it without needing to define custom types for common configurations.

[lexical-examples] Chore: Add DOMExportOutputMap type to the exportMap

---

packages/lexical-react/src/useLexicalSubscription.tsx

We call `initialValueFn` on each re-render, fixing that

Prevent initial value fn to be called on rerender

---

packages/lexical-table/src/LexicalTableSelectionHelpers.ts

The firefox workaround for down arrow key navigation introduced in #6759 was missing a table check, so it did not work correctly when multiple tables are present.
https://github.com/facebook/lexical/pull/6759#issuecomment-2478582679
https://github.com/user-attachments/assets/6b6815fb-30e0-4549-aac1-27349f360098

[lexical-table] Bug Fix: Fix down arrow key handling in TableObserver

---

packages/lexical-link/src/__tests__/unit/LexicalLinkNode.test.ts
packages/lexical/src/__tests__/utils/index.tsx

Test for removing link from a text node, when the node has children (like mark node)
Closes #6665

[lexical-link] Test:  Removing link from node(children)

---

packages/lexical-react/src/LexicalContentEditable.tsx

The name of the type seems too generic, so I suggest renaming it to:
Like the link below
https://github.com/facebook/lexical/blob/main/packages/lexical-react/src/LexicalTablePlugin.ts

[lexical-react] Fix(lexical-react): ContentEditable props type rename

---

packages/lexical-utils/flow/LexicalUtils.js.flow

The `calculateZoomLevel` function, along with several other utility functions, is missing Flow type declarations in `LexicalUtils.js.flow`. This causes Flow to throw missing-export errors, requiring `$FlowFixMe` comments to suppress the errors.
This pull request adds type declarations to `LexicalUtils.js.flow` for the following functions:
•	calculateZoomLevel
•	$getNextRightPreorderNode
•	$isEditorIsNestedEditor
•	objectKlassEquals
•	$filter
•	$insertFirst
Closes #6823
Before the fix, the following import:
```javascript
import { calculateZoomLevel } from "@lexical/utils";
```
would case this error when running with Flow
```
Cannot import calculateZoomLevel because there is no calculateZoomLevel export in
@lexical/utils. [missing-export]
// @flow
import { calculateZoomLevel } from …
```

[lexical-utils] Bug Fix: Add missing Flow type declarations

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx

Table Action Menu - fix UI issue with Merge Cells item

---

packages/lexical-list/src/__tests__/unit/LexicalListNode.test.ts
packages/lexical-website/docs/concepts/listeners.md
packages/lexical/src/LexicalEditor.ts

The default value for the `skipInitialization` option in `registerMutationListener` was deprecated in #6357 and was intended to change to `false`. This PR updates the default (`DEFAULT_SKIP_INITIALIZATION`) and corresponding comments/docs to reflect the correct value - False.
Closes #6846

[Lexical] Chore: Update default skipInitialization to false for registerMutationListener

---

packages/lexical-selection/flow/LexicalSelection.js.flow

selection parameter in $setBlocksType is set to _RangeSelection_ however, the function defines selection as a _BaseSelection | null_ type.

[lexical-selection] Bug Fix: Wrong selection type in $setBlocksType

---

packages/lexical-website/docs/concepts/nodes.md

There are restrictions with RootNode that is not clearly laid out for the user. This PR expands more on that in documentation for Root Node. It should point user to write direction
Closes #6404

Add Documentation for  RootNode's semantic and use case

---

packages/lexical-utils/src/index.ts

Add feature detection to `calculateZoomLevel` in situations when we are not sure if the browser implements standardized CSS zoom. We still assume that Firefox does, but since only Chrome >= 128 implements it and Safari doesn't implement it yet we use feature detection (creating a div in the document but off-screen, measuring it with and without zoom, then removing it). It's measured twice in case there's a zoom on the body which could cancel out a static measurement.
Closes #6863

[lexical-utils] Bug Fix: Add feature detection to calculateZoomLevel

---

packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx
packages/lexical-playground/src/plugins/TableCellResizer/index.tsx
packages/lexical-playground/src/plugins/TableHoverActionsPlugin/index.tsx

When used in a table cell, the link editor loses focus and the link is not applied. Finding the root cause of this one was tricky, but the gist of it was that we were calling editor.update on mousemove for TableHoverActions and TableCellResizer and because of how reconciliation currently works the DOM selection is always resolved during an editor.update cycle so it would get reset under these circumstances since the DOM selection was in a portal for the link editing modal.
* Trying to narrow it down by disabling one mousemove plugin at a time didn't work because two plugins had the same bug
* Replacing EditorState._selection with a getter/setter that had debugging logs and a breakpoint didn't work because this was happening during reconciliation when this change goes through module global …

[lexical-playground] Bug Fix: Preserve the selection using the link editor from a table

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/LexicalTableObserver.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

Fixes tab navigation in tables when merged cells are present
Closes #6878
Closes #6729
https://github.com/user-attachments/assets/0fc74b2e-802f-48fa-bdf9-6b67fcd2ee0e
https://github.com/user-attachments/assets/087a2a7d-3984-40b5-b3df-d47a0fcddde7

[lexical-table] Bug Fix: Fix table tab navigation

---

packages/lexical-table/src/LexicalTableNode.ts

Fix TableNode.exportDOM regression when using scrollable tables
Closes #6882
I don't have time to do unit tests right now but this fixes it, if you wanted to release ASAP.

[lexical-table] Bug Fix: Fix scrollable table exportDOM

---

packages/lexical-playground/__tests__/e2e/Autocomplete.spec.mjs
packages/lexical-playground/src/plugins/AutocompletePlugin/index.tsx
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

LexicalEditor.setEditorState has a bunch of shared code with LexicalEditor.update such that it doesn't need to be issued from inside of an update. However, if it is issued inside of an update then it will cause an extra `$commitPendingUpdates` call after the state and selection are already read-only which will throw in some situations when node transforms are in use.
This fix ensures that setEditorState is working with a writable state and selection so that transforms can run, and skips the redundant `$commitPendingUpdates` call for the scenarios when it is being called from inside an existing update context (e.g. a dispatchCommand from the history plugin)
Closes #6843
https://github.com/user-attachments/assets/c36ca953-d9cd-4b23-9d96-b9ba1b7b0a98 …

[lexical][lexical-playground] Bug Fix: Allow setEditorState to work correctly inside of an update

---

packages/lexical-table/src/LexicalTableCellNode.ts
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/LexicalTableRowNode.ts
packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx

The exportDOM for TableNode didn't consider partial table selections, and didn't have any tests.
Follow-up to #6884
No tests. Would export the full table colgroup and/or not have all of the wrapping elements.
TableNode exportDOM behaves as expected with tests.

[lexical-table] Bug Fix: TableNode exportDOM fixes for partial table selection

---

packages/lexical-website/docs/maintainers-guide.md

[Documentation Update] Add release protocol to maintainers-guide.md

---

packages/lexical-link/src/__tests__/unit/LexicalLinkNode.test.ts
packages/lexical-link/src/index.ts

When we are creating LinkNode elements from an existing RangeSelection the anchor or focus could be an element point, and in those cases we don't have good automatic handling of the selection when they get reparented so we end up with an invalid selection. This wraps that logic with a function that looks up the existing internal boundary nodes of the selection and preserves them for the LinkNode creation process.
Closes #2569
No unit tests
https://github.com/user-attachments/assets/005fc115-6332-4fd9-a5e6-d8246e4ae425
Unit tests
https://github.com/user-attachments/assets/15f58eca-cd62-4dac-9de4-6ad6901a6360

[lexical-link] Bug Fix: Preserve the start/end of the selection for non-text points when creating a LinkNode

---

packages/lexical/src/LexicalEditor.ts

Chrome has issues with focusing into content editable when it's within a flex element. We don't want to manually introduce wrapper is it will break styling in apps, but can at least warn in dev mode:
https://github.com/user-attachments/assets/1c1b4a88-25f5-46e2-9a85-7de024430267

Warn about "display: flex" container for the editor

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/src/plugins/TablePlugin.tsx
packages/lexical-react/src/LexicalTablePlugin.ts
packages/lexical-react/src/shared/useCharacterLimit.ts
packages/lexical-table/flow/LexicalTable.js.flow
packages/lexical-table/src/LexicalTableCellNode.ts
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/LexicalTablePluginHelpers.ts
packages/lexical-table/src/LexicalTableRowNode.ts
packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx
packages/lexical-table/src/index.ts
packages/lexical-utils/flow/LexicalUtils.js.flow
packages/lexical-utils/src/__tests__/unit/descendantsMatching.test.tsx
packages/lexical-utils/src/__tests__/unit/iterators.test.tsx
packages/lexical-utils/src/__tests__/unit/unwrapAndFilterDescendants.test.tsx
packages/lexical-utils/src/index.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

* Enforce Table invariants with node transforms that are registered by the table plugin
* Move the majority of the Table plugin's code to `@lexical/table` so that it can be more easily used in non-React applications
* Add a new `$unwrapAndFilterDescendants` to `@lexical/utils` for use in these transforms (it's possibly useful elsewhere that we have a fixed schema, like ListNode/ListItemNode)
TableNode
- may only have TableRowNode children
TableRowNode
- must have a TableNode parent
- may only have TableCellNode children
TableCellNode
- must have a TableRowNode parent,
- must be non-empty (an empty ParagraphNode will be added)
Closes #6910
Playground crash when pasting a table that has tbody, thead, tfoot, or and/or caption
No crash, new unit tests for new functionality, specifically …

[lexical-table][lexical-utils][lexical-react]: Bug Fix: Enforce table integrity with transforms and move non-React plugin code to @lexical/table

---

package-lock.json
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/package.json
packages/lexical-playground/src/plugins/CodeActionMenuPlugin/components/PrettierButton/index.tsx

- **Current behavior**: The codebase uses synchronous `prettier.format` calls compatible with Prettier v2.
- **Changes introduced**:
- Upgraded Prettier from `^2.3.2` to `^3.4.2`.
- Updated all usages of `prettier.format` to handle its new asynchronous behavior in Prettier v3.
- Adjusted the handling of Prettier plugins and parsers in `PrettierButton` to ensure compatibility with Prettier v3, including dynamic imports and necessary adaptations.
These changes update the `lexical-playground` package to be fully compatible with the API changes in Prettier v3.

[lexical-playground] Chore: Update Prettier to v3

---

.github/workflows/tests.yml

Removing core tests workflow exclusion for the following reasons:
1. Cost-wise, most PRs fall outside of this bucket
2. We can enforce that status are passing on GitHub

Update core-tests workflow triggers

---

packages/lexical-playground/src/themes/PlaygroundEditorTheme.css

fix 6931: CSS changes in the playground to allow scrolling if the cell content overflows, and inheriting the same behavior for the nested `<p>` tag.
Bug Fix
Made changes to the playground CSS to allow scroll of table content, since there's a nested p tag, have added scroll:inherit to it
Closes #6931
Try scrolling of various contents inside playground table's cells
https://github.com/user-attachments/assets/8605cc74-b300-4cda-bcc4-e2fa259c1d4f

[lexical-playground] Bug Fix: Allow scrolling if the table cell content overflows

---

packages/lexical-website/docusaurus.config.js

The community section of the website features Discord prominently but it's not in the footer. This adds it to the footer for quick reference.

[lexical-website] Add Discord to the community section of the footer

---

packages/lexical-utils/src/markSelection.ts

The usage of updateDOM in markSelection seemed to create DOM churn in certain circumstances for CJK composition inputs which affected user input and selection. Refactoring the function to instead use the invariant that if updateDOM did return true, then the identity of the rendered DOM element would've changed.
While I was in there I also refactored the range code to support the getDOMSlot API. We don't currently have any code that offsets the first child, but if we did then we'd have another bug to fix here.
Closes #6947
Closes #6946
Should be covered by existing SelectionAlwaysOnDisplay test coverage

[lexical-utils] Bug Fix: Refactor markSelection for getDOMSlot and not using updateDOM

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/TablesHTMLCopyAndPaste.spec.mjs
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx

TableNode's importDOM only supported the style attribute for importing col width, but Google Docs uses the deprecated width property. This implements both, prioritizing the style attribute over the width attribute.
Closes #6969
Google Docs colgroup would be ignored because it uses the deprecated width property instead of CSS style
Google Docs colgroup widths are imported (see e2e test addition + update)

[lexical-table] Feature: Support google docs colgroup import (via deprecated col width attribute)

---

packages/lexical-react/src/useLexicalNodeSelection.ts

Add documentation for the `useLexicalNodeSelection` hook.
Closes #6975
No documentation existed for the `useLexicalNodeSelection` hook, making it harder for developers to integrate and use.
Comprehensive documentation added for the `useLexicalNodeSelection` hook, including usage examples, parameter details, and return values for improved clarity and ease of integration.

[Documentation][lexical-website]: Documentation for useLexical node selection hook

---

packages/lexical-table/src/LexicalTableObserver.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

For `$deleteCellHandler` method, like for `deleteTextHandler` and etc., a check has been added to ensure the current selection belongs in the target table node (`tableNode` param passed to `applyTableHandlers`)
Closes #6972
1. Open playground
2. Remove all content
3. Append first table
4. Append some text
5. Append second table
6. Select all cell's of second table
7. Press `Del`
First table deleted
https://github.com/user-attachments/assets/63e8f39a-fdbd-4bd9-8621-f139cd4ed90c
Second(selected table) deleted
https://github.com/user-attachments/assets/625bc97c-29c0-4c8d-acf2-f8a9bd440790

[lexical][lexical-table] Bug fix: TablePlugin:  - check is current selection in target table node

---

packages/lexical/flow/Lexical.js.flow

Seems that flow isnt able to compile `this` type as an input param type: see sample 
[error](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SQAOlB2U8MCQSAACAAyCmy3AAchANLzgOzebyhIw2JlsAARADyAFkABTSmW82YNMUaZC8iS1Wm8bUASkl2plLAkQkoUAA3Nr6ey3VBciAGiYSHBoEkGgAGKwAJgArAB2KwARhA9KAA)
This results in downstream errors such as this scenerio:
```
export class QuoteLineNode extends TextNode {
updateDOM(
prevNode: TextNode,
dom: HTMLElement, …
```

[lexical] Fix flow error: change this to any

---

packages/lexical-react/flow/LexicalAutoLinkPlugin.js.flow
packages/lexical-react/flow/LexicalBlockWithAlignableContents.js.flow
packages/lexical-react/flow/LexicalCharacterLimitPlugin.js.flow
packages/lexical-react/flow/LexicalClearEditorPlugin.js.flow
packages/lexical-react/flow/LexicalCollaborationPlugin.js.flow
packages/lexical-react/flow/LexicalComposer.js.flow
packages/lexical-react/flow/LexicalContentEditable.js.flow
packages/lexical-react/flow/LexicalDraggableBlockPlugin.js.flow
packages/lexical-react/flow/LexicalErrorBoundary.js.flow
packages/lexical-react/flow/LexicalHashtagPlugin.js.flow
packages/lexical-react/flow/LexicalHistoryPlugin.js.flow
packages/lexical-react/flow/LexicalHorizontalRuleNode.js.flow
packages/lexical-react/flow/LexicalMarkdownShortcutPlugin.js.flow
packages/lexical-react/flow/LexicalNestedComposer.js.flow
packages/lexical-react/flow/LexicalPlainTextPlugin.js.flow
packages/lexical-react/flow/LexicalRichTextPlugin.js.flow
packages/lexical-react/flow/LexicalTableOfContentsPlugin.js.flow
packages/lexical-react/flow/LexicalTreeView.js.flow

These types can be used without importing React since Flow v0.231.0. This PR replaces them with the non-dollar version, so that Flow can eventually remove these types.
flow

[lexical-react] Refactor: Replace `React$MixedElement` and `React$Node` with `React.MixedElement` and `React.Node`

---

packages/lexical/flow/Lexical.js.flow

Some variables and function are missing in flow file.
Here are classes affected:
- EditorThemeClasses
- BaseSelection
- NodeSelection
- RangeSelection
- DOMConversionFn
This is the following of #6866

[lexical] Bug Fix: Flow is missing some variables and functions

---

packages/lexical-playground/__tests__/regression/6974-delete-character-backward.spec.mjs
packages/lexical/src/LexicalSelection.ts

`ElementNode.getDescendantByIndex` has error-prone semantics where it will return the last descendant when the index overflows. There was already a workaround for over-selection on the lastNode side for `getNodes()` and this adds a similar workaround for the firstNode side.
The most common side-effect of this (literal) edge case is that too many nodes would be deleted by `removeText`, particularly when an element ends with a `DecoratorNode` and the point is at the offset after it.
Closes #6974
Closes #6851
Closes #6842
See new regression test, plus all existing suites.

[lexical] Bug Fix: Fix getNodes over-selection

---

packages/lexical-playground/__tests__/e2e/Headings/HeadingsEnterAtEnd.spec.mjs
packages/lexical-playground/__tests__/e2e/Headings/HeadingsEnterInMiddle.spec.mjs

`HeadingsEnterAtEnd.spec.mjs` was called `HeadingsEnterInMiddle.spec.mjs` and `HeadingsEnterInMiddle.spec.mjs` was called `HeadingsEnterAtEnd.spec.mjs`. Now the file names have been switched.
The file contents have not been touched, their names have just been switched. I did consider if I should pick a new name for one of the files since this would have produced a cleaner diff. Let me know if you would prefer this instead.

[lexical-playground] Refactor: switch headings test file names

---

packages/lexical-code/src/__tests__/unit/LexicalCodeNode.test.ts
packages/lexical/src/LexicalUtils.ts

The registerNodeTransform changes in #6894 have a subtle bug when there's a pending node map change with removed nodes that have been GC'd
Closes #7014
Exception under certain conditions
Unit test to simulate error conditions, no more exception.

[lexical] Bug Fix: Fix registerNodeTransform regression introduced in #6894

---

packages/lexical-playground/src/plugins/TableHoverActionsPlugin/index.tsx

After introducing the getDOMSlot usage, the render coordinates for the table hover actions had to be adjusted.
Before:
https://github.com/user-attachments/assets/2621126e-1e7f-4950-b595-1a5f444b019e
After:
https://github.com/user-attachments/assets/ce0a85a8-9499-4368-9172-fdf688e835d2

[lexical-playground] Fix table hover actions button position

---

packages/lexical-mark/src/MarkNode.ts

Ternary logic introduced in https://github.com/facebook/lexical/commit/7c21d4ff39a6ede7dcbe061af17ec11b0ed48b2c#diff-b30867251dac89bfc41aba98899f9ca7e6b1045cc8bcfbcc9e9824caaf53d695R112-R122 is the wrong way around. Trying to add a new ID is a no-op, and adding an existing ID duplicates it.
I have the following test code to replace IDs:
```
console.dir(oldIdToNewId);
console.dir(node.getIDs());
const newId = oldIdToNewId[id];
node.addID(newId);
node.deleteID(id);
console.log('replaced %s with %s', id, newId);
console.dir(node.getIDs());
```
Which produces the following on 0.23.0:
```
{
'e338a2b4-3a70-4a73-9871-6b61f2ed8caa': '57404623-3ae5-5cfa-812f-762e507a69ae'
}
[ 'e338a2b4-3a70-4a73-9871-6b61f2ed8caa' ]
replaced e338a2b4-3a70-4a73-9871-6b61f2ed8caa with …
```

[lexical-mark] Bug Fix: reverse ternary in MarkNode.addID

---

packages/lexical/src/nodes/LexicalTabNode.ts
packages/lexical/src/nodes/__tests__/unit/LexicalTabNode.test.tsx

Fixes TabNode serialization regression in the https://github.com/facebook/lexical/pull/6970 refactor. The invariant condition was inverted.
Closes #7030
No test coverage of TabNode serialization, so this failure went undetected.
Fixed invariant and added test coverage

[lexical] Fix TabNode deserialization regression 

---

packages/lexical/src/LexicalEditor.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

`setRootElement(null)` now triggers the same sort of reconciliation with a `history-merge` tag that `setRootElement(element)` triggered.
Previously, when `setRootElement(null)` was called with any pending updates, it would put the editor in a situation where `editor.getEditorState()` would return a writable EditorState. Now the invariant is preserved such that `editor.getEditorState()` always returns a fully reconciled and read-only EditorState, but to match previous semantics such that the current editorState would synchronously get set from the pendingEditorState, `setRootElement` now always causes a commit when the root element changes instead of just when it changes to a non-null element.
I think there were likely other subtle bugs due to the previous behavior, since setting …

[Breaking Change][lexical] Bug Fix: Commit updates on editor.setRootElement(null)

---

packages/lexical-list/README.md
packages/lexical-list/flow/LexicalList.js.flow
packages/lexical-list/src/formatList.ts
packages/lexical-list/src/index.ts
packages/lexical-playground/__tests__/e2e/List.spec.mjs
packages/lexical-selection/src/range-selection.ts
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/__tests__/unit/LexicalListPlugin.test.tsx
packages/lexical/src/index.ts

* `insertList` and `removeList` are now deprecated, use `$insertList` and `$removeList` instead.
* `INSERT_CHECK_LIST_COMMAND`, `INSERT_ORDERED_LIST_COMMAND`, `INSERT_UNORDERED_LIST_COMMAND` and `REMOVE_LIST_COMMAND` now update synchronously when dispatched from inside an update, rather than deferring a nested update (this is the expected behavior for commands)
* `editor.focus()` now happens synchronously when called from inside of an update, as if it was implemented with a command dispatch. Previously it would defer which is confusing behavior because the expected side-effect is to change the selection which you really do want to happen synchronously.
The breaking changes are the result of trying to unit test this functionality and finding out that editor.focus and list commands are …

[Breaking Change][lexical][lexical-selection][lexical-list] Bug Fix: Fix infinite loop when splitting invalid ListItemNode

---

packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx
packages/lexical-playground/src/nodes/ImageComponent.tsx
packages/lexical-playground/src/nodes/InlineImageNode/InlineImageComponent.tsx
packages/lexical-playground/src/nodes/PageBreakNode/index.tsx
packages/lexical-playground/src/nodes/PollComponent.tsx
packages/lexical-react/src/LexicalBlockWithAlignableContents.tsx
packages/lexical-react/src/LexicalHorizontalRuleNode.tsx

Stumbed upon nested updates in the $onDelete methods while troubleshooting some selection issues. Not 100% sure if this is correct.

Clean up nested editor update

---

.eslintrc.js
examples/vanilla-js-iframe/README.md
examples/vanilla-js-iframe/index.html
examples/vanilla-js-iframe/package-lock.json
examples/vanilla-js-iframe/package.json
examples/vanilla-js-iframe/src/main.ts
examples/vanilla-js-iframe/src/prepopulatedRichText.ts
examples/vanilla-js-iframe/src/styles.css
examples/vanilla-js-iframe/src/vite-env.d.ts
examples/vanilla-js-iframe/tsconfig.json
examples/vanilla-js-iframe/vite.monorepo.config.ts
packages/lexical-clipboard/src/clipboard.ts
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalMutations.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/LexicalUtils.ts

Sometimes when an iframe is used as the contentEditable then the MutationObserver can fire after the input event, even if the mutation actually did happen. This causes problems that were undiagnosed prior to the addition of `$validatePoint` in `__DEV__` (part of #6759) because the Lexical selection would refer to DOM coordinates that were not yet valid in the Lexical document, because the DOM was mutated before getting the selection. When the mutation observer happens first this doesn't occur because either the mutation is applied and/or the selection code is skipped due to `getIsProcessingMutations()` (see `$internalCreateRangeSelection`). This is related to the optimization(?) in #794 that avoids explicitly flushing root mutations on input.
This PR:
- Adds a vanilla-js-iframe example as …

[lexical] Bug Fix: Handle MutationObserver/input event re-ordering when using contentEditable inside of an iframe

---

.github/workflows/size-limit.yml
.size-limit.js
package-lock.json
package.json
scripts/build.js

This may cause some regression in the cjs build size or cause some other configuration related issue, particularly for www\. I suspect that most people in OSS are using esm builds at this point, but some extra scrutiny should be used at Meta when evaluating this PR.
The cjs prod build has used @ampproject/rollup-plugin-closure-compiler for some time, but that project is abandoned (last release Aug 2021) and causes hard to debug issues whenever you end up using syntax that is valid JS according to the rest of the toolchain but not supported by that abandoned project (e.g. property initializers in classes).
terser is already used for the lexical esm build which has been in production for some time now, it is currently the most popular tool for this purpose, and it is maintained on top of a …

[Breaking Change][*] Chore: Use terser for optimizing cjs prod build

---

.github/workflows/size-limit.yml

Follow up to #7047 - since we can't properly test pull_request_target triggers until after they are in main this mistake went unnoticed. 
Closes #6852
size-limit always says 0% difference because it's measuring main and main
size-limit should do something useful

[*] Bug Fix: Use GITHUB_OUTPUT instead of GITHUB_ENV for size-limit action

---

packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical-selection/src/__tests__/utils/index.ts
packages/lexical-utils/src/__tests__/unit/LexicalUtilsInsertNodeToNearestRoot.test.tsx
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalMutations.ts
packages/lexical/src/LexicalNormalization.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/__tests__/unit/LexicalNode.test.ts
packages/lexical/src/nodes/LexicalTextNode.ts

When we use native selection methods to move the cursor in Firefox it will sometimes resolve to an element point, rather than a text point, which violates some assumptions baked into removeText and other internals.
This adds a normalization step to RangeSelection.applyDOMRange (on all platforms) that can be manually toggled off if necessary. I don't think this is needed but I also haven't seen a full e2e test run yet.
Closes #6991
Closes #7049
Backspacing across the border of an ElementNode will cause the majority of that ElementNode to be deleted in Firefox
Firefox behaves as other browsers do, and now we have an e2e test (with LinkNode) to demonstrate that the behavior is fixed

[lexical] Bug Fix: Normalize selection after applyDOMRange to account for Firefox differences

---

packages/lexical/src/LexicalEditor.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

S482409: Editors on Meta's www were crashing with error: `Got unexpected null or undefined` on reloading the editor.
the root cause is a nullthrows at 
```
const parentElementDOM = nullthrows(
editor.getElementByKey(parentElementNode.getKey()),
);
```
[MLCFloatingParagraphStylesPlugin.react.js](https://www.internalfb.com/code/www/[32c8b8ca986ab3fd52f78aabcc131eb033653175][blame]/html/js/shared/lexical_composer/plugins/MLCFloatingParagraphStylesPlugin.react.js?lines=61-63) in the www integration layer. More investigation needed to determine whats the best approach to handle null being returned to parentElementDOM.
PR7023 is suspected to cause the change, and carries more risk then expected. Reverting the sync diff with PR7023 mitigates the issue. sorry @etrepum to unblock the syncs, may we …

Revert [Breaking Change][lexical] Bug Fix: Commit updates on editorSetRootElement(null) (#7023)

---

packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

Fixes https://github.com/facebook/lexical/issues/6909
To differentiate between table alignment and cell text alignment, the table-level alignment logic only kicks in when the selection is the whole exact table. This does introduce the extra step if one wants to align all cell texts to do it in 2 steps, all columns except one and then the last column.
Before:
https://github.com/user-attachments/assets/d1851ec3-6844-4bb7-89f9-02bdf1000abf
After:
https://github.com/user-attachments/assets/30265b64-66c0-4b70-85d2-988f8eb7cb83

[lexical-table] Support table alignment

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical/src/LexicalEvents.ts

Triple click on paragraph (or other block element) with link as a first child would select link instead of whole element's content
https://github.com/user-attachments/assets/1d1d03ff-eaf9-4cf0-8f5e-dbafa632ae67
https://github.com/user-attachments/assets/e48c8cf5-9d03-4284-a112-fc03455989ff

fix: triple click around inline elements (links)

---

packages/lexical-react/src/shared/useYjsCollaboration.tsx
packages/lexical-yjs/src/SyncCursors.ts
packages/lexical-yjs/src/SyncEditorStates.ts
packages/lexical-yjs/src/index.ts

We created a custom `syncCursorPositions` function in our app to allow for more advanced styling and behavior than what the implementation exported by `@lexical/yjs` allows (which requires some CSS trickery even just to customize basic styling)
However we were noticing that sometimes some of the cursors would use the styles from the Lexical impl and not ours, even though those styles didn't exist in our codebase. It turned out that the `syncYjsChangesToLexical` function calls the lexical implementation of `syncCursorPositions`, so depending on which implementation ran first, some cursors would use incorrect styles. Also, the lexical implementation removes cursors for user states which are not focusing, while ours does not. This would cause flickering of the cursors since the Lexical impl …

[lexical-yjs] Feature: Allow passing in custom `syncCursorPositions` function to collab hook

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical/src/__tests__/unit/HTMLCopyAndPaste.test.ts

fixes https://github.com/facebook/lexical/issues/4801
A troubling issue has been identified with the iOS keyboard's autocorrect behavior and how it affects text formatting.
When a user selects a word prediction, or, when the operating system injects an autocorrected word (such as when typing `its` and not including the apostrophe), the data transfer type is incorrectly reported as `text/html`.  This does not reflect the actual content, as the payload only contains plain text.
Addressing this issue involves a very straightforward validation to ensure the presence of element nodes within the parsed DOM when the data type is reported as `text/html`, before proceeding with inserting the DOM nodes.
My solution simply checks for the presence of element nodes in the parsed DOM using …

fix: iOS Autocorrect strips formatting by reporting wrong dataType

---

packages/lexical-list/src/__tests__/unit/formatList.test.ts
packages/lexical-list/src/formatList.ts

Currently, if the selection is at the root and you toggle one of the list options, it throws an error `Error: replace: cannot be called on root nodes`.
This PR fixes this by selecting the first child of the root if available, or creating a new paragraph, appending and selecting it before re-running the `insertList` function.
https://github.com/user-attachments/assets/af17623e-5240-4552-91f3-cb01222fe703
https://github.com/user-attachments/assets/23e87498-03bd-45bc-a999-a61849854737

[lexical-list] Bug Fix: Prevent error when calling formatList when selection is at root

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/TablesHTMLCopyAndPaste.spec.mjs
packages/lexical-table/src/LexicalTableUtils.ts

Currently, if a table was pasted that has an empty row, the `$tableTransform` would throw an error. This is because in `$computeTableMapSkipCellCheck`, an array for a row is only initialized inside the loop that goes through its children. This causes there to be a gap in the gridMap since an array for the empty row never gets initialized, which then causes `gridMap[i]` to be undefined and throw an error.
This PR fixes this by making sure an empty array is initialized at the index of the empty row, which in turn will be filled with the necessary amount of cells by `$tableTransform`
Added e2e test to cover this scenario

[lexical-table] Bug Fix: Prevent error if pasted table has empty row

---

packages/lexical-playground/src/themes/PlaygroundEditorTheme.css

Fix the overflow of individual items in the columns layout.
Before:
After:

[lexical-playground] Fix Columns Layout Item Overflow

---

packages/lexical/src/LexicalEditor.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

https://github.com/facebook/lexical/pull/7023 introduces the correct reconcillation behavior on setRootElement(null).
https://github.com/facebook/lexical/pull/7023 was reverted in https://github.com/facebook/lexical/pull/7052, as there was an incompatibility with an edge case nullsthrows on www.
In www we have landed a fix for the nullthrows error, making it safe to sync https://github.com/facebook/lexical/pull/7023 over to www, so unreverting https://github.com/facebook/lexical/pull/7023.

Unrevert [Breaking Change][lexical] Bug Fix: Commit updates on editor.setRootElement(null) #7023

---

packages/lexical/src/LexicalEditor.ts

[lexical] Refactor: Use RegisteredNodes type
Currently, the Map<string, RegisteredNode> type is directly used for the registeredNodes variable instead of utilizing the predefined RegisteredNodes type.This PR updates the type definition for the registeredNodes variable to use the RegisteredNodes type instead of Map<string, RegisteredNode>. This improves code consistency and adheres to the existing type alias for better readability and maintainability.

Fix: Use already defined RegisteredNodes type

---

packages/lexical/src/LexicalEvents.ts

Add comments and rename the internal `isSafariEndComposition` variable to `isSafariEndingComposition` introduced in the Safari compositing workaround https://github.com/facebook/lexical/pull/7061
No need, this is a variable rename and the addition of some comments

[lexical] Chore: Rename variable and add comments for Safari compositing workaround

---

packages/lexical-playground/__tests__/e2e/Collaboration.spec.mjs
packages/lexical-yjs/src/CollabElementNode.ts

Fixes a bug in `applyChildrenYjsDelta` which caused Lexical and Yjs to get out of sync. Once in this state, some changes would not sync to other clients; the changes would be lost on refresh.
This can be reproduced in the Playground with the following steps:
1. In the left editor, type "Hello World"
2. Select "World" and change the formatting to bold
3. In the right editor, type a character in the middle of "World", eg "Wor_ld"
4. In the left editor, click undo then redo
5. Any text added at the end in the left editor won't be synced to the right editor
When applying change deltas from Yjs, an `insertDelta` can be a string or a `sharedType`. If `currIndex` is pointing to some position within a text node and `insertDelta` is a string, then the new text is spliced in correctly. If …

[lexical-yjs] Bug Fix: handle text node being split by Yjs redo

---

packages/lexical-website/docs/concepts/selection.md

Reprensenting --> representing

Selection | Lexical: 1 Spelling Update Update selection.md

---

packages/lexical-playground/src/plugins/ContextMenuPlugin/index.tsx

- Fixed an issue where Delete Node did not handle specific node types ( `image`, `inline-image`, `page-break`, `excalidraw`, `horizontalrule`).
- Added support for these node types to ensure consistent deletion behavior.
Previously, the "Delete Node" option in the context menu did not handle specific node types (`image`, `inline-image`, `page-break`, `excalidraw`, `horizontalrule`). Attempting to delete these nodes would fail, causing inconsistent behavior.
**Changes in this PR:**
This PR fixes the issue by adding support for these node types. The following updates were made:
Added handling for `isNodeSelection` to delete selected nodes of specific types.
Extended the list of deletable node types.
Imported `$isNodeSelection` from Lexical to support these changes.
This PR ensures that …

[lexical-playground] Bug Fix: Ensure Delete Node handles all node types

---

packages/lexical-utils/src/__tests__/unit/LexicalNodeHelpers.test.ts
packages/lexical-utils/src/index.ts

I previously submitted https://github.com/facebook/lexical/pull/7094, which changed the behaviour of `$dfsIterator` to allow it to sometimes traverse the tree backwards. The feedback there was that changing the behaviour would not be the safest choice, and instead this should be implemented as a new function that developers can choose to use in their application code.
The use-case for this is to traverse backwards from a starting point, towards the beginning of the editor, until you meet some condition. For example:
```
let previousTextNode = null;
for (const node of $dfsIterator(startNode, $getRootNode())) {
if ($isTextNode(node)) {
previousTextNode = node;
break
}
}
```
The alternative is to call $dfs().reverse(), but that is slow for editors with many nodes (lots of overhead).
It is …

[lexical-utils] Feature: add reverse dfs iterator

---

packages/lexical-utils/src/__tests__/unit/LexicalNodeHelpers.test.ts
packages/lexical-utils/src/index.ts

The version of `$reverseDfs` introduced in #7107 has confusing semantics and does not work as you would expect a DFS traversal to operate. This change modifies the implementation to be in line with $dfs but with a right to left traversal instead of a left to right traversal. Since we're working with a tree data structure rather than a flat array, expecting the iteration results to be exactly the reverse is not in line with normal expectations.
It was my mistake for approving this without a more careful audit of the code, on the surface it is very similar and the quality of the PR was very high otherwise (tests, API docs, etc.). I only noticed the surprising semantics when I was trying to re-implement it in terms of NodeCaret in #7046. I had expected it to work differently because the …

[lexical-utils] Fix: Modify $reverseDfs to be a right-to-left variant of $dfs

---

packages/lexical-mark/__tests__/unit/LexicalMarkNode.test.ts
packages/lexical-mark/src/index.ts

`$wrapSelectionInMarkNode` currently wraps text nodes and inline element nodes, leaving other nodes unwrapped. This makes the function also include inline decorator nodes.
Marks only appear to be used by comments in the Playground. I couldn't see any existing unit tests for marks, or E2E tests for comments, so went with manual testing for this.
The mark does not include the equation node, though it is captured in the comment text:
The mark includes the equation node:

[lexical-mark] Feature: include inline decorator nodes in marks

---

packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical-list/src/__tests__/unit/LexicalListItemNode.test.ts

`getIndent` and `toJSON` serialization should account for Nodes that are not attached. Currently, we have a very simple parent check.
Otherwise, I think that the strict parent relationship expressed in the `getIndent` function is correct.
Closes https://github.com/facebook/lexical/issues/7115

Fix ListItemNode serialization throws

---

.github/workflows/size-limit.yml

mitigate S487385
risk of merging this: might not be able to catch size regressions on github. However on www, we can still catch size regressions on the sync diff triggered daily with unigraph signals

[workflow] disable size-limit job

---

packages/lexical-mark/__tests__/unit/LexicalMarkNode.test.ts
packages/lexical-mark/src/index.ts
packages/lexical/src/LexicalSelection.ts

`$wrapSelectionInMarkNode` had incorrect logic for dealing with point offsets, and the tests were written to work with this incorrect logic.
This PR fixes that logic and adds a `__DEV__` invariant to PointType to check that we are not setting text or element points with the wrong type of node (AFAIK this test suite was the only place doing this incorrectly). The logic was much simpler once `extract()` was used instead of `getNodes()`.
There is some risk if there is code that is specifically creating invalid points to work around this issue as the tests were written, instead of the correct workaround which would've been to normalize the endpoints of the selection to text nodes.
There is some other risk with the new `PointType.set` invariant, but only in `__DEV__`, and this is only …

[lexical][lexical-mark] Bug Fix: $wrapSelectionInMarkNode with element points

---

packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalSelection.ts

Fixes #4340, #5042 and #1965 
1. On Chrome on Android, deletions are usually handled by the browser instead of the `DELETE_CHARACTER_COMMAND`, however the browser is unable to deleted decorator nodes, this PR detects this scenario and dispatches `DELETE_CHARACTER_COMMAND` accordingly
2. When deleting text across paragraphs, Chrome on Android shifts the selection rightwards, this PR restores the correct selection
https://github.com/user-attachments/assets/b5842cfe-9fba-47a4-a063-6f13766b25f6
https://github.com/user-attachments/assets/87ffbb2b-1dce-4b6a-ad72-a321b2ec41c7

[lexical] Bug Fix: Fix Chrome on android deletion bugs

---

packages/lexical-react/flow/LexicalLinkPlugin.js.flow

Flow type def was not in sync with original source:
https://github.com/facebook/lexical/blob/87eeb95ec756df34ee4972ed86d29cc3ed7d5ec8/packages/lexical-react/src/LexicalLinkPlugin.ts#L26-L30

[bugfix] Fix flow typedef for links plugin to include attributes

---

.github/workflows/call-increment-version.yml
.github/workflows/nightly-release.yml
.github/workflows/version.yml
scripts/npm/postversion.js

Committing to the repo doesn't need an SSH_KEY secret because the GITHUB_TOKEN can do it all in safer manner.
* Use the updated workflow to create a release branch
* ✅ https://github.com/facebook/lexical/actions/runs/13185564867/job/36806710812
* The workflow should create the release branch correctly
* ✅ https://github.com/facebook/lexical/tree/latest__release
* ✅ https://github.com/facebook/lexical/tree/0.24.0__release
* The tests should run after creating a PR with the branch
* IIRC there are some limitations in the GitHub APIs to prevent workflows from infinitely triggering other workflows, but I think since a human manually creates the release PR this might not be an issue for us. Be careful to verify this.
* ✅ https://github.com/facebook/lexical/pull/7144

[ci] Chore: Remove SSH_KEY secret

---

scripts/npm/postversion.js

In situations where the release tag needs to be created multiple times, such as when an issue is found before doing the release, or when testing the create release branch workflow, it can be beneficial to overwrite an existing tag.
* Run create release branch workflow multiple times with the same settings
* This previously failed https://github.com/facebook/lexical/actions/runs/13188051075/job/36814809716 because an v0.24.0 tag was created while testing
* Verify that the subsequent run succeeded and it overwrote the tag and branches
* Precondition: the https://github.com/facebook/lexical/releases/tag/v0.24.0 tag is currently at https://github.com/facebook/lexical/commit/d6d68edec7da8ecfa5dc4fc32f9c364c6d11f317 from #7143 / #7144 testing and this is also where the …

[ci] Bug Fix: Force tag update so create release branch can be run multiple times

---

packages/lexical/src/nodes/LexicalElementNode.ts

The current implementation of sibling traversal contains a logical error that can cause an infinite loop. In the loop that counts previous siblings, the iteration update statement incorrectly references the original node's previousSibling instead of updating the sibling reference:
Current code (always references the same sibling):
https://github.com/facebook/lexical/blob/fcc374018043620ec025262b352baa91d9536b6e/packages/lexical/src/nodes/LexicalElementNode.ts#L287-L297
This PR fixes the issue by properly updating the sibling reference in each iteration:
```javascript
for (
let sibling = node.previousSibling;
sibling !== null;
sibling = sibling.previousSibling // Correctly traverses the sibling chain
) {
i++;
}
```
This change ensures proper traversal through the DOM tree and prevents …

[lexical] Bug fix: Fixes infinite loop in sibling traversal

---

packages/lexical-website/docs/concepts/traversals.md

Fixes small typo in "Node Traversals with NodeCaret".
The type is defined as `export type CaretType = 'sibling' | 'child';`.

[lexical-website] Documentation Update: CaretType has sibling and child.

---

scripts/build.js

T214354208 Getting regeneratorRuntime is not defined errors in lexical clipboard . These errors dont seem to cause any noticeble crashes or behavior 
root cause:
- error coming from here: [https://github.com/facebook/lexical/blob/cleanup-size-limit/packages/lexical-clipboard/src/clipboard.ts#L408](https://l.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2Ffacebook%2Flexical%2Fblob%2Fcleanup-size-limit%2Fpackages%2Flexical-clipboard%2Fsrc%2Fclipboard.ts%23L408&h=AT3IyeCaEj6wIHvuEbY12AXfWvlTIQ5HG-wefFJYd0y3ZOV2mLwdgfGSdqutfdVQQupU2G4NRjlNE8v1h6PCePySDOzDPxeASddFQZPTAAZ8q7R8BDV7gfeHwsYH0f9I4F7fGKOo)
- [tbc, but likely] thrown because haste in www does a validation for non es3 features. async function is not supported in es3, hence the  regeneratorRuntime is not defined error without any …

[scripts] add @noEnforceES3 to build script

---

scripts/build.js

Turns out we were still transpiling `async` internally

Update WWW build flag

---

packages/lexical-utils/src/__tests__/unit/LexicalNodeHelpers.test.ts
packages/lexical-utils/src/index.ts

Running $dfs from non-first child node would reset caret and traverse from the first child:
```
P1
T1  T2 T3
$dfs(T2) -> [T1, T2, T3]
while expected
[T2, T3]
```
@etrepum wondering if you recall why that $rewind() was added

[fix] $dfs traversal from the middle of the tree leaves

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-table/src/LexicalTableUtils.ts

Currently, when merging table cells that include already merged cells, the selection and merge behavior can result in:
1. Non-rectangular selections being allowed
2. Table distortion after merging
3. Missing cells in some cases
4. Inconsistent behavior compared to other table editors like Excel
This PR fixes the table cell merging functionality to ensure selections are always rectangular and merges are performed correctly:
1. Improved Selection Boundary Calculation
- Implemented a two-pass algorithm for accurate boundary detection:
* First pass: Scans the grid to find all cells in selection, including merged cells
* Second pass: Expands boundaries to ensure a complete rectangle
- Added proper handling of cell spans:
* Consider both `startRow + rowSpan - 1` and `startColumn + colSpan - 1` …

[lexical-table] Bug Fix: Ensure rectangular table cell merge behavior (#7161)

---

packages/lexical-react/src/shared/LexicalMenu.ts

kudos to Cindy for this potential fix! im only helping to bring the changes to oss from D69406624
S488810 - the mentions menu autoflips wrongly causing janky behavior on diffs/tasks comments
issue reported by users:
https://github.com/user-attachments/assets/0f9c1610-c17d-45e9-8b6c-32df3bd58b22
so far im unable to repro the comments box flicker, this is what i get, an overflowing typeahead menu
https://github.com/user-attachments/assets/e4a004a0-31bc-4091-bf46-41064de1ac8b
https://github.com/user-attachments/assets/48b18905-9a34-4b70-abd1-3e11cf718aa8 
- looks ok on playground, also tried repositioning the @ to change menu pos, etc

[lexical-react] positionMenu on rendering typeahead mentions menu

---

scripts/error-codes/formatProdErrorMessage.js

Internal requirement, no template strings with 2 forward slahes, otherwise our parser gets angry.
Tested manually it still works

No forward slash in template

---

packages/lexical-utils/src/__tests__/unit/LexicalNodeHelpers.test.ts
packages/lexical-utils/src/index.ts

Missed in #7174 that depth was not calculated properly if we're starting iterator from inline node. In that case depth of its parent was used:
```
P
T1 T2 T3
```
```js
$dfs(T2) -> [[depth: 1, node: T2], [depth: 1, node: T3]]
```
while expected
```js
$dfs(T2) -> [[depth: 2, node: T2], [depth: 2, node: T3]]
```

[fix] DFS depths when starting from inline node

---

packages/lexical-playground/__tests__/e2e/List.spec.mjs
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/nodes/LexicalElementNode.ts

`ElementNode.collapseAtStart(range)` would previously only be called on the direct parent of the anchor's node, so the presence of anything like a LinkNode would prevent a ListItemNode from collapsing. Now it will also be called on parents under certain conditions.
Previously the collapse algorithm looked only at the direct parent of the anchor. If the anchor is inside an inline node (e.g. a TextNode in a LinkNode) then the expected behavior will not happen (such as a LinkItemNode being replaced with a ParagraphNode).
Now the algorithm works like this:
- Start with the anchor node (if its offset is 0) and then all of its parents:
- If the current node is an ElementNode
- If node.collapseAtStart(range) returns true, stop
- If node.isInline() returns false, stop
- If the node is not the …

[Breaking Change][lexical][lexical-link] Bug Fix: Collapse through inline elements in deleteCharacter

---

packages/lexical/flow/Lexical.js.flow

- The `getNearestEditorFromDOMNode` function is missing Flow type definition in `Lexical.js.flow`
- This causes Flow errors when importing and using the function, requiring `$FlowFixMe` to suppress
- Add proper Flow type definition for `getNearestEditorFromDOMNode` in `Lexical.js.flow`
- This allows proper type checking when importing the function
- Removes the need for `$FlowFixMe` suppression
Closes #7148
```typescript
// packages/lexical-playground/src/test-flow-issue.js.flow
// @flow strict
import {getNearestEditorFromDOMNode} from 'lexical';
// Flow error: Cannot import getNearestEditorFromDOMNode because there is no getNearestEditorFromDOMNode export in lexical. [missing-export]
function test(node: Node) {
getNearestEditorFromDOMNode(node);
} …
```

[lexical] Bug Fix: add missing flow type for getNearestEditorFromDOMNode

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

Currently, the typeahead menu (emoji/mentions picker) does not respect the editor's read-only mode. When the editor is in read-only mode:
1. The typeahead menu still opens when typing triggers (: or @)
2. Users can still select and insert emojis/mentions
3. The menu stays open even if editor switches to read-only mode while menu is open
This PR fixes the issue by:
1. Adding a read-only mode check before showing the typeahead menu
2. Adding an editable state listener to close the menu when editor becomes read-only
3. Ensuring complete compliance with read-only mode behavior
Closes #7160
https://github.com/user-attachments/assets/61473734-e4db-486c-985e-f9480d9aa4c7
https://github.com/user-attachments/assets/2eb0e34f-66b9-44c3-87b2-8e129e89defa

[lexical-react] Bug Fix: Make typeahead menu respect read-only mode

---

packages/lexical-code/src/CodeHighlighter.ts
packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs

- When editing in markdown source mode, cursor selection can escape the code block boundaries
- After pressing arrow keys (up/down), typing appears outside the markdown source box
- Text input appears in the root editor instead of staying within the code block
- Ensure cursor stays within code block when using arrow keys
- Verify text input remains contained within the code block
- Add test cases to verify and enforce proper selection boundaries
- Add assertions for correct node selection paths and offsets
- Test both start and end boundary conditions of the code block
Closes #6311
https://github.com/user-attachments/assets/b1d9337d-40b4-4883-b6d5-3757c498200b
https://github.com/user-attachments/assets/33069c7f-681f-487b-ad45-a02198fe5509
Fixes #6311

[lexical-code][lexical-playground] Bug Fix: Fix selection boundaries in code block

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/lexical/ContextMenuCopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-react/src/shared/LexicalMenu.ts

Credit to Cindy Zhang.
The currently menu position logic can interfere with other (third-party) components that attempt to position the component nicely within the screen. Immediate position makes it play better with these.

Position menu immediately

---

packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx

Adds supports for freezing the top row, but unsure if we want it, because if activated, the scrollable container cannot be scrollable horizontally, so we need to clip the content for this to work or have the whole document canvas expand (old behaviour, pre-wrapper).
Details here: https://github.com/w3c/csswg-drafts/issues/865#issuecomment-350585274
All workarounds involve Javascript and are far from nice.
My current most rational idea would be to show the option to freeze/unfreeze the top row ONLY IF the table doesn't have a scrollbar and the moment the table gets wider and an overflow comes into effect to automatically disable the frozen top row for the table and hide the option from the menu.
I'm open to better suggestions, because it does seem like something cool to have. …

[lexical-table] Freeze top row using pure CSS

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/README.md
packages/lexical-table/src/LexicalTablePluginHelpers.ts
packages/lexical-table/src/__tests__/unit/LexicalTablePlugin.test.tsx

- Tables can be nested inside table cells through both insertion and paste operations
- This leads to unintended selection behavior where selecting cells in inner tables also selects outer table cells
- Nested tables are not a supported use case as confirmed by @ivailop7 
- Prevent table insertion inside table cells via `INSERT_TABLE_COMMAND`
- Block table paste operations within cells via `SELECTION_INSERT_CLIPBOARD_NODES_COMMAND`
- Add comprehensive test coverage:
- Unit tests to verify command handlers in `TablePlugin`
- E2E tests in `Tables.spec.mjs` to verify user interactions
Closes #7154
Nested tables have never worked correctly, but there was partial "support" for them in the code. While it may make sense to support them in the future, a …

[Breaking Change][lexical-table] Bug Fix: Prevent nested tables

---

packages/lexical/src/LexicalSelection.ts

https://github.com/facebook/lexical/pull/7122 added a `setBaseAndExtent` call on `LexicalSelection.ts` line `2935` that as far as I understand is intended to be caught and ignored if an error is thrown, but since it's wrapped inside of a `setTimeout` callback it's still uncaught. 
Would be nice if it was handled the same way as the `setBaseAndExtent` call which isn't in the `setTimeout` callback (line `2925`). if that's the intention at least. 
lmk if it makes sense, thx.
potential Uncaught `Failed to execute 'setBaseAndExtent'` may happen
potential Uncaught `Failed to execute 'setBaseAndExtent'` don't happen, as I assume was the intention

[lexical] Bug Fix: catch setTimeout wrapped setBaseAndExtent call

---

scripts/__tests__/integration/fixtures/lexical-esm-astro-react/package-lock.json
scripts/__tests__/integration/fixtures/lexical-esm-astro-react/package.json
scripts/__tests__/integration/utils.js

astro integration test strangely started failing. Locally it seems that the server would just hang on requests instead of serving them. Looks like it might've been the --no-package-lock usage, which was intended to make sure we were testing a recent version of the frameworks under test, but it's not really worth the hassle on our end to have that setting.
Integration tests would fail for no good reason (e.g. https://github.com/facebook/lexical/actions/runs/13383012921/job/37374781282)
Integration tests pass again

[ci] Chore: Upgrade astro to fix mysterious integration test failure

---

packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx

TableNode ignored its __style attribute, this PR adds support for it
Closes #7201
`tableNode.setStyle(…)` has no effect on the DOM
`tableNode.setStyle(…)` is reconciled to the DOM, and this is unit tested.

[lexical-table] Feature: Support TableNode.__style in createDOM and updateDOM

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-playground/src/plugins/CollapsiblePlugin/index.ts

Now that we have more robust handling of deleteCharacter around decorators and shadow roots, we can get rid of the expectation that CollapsibleContainerNode does something weird. AFAICT this behavior was a result of the implementation and not something that was specifically intended?
Follow-up to #7155 
Related #3082 #4257 https://github.com/facebook/lexical/blame/f5e6329c3773a3e968eeb06a50ae002ce8b1318f/packages/lexical-playground/src/plugins/CollapsiblePlugin/index.ts#L169
Closes #7203
Delete forward before a CollapsibleNode would pierce the shadow root and unroll its content at the caret
Delete forward before a CollapsibleNode will do nothing, like other shadow roots (e.g. table)

[Breaking Change][lexical-playground]: Refactor: Remove special case for collapsible forward deletion

---

packages/lexical-playground/src/nodes/EquationNode.tsx
packages/lexical-playground/src/nodes/ExcalidrawNode/index.tsx
packages/lexical-playground/src/nodes/ImageNode.tsx
packages/lexical-playground/src/nodes/InlineImageNode/InlineImageNode.tsx
packages/lexical-playground/src/nodes/PollNode.tsx
packages/lexical-playground/src/nodes/StickyNode.tsx

- Playground node decorators (`PollNode`, `ImageNode`, etc.) have redundant Suspense wrappers in their decorate methods
- Each decorator is wrapped twice in Suspense components - once by `useDecorators` hook and again in the node's `decorate` method
- This creates unnecessary component nesting and impacts React's reconciliation efficiency
- Removes redundant Suspense wrappers from node `decorate` methods since `useDecorators` already provides `Suspense` functionality
- Removes unused `Suspense` imports from affected files
- Simplifies component tree and improves React reconciliation process
- Affects the following nodes:
- PollNode
- ImageNode
- InlineImageNode
- ExcalidrawNode
- StickyNode
- EquationNode
This PR removes redundant Suspense wrappers …

[lexical-playground] Refactor: Remove redundant Suspense from node decorators

---

packages/lexical-react/src/__tests__/unit/Collaboration.test.ts
packages/lexical-react/src/__tests__/unit/utils.tsx
packages/lexical-yjs/src/SyncEditorStates.ts

If you have multiple adjacent text nodes in a single block, and they're all merged (normalised) in a single update, and that update is either tagged `collaboration` or `historic`, then Lexical and Yjs get out of sync. This is caused by collab nodes being removed from their parent too early in `$handleNormalizationMergeConflicts`, which leads to offset calculations being wrong.
I don't know how the editor gets into this state through normal user behaviour, but we've seen it in production multiple times now. Most recently today, where a user had a document with lots of repeated content, similar to https://github.com/facebook/lexical/issues/6614#issuecomment-2424855275 (we're on 0.24.0 though).
I'm still working on a repro which could be added to E2E tests, but for now I've resorted to …

[lexical-yjs] Bug Fix: Normalize multiple adjacent merge conflicts in one block

---

packages/lexical-table/README.md

The usage example in @lexical/table's readme was not correct. Rather than trying to correct the inline example, I thought it would be better to point to the example project that is checked by CI (at least so far as building and passing type checks).

[lexical-table] Docs: Fix @lexical/table README.md

---

packages/lexical-list/src/index.ts

Export `ListNodeTagType` since it's helpful to consumers. Otherwise, they need to do something like the following to obtain the type:
```ts
import type { ListNodeTagType } from 'node_modules/@lexical/list/LexicalListNode'
```
n/a

[@lexical/list] Feature: export `ListNodeTagType`

---

packages/lexical-list/src/formatList.ts
packages/lexical-playground/__tests__/e2e/List.spec.mjs

List item node loses selection style and format when exit nested list.
- Go to Playground
- Insert a new list
- Change text style, i.e. font, color or formatting
- Write a bullet point
- Press `Enter` and `Tab` to start nested list
- Write a text
- Press enter twice to exit nested list
- Write a text
- [Bug] Expect the text losing styles and format
https://github.com/user-attachments/assets/f02edaa0-d1cf-40a2-8909-2480e2f93bf8
https://github.com/user-attachments/assets/155248d2-f5eb-482f-8656-574b308508fd

[lexical-list] Bug Fix: retain selection styling when exiting nested list

---

packages/lexical-playground/src/plugins/TableHoverActionsPlugin/index.tsx
packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts
packages/lexical-playground/src/utils/getThemeSelector.ts

The [TableHoverActionsPlugin](packages/lexical-playground/src/plugins/TableHoverActionsPlugin/index.tsx) has following class names hard coded instead of being referenced from theme.
- PlaygroundEditorTheme__tableAddRows
- PlaygroundEditorTheme__tableAddColumns
- PlaygroundEditorTheme__tableCell
This PR fixes the hard coded names.
There is no change in behaviour due to the fix. It only enables the Table Hover Action Plugin to keep working if the Playground theme is modified.

[lexical-playground] fix: hard coded theme classes for table hover actions

---

packages/lexical-playground/src/nodes/ImageComponent.tsx

Currently the image element in editor sheet rerenders on every character modified in the editor, which leads to typing speed latency when more number of images are present in the editor. Updated the code to ensure its only rerendered when needed
https://github.com/user-attachments/assets/5475d683-0f95-4971-8442-76fde72bfc35
https://github.com/user-attachments/assets/178ede8b-3f0b-4e68-9e8e-1095249755c3

[lexical-playground] Refactor: Image component rerenders on every editor update

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-table/src/LexicalTablePluginHelpers.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

- When triple-clicking a table cell, it incorrectly selects adjacent cells
- For cells in the last column, it selects cells in the next row
- Selection behavior is inconsistent across different cells in the table
- Test has browser-specific checks:
- For Firefox: expects to select the full text content of the clicked cell
- For Chromium: expects to select the first cell instead of the clicked cell
Changes added by this PR:
- Adds `$tableClickCommand` to handle triple-click events specifically for table cells: (The implementation is based on @etrepum's approach from PR #7005)
- Checks if clicked block's parent is a table cell
- Uses `select(0)` to properly select the entire block content
- Prevents selection from spreading to adjacent cells
- Adds …

[lexical-table] Bug Fix: Prevent adjacent cell selection on triple-click

---

package-lock.json
packages/lexical-website/package.json

This pull request is to update the  docusaurus version
currently, inside lexical-website, the docusaurus/plugin-client-redirects has a different version(3.7.0) so the `docusaurus build` would fail.
when run `docusaurus build`
Error: Invalid name=docusaurus-plugin-client-redirects version number=3.7.0.
All official [@docusaurus](https://www.internalfb.com/intern/profile/docusaurus)/* packages should have the exact same version as [@docusaurus](https://www.internalfb.com/intern/profile/docusaurus)/core (number=3.6.0).
able to run `docusaurus build`

[Update] Upgrade docusaurus version

---

packages/lexical-playground/__tests__/regression/7246-delete-character-backward-list.spec.mjs
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleContainerNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
packages/lexical/src/LexicalSelection.ts

As a follow-up to #7180 the collapseAtStart logic now continues through both inline and non-inline nodes so long as there are no previous siblings, roots, or shadow roots encountered. This is because nodes such as CollapsibleTitleNode had a collapseAtStart that returns true but contain nodes that are not inline and have a collapseAtStart that returns false (e.g. ParagraphNode). 
In order to fix an inconsistency for how nested !isInline elements behave, CollapsibleContainerNode is now a shadowRoot. The CollapsibleContentNode was already a shadowRoot. This is now similar to the situation for tables where both TableNode and TableCellNode are both shadowRoot. The fix here also moved collapseAtStart from CollapsibleTitleNode to CollapsibleContainerNode which makes a bit more sense since the …

[Breaking Changes][lexical][lexical-list][lexical-playground] Bug Fix: deleteCharacter through ListNode->ListItemNode

---

packages/lexical/src/caret/LexicalCaret.ts

fix to match the function it is throwing from

[lexical] fix typo in Caret error msg

---

packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx

Table Action Menu is not positioned properly when the window is vertically scrolled.
https://github.com/user-attachments/assets/be36b015-03b1-47f3-b6ab-db2c8bc382b6
https://github.com/user-attachments/assets/b816f51e-c2e1-4b2f-941e-1e017379639f
I have tested the following scenarios and they work fine after the fix:
- when there is enough space below the Menu Button to display the Menu
- when there is not enough space below the Menu Button but enough space above
- when there is not enough space below and above the Menu Button
- tested the above three scenarios when page is scrolled and not scrolled

[lexical-playground] Bug Fix Table Action Menu dropdown positioning

---

packages/lexical-mark/__tests__/unit/LexicalMarkNode.test.ts
packages/lexical/src/LexicalUtils.ts

The [&lt;mark&gt;](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-mark-element) element was not correctly identified as an inline element.
Closes #4641
All pre-existing unit tests pass. A simple `<mark>`-specific test was added to the `lexical-mark` unit tests.
```typescript
const dom = new DOMParser().parseFromString(
`<html><body>Foo <mark>Bar</mark> !</body></html>`,
'text/html',
);
const nodes = $generateNodesFromDOM(editor, dom);
```
Output:
```html
<span data-lexical-text="true">Foo</span><mark data-lexical-text="true"><span>Bar</span></mark><span data-lexical-text="true">!</span>
```
```typescript
const dom = new DOMParser().parseFromString(
`<html><body>Foo <mark>Bar</mark> !</body></html>`,
'text/html',
);
const nodes = $generateNodesFromDOM(editor, dom); …
```

[lexical][lexical-mark] Bug Fix: Identify <mark> as inline element

---

packages/lexical-selection/src/range-selection.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/__tests__/unit/LexicalSelection.test.ts
packages/lexical/src/caret/LexicalCaretUtils.ts

Fixes a long-standing bug in Point.isBefore by using the NodeCaret implementation of `$comparePointCaretNext`
Closes #3181
If two points that are not normalized are compared, and isBefore's incorrect normalization causes the compared nodes to match (without fixing up the offsets) then the result can be wrong because the offsets refer to a different node entirely.
The normalization is now correctly performed with carets, and there's a unit test to confirm that the known broken situation is now fixed.

[lexical] Bug Fix: Point.isBefore could return incorrect result due to normalization

---

packages/lexical-react/src/shared/LexicalMenu.ts

anchor element not cleanup when component unmount

[@lexical/react]  Bug Fix: anchor element not cleanup when component unmount

---

packages/lexical/src/LexicalEvents.ts

Fixes #4340 
This is a second attempt to fix the abovementioned bug, following the unsuccessful attempt in #7122 (apologies for the issues introduced then)
In this PR, selection is only restored during deletion and when several other criteria have been met, this should minimise the chances of any unintended side effects.
https://github.com/user-attachments/assets/6f555449-8112-400b-8d21-ed35b249f428
https://github.com/user-attachments/assets/7617e10e-faf6-4d25-b1ab-e73c5f8a0dad

Fix selection shifting when deleting paragraphs on android

---

packages/lexical/src/LexicalCommands.ts
packages/lexical/src/LexicalNode.ts

Updating to 0.26.0 causes our project to crash executing a standalone node script that imports from `lexical` (this cannot be reproduced when importing lexical from a bundler).
The reason for that is this import that made it into the lexical build:
This is caused by the following newly introduced import statement in `packages/lexical/src/LexicalNode.ts`:
`import {Klass, KlassConstructor, NODE_STATE_KEY} from 'lexical';`
Imports from self like that are not valid and cause issues. I have verified that removing it fixes our issue.
Notably, such self-import statements can easily slip in (especially with VS Code’s auto-import suggestions). To help guard against this, we’ve created a custom ESLint rule ([no-imports-from-self](https://github.com/payloadcms/payload/blob/main/packages/eslint-plugin …

[lexical] Bug Fix: invalid import from self

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/keyboardShortcuts/index.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/nodes/InlineImageNode/InlineImageNode.tsx
packages/lexical-selection/src/range-selection.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/caret/LexicalCaretUtils.ts
packages/lexical/src/index.ts

To handle platform differences and avoid piercing shadow roots, arrow key navigation for RangeSelection is now handled by lexical in more scenarios when crossing the boundaries of elements. This should only affect "exotic" custom element nodes such as TableNode. All code in @lexical/table has been updated accordingly, but if you have something like a custom table implementation then it may require additional updates (probably in the direction of removing workarounds rather than adding them).
Address deleteLine regression in #7248. The selection movement code had some logic errors and adding carets to the mix (which validate text offsets) messed it up. This fixes the problem mostly by improving RangeSelection.modify.
It now:
* Checks for decorators around the focus and manually implements …

[Breaking Changes][lexical] Bug Fix: Address deleteLine regression in #7248

---

packages/shared/src/formatDevErrorMessage.ts
packages/shared/src/formatProdErrorMessage.ts
scripts/build.js
scripts/error-codes/__tests__/unit/transform-error-messages.test.js
scripts/error-codes/transform-error-messages.js

Refactor the invariant and its associated transform-error-messages babel plug-in to use a format function regardless of whether it's in dev or prod mode. This makes it easier to place a breakpoint where an exception will be thrown since now there is a function called unconditionally in error situations.
In this refactor I also moved the format*Error functions to TypeScript modules in the shared package so they could get picked up easily by vite and maintained in the same syntax as the rest of the project without having any additional aliases or resolution functions.
Separately we might consider renaming these functions to `throw*ErrorMessage` instead of `format*ErrorMessage` to be more clear that they don't return, but I didn't know if there was any internal tooling at Meta that would be …

[*] Chore: Refactor shared/invariant for easier dev debugging

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/regression/7266-column-header-merged-cells.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx

This PR:
- updates `toggleTableColumnIsHeader` to ensure column headers are applied correctly.
- creates `assertTableHTML` to allow legacy tables to be tested in regression tests.
- updates a tables test to handle the new column header logic (we are now using recommended best practices for column headers with merged cells).
There is opportunity here to update `toggleTableRowIsHeader` to use similar logic to `toggleTableColumnIsHeader` for consistency if we deem it within the scope of this PR.
Closes #7266
1. Merge some cells vertically in a column.
2. Toggle column header for that column.
https://github.com/user-attachments/assets/3f74cbe6-9ea6-458a-b6b3-7d974d516503
https://github.com/user-attachments/assets/01ffd04d-1df8-4841-9add-40291456d6d2

[lexical-playground] Bug Fix: apply correct column headers when column contains vertically merged cells

---

.github/workflows/call-core-tests.yml
.github/workflows/close-stale-pr.yml

The GITHUB_TOKEN secrets present in these workflows shouldn't be necessary, since the workflow generates tokens with the requested permissions

[ci] Chore: Remove unused GITHUB_TOKEN secrets from workflows

---

packages/lexical-utils/src/__tests__/unit/LexicalNodeHelpers.test.ts
packages/lexical-utils/src/index.ts

Take #2 of https://github.com/facebook/lexical/pull/7274
The introduction of [Carets](https://github.com/facebook/lexical/pull/7046/files#diff-33353db27f56a5d74e7281df0a8a2fc223eef41e9dc2efc723a412560a0148c9R239) changed `$dfs` to include siblings of the start node's parent, if the start node is the last child of its parent.
I've added a test case and confirmed that the test passes on 0.24.0, i.e. before the caret changes were introduced. I haven't got myself familiarised with the caret API yet though, and couldn't easily see what needed to change to fix this behaviour. On main, test fails with:
```
● LexicalNodeHelpers tests › dfs order › DFS starting at last child of element node should not include parent's siblings
expect(received).toEqual(expected) // deep equality
- Expected  -  0
+ …
```

[lexical-utils] Bug Fix: don't include parent's siblings when starting $dfs at last child

---

packages/lexical-playground/__tests__/e2e/Images.spec.mjs
packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/regression/5583-select-list-followed-by-element-node.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

When clicking and dragging from a table cell in Firefox it seems that the pointer gets captured and the target never leaves the initial location. This refactors the LexicalTableSelectionHelpers mousemove handler to always use the event coordinates rather than the event target in Firefox.
Closes #7245
Clicking and dragging to create a table selection stopped updating very quickly, see #7245
Can click and drag to create a table selection in Firefox

[lexical-table] Bug Fix: Click and drag table selection in Firefox

---

eslint-plugin/src/rules/no-imports-from-self.js

When an invalid import is generated (usually by vscode heuristics) we generally know what the import *should* be so we might as well provide a fixer at the same time.
Get a lint error when circularly importing a module
Also get a lint error, but make it fixable by replacing the package name with `.`, e.g. in
packages/lexical/src/LexicalNodeState.ts
```ts
import {NODE_STATE_KEY} from 'lexical';
```
Error: Exported module 'lexical' should not import from itself. Use a relative import instead.
Suggestion: Rename import 'lexical' to '.' (lexical/no-imports-from-self)
An also correct fix (and what is actually in that particular module right now) would be to do the import directly from the module that defines it:
```ts
import {NODE_STATE_KEY} from './LexicalConstants';
```
But given the …

[CI] Feature: Add a fixer for the no-imports-from-self lint

---

examples/react-plain-text/package.json
examples/react-plain-text/vite.config.monorepo.ts
examples/react-plain-text/vite.config.ts
examples/react-rich-collab/package.json
examples/react-rich-collab/vite.config.monorepo.ts
examples/react-rich-collab/vite.config.ts
examples/react-rich/package.json
examples/react-rich/vite.config.monorepo.ts
examples/react-rich/vite.config.ts
examples/react-table/package.json
examples/react-table/vite.config.monorepo.ts
examples/react-table/vite.config.ts
examples/vanilla-js-iframe/package.json
examples/vanilla-js-iframe/vite.config.monorepo.ts
examples/vanilla-js-iframe/vite.config.ts
examples/vanilla-js-plugin/package.json
examples/vanilla-js-plugin/vite.config.monorepo.ts
examples/vanilla-js-plugin/vite.config.ts
examples/vanilla-js/package.json
examples/vanilla-js/vite.config.monorepo.ts
examples/vanilla-js/vite.config.ts

Since typescript configs are used the conditional import approach (#7208) didn't work for conditional vite plugins, since they still had to exist on disk for rollup to process it. This splits the configuration for all example projects into two files, vite.config.ts and vite.config.monorepo.ts which works around the problem.
Gallery examples didn't work on stackblitz, because only the example was checked out and not the whole repo
https://lexical.dev/gallery
Gallery examples work: https://lexical-git-fork-etrepum-fix-gallery-vite-config-fbopensource.vercel.app/gallery

[lexical-website] Bug Fix: Fix vite.config.ts for gallery examples

---

packages/lexical-playground/src/plugins/TableCellResizer/index.css
packages/lexical-playground/src/plugins/TableCellResizer/index.tsx

This pull request includes several changes to improve touch support for the `TableCellResizer` plugin.
Enhancements to touch support and event handling:
* [`packages/lexical-playground/src/plugins/TableCellResizer/index.css`](diffhunk://#diff-dd8f4a9b1046befb4eff4fc8d818e1c75740c8edc8d1680403ca778229e8356dR13-R19): Added styles for coarse pointer devices to improve touch interaction.
* [`packages/lexical-playground/src/plugins/TableCellResizer/index.tsx`](diffhunk://#diff-21abbbd7f4404e12ac6e30e272b3ceaed16a4a7a184c2814a88e478090ca40a0L109-R113): Replaced `MouseEvent` with `PointerEvent` to handle both mouse and touch events, and added specific handling for touch events such as `onTouchMove` and `onClick`. [[1]](diffhunk://#diff-21abbbd7f4404e12ac6e30e272b3ceaed16a4a7a184c2814a88e478090ca4 …

[lexical-playground] Feature: Add touch support for TableCellResizer

---

packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-table/src/LexicalTableObserver.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

[commit #fcb7666](https://github.com/facebook/lexical/commit/fcb7666) introduced a regression for table cell selection on touch devices, previously clicking a cell while cursor is inside another cell would select the cells in between, clicking again collapses the selection.
* [`packages/lexical-table/src/LexicalTableSelectionHelpers.ts`](diffhunk://#diff-4efac82ecef2990d8b44ca49b63c50e2767e9496650884a89ba7111c57152e15R309-R341): Implemented a function to handle click events, specifically for touch input, and update the table selection accordingly.

[lexical-table] Add table cell selection handler for touch devices

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/src/plugins/TableCellResizer/index.tsx

- Row height resizing doesn't work correctly after merging cells
- The height style is applied to the wrong row when resizing merged cells
- Fixed row height calculation logic in TableCellResizer plugin to properly handle merged cells:
1. Added detection of full row merges by checking `tableCellNode.getColSpan() === tableNode.getColumnCount()`
2. Updated row index calculation to apply height to:
- First row (`baseRowIndex`) for full row merges
- Last row (`baseRowIndex + rowSpan - 1`) for partial merges
- Simplified height calculation logic to use direct cell heights
- Added E2E test "Resize row with merged cells spanning multiple rows" to verify the behavior
Closes #7304
- Insert a table
- Merge cells (full row)
- Try to resize the row height using …

[lexical-playground] Bug Fix: row height resizing for merged cells

---

packages/lexical-table/src/LexicalTableObserver.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts

This pull request adds a new property to track the type of pointer used and delegates the creation of a table selection until selection change occurs.
This approach would fix #7308.

[lexical-table] Bug Fix: Fix unintended touch table cell selection when scrolling

---

package-lock.json
packages/lexical-react/package.json
packages/lexical-react/src/__tests__/unit/PlainRichTextPlugin.test.tsx

This reduces the amount of dependencies installed by `@lexical/react`.
- `@lexical/clipboard`: This is not _directly_ used in @lexical/react
- `@lexical/selection`: This is not _directly_ used in @lexical/react
- `@lexical/code`: This is only used in a test file and does not have to be installed by the end-user. => I moved it to `devDependencies`.
This is the first step to ensuring that `@lexical/code` is not installed in projects that don't use it. The next step would be to remove it from `@lexical/markdown`.

[lexical-react]: Chore: remove unused dependencies from @lexical/react

---

packages/lexical-table/flow/LexicalTable.js.flow
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical/flow/Lexical.js.flow
packages/lexical/src/nodes/LexicalElementNode.ts

If you're using the undocumented internal getDOMSlot API, you may need to change your types. There is now a type parameter for ElementDOMSlot so that the element property can be specialized.
TableNode.updateDOM didn't work correctly when there was a wrapper node involved in certain situations. This unifies the createDOM and updateDOM code paths and refines the types for ElementDOMSlot and its usage in TableNode so that this mistake can't be made again.
Try toggling striping off in a node loaded with striping on, it won't do anything
[playground repro](https://playground.lexical.dev/#doc=H4sIAAAAAAAAE-2ZwWvCMBTG_5d3DtJWoTPXwc6DHjyIh5i82bAsKa-vOhH_96FVUGHDedhEHhRCaL7k6-_1fZdsAJ3nRBUbRtAboJR4N9raB0cYQU_PJjMFzhNa9imCjl0ICt4SfRgGDaDAR4eRQWcKeN0gaGgMmQWZpgYFS6R2L8wVMH7yy0GZ9dOK12Enga363sG_e_v9MW …

[Breaking Change][lexical][lexical-table] Bug Fix: Scrollable TableNode updateDOM fixes and getDOMSlot type refactoring

---

packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx
packages/lexical/src/index.ts

In order to better support NodeState and other use cases (e.g. some sort of "createdDOM/updateDOM" middleware) where it's useful to know about *all* nodes that were mutated in the DOM this adds the mutatedNodes property to UpdateListenerPayload and adds some API docs.
With this change it would be possible to implement mutation listeners as an updateListener so we could reduce some surface area in the future with a reduced core.
Includes unit tests for expected behavior of the payload.

[lexical] Feature: Add mutatedNodes to UpdateListener payload

---

packages/lexical-list/package.json
packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical-playground/__tests__/e2e/List.spec.mjs
packages/lexical-playground/src/themes/PlaygroundEditorTheme.css

The approach used in #7024 (since v0.26.0) to have a ListItemNode bullet inherit the style of the first text node was too broad, the inline style on the ListItemNode cascades to *all* of its children. The only way around this is to change the approach.
To retain this feature, you need to add CSS to your theme to specifically style the marker pseudo-element based on these new custom properties. Here's an example from the playground css:
```css
.PlaygroundEditorTheme__listItem::marker {
color: var(--listitem-marker-color);
background-color: var(--listitem-marker-background-color);
font-family: var(--listitem-marker-font-family);
font-size: var(--listitem-marker-font-size);
}
```
The first approach to applying text styles to ListItemNode simply set the style attribute, which has the …

[Breaking Change][lexical-list] Bug Fix: Move ListItemNode text style inheritance to custom properties and CSS

---

packages/lexical-playground/__tests__/regression/7319-delete-character-backward-nodeselection.spec.mjs
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx
packages/lexical-playground/src/nodes/ImageComponent.tsx
packages/lexical-playground/src/nodes/InlineImageNode/InlineImageComponent.tsx
packages/lexical-playground/src/nodes/PageBreakNode/index.tsx
packages/lexical-playground/src/nodes/PollComponent.tsx
packages/lexical-react/src/LexicalBlockWithAlignableContents.tsx
packages/lexical-react/src/LexicalHorizontalRuleNode.tsx
packages/lexical-rich-text/src/index.ts
packages/lexical/src/LexicalSelection.ts

If you have any `$onDelete` handlers copied from the playground for `KEY_DELETE_COMMAND` and `KEY_BACKSPACE_COMMAND`, you can delete them all now. If you leave them in, it will have similar bugs as prior to this PR.
The default `KEY_DELETE_COMMAND` and `KEY_BACKSPACE_COMMAND` handlers now preventDefault and call `DELETE_CHARACTER_COMMAND` for NodeSelection (in addition to the existing RangeSelection behavior).
The `DELETE_CHARACTER_COMMAND` handler now handles NodeSelection by calling the new `NodeSelection.deleteNodes()` method which places a new RangeSelection where the first selected node was (if any, and if it was the current selection) and then removes all of the selected nodes.
NodeSelection has no default handler for when the delete or backspace keys are pressed. This results in …

[Breaking Change][lexical][lexical-playground] Feature: Add a default delete handler for NodeSelection

---

packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx

The playground table actions `clearSelection()` sets the selection to the beginning of the document for no good reason, which causes the page to scroll.
Closes #7335
See #7335
The selection is actually cleared

[lexical-playground] Table actions should clear selection instead of moving it to the beginning

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical-plain-text/src/index.ts
packages/lexical-react/src/LexicalLinkPlugin.ts
packages/lexical-rich-text/src/index.ts
packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical-utils/src/index.ts

- adds type predicate to `objectKlassEquals`
- removes unnecessary type assertions following `objectKlassEquals` calls
it is backward compatible since the return type is still boolean but just with type predicate.

[lexical-utils] Feature: Add type predicate to objectKlassEquals

---

packages/lexical-list/src/LexicalListNode.ts
packages/lexical-website/docs/concepts/transforms.md
packages/lexical/src/LexicalReconciler.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx
packages/lexical/src/nodes/LexicalRootNode.ts

This PR moves the incorrectly overridden `append` methods for RootNode and ListNode and moves it to the ElementNode's primitive `splice` method. For RootNode this means that the exception you'd get for appending a leaf node to the root will be thrown in all situations when that node is inserted, rather than just append. For ListNode this means that the automatic ListItemNode wrapping applies in all situations when children are inserted into the node, not just append.
The `$applyAllTransforms` loop has a fast path to ignore ElementNode that were not intentionally marked as dirty (ancestors of parents).
```ts
if (nodeKey !== 'root' && !intentionallyMarkedAsDirty) {
continue;
}
```
This is a sensible thing to do, but the way it was implemented *discarded* the fact that this node was not …

[Breaking Change][lexical] Bug Fix: Fix bug in transformer loop that would cause nodes not to get reconciled

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/TablesHTMLCopyAndPaste.spec.mjs
packages/lexical-table/src/LexicalTableCellNode.ts
packages/lexical-table/src/__tests__/unit/LexicalTableCellNode.test.ts

The importDOM implementation for TableCellNode has been corrected to behave as other Lexical roots do with regard to converting `<br>` tags to `LineBreakNode` and wrapping runs of top-level inline nodes (including inline decorators) with `ParagraphNode`. If you have any specific workarounds accounting for the previous behavior, you can remove them. The one difference from other import paths is that a solitary `<br>` (e.g. `<td><br></td>`) is converted to an empty `ParagraphNode` rather than a `ParagraphNode` containing a `LineBreakNode`.
Table cell line breaks behave differently from the intended HTML behavior.
Modify the logic to align with the intended HTML line breaks.
Closes #7261
Add TC to `TableCellNode.importDOM`
| case | html | editor |
| ---- | ---- | ------ |
| inline decorator …

[Breaking Change][lexical-table] Bug Fix: Table cell line breaks behave differently from the intended HTML behavior.

---

packages/lexical-playground/src/plugins/DraggableBlockPlugin/index.css
packages/lexical-playground/src/plugins/DraggableBlockPlugin/index.tsx
packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx
packages/lexical-playground/src/ui/ContentEditable.css
packages/lexical-react/flow/LexicalDraggableBlockPlugin.js.flow
packages/lexical-react/src/LexicalDraggableBlockPlugin.tsx

Allows passing a function to receive the DOM element identified by the DraggableBlockPlugin. 
An example application of this is the addition of a "+" button that allows the creation of a block above the identified one. This feature is particularly useful in the playground, as it allows adding a new block at the top of the page without having to drag and drop, for example.

[lexical-playground][lexical-react] Feature: Push Draggable Element to Parent

---

packages/lexical-playground/src/plugins/DraggableBlockPlugin/index.css
packages/lexical-playground/src/plugins/DraggableBlockPlugin/index.tsx

Switch from a div to a button and add the appropriate css and title attribute, this resolves a lint warning and generally improves accessibility.
No visual change other than the title.

[lexical-playground] Chore: Improve accessibility of DraggableBlockPlugin add block button

---

packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalNode.ts
packages/lexical/src/nodes/__tests__/unit/LexicalRootNode.test.ts

If you are somehow relying on an editor always creating a `RangeSelection` in an update when the `RootNode's` last child was removed, then you will have to change your code to explicitly set a selection before or after the editor is made empty. The intent of this code was to *move* a selection to the root if all of its children were removed, but a bug in `LexicalNode.remove()` would *always* create that selection when the root became empty during an update. A more likely scenario is that you might be able to remove `setSelection(null)` and/or `$addUpdateTag('skip-dom-selection')` workarounds for this specific issue (leaving them in should not cause any issue).
Removing the last child of RootNode would always create a RangeSelection, when the intent should be to do so only in cases when …

[Breaking Change][lexical] Bug Fix: Only select RootNode on removal of last child if there was an existing selection

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx

Currently, the table action menu button remains visible even when a cell is partially visible due to overflow, as reported in issue #7331. This creates a confusing user experience since the menu appears for cells that are not fully in view.
This PR improves the table action menu visibility check by properly handling cell overflow in the scrollable container. The menu is now correctly hidden when a cell is partially visible and reappears when scrolled into full view.
Technical Changes:
1. Created `checkTableCellOverflow` in `TableActionMenuPlugin` to:
- Check direct cell overflow (width/height)
- Verify cell is fully visible within its scrollable container
- Handle both single cell and table selection cases
2. Added E2E test to verify:
- Menu …

[lexical-playground] Bug Fix: Table action menu visibility with cell overflow

---

packages/lexical-markdown/src/MarkdownExport.ts
packages/lexical-markdown/src/MarkdownImport.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-markdown/src/importTextTransformers.ts
packages/lexical-playground/__tests__/e2e/Hashtags.spec.mjs

Fixes https://github.com/facebook/lexical/issues/2715
This PR adds full support for escaping markdown characters during import and export. For example, `\*` now correctly becomes a literal `*` in the editor, and when exporting back to markdown, those special characters are automatically escaped (e.g. `*` becomes `\*`), preventing accidental formatting on re-import.
Safari [now has much better support for negative lookbehind regex](https://caniuse.com/?search=Negative%20Lookbehind), which is why I removed the conditions specific to it.
Previously, any escaped characters (e.g. `\*`) were imported as literal `\*`. Now the backslash is stripped, and the escaped character (`*`) is imported instead.
Previously, all markdown characters that were part of a text node (e.g. `**`) were exported …

[Breaking Change][lexical-markdown] Feature: Support escaping markdown characters

---

packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs
packages/lexical-playground/__tests__/regression/6974-delete-character-backward.spec.mjs
packages/lexical-playground/src/ui/KatexRenderer.tsx

Current Behavior: 
The KatexRenderer component uses empty image tags with `src="#"` around equations to prevent Android composition issues. However, this causes Safari to display question marks around the equations, creating an undesirable visual artifact.
This PR replaces the empty image tags' src attribute with a transparent 1x1 pixel GIF data URL and adds width/height=0 attributes. This maintains the Android composition prevention functionality while fixing the Safari display issue. The images will now be completely invisible across all browsers.
Closes #6824
When adding an equation in Safari:
- Question marks appear on either side of the equation
- The issue is specific to Safari browser
- No question marks visible around equations in Safari
- Equations render …

[lexical-playground] Bug Fix: Fix equation rendering in Safari

---

packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx

If you're using the new tableFrozenColumn or tableFrozenRow features you may need to change your CSS or test expectations since the tableFrozenRow and tableFrozenColumn classes are set on the scrollable table wrapper and not the table element. Generally this wouldn't break code unless you are using selectors such as `.tableFrozenColumn > tr` or `table.tableFrozenColumn` that wouldn't work correctly when the class is on the wrapper.
The tableFrozenRow class needs to affect the table wrapper's overflow-x, so it needs to be set on that element. An alternative solution would be to use the newer `:has` pseudo-selector, but that is only recently available in modern browsers.
Closes #7370
Unit test modified for new behavior

[Breaking Change][lexical-table][lexical-playground] Bug Fix: Set tableFrozenColumn and tableFrozenRow classes only on the scrollable table wrapper

---

package-lock.json
packages/lexical-playground/package.json
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx
packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawImage.tsx
packages/lexical-playground/src/plugins/ExcalidrawPlugin/index.tsx
packages/lexical-playground/src/ui/ExcalidrawModal.tsx
packages/lexical-playground/vite.config.ts
packages/lexical-playground/viteCopyExcalidrawAssets.ts

Updates lexical excalidraw plugin and associated vite configuration for [excalidraw v0.18.0](https://github.com/excalidraw/excalidraw/releases/tag/v0.18.0)
Manual testing that the excalidraw modal still works and the fonts load locally rather than from CDN

[lexical-playground] Chore: Update excalidraw to v0.18.0

---

packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/nodes/StickyComponent.tsx
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleContainerNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleContentNode.ts
packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
packages/lexical-playground/src/plugins/CommentPlugin/index.tsx
packages/lexical-playground/src/plugins/ShortcutsPlugin/shortcuts.ts
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-playground/src/plugins/TablePlugin.tsx
packages/lexical-playground/src/plugins/TestRecorderPlugin/index.tsx
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-playground/src/utils/getThemeSelector.ts

Remove use of the 'shared' package from lexical-playground so that it's easier to re-use. These usages fell into three categories:
* shared/environment - this is all exported from @lexical/utils
* shared/invariant - these can be replaced with `if (!condition) { throw new Error(message); }`
* shared/useLayoutEffect - this is only meaningfully different from react's export when using react <18 when doing SSR and realistically the only difference is a warning, so no compelling reason to use this or export it from @lexical/react
Existing e2e tests should all pass

[lexical-playground] Chore: Remove shared imports from playground

---

packages/lexical-list/src/__tests__/unit/formatList.test.ts
packages/lexical-list/src/formatList.ts

When we select empty nested list (meaning there's no content in it), and try to format to a different type it won't work and only change list type for those having at least some text in it. 
Updated code assumed that there will be some content within list items to traverse up to list item itself, while it's not the case for empty ones.
Before
https://github.com/user-attachments/assets/39430f32-65c6-40b0-b79f-abea3f34bc95
After
https://github.com/user-attachments/assets/f8bb1666-ddbf-436a-84f1-172d48ad9ab9

[lexical-list] Bug Fix: empty list item type change

---

examples/react-plain-text/package-lock.json
examples/react-rich-collab/package-lock.json
examples/react-rich/package-lock.json
examples/react-table/package-lock.json
package-lock.json
scripts/__tests__/integration/fixtures/lexical-esm-astro-react/package-lock.json
scripts/__tests__/integration/fixtures/lexical-esm-nextjs/package-lock.json

GitHub detected  vulnerabilities in these dependencies:
* @babel/runtime-corejs3 
* vite
* prismjs
* @babel/helpers
* @babel/runtime-corejs3 
existing test cases

Update dependencies: vite,@babel/runtime,prismjs,@babel/helpers

---

packages/lexical-playground/__tests__/e2e/Images.spec.mjs
packages/lexical-playground/src/nodes/ImageComponent.tsx

Currently, when an image is inserted with 'inherit' dimensions in the Lexical playground, it defaults to arbitrary 200x200 dimensions without considering the image's natural size. This causes visual inconsistency and incorrect image rendering on initial load.
1. Using the image's natural dimensions (naturalWidth/naturalHeight) when width/height is set to 'inherit'
2. Maintaining proper aspect ratio during scaling
3. Adding proper dimension detection on both initial mount and image load
4. Keeping the existing maxWidth and maxHeight (500px) constraints for editor usability
5. Using fallback dimensions (200x200) only while the image is loading
Closes #7376

[lexical-playground] Bug Fix: Use natural dimensions for inherited image size

---

packages/lexical-markdown/src/MarkdownImport.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts

Currently, when `shouldPreserveNewLines` is enabled, paragraphs after block elements (lists, quotes, and paragraphs) are incorrectly merged into the block. This causes issues with markdown formatting where new paragraphs are unintentionally becoming part of the previous block element.
This PR modifies the paragraph merging logic to respect the `shouldPreserveNewLines` setting. When enabled, paragraphs will maintain their separation from previous block elements, aligning with GitHub's markdown editor behavior for list and common markdown formatting expectations as discussed here: https://github.com/facebook/lexical/issues/6606.
- Updates the merging logic in `$importBlocks` to properly handle paragraph separation when `shouldPreserveNewLines` is true
- Updates test case to expect separate …

[Breaking Change][lexical-markdown] Bug Fix: Preserve paragraph separation after block elements

---

packages/lexical-link/src/index.ts
packages/lexical-playground/__tests__/e2e/Links.spec.mjs
packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx

Currently, the `$toggleLink` function in `@lexical/link` package only supports `RangeSelection`, making it impossible to add links to images or other nodes that use `NodeSelection`. The `FloatingLinkEditorPlugin` also doesn't show up when clicking on images, preventing users from adding or editing links on images.
This PR adds support for linking images in Lexical by:
1. Extending `$toggleLink` to handle both `RangeSelection` and `NodeSelection`
2. Updating FloatingLinkEditorPlugin to:
- Show link toolbar when clicking images
- Handle link editing for image nodes
- Position toolbar correctly for image selections
3. Adding comprehensive test coverage for:
- Adding/editing/removing links on single images
Closes #4645
https://github.com/user-attachments/assets/3ff74605-82ca-4573-8d83-9c5d25e8 …

[lexical-link][lexical-playground] Feature: Add support for image links via NodeSelection

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-react/src/__tests__/unit/Collaboration.test.ts
packages/lexical-yjs/src/Utils.ts
packages/lexical/src/LexicalReconciler.ts
packages/lexical/src/__tests__/unit/LexicalReconciler.test.ts

`LexicalReconciler` tries to determine whether text should be LTR or RTL based on a regex.
- https://github.com/facebook/lexical/blob/7c0ce40/packages/lexical/src/LexicalReconciler.ts#L367-L369
- https://github.com/facebook/lexical/blob/7c0ce40/packages/lexical/src/LexicalUtils.ts#L185-L193
- https://github.com/facebook/lexical/blob/7c0ce40/packages/lexical/src/LexicalConstants.ts#L101-L104
If a given block has no directioned text, then the `activeEditorDirection` is used. This more-or-less-global variable is set to `null` at the start of reconciliation but updated when a node with directioned text is encountered.
That's fine when processing the whole tree: node get updated in reading order. However, if you process only _some_ nodes in the tree, then you can end up changing the direction …

[lexical-yjs] Bug Fix: don't sync ElementNode __dir property

---

packages/lexical-rich-text/src/index.ts

- When clicking on an Excalidraw decorator, the button becomes active and becomes the target of keyboard events
- The right arrow key handler checks if the target is inside a decorator (`!$isTargetWithinDecorator`) and ignores the event
- This check was originally added in PR #2895 for all arrow keys to fix keyboard controls on internal decorators
- Later, PR #2929 removed this check from left arrow key, but it remained for right arrow key
- This creates an inconsistent behavior where right arrow doesn't work initially, but works after pressing left arrow
- Remove the `!$isTargetWithinDecorator` check from `KEY_ARROW_RIGHT_COMMAND` to match the behavior of `KEY_ARROW_LEFT_COMMAND`
- This allows consistent bi-directional arrow key navigation when decorator nodes are selected
- The change …

[lexical-rich-text] Bug Fix: Fix right and up arrow key navigation with decorator nodes

---

packages/lexical-markdown/src/MarkdownShortcuts.ts
packages/lexical-playground/__tests__/e2e/Markdown.spec.mjs

Prevent text-format Markdown shortcuts from matching with text in code-formatted text nodes.
For example, this ensures that typing the following:
```
`void*` and `int*`
```
results in "<code>void*</code> and <code>int*</code>" instead of "<code>void</code><i> and <code>int</code></i>".
Closes #7349
Run E2E tests: `npm run test-e2e-chromium Markdown.spec`
https://github.com/user-attachments/assets/51f3483c-2fa8-419f-affb-2d1e00b2ccd4
https://github.com/user-attachments/assets/134489a7-d770-48e5-b771-69351e9ddf4c

[lexical-markdown] Bug Fix: Prevent Markdown shortcuts from applying to code-formatted text

---

packages/lexical-yjs/src/SyncEditorStates.ts

This MR fixes an issue where your cursor would get scrolled back into view in a collab editor if your cursor was not in view and someone else made a change anywhere else in the state.
https://github.com/user-attachments/assets/69ea0e7d-de6d-4daa-8122-8646f43c9233
https://github.com/user-attachments/assets/2ca0f01e-b564-40eb-b21d-9cc033065256

[lexical-yjs] Bug Fix: Fix scroll position getting changed when someone else makes a change in collab

---

packages/lexical-markdown/src/MarkdownExport.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-markdown/src/importTextTransformers.ts

Currently, `exportTextFormat` in `MardownExports` trim the input first to handle the case looking like `**   foo   **`
An edge case here is if the string consists only of whitespaces, the trimmed string will be empty.
Based on the discussion [here](https://github.com/facebook/lexical/issues/6526#issuecomment-2725146825), one possible solution is replacing the whitespace with its corresponding code points,  which is also compatible with CommonMark.
Also, modify some test cases that have leading and trailing whitespaces.
Closes #6526 
https://github.com/user-attachments/assets/8a8882e7-db70-4401-9461-31db07fc5b88
https://github.com/user-attachments/assets/772fe8fa-634c-40ce-a217-3a8db2eca2e9
------------------
Test other whitespaces …

[RFC][lexical-markdown] Replace whitespace with code point when the string has leading and trailing whitespaces

---

packages/lexical/src/LexicalEditor.ts

Currently, we mark the selection dirty and force the selection back to it.
We freeze the selection object in `LexicalUpdates::$commitPendingUpdates` when in `DEV` mode for performance reasons
```javascript
if (!pendingEditorState._readOnly) {
pendingEditorState._readOnly = true;
if (__DEV__) {
handleDEVOnlyPendingUpdateGuarantees(pendingEditorState);
if ($isRangeSelection(pendingSelection)) {
Object.freeze(pendingSelection.anchor);
Object.freeze(pendingSelection.focus);
}
Object.freeze(pendingSelection);
}
}
```
In some cases, we have observed this error:
```
Uncaught TypeError: Cannot assign to read only property 'dirty' of object '#<RangeSelection>'
```
To prevent this, we can clone a node and use  `$setSelection` instead of assigning dirty to true directly. 
existing tests.
Have seen …

[Bug Fix] Clone a node and use  `$setSelection` instead of assigning dirty to true directly. 

---

packages/lexical-devtools-core/src/TreeView.tsx
packages/lexical-react/src/LexicalTreeView.tsx

- The debug view in TreeView component only updates when the editor state changes
- Commands that don't modify state (like KEY_ESCAPE_COMMAND) are not displayed until the editor regains focus
- This creates confusion for developers trying to debug command interactions
- Added a new `commandsLog` prop to TreeView to track commands independently of state changes
- Modified the update logic to trigger view refresh when either editor state or commands log changes
- Preserved existing time-travel functionality by only recording state changes in timeline
Closes #7379
1. Open the Playground
2. Click/focus the editor
3. Press Escape
4. KEY_ESCAPE_COMMAND is not logged in the debug view
5. Click outside the editor and back in
6. Only then does KEY_ESCAPE_COMMAND appear in the debug view
1. Open …

[lexical-devtools-core] Bug Fix: Update debug view to show KEY_ESCAPE_COMMAND immediately

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx
packages/lexical-react/src/shared/LexicalMenu.ts

- LexicalMenu and LexicalTypeaheadMenuPlugin automatically select the first menu item when rendered
- Users have to work around this by creating a hidden no-op first option
- No built-in way to disable the auto-selection behavior
- Added new `autoSelectFirstItem` prop (defaults to true for backward compatibility)
- When set to false, no menu item is selected on initial render
- Improved keyboard navigation to handle unselected state:
- Arrow down selects first item
- Arrow up selects last item
- Once an item is selected, maintains existing cycling behavior
- Added TypeScript types and prop interfaces for better type safety
Closes #7364
When opening any menu (e.g., component picker with "/"), the first item is always automatically selected
When `autoSelectFirstItem={false}`:
- Menu opens …

[lexical-react] Feature: Add option to disable first item auto-selection in menus

---

packages/lexical-devtools/tsconfig.json
packages/lexical/src/caret/LexicalCaret.ts
packages/shared/src/__mocks__/devInvariant.ts
packages/shared/src/devInvariant.ts
packages/shared/src/formatProdWarningMessage.ts
scripts/error-codes/__tests__/unit/transform-error-messages.test.js
scripts/error-codes/transform-error-messages.js
tsconfig.build.json
tsconfig.json

Change `$getTextNodeOffset` boundary checking to clamp with minified warning in prod and error in `__DEV__`. Adds a new `devInvariant` function with associated transform to provide this error-in-dev-warning-in-prod functionality that re-uses the same error map and transform-error-messages babel plugin.
We don't really have a facility to easily test behavior that only happens in `!__DEV__` but the transform itself is tested

[lexical] Chore: Change $getTextNodeOffset invariant to warn in prod (error in __DEV__)

---

packages/lexical-playground/__tests__/e2e/Indentation.spec.mjs
packages/lexical-rich-text/src/index.ts
packages/lexical/src/LexicalUtils.ts

Prevent paragraph indentation from becoming negative, which can trigger an invariant when converting to list nodes.
Closes #7410
`npm run test-e2e-chromium Indentation`

[lexical-rich-text] Bug Fix: Prevent indentation from becoming negative

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx
packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical-table/src/LexicalTableUtils.ts
packages/lexical-table/src/index.ts

Improve how we handle pasting table into table:
- Properly account for merged cells in both tables. Presence of merged cells currently causes very buggy behavior when pasting (including the possibility of creating nested tables).
- If the current selection is a range selection, allow the table being modified to grow if necessary to contain the table being pasted. This is in line with GDocs behavior.
- If the current selection is a table selection, constrain the modifications to be within the selection boundary. This is in line with GDocs behavior.
Closes #7262
Closes #7263
Added E2E tests for table pasting: `npm run test-e2e-chromium Tables.spec`
https://github.com/user-attachments/assets/d2f03651-8149-4697-b1f5-b7a222d8e650
https://github.com/user-attachments/assets/174211b4-c454-44e6-9e8 …

[lexical-table] Feature: Improve logic for pasting table into table

---

packages/lexical-playground/__tests__/e2e/ClearFormatting.spec.mjs
packages/lexical-playground/src/plugins/ToolbarPlugin/utils.ts

1. Add any text 
2. Select added text and try indent/outdent selected text
3. Now while keeping selection try `clear-formatting` it won't have any effect
https://github.com/user-attachments/assets/5f19a594-c28f-4463-a644-713235bb0306
https://github.com/user-attachments/assets/9388792e-1cf0-4b22-abc0-662bbfdc024f
clear formatting will be improved and cover wider range

[lexical-playground] Bug: clear formatting should also clear any indent/outdent if applied

---

packages/lexical-list/src/__tests__/unit/registerListStrictIndentTransform.test.ts
packages/lexical-list/src/index.ts
packages/lexical-playground/src/Editor.tsx
packages/lexical-playground/src/appSettings.ts
packages/lexical-react/src/LexicalListPlugin.ts

We are adding a strict indent feature for lists.
This feature helps in creating an accurate Markdown converter.
Additionally, it can be optionally enabled as needed.
https://github.com/user-attachments/assets/75fd4f1f-7b1c-49e3-96f2-fc7748b0c567
https://github.com/user-attachments/assets/e1235286-b37a-4ca8-bd35-ee08439a576d

[lexical-list] Feature: Enforce strict list indentation

---

packages/lexical-playground/src/nodes/ImageComponent.tsx

- When an image fails to load in the Lexical editor, the fallback image-broken.svg does not display immediately
- The fallback image only appears after making changes to the editor (like typing)
- The image-broken.svg fails to load because it's trying to load from the wrong path
- Improved error handling in `useSuspenseImage` hook to properly handle image loading failures
- Modified LazyImage component to maintain proper error state and show fallback immediately
- Ensured failed images aren't cached to allow retry attempts
Closes #7387
- Try to load an invalid image URL in the editor
- Observe that the broken image fallback doesn't appear immediately
- Need to make changes to the editor to see the fallback
https://github.com/user-attachments/assets/74df4cdf-acb9-4aad-baf9-9b370035ecdc
- …

[lexical-playground] Bug Fix: Immediate broken image display on load failure

---

packages/lexical/src/nodes/LexicalTextNode.ts
packages/lexical/src/nodes/__tests__/unit/LexicalTextNode.test.tsx

When using text formatting options like lowercase, uppercase, and capitalize, Lexical only adds CSS classes to the exported HTML without the necessary inline styles. This means the formatting doesn't work when the content is viewed outside of Lexical's CSS context.
- This PR adds inline `text-transform` styles to the HTML elements during export via `TextNode.exportDOM()`. Now when users export content with these text transformations, the formatted text will maintain its appearance even when viewed without the Lexical CSS classes.
- Unit tests have been added to verify that the exported HTML contains the correct text-transform styles for all capitalization formats (lowercase, uppercase, and capitalize).
Closes #7328
When applying uppercase, lowercase, or capitalize to text and exporting …

[lexical] Feature: Add text-transform styles to exported HTML

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/src/LexicalTableObserver.ts

Currently, when a table containing merged cells is fully selected and the backspace key is pressed, the table does not get deleted. This behavior is inconsistent with tables that don't have merged cells, where backspace deletion works as expected.
This PR fixes the table deletion behavior to work consistently regardless of whether the table has merged cells or not. When a table is fully selected and backspace is pressed, the table will be properly deleted and replaced with an empty paragraph, maintaining consistent behavior across all table types.
Changes made:
1. Updated `TableObserver.$clearText` to properly handle merged cells during table deletion
2. Added e2e test to verify table deletion behavior with merged cells
Closes #7444
When a table with merged cells is fully selected and …

[lexical-table][lexical-playground] Bug Fix: Handle backspace deletion of tables with merged cells

---

examples/vanilla-js-iframe/src/main.ts
examples/vanilla-js-plugin/src/main.ts
examples/vanilla-js/src/main.ts
packages/lexical-code/src/__tests__/unit/LexicalCodeNode.test.ts
packages/lexical-history/src/__tests__/unit/LexicalHistory.test.tsx
packages/lexical-history/src/index.ts
packages/lexical-markdown/src/MarkdownShortcuts.ts
packages/lexical-plain-text/src/index.ts
packages/lexical-playground/esm/index.mjs
packages/lexical-playground/src/plugins/ActionsPlugin/index.tsx
packages/lexical-playground/src/plugins/AutocompletePlugin/index.tsx
packages/lexical-playground/src/plugins/CommentPlugin/index.tsx
packages/lexical-playground/src/plugins/TableCellResizer/index.tsx
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical-react/src/LexicalAutoEmbedPlugin.tsx
packages/lexical-react/src/LexicalComposer.tsx
packages/lexical-react/src/LexicalOnChangePlugin.ts
packages/lexical-react/src/shared/useCharacterLimit.ts
packages/lexical-react/src/shared/useYjsCollaboration.tsx
packages/lexical-rich-text/src/index.ts
packages/lexical-website/docs/concepts/selection.md
packages/lexical-yjs/src/SyncEditorStates.ts
packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx
scripts/__tests__/integration/fixtures/lexical-esm-sveltekit-vanilla-js/src/routes/+page.svelte

Currently, string literals are being used directly for update tags in documentation and code (e.g., 'skip-dom-selection', 'history-merge'). This makes the code prone to typos and lacks proper TypeScript type checking.
This PR replaces string literal update tags with their corresponding exported constants from LexicalUpdateTags.ts. 
These changes improve:
- Type safety through TypeScript validation
- Code maintainability
- IDE support with autocomplete
- Consistency between documentation and implementation
Closes #7446
Documentation and code use string literals:
```js
$addUpdateTag('skip-dom-selection');
editor.update(prepopulatedRichText, { tag: 'history-merge' });
```
```js
$addUpdateTag(SKIP_DOM_SELECTION_TAG);
editor.update(prepopulatedRichText, { tag: HISTORY_MERGE_TAG });
```

Chore: migrate string literals to update tag constants

---

packages/lexical/src/LexicalUtils.ts

- `internalMarkNodeAsDirty` has a TODO comment suggesting to split it into separate element/leaf functions
- After analysis and review feedback, the current single-function implementation is actually preferred
1. Remove the outdated TODO comment as the current implementation is better because:
- Avoids unnecessary code duplication
- Maintains better performance
- Keeps code size minimal
- Improves maintainability
The change is minimal but important - removing an outdated TODO comment that would lead developers down a suboptimal path. The current implementation is more maintainable and efficient than splitting it would be.
Closes #7456

[lexical] Chore: Update internalMarkNodeAsDirty TODO comment

---

packages/lexical-playground/src/plugins/ShortcutsPlugin/index.tsx
packages/lexical-playground/src/plugins/ShortcutsPlugin/shortcuts.ts

Currently, comments can only be added through the UI button that appears when text is selected in the Lexical editor.
This PR adds keyboard shortcut support (⌘+Option+M on Mac, Ctrl+Alt+M on Windows/Linux) for adding comments, similar to Google Docs. The changes include:
1. Adding a new `ADD_COMMENT` constant to the `SHORTCUTS` object
2. Adding `isAddComment` helper function to detect the shortcut
3. Updating `ShortcutsPlugin` to handle the comment shortcut using `INSERT_INLINE_COMMAND`
Closes #7463
Currently, users can only add comments by:
1. Selecting text in the editor
2. Clicking on the comment button that appears in the UI
3. No keyboard shortcut support exists
Users can now:
1. Select text in the editor
2. Press ⌘+Option+M (Mac) or Ctrl+Alt+M (Windows/Linux) to add a comment
3. The …

[lexical-playground] Feature: Add keyboard shortcut for comments

---

packages/lexical-playground/src/index.css

- The text format dropdown button width changes dynamically based on the selected format text (e.g., "Normal", "Heading 1")
- This causes other toolbar buttons to shift position when switching formats
- Creates a jarring visual experience and poor UX
- Added fixed width (7em) to dropdown button text
- Added text overflow handling with ellipsis for longer format names
- Ensured proper text alignment and spacing
- Fixed visual disruption when switching between text formats
Closes #7461
https://github.com/user-attachments/assets/23ae3b6c-9ed7-4873-92fa-a9c80a9d5438
https://github.com/user-attachments/assets/b5c90954-c993-4526-a7b8-280d8a5125b4
The changes can be tested by:
1. Opening the Lexical playground preview for this PR
2. Clicking on the text format dropdown (shows "Normal" by …

[lexical-playground] Bug Fix: Stabilize text format dropdown width in toolbar

---

packages/lexical-yjs/src/CollabElementNode.ts
packages/lexical-yjs/src/Utils.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts

- The removeFromParent function in both packages makes multiple separate getWritable() calls
- Has nested conditional logic for sibling pointer updates
- Contains repeated null checks and sibling key access operations
- Has a TODO comment noting operation duplication
- Batch all getWritable() calls at the start of the function
- Consolidate related pointer updates into cleaner blocks
- Simplify null checks and conditional logic
- Maintain identical functionality with improved code structure
- Remove the TODO comment as the operations are now optimized
Closes #7452
All existing tests should continue to pass as the functionality remains unchanged.

[lexical-yjs][lexical] Refactor: Simplify removeFromParent internal operations

---

packages/lexical-playground/src/plugins/ShortcutsPlugin/index.tsx
packages/lexical-playground/src/plugins/ShortcutsPlugin/shortcuts.ts
packages/lexical/src/LexicalCommands.ts

While reviewing #7443 it was discovered that we have this `KEY_MODIFIER_COMMAND` that is hard to use correctly and not particularly useful when `KEY_DOWN_COMMAND` can be used instead with a small check to verify that some modifier is pressed.
This PR deprecates this `KEY_MODIFIER_COMMAND` and refactors the playground's keyboard shortcuts to use the new `isModifierMatch` function in combination with `KEY_DOWN_COMMAND`.
Existing e2e tests for playground shortcuts continue to work

[lexical][lexical-playground] Chore: Deprecate KEY_MODIFIER_COMMAND and use KEY_DOWN_COMMAND for playground shortcuts

---

packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-markdown/src/importTextTransformers.ts

Addresses markdown backslash escape sequence regression introduced by #7353. The escape sequence was exported but not correctly imported.
Closes #7473
Unit test coverage

[lexical-markdown] Bug Fix: Add import support for backslash escape sequences

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/ImageHTMLCopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/Tables.spec.mjs

Disables a flaky "Can expand table to fit content when pasting table into table" test in collab. The functionality of this test is not particularly relevant to collab.
Also disables this test in collab:
```
[chromium] › packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/ImageHTMLCopyAndPaste.spec.mjs:64:3 › HTML Image CopyAndPaste › Copy + paste + undo multiple image 
```
Spurious test failures
Fewer spurious test failures

[lexical-playground] Chore: Disable flaky "Can expand table to fit content when pasting table into table" in collab

---

packages/lexical/src/LexicalUtils.ts

#7443 modified built-in keyboard shortcuts (including Enter and Shift+Enter) to use exact modifier matching. Unfortunately internally we have a decent amount of plugins relying on the old inexact matching to handle the Enter key (with various modifiers), across both public and internal products. This PR reverts the triggering of `KEY_ENTER_COMMAND` to the state before #7443, to give us time to migrate our plugins to use `KEY_DOWN_COMMAND` instead (if we want to move ahead with exact-matching for the Enter command).
Existing tests

[lexical] Chore: Revert Enter command to use inexact matching

---

packages/lexical/src/LexicalCommands.ts

Update KEY_ENTER_COMMAND API docs to reflect current semantics (as of #7479, and prior to #7443)
No runtime code changes

[lexical] Chore: Update KEY_ENTER_COMMAND API docs

---

packages/lexical-playground/__tests__/e2e/AutoLinks.spec.mjs

I think there were some timing dependencies in the autolink tests which caused the direction of the paragraph to get set or not. This refactors the tests to test each expected URL separately and to include some non-URL text to avoid a race condition in setting the direction of the paragraph (both by executing faster and by ensuring the direction is set).
Tests fail intermittently
No more race conditions for these tests

[lexical-playground] Chore: Refactor autolink tests for reliability

---

packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

LexicalTypeaheadMenuPlugin can only be triggered if there is no TextNode before trigger, i.e. whitespace or a paragraph and there is no way to configure this behaviour, i.e.
- @Bob@B - won't trigger menu
Make this behaviour configurable by ignoring element boundary check

[lexical-react] Feature: make check for entity boundary configurable in LexicalTypeaheadMenuPlugin

---

packages/lexical-react/src/LexicalTablePlugin.ts
packages/lexical-table/src/LexicalTableNode.ts
packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx

When the `TablePlugin` initializes its `setScrollableTablesActive` effect after the editor has already rendered some tables there may be a mismatch. This change forces all existing tables to re-render when a change in `hasHorizontalScroll` is detected. In order to perform this update efficiently it marks table nodes as dirty by temporarily registering a no-op transform on TableNode, and its updateDOM implementation was changed to detect when the presence of a wrapper does not match the `$isScrollableTablesActive` setting.
Closes #7445
Unit test coverage

[lexical-react][lexical-table] Bug Fix: Re-render tables when the hasHorizontalScroll setting is changed

---

packages/lexical-table/src/LexicalTableNode.ts

Currently the table node does not set frozen columns and frozen rows on conversion. Since a replacement `TableNode` has no access to the `domNode` in `$convertTableElement`, only row striping is correctly set on the node.

[lexical-table] Bug Fix: Add missing DOM import for TableNode frozen rows and columns

---

packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts
packages/lexical-markdown/src/utils.ts

Currently, when creating links without protocols (like `[youtube](www.youtube.com)`) using the Link transformer, they're treated as relative paths instead of external URLs. This causes links to navigate to incorrect destinations (e.g., https://playground.lexical.dev/www.youtube.com instead of https://www.youtube.com).
This PR:
1. Adds URL handling utility functions to detect and format different types of URLs
2. Updates the LINK transformer to use these utilities
3. Adds tests to ensure the behavior works correctly
The fix improves the user experience for content creators by:
- Adding https:// to common URLs without protocols
- Adding mailto: to email addresses
- Adding tel: to phone numbers
- Preserving relative URLs
Closes #7497
When clicking a link created as …

[lexical-markdown] Bug Fix: Link Transformer URL Protocol Handling

---

packages/lexical-list/src/__tests__/unit/LexicalListItemNode.test.ts
packages/lexical-list/src/formatList.ts

Currently, when a list item with marker styles (like `--listitem-marker-font-size`) is indented, the parent list item that gets created does not inherit these styles. This causes inconsistent marker styling when indenting list items.
1. Modified `$handleIndent` in `formatList.ts` to copy the text style from the list item being indented to the newly created parent list item
2. Added unit tests to verify the marker style inheritance behavior
Closes #7491
When a list item with custom marker styles is indented, the parent list item loses those styles:
```html
<li>
<ul>
<li style="--listitem-marker-font-size: 60px;">Child item</li>
</ul>
</li>
```
https://github.com/user-attachments/assets/2ce40bd5-4eb4-4807-a5be-252a0688d958
The parent list item now inherits the marker styles when a child is …

[lexical-list] Bug Fix: Inherit marker styles when indenting list items

---

packages/lexical-playground/__tests__/e2e/List.spec.mjs
packages/lexical-rich-text/src/index.ts

The dedent-on-backspace heuristic in lexical-rich-text only checked if the selection was collapsed at the start of a node in an indented block, so it could trigger in situations where the selection was nested anywhere in an indented block. The intent is that this behavior should only happen at the first caret position in the block, so now it checks that the selection is at the first descendant of the block.
Closes #7515
Closes #7514
e2e test to confirm that dedent does not happen if the selection is at the beginning of a TextNode that occurs after a DecoratorNode in an indented list. All other e2e tests should pass.

[lexical-rich-text] Bug Fix: Backspace should only dedent at first descendant of indented block

---

packages/lexical-playground/src/plugins/EmojiPickerPlugin/index.tsx
packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

The typeahead menu does not recognize queries containing underscores (`_`) or dashes (`-`). For example, typing `:man_beard` or `:t-rex` does not trigger the typeahead menu as expected.
This PR makes the punctuation set for typeahead queries configurable via an optional parameter in `useBasicTypeaheadTriggerMatch`.
- The default punctuation set is restored for backwards compatibility.
- The emoji plugin now passes a custom punctuation set, allowing underscores and dashes in emoji queries.
This enables the typeahead menu to correctly match and display suggestions for queries like `:man_beard` and `:t-rex` in the emoji picker, without affecting other typeahead usages.
Closes #7519
https://github.com/user-attachments/assets/69979fde-8946-4aa0-b529-91000429490e

[lexical-react][lexical-playground] Bug Fix: Make typeahead punctuation configurable; allow underscores and dashes in emoji queries 

---

packages/lexical-devtools/wxt.config.ts

When process.env.LEXICAL_VERSION was added to the build, the devtools config wasn't also updated
Closes #7524
The latest lexical devtools extension doesn't work with an error message related to process.env.LEXICAL_VERSION
https://discord.com/channels/953974421008293909/953974421486436393/1370450398522904750
The devtools builds and runs
```
npm run -w packages/lexical-devtools dev
```

[lexical-devtools] Bug Fix: Update devtools vite config for process.env.LEXICAL_VERSION

---

packages/lexical-devtools/wxt.config.ts
packages/lexical-playground/vite.config.ts
scripts/build.js

Presumably the babel normalized windows paths must not start with a / (e.g. `c:/` or something). The `/` at the beginning is redundant on all platforms anyway, and removing it seems to fix it on Windows (reportedly).
https://discord.com/channels/953974421008293909/953974421486436393/1371755536587948172
https://discord.com/channels/953974421008293909/953974421486436393/1371912767992238211

[lexical-playground] Bug Fix: Use babel MatchPatterns that work correctly on windows

---

packages/lexical-list/src/LexicalListItemNode.ts
packages/lexical-rich-text/src/index.ts
packages/lexical/src/nodes/LexicalParagraphNode.ts

There is a small bug in exportDOM functions on
- ListNode
- ParagraphNode
- HeadingNode
- QuoteNode
style text-align gets added in any case, even if getFormat is unset. While it's not a big deal on most dom implementations, we can end up with :
```
<li style="text-align: ">Value</li>
```
```
<li style="text-align: ">Value</li>
```
```
<li>Value</li>
```

[lexical] Bug Fix : Prevent from adding element.style.textAlign when formatType is unset

---

packages/lexical/src/nodes/LexicalElementNode.ts
packages/lexical/src/nodes/__tests__/unit/LexicalElementNode.test.tsx

The "afterthought" (third expression) of the outer for loop in indexPath was constant and would never terminate in some scenarios, referencing child instead of node.
Closes #7548
New unit test coverage

[lexical] Bug Fix: Fix loop in indexPath

---

packages/lexical-playground/__tests__/keyboardShortcuts/index.mjs
packages/lexical-playground/src/plugins/ShortcutsPlugin/shortcuts.ts
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx

I found that keyboard shortcuts for Bullet list, Strikethrough and Quote block formatting were conflicting with some existing shortcut combinations on Windows machine. So while updating to these new shortcuts I've tried to mimic what google docs does along with aim to have somewhat similar key combinations for both Mac and Windows devices
Closes #7535 
updated relevant tests
| Action | Mac | Windows |
|--------|--------|--------|
| Numbered List | ⌘+Opt+5 | Ctrl+Alt+5 |
| Bullet List | ⌘+Opt+4 | Ctrl+Alt+4 |
| Check List | ⌘+Opt+6 | Ctrl+Alt+6 |
| Strikethrough | ⌘+Shift+S | Ctrl+Shift+S |
| Quote Block | ⌘+Opt+Q |  Ctrl+Alt+Q |
| Action | Mac | Windows |
|--------|--------|--------|
| Numbered List | ⌘+Shift+7 | Ctrl+Shift+7 |
| Bullet List | ⌘+Shift+8 | Ctrl+Shift+8 |
| Check List | …

[lexical-playground] Bug Fix: Change list, strikethrough and quoteblock shortcuts to match Google Docs for Windows compatibility

---

packages/lexical-list/src/checkList.ts

The checkbox onclick handler currently assumes the checkbox size to be 20px, which works for current scenarios as the checkbox doesnt grow with the font size.
instead of hardcoding the checkbox width, now we're using the calculated width of the checkbox
https://github.com/user-attachments/assets/cc88359f-b179-401a-a532-e1c981d93dc2
https://github.com/user-attachments/assets/cb12f24e-d46e-4d35-a643-02279ac778d0

[lexical-list] Bug Fix: Removed the hardcoded checkbox width in checklist onclick helper

---

packages/lexical-playground/src/plugins/ShortcutsPlugin/shortcuts.ts
packages/lexical/src/LexicalEvents.ts

Currently Apple Pencil inputs effectively breaks the editor because pen inputs do not update the selection state. This PR ensures pen input events update the selection state in the same way as touch input events.
Apple pencil inputs also create keyboard events when making scribbles. The key property for these events are undefined and broke the shortcuts plugin. This PR also fixes that.
Closes #7542

[lexical][lexical-playground] Bug Fix: Support Apple Pencil

---

packages/lexical-playground/src/plugins/TabFocusPlugin/index.tsx

- What is the current behavior that you are modifying? 
`COMMAND_PRIORITY_LOW` was re-defined in the plugin file.
- What are the behavior or changes that are being added by this PR?
`COMMAND_PRIORITY_LOW` is now sourced from the `lexical` package

[lexical-playground] Chore: source command priority from package

---

packages/lexical-playground/src/themes/PlaygroundEditorTheme.css

Currently, when a table column is frozen using the "Freeze First Column" option, the row striping (alternating row background colors) disappears for the frozen column. This happens because the frozen column cells have a hardcoded white background that overrides the row striping styles.
This PR fixes the issue by:
- Maintaining row striping in frozen columns by explicitly setting background colors for odd/even rows
Closes #7571
- Create a table with multiple rows and columns
- Right click the first column -> Remove Column Header
- Right click -> Toggle Row Striping
- Right click -> Freeze First Column
- Notice that the frozen column loses its row striping, showing only white background
https://github.com/user-attachments/assets/23b56670-f1ca-4c28-8144-fe1c8875a547
- Create a table with …

[lexical-playground] Bug Fix: Preserve row striping in frozen table columns

---

package-lock.json
packages/lexical-website/docusaurus.config.js
packages/lexical-website/package.json

This pull request is to fix docusaurus build
currently, inside lexical-website, if you run npm run build, it will fail. Error
```
[ERROR] Error: Docusaurus config `future.experimental_faster.ssgWorkerThreads` requires the future flag `future.v4.removeLegacyPostBuildHeadAttribute` to be turned on.
```
Also upgrading the docusaurus to 3.8, seems there are some performance improvements:
https://docusaurus.io/blog/releases/3.8
inside lexical-website, if you run `npm run build`, it will fail
able to run `npm run build`

[Update] Fix docusaurus build by adding removeLegacyPostBuildHeadAttribute flag

---

packages/lexical-playground/__tests__/e2e/Tables.spec.mjs
packages/lexical-table/src/LexicalTableUtils.ts

When selection contained a cell with a row span > 1 that overflowed it from the bottom and an user tried to remove selected rows, an exception was thrown.
1. Create a table
2. Merge cells in a column
3. Select rows within merged cells
4. Remove rows
Closes #7530 
When selection contains merged cells, an attempt to remove selected rows throws an exception.
https://github.com/user-attachments/assets/23ca978b-d50d-46da-a50d-95f6d14fabb4
Removing rows doesn't throw an exception.
https://github.com/user-attachments/assets/b11ed68a-7eb6-4d16-bfb1-b32df5f5ab12

[lexical-table] Bug Fix: error when deleting multiple rows with merged row cells

---

packages/lexical-link/flow/LexicalLink.js.flow
packages/lexical-link/src/__tests__/unit/LexicalLinkNode.test.ts
packages/lexical-link/src/index.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts

The URL formatting added to the markdown transform in #7499 was reverted in #7560 because it changed the document model in ways that were incompatible with some uses at Meta, such as using a handlebar style `{{variable}}` as the URL.
This PR takes the `formatUrl` implemented in the original PR and moves it to lexical-link where it is used only in rendering the href of the anchor tag, which solves the use case of having link click have the expected behavior but without changing anything at in the document model (the exact href will round-trip).
Unit tests

[lexical-link] Feature: Move URL formatting from #7499 to LinkNode sanitizeUrl

---

packages/lexical-playground/src/ui/ExcalidrawModal.tsx

- The `useCallbackRefState` hook was removed since it's redundant. The set function of `useState` is stable.
- Optional chaining
N/A

[lexical-playground] Refactor: simplify ExcalidrawModal

---

packages/lexical-playground/__tests__/e2e/CharacterLimit.spec.mjs
packages/lexical-react/src/shared/useCharacterLimit.ts

Fix for an infinite loop bug caused by auto link plugin and overflow that were wrapping each other indefinitely.
Added an additional check within $wrapOverflowedNodes function that skips leaf nodes that already have an overflow parent.
Closes #7474
Closes #6662 
Closes #6668
When typing in an autolink with a character limit on, page freezes
Page doesn't freeze anymore
https://github.com/user-attachments/assets/07db956b-d9a2-46ab-b2b8-e000f09d64b7

[lexical-react] Bug Fix: page freezes when typing a link in an overflow area

---

packages/lexical-playground/src/plugins/ComponentPickerPlugin/index.tsx
packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx

- Currently, there is support for adding custom punctuation in search keywords, but it’s not possible to search multiple words.
- After this feature, simple use cases related to the LexicalTypeahead Plugin that allow white spaces will be greatly simplified.
I have added an allowWhitespace prop in useBasicTypeaheadTriggerMatch, and based on its value, it will control whether to exclude whitespaces or not.
Closes #7583
Not able to type "Heading 1" as search keyword
https://github.com/user-attachments/assets/756a3266-619d-4d3a-b4c8-adca2e3dd01b
By adding `allowWhitespace: true` it would be possible to search "Heading 1"
https://github.com/user-attachments/assets/9318db49-8756-4cd1-889c-3498cb1e55d6

[lexical-react][lexical-playground] Feature: allow whitespaces in search keyword in useBasicTypeaheadTriggerMatch 

---

packages/lexical-markdown/src/MarkdownTransformers.ts
packages/lexical-markdown/src/__tests__/unit/LexicalMarkdown.test.ts

Currently, some nodes are selected in markdown transformers in their replace call. This changes this select to only occur when not importing. This prevents the editor from being focused inadvertently when importing.
Closes #7576 
Using the code from original stackblitz: https://stackblitz.com/edit/facebook-lexical-i9kn8h4q?file=src%2FApp.tsx
https://github.com/user-attachments/assets/5b754cb9-02ad-4fbb-ae1f-df5667a2c4b2
With the markdown import overridden to use my fork.
https://github.com/user-attachments/assets/86b9d451-7e3a-4be1-bcf7-8264553eb817

[lexical-markdown] Bug Fix: Don't select nodes when importing

---

packages/lexical-selection/src/lexical-node.ts
packages/lexical-yjs/src/CollabTextNode.ts
packages/lexical/src/LexicalEvents.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts
packages/lexical/src/nodes/LexicalTabNode.ts
packages/lexical/src/nodes/LexicalTextNode.ts
packages/lexical/src/nodes/__tests__/unit/LexicalTabNode.test.tsx

For legacy reasons TabNode is a 'normal' mode TextNode with the `IS_UNMERGEABLE` detail flag (used only in the reconciler's normalization), but the conditions in the rest of the core used `node.isToken()` to determine if the node should be modified or replaced without checking the `IS_UNMERGEABLE` flag.
To keep legacy serialization as-is, this PR changes the core to use `$isTokenOrTab` (new) and `$isTokenOrSegmented` functions instead of calling the `TextNode.isToken` method directly, and these functions both now check `$isTabNode` as part of their condition.
This also changes all property setters of `__text` to go through the `setTextContent` method (except for `@lexical/selection`'s `$sliceSelectedTextNodeContent` which is used in an unusual "read-only" way), and adds an additional …

[lexical][lexical-selection] Bug Fix: Treat all TabNode as if they are in token mode

---

scripts/__tests__/integration/fixtures/lexical-esm-nextjs/package-lock.json
scripts/__tests__/integration/fixtures/lexical-esm-nextjs/package.json

GitHub has identified a security vulnerability in a package dependency defined in the repository
* Manifest file: scripts/tests/integration/fixtures/lexical-esm-nextjs/package-lock.json 
* Package name: next (https://npmjs.com/package/next)
* Affected versions: >= 13.0, < 15.2.2
* Fixed in version: 15.2.2
* Severity: LOW
so update the next package version 
npm run build/npm run test

[scripts] update next version in lexical-esm-nextjs

---

packages/lexical-react/src/LexicalAutoLinkPlugin.ts

- What is the current behavior that you are modifying?
In the AutoLinkPlugin, specifically in the `TOGGLE_LINK_COMMAND` handler, a value is returned from a `forEach` loop, which has no effect, is confusing and doesn't make much sense.
- What are the behavior or changes that are being added by this PR?
The return value was removed.

[lexical-react] Chore: Remove confusing return value

---

packages/lexical-devtools-core/src/generateContent.ts

- The current behavior is that the `CustomPrintNodeFn` type is strictly typed to return `string`. This causes a TypeScript error if your provided function returns `undefined` to fall back to the default node printing logic, even though the runtime code handles this scenario.
- This PR modifies the `CustomPrintNodeFn` type definition to be `string | undefined`. This aligns the type with the existing runtime behavior and resolves the TypeScript error.
Closes #7612
If you provided a `customPrintNode` function like this, you would encounter a TypeScript error:
```typescript
const myCustomPrintNode: CustomPrintNodeFn = (node) => {
if (node.getType() === 'custom') {
return 'Custom node representation';
}
return undefined; // TypeScript error: Type 'undefined' is not assignable to type 'string'. …
```

[lexical-devtools-core] Bug Fix: Allow CustomPrintNodeFn to return undefined

---

packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalUpdates.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx

`registerMutationListener` currently maps from the listener function to the corresponding node class. If you then call `registerMutationListener` with a different class, it overwrites the first. This also means that the cleanup function from the first class could end up removing the listener for the second class.
`registerNodeTransform` on the other hand already allows you to register the same listener function to multiple classes. This change brings the same behaviour to `registerMutationListener`.
Added unit test, fails before change, passes after.

[lexical] Bug Fix: allow same mutation listener fn to be registered to multiple nodes

---

packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalUtils.ts

Workarounds for #7258 combined with loose inheritance (not compliant with ES6)
Can't really test this in-repo very easily since lexical is built as ES6

[lexical] Bug Fix: Workarounds in $config protocol for loose inheritance

---

package-lock.json
packages/lexical-react/package.json
packages/lexical-react/src/__tests__/unit/LexicalContentEditableElement.test.tsx
packages/lexical-react/src/__tests__/unit/LexicalNestedComposer.test.tsx
packages/lexical-react/src/shared/LexicalContentEditableElement.tsx

- removing `role` in read-only editor leads to an a11y violation `aria-prohibited-attr`
Closes #7500
- add `jest-axe` for a11y check
`npm run test-unit packages/lexical-react/src/__tests__/unit/LexicalContentEditableElement.test.tsx`
`npm run test-unit packages/lexical-react/src/__tests__/unit/LexicalContentEditableElement.test.tsx`

[lexical-react] Bug Fix: aria-prohibited-attr violation on LexicalContentEditableElement

---

packages/lexical-clipboard/src/clipboard.ts
packages/lexical/src/__tests__/unit/HTMLCopyAndPaste.test.ts

When pasting rich text content, the editor selection's active format and style are now updated to match the style of the last character of the pasted content.
This ensures that continuing to type after a paste operation will correctly inherit the formatting (e.g., bold, italics, background-color, font-size) from the pasted material.
Closes #7490 
https://github.com/user-attachments/assets/826cfda6-7994-49dd-8d82-0d9f658a0ffa
/automated-tests*
https://github.com/user-attachments/assets/2d9f4731-90de-4ad3-99fd-73189779ff29

[lexical-clipboard] Inherit style when typing after pasting rich text

---

packages/lexical-table/src/LexicalTableSelectionHelpers.ts
packages/lexical-table/src/__tests__/unit/LexicalTableMobileSelection.test.tsx

Currently tapping on cell in a table on mobile while the selection is in another cell creates a cell selection, this change ensures that it only happens when dragging.
Closes #7650

[lexical-table] Bug Fix: Fix table selection for touch devices

---

packages/lexical-playground/src/nodes/AutocompleteNode.tsx

Since #7659 fixed the code that generates importDOM warnings we now have a new warning for AutocompleteNode's lack of importDOM in the playground. This fixes that warning.
> AutocompleteNode should implement "importDOM" if using a custom "exportDOM" method to ensure HTML serialization (important for copy & paste) works as expected
No warning

[lexical-playground] Chore: Fix AutocompleteNode importDOM warning

---

packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx

Added a event listener to the FloatingLinkEditor component to ensure the link popup closes when it loses focus. 
Closes #7665 
https://github.com/user-attachments/assets/9d4d6937-1e18-46aa-be7e-806d43482bf8
https://github.com/user-attachments/assets/72634740-a8bd-4c55-97db-233e04548ca5

[lexical-playground] fix: close link popup when user clicks out of it

---

packages/lexical/src/LexicalEditor.ts
packages/lexical/src/LexicalNode.ts
packages/lexical/src/__tests__/unit/LexicalNode.test.ts

Follow-up to #7258
The `$config` protocol initially assumed that no code was calling `Node.getType()` before the Node was used in an editor, but there is a use case with plug-ins. This changes the stub implementation of `LexicalNode.getType()` to support the `$config` protocol directly.
Calling `Node.getType()` on a node using the `$config` protocol will throw if it has not first been registered with an editor
Calling `Node.getType()` is safe at all times

[lexical] Bug Fix: LexicalNode.getType() fallback to $config protocol

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-selection/src/range-selection.ts

This updates the `$shouldOverrideDefaultCharacterSelection` to the correct "backward" value when inside an RTL element.
Closes #7685.
https://github.com/user-attachments/assets/7143b0f1-ec1d-4e3e-b5da-ca2e453a1c4e
https://github.com/user-attachments/assets/90ba1799-9ab7-4329-95bb-a33cbe874cf3

[lexical-selection] Bug Fix: Correct backward inversion for RTL

---

packages/lexical-playground/src/index.css
packages/lexical-playground/src/plugins/ContextMenuPlugin/index.tsx
packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
packages/lexical-react/src/LexicalNodeContextMenuPlugin.tsx

Add support for icons in the new floatingUI-based context menu (LexicalNodeContextMenu).

[lexical-react] feat: Context Menu icons

---

packages/lexical-playground/src/plugins/ImagesPlugin/index.tsx

I guess this is kind of an edge case: When the image is wrapped within a Link Node, toggle the link upon drop
Closes #7692
https://github.com/user-attachments/assets/44abe44b-3ebf-4cfe-ae8c-d127623c13d0
https://github.com/user-attachments/assets/b7913055-5454-4a3d-bb3a-711bd0477cd6

[lexical-playground]Bug Fix: Image links lose link state when dragged

---

packages/lexical-playground/__tests__/e2e/Composition.spec.mjs
packages/lexical-playground/__tests__/e2e/Mutations.spec.mjs
packages/lexical/src/LexicalMutations.ts
packages/lexical/src/LexicalSelection.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/caret/LexicalCaret.ts

In some scenarios when IME input is happening, the browser's Text node will have a selection or content that is not represented in the lexical TextNode (a trailing zero-width-space). This changes the `$internalResolveSelectionPoint` implementation such that it will only resolve valid offsets by clamping to the size of the TextNode.
There were also scenarios where the MutationObserver handles text mutations without updating the lexical selection, so a similar fix was applied to `flushMutations`
Closes #7715 (superseded by this PR)
Closes #7639
e2e tests pass, added new e2e test to exercise flushMutations edge cases

[lexical] Bug Fix: Clamp DOM selection offsets to valid lexical TextNode offsets in $internalResolveSelectionPoint

---

packages/lexical-react/src/LexicalCollaborationPlugin.tsx

This fix resolves a race condition by ensuring the Yjs document reference is captured after the provider is initialized, rather than during the component's render function.
**Before:** The doc state was initialized with `yjsDocMap.get(id)` during the new component's render phase, which could capture a stale document reference because the old component instance's cleanup may not have executed yet.
**After:** The doc state is now set within the provider useEffect, ensuring it always references the fresh document that corresponds to the newly created provider. By doing this we guarantee that:
- The new component's render function doesn't prematurely capture a stale document
- The provider factory has completed and stored the current document in the map
- Any previous component cleanup has …

[lexical-react] Bug Fix: prevent race condition in CollaborationPlugin during rapid mount/unmount cycles

---

packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/TablesHTMLCopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/TextFormatHTMLCopyAndPaste.spec.mjs
packages/lexical-playground/__tests__/e2e/CopyAndPaste/lexical/CopyAndPaste.spec.mjs
packages/lexical-playground/src/plugins/ToolbarPlugin/fontSize.tsx
packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
packages/lexical/src/__tests__/unit/HTMLCopyAndPaste.test.ts

Consider font sizes in pt as well along with px in `parseAllowedFontSize` as most of editors like Google docs and MS word export font-sizes in pt when copied content
Closes #7718
Closes #7726
tests added for custom font-size in HTMLCopyAndPaste.test.ts
https://github.com/user-attachments/assets/3d5ed1a4-5780-44b9-92a3-25a735b37728
After
https://github.com/user-attachments/assets/65c2d61c-d1dc-4805-9460-e73b15542bb1

[lexical-playground] Bug Fix: include font sizes in pt as well in parseAllowedFontSize

---

packages/lexical/src/LexicalCommands.ts

Fix small documentation issue with key arrow down. The documentation says it fires on key arrow up.

Fix Key Arrow Down Documentation

---

packages/lexical-playground/__tests__/e2e/SelectionAlwaysOnDisplay.spec.mjs
packages/lexical-utils/src/markSelection.ts

**Problem**
The selectionAlwaysOnDisplay utility wasn't working correctly for right-to-left text selections (when users drag from right to left). The visual selection mark would not appear properly when the editor lost focus after making a right-to-left selection.
**Root Cause**
The issue was in the rangeFromPoints function in markSelection.ts. The function was only checking focusNode.isBefore(anchorNode) to determine selection direction, which works for selections across different DOM nodes but fails for selections within the same text node.
For same-node selections:
Left-to-right: anchor.offset < focus.offset (e.g., 5 → 10)
Right-to-left: anchor.offset > focus.offset (e.g., 10 → 5)
The original logic didn't account for this offset-based direction detection.
**Solution**
Enhanced the …

[lexical-utils] fix: Backward selection was not being retained

---

examples/react-rich-collab/package-lock.json
examples/react-rich-collab/package.json

- `npm i && npm run dev` run out of the box
- however below error is thrown
```
11:55:27 PM [vite] Internal server error: Failed to resolve import "@lexical/utils" from "src/plugins/ToolbarPlugin.tsx". Does the file exist?
```
- `package-lock.json` is outdated, adding `@lexical/utils` in `package.json` and `npm i`  resolves the issue 
- seems other packages also has outdated `package-lock.json`. Shall we bump all of them & run `npm i` at build process everytime?
- tested `npm i && npm run dev` able to start

[lexical-examples]  Bug Fix: missing dependency @lexical/utils at examples/react-rich-collab

---

.github/workflows/call-post-release.yml
.github/workflows/pre-release.yml
packages/lexical-website/docs/maintainers-guide.md

Per #7743 the package-lock files are not updated for examples when a release is published. This is a bit tricky because we can't update them until after the release happens, so it needs to be in a separate PR.
This updated workflow will automatically create a branch after a release is published with updated package-lock files. Like with updating a version, creating the associated PR is a manual process (github won't run actions for an automated PR unless it is using a personal access token).
There isn't a lot we can do to test actions like this without releasing them. In order to run it we first need to merge it to the default branch (main). Once the file is in place on main we can iterate on it from a branch if any issues arise.
* Run it directly with workflow_dispatch to make sure it …

[*] Chore: Add a post-release action to update the examples

---

packages/lexical-playground/__tests__/e2e/Selection.spec.mjs
packages/lexical-playground/__tests__/utils/index.mjs
packages/lexical-rich-text/src/index.ts
packages/lexical-selection/src/index.ts
packages/lexical-selection/src/range-selection.ts
packages/lexical-selection/src/utils.ts

This updates the right/left key arrow handlers to correct whether the previous/next node should be selected, for RTL scenarios.
Closes #7771.
Closes #7775.
Added a test for this.
https://github.com/user-attachments/assets/015b166a-9dc2-46b1-a599-c8f1cff2c33e
https://github.com/user-attachments/assets/543d3d0a-468d-40b8-bc54-f0af870c74e9

[lexical] Bug Fix: Correct exit direction from decorator nodes in RTL

---

packages/lexical-history/README.md

This PR fixes a minor issue in the **Lexical History** undo/redo documentation example. The previous example was missing a required argument for `dispatchCommand`, which caused a TypeScript error
```ts
onClick={() => editor.dispatchCommand(UNDO_COMMAND)}
```
```text
Expected 2 arguments, but got 1.ts(2554)
LexicalEditor.d.ts(513, 79): An argument for 'payload' was not provided.
```
The example has been updated to include the missing argument `payload` as `undefined`
```ts
onClick={() => editor.dispatchCommand(UNDO_COMMAND, undefined)}
```

[lexical-history] Add Missing Argument for DispatchCommand in Undo/Redo Docs Example

---

packages/lexical-react/src/LexicalNodeContextMenuPlugin.tsx

Explicitly specify the key attribute in the implementation of NodeContextMenuPlugin instead of relying on a spread. This seems to cause a problem with the way next.js handles jsx. I was expecting it to show up when using React 19 but it didn't seem to complain in the draft #7802 (before I added the commit for this fix).
Closes #7801
I think this requires next.js to reproduce so it's hard in our current test environment

[lexical-react] Fix: Use explicit key attr in NodeContextMenuPlugin

---

packages/lexical-link/src/index.ts
packages/lexical-selection/src/range-selection.ts
packages/lexical-utils/src/index.ts
packages/lexical/src/LexicalUtils.ts
packages/lexical/src/index.ts

- Current behavior: `$findMatchingParent` and `$getAncestor` logic lived in multiple places (`@lexical/utils`, `@lexical/selection`), leading to duplicated implementations and layering violations. This duplication also surfaced as duplicate symbol/implementation errors in CI when both versions were in play.
- Changes in this PR:
- Move a single, typed implementation of `$findMatchingParent` into core (`packages/lexical/src/LexicalUtils.ts`) with overloads (type‑predicate support).
- Export `$findMatchingParent` from core (`packages/lexical/src/index.ts`).
- `@lexical/utils`: re‑export `$findMatchingParent` from `lexical` and remove the duplicate implementation.
- `@lexical/selection`: provide a local exported `$getAncestor` wrapper that delegates to core `$findMatchingParent` (import from …

[lexical][lexical-selection][lexical-utils] Refactor: Consolidate ancestor lookup via findMatchingParent

---

packages/lexical/src/LexicalUtils.ts
packages/lexical/src/__tests__/unit/LexicalEditor.test.tsx
vitest.config.mts

People can get themselves into scenarios where multiple versions of lexical are on the same page. We have some detection for this already with editors, but it doesn't get caught when an editor is configured with nodes that subclass nodes from some other version of lexical. This adds an additional check and provides a detailed error message for that scenario.
Closes #7819
Unit test to verify that an error happens in this sort of case.
`FakeLexicalNode (type fake-node) does not subclass LexicalNode from the lexical package used by this editor (version 0.35.0+git). All lexical and @lexical/* packages used by an editor must have identical versions. If you suspect the version does match, then the problem may be caused by multiple copies of the same lexical module (e.g. both esm and cjs, or …

[lexical] Chore: Improve error message when a node is registered from a foreign lexical module

---

packages/lexical-clipboard/src/clipboard.ts

When the editor is mounted in a different window, for example when using [react-new-window](https://www.npmjs.com/package/react-new-window), then `copyToClipboard` copies the selection from the main window.
Tried to get a repro working with unit tests but couldn't get selection working with JSDOM.
Copy using context menu gets the text from the parent window's selection:
https://github.com/user-attachments/assets/5eaeed0c-2910-4dd9-8315-c2aae9e4665f
https://github.com/user-attachments/assets/d30c01e7-3b11-4c26-9995-82a9bf1b3cd1

[lexical-clipboard] Fix: copy correct selection when editor in different window/document

---

packages/lexical-clipboard/src/clipboard.ts

`$copyToClipboardEvent` updates a `ClipboardEvent` based on the current selection - however returning null for an absent or empty selection will prevent the Lexical content from getting cleared for an empty selection. This means the 'text/plain' and 'text/html' contents will update to empty strings, but the 'application/x-lexical-editor' will still have whatever stale value was present previously.
An alternative fix to the one committed already is to delete the content when null, rather than skipping, i.e.
```
const v = $editorFn(editor, selection);
if (v !== null) {
clipboardData[mimeType] = v;
} else {
delete clipboardData[mimeType]
}
```
This would preserve the `null` return for `$getLexicalContent`, though it doesn't look like anything in the repo depends on it.
No affected tests - …

[lexical-clipboard] Bug Fix: Update Lexical Clipboard with Empty Selection

---

packages/lexical-react/src/shared/LexicalMenu.ts

Whenever the editors total height is so small that the LexicalMenu's popover is outside the bounds of it's parent element, the `isTriggerVisibleInNearestScrollContainer` results in `false` whenever the `useEffect` inside `useDynamicPositioning` is run. This happens on scrolling and also navigating all the way to the bottom via the arrow keys.
This PR proposes the addition of a margin to the visibility check in order for the popover trigger to still be considered "visible" even if it's slightly out of bounds.
Closes #7837
https://github.com/user-attachments/assets/98c5efe0-783c-44e7-886a-2362ea27e9bd
https://github.com/user-attachments/assets/48f8ffff-ad33-44e2-ae4f-23e3be36b911

[lexical-react] Bug Fix: Add visibility margin to `isTriggerVisibleInNearestScrollContainer` to prevent popover from wrongfully closing

---

packages/lexical-extension/src/config.ts
packages/lexical-extension/src/getExtensionDependencyFromEditor.ts
packages/lexical-extension/src/getPeerDependencyFromEditor.ts
packages/lexical-extension/src/namedSignals.ts
packages/lexical-extension/src/watchedSignal.ts
packages/lexical/src/extension-core/defineExtension.ts

Add the `@experimental` tag to the jsdocs for extension functions to make it clear that these APIs are subject to change

[lexical-extension][docs] Chore: Add @experimental to extension functions

---

packages/lexical-table/src/LexicalTableSelection.ts
packages/lexical-table/src/__tests__/unit/LexicalTableSelection.test.tsx

If you have a table selection, delete the table, then access that selection immediately afterwards (eg `selection.getNode()`), and error is thrown ("node not found"). This can occur via an update listener as shown in #7140 
It is also common in collab scenarios where one client has a table selection and another client deletes the selected rows.
I have reproduced the error in a unit test, and fixed it by adding extra checks in `getNodes` to detect the invalid selection.
fixes #7140
Added unit text reproducing the error `Error: Point.getNode: node not found`
Test passes with code fix

[lexical-table] Bug Fix: Handle accessing table selection following table deletion

---

packages/lexical-rich-text/src/index.ts

For whatever reason we didn’t have preventDefault for the up/down arrows for node selection. As a result, the caret jumps two lines when exiting a decorator.
Insert decorator (easier to spot with block level decorator, like Youtube node)
https://github.com/user-attachments/assets/8039713e-cd18-4826-a71c-62fa14b77082
https://github.com/user-attachments/assets/a212fa85-b553-4067-ad56-7497c35739b6

[lexical-rich-text] Bug fix: up/down arrows for node selection

---

packages/lexical-yjs/src/SyncEditorStates.ts

Fix the following tsc error for consumers
```
$ ./client/node_modules/.bin/tsc --noEmit
Error: node_modules/@lexical/yjs/SyncEditorStates.d.ts(10,39): error TS2307: Cannot find module 'node_modules/yjs/dist/src/internals' or its corresponding type declarations.
```

[lexical-yjs] Chore: fix imports of Yjs XML types
